### ISSUE TITLE
Timeout for addRemoteCandidate. Consider sending an end-of-candidates notification

### ISSUE THREAD

**Issue by Aleksei-Suprun-Mera** [webrtcHacks/adapter#1006]
Hello.
## Description
I have the error "Timeout for addRemoteCandidate. Consider sending an end-of-candidates notification" in Edge Microsoft EdgeHTML 18.18363 (Microsoft Edge 44.18362.449.0)

Thanks

**Comment by SDCRoman** [comment]
How do you fixed the issue?

**Comment by Aleksei-Suprun-Mera** [comment]
> How do you fixed the issue?

I didn't resolve this issue. Edge requires a call addIceCandidate(null) when all remote candidates have been added. If you don't do that this will happen automagically after 3-4 seconds, but that increases the chance of failure.

**Comment by Aleksei-Suprun-Mera** [comment]
> How do you fixed the issue?

Have you fixed this issue?

**Comment by SDCRoman** [comment]
> > How do you fixed the issue?
> 
> Have you fixed this issue?

No, it seems it does not work on the old Edge versions. But I noticed that windows recently updates Edge to the chromium based Edge. Hopefully the issue will vanish then.

**Comment by kisakson** [comment]
I am also running into this issue in Legacy Edge, except I don't get it consistently. I already send a null candidate at the end of candidates which I would have expected to fix this issue. Currently testing in Microsoft Edge 42.17134.1098.0, Microsoft EdgeHTML 17.17134.
Has anyone else been able to make any progress on this or learn anything new about how to work around this?
