### ISSUE TITLE
adapter-lestest.js would change my constructor

### ISSUE THREAD

**Issue by SuuuuperAA** [webrtcHacks/adapter#1010]
# Please read first!

- [√] I have provided browser name, version and adapter.js version
- [√] This issue only happens when adapter.js is used

## Versions affected

**Browser name including version (e.g. Chrome 64.0.3282.119,and 360 browser)**

**adapter.js (e.g. 6.1.0)**

## Description
I used arcgis for javascript to build map,The way a functional module is introduced is the asynchronous loading of require,One of these modules is correctly loaded as a constructor the first time it's loaded, but the second time it's loaded it's changed to an object that contains basic browser information.This problem was eliminated when I removed adapter-lestest. Js, and it didn't appear in the Google browser, it appeared in the 360 browser, and I haven't tested the other browsers.I found several problems with the same name and changed the naming, but the problem remained,help me please~

**Comment by fippo** [comment]
https://webrtc.github.io/adapter/adapter-latest.js will export itself as window.adapter. If you don't want that try https://github.com/webrtcHacks/adapter/blob/gh-pages/adapter-7.4.0-variants/adapter_no_global.js

Alternatively, don't use the pre-built version.
