### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by chicoxyzzy** [webrtcHacks/adapter#1014]
Are there any plans on migrating to TypeScript? Would you be interested in such contributions?

**Comment by fippo** [comment]
whoops, I forgot about this.
If you look at the [activity](https://github.com/webrtcHacks/adapter/graphs/contributors) this repo is now in the maintenance mode phase of its lifecycle - you still need it but I don't think there is going to be much to add anymore. So I doubt that porting to typescript is worth the effort.

Does #1013 help make it more usable from TS at least?

**Comment by chicoxyzzy** [comment]
Thanks for merging #1013, I think that'll be enough!

**Comment by fippo** [comment]
:+1: if you could test 7.4.0 (which is currently tagged as beta) that would be great!
