### ISSUE TITLE
Invalid/old link to webrtc.org in README

### ISSUE THREAD

**Issue by wrbl606** [webrtcHacks/adapter#1019]
There is a link to [webrtc.org/web-apis/interop](https://webrtc.org/web-apis/interop) in the first README paragraph which directs to a 404 page:
![obraz](https://user-images.githubusercontent.com/15102395/74126708-e548e400-4bd8-11ea-96ba-04cd95993556.png)

![Screenshot_2020-02-10 404 Page Not Found WebRTC](https://user-images.githubusercontent.com/15102395/74126537-7c616c00-4bd8-11ea-9ebc-2fbb82923bc0.png)

I think, all of the links README should point to a valid outside resources and the mentioned one is not.

**Comment by fippo** [comment]
see https://github.com/webrtc/webrtc-org/issues/246

**Comment by anatolid** [comment]
The information about interop on the old site is outdated. The webrtc.org contains information about testing, and general interop info can be found on MDN.
