### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by llKoull** [webrtcHacks/adapter#1020]
- [] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [X] I have provided browser name, version and adapter.js version
- [X] This issue only happens when adapter.js is used

## Versions affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**
Chrome 80.0.3987.87 (64 bits) on MacOS and Win64

**adapter.js (e.g. 6.1.0)**
webrtc-adapter": "^7.5.0"

## Description
I'm using webrtc-adapter in a RactJS project and it has been working until today. I launched the project today and i saw the error that you can see in the attached file.

I've been trying to recompile all my project, reinstall the dependencies or revert it, but i didn't succed

![Captura de pantalla 2020-02-10 a las 19 28 44](https://user-images.githubusercontent.com/5525265/74182049-9afc4d00-4c42-11ea-9b17-c7f720a24ae2.png)

## Steps to reproduce
I don't know the steps to reproduce the issue, i just launched the project today and it didn't work (older versions that the yesterday's one that worked correctly, today are not working)

**Comment by fippo** [comment]
can you check if the commit from https://github.com/webrtcHacks/adapter/tree/fixfix
i.e. changing that condition to
```
  const addIceCandidateNullSupported =
    window.RTCPeerConnection &&
    window.RTCPeerConnection.prototype.addIceCandidate.length === 0;
```
fixes the issue? Its quite uncommon for window.RTCPeerConnection (or window.RTCPeerConnection.prototype.addIceCandidate) to be undefined but...

As a workaround, pin to the latest 7.4.x

**Comment by llKoull** [comment]
Hi @fippo!!

Thanks for your answer. I tried to use the code of the branch fixfix but i got the same error:

![Captura de pantalla 2020-02-11 a las 9 36 29](https://user-images.githubusercontent.com/5525265/74221425-6627de80-4cb2-11ea-9e98-7576376ae290.png)

I also tried the latest 7.4.x version with the same result:

![Captura de pantalla 2020-02-11 a las 9 39 06](https://user-images.githubusercontent.com/5525265/74221461-79d34500-4cb2-11ea-98db-9a778edabaec.png)

I saw that the condition did change but the error is the same :S

Thanks and best regards!

**Comment by llKoull** [comment]
Hi! I made a PR that fixed this issue: https://github.com/webrtcHacks/adapter/pull/1021

Thanks and best regards!

**Comment by fippo** [comment]
in what cases in addIceCandidate undefined? That is a fairly common method of RTCPeerConnection and it would be highly unusual for it to be undefined. Can you reproduce that in an incognito window (which should disable most extensions)?

**Comment by llKoull** [comment]
Unfortunately i don't know how to reproduce this case. As i explained in my first message, this library has been working perfectly until some days ago but it started to fail in Chrome 80.0.3987.87 under Windows and MacOS. I don't know if the version of Chrome is affecting it.

Thanks!

**Comment by fippo** [comment]
not actionable since we lack a reproduction, closing
