### ISSUE TITLE
RTCPeerConnection createOffer Promise resolves with undefined object

### ISSUE THREAD

**Issue by mdelete** [webrtcHacks/adapter#1028]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Versions affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**

Brave Version 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)

**adapter.js (e.g. 6.1.0)**

7.5.1

## Description

When trying to create an offer for a new RTCPeerConnection the Promise resolves with an undefined value.

## Steps to reproduce

```
rtcPeerConnection.createOffer({
  offerToReceiveAudio: 1,
  offerToReceiveVideo: 1
});
```

## Expected results

`Promise {<resolved>: Object { type: "offer", ... }}`

## Actual results

`Promise {<resolved>: undefined}`

**Comment by fippo** [comment]
Can't reproduce, that code works for me. If you can reproduce can you try without adapter?

**Comment by mdelete** [comment]
Issue seems to be the browser blocking fingerprinting. What's weird in this case is, that the unblocking-menu of Brave does not show this, sometimes isn't even accessible. So definitely a browser issue, but maybe calls for better error-handling. Will investigate further.

**Comment by fippo** [comment]
https://github.com/feross/simple-peer/issues/701 has a pretty good description of the issue.
