### ISSUE TITLE
create offer got broken sdp with out any video media like h264 or vp8 on iOS browser safari and chrome

### ISSUE THREAD

**Issue by jjunk1989** [webrtcHacks/adapter#1029]
## Versions affected

 iOS browser safari and chrome. system 12.4.5

use 
```
npm install webrtc-adapter 
```
and package.json show me version `7.5.1`

## Description

My webrtc works fine when i use adapter adapter-6.3.2. 
When i swith to the new adapter version(7.5.1) ios sdp broken without any media in there, no h264 ,
when i got callback from createOffer.

## Steps to reproduce

My codes work fine with adapter-6.3.2. Just something typescript like this

```
    this.offerOptions = {  
            offerToReceiveAudio: true,
            offerToReceiveVideo: true,
            iceRestart: true,
        };
    this.pc: RTCPeerConnection = new RTCPeerConnection(this.pcConfig);
this.pc.createOffer(this.offerOptions)
       .then(this.onCreateOfferSuccess)
        .catch((error: any) => {
              Log.warn('createOffer error:', error);
        });
```

## Expected results

Got right sdp with h264.

## Actual results

No h264 show in sdp.

**Comment by dagingaa** [comment]
Hey!

Thank you for reporting a bug. I've tried to replicate this on iOS 13.4.1 which is what I have available, and there H264 works. Could you create a fiddle or codepen with a reproducible results so I can test it out?

**Comment by fippo** [comment]
no reproduction so closing
