### ISSUE TITLE
Incorrect implementation of EventTarget

### ISSUE THREAD

**Issue by tjwoon** [webrtcHacks/adapter#1034]
- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used

## Versions affected

- Chrome Version 81.0.4044.129 (Official Build) (64-bit) on Ubuntu 20.04.
- webrtc-adapter 7.6.0

## Description

According to [the spec](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection), `RTCPeerConnection` inherits from `EventTarget`. `EventTarget`s implement the `addEventListener` method, which takes either a function [or an `EventListener`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) instance as the 2nd parameter.

Therefore we should be able to pass any object which implements a `handleEvent` method, and the RTCPeerConnection will invoke the method on any events.

## Steps to reproduce

```javascript
import 'webrtc-adapter'
class Test {
    constructor() {
        this.pc = new RTCPeerConnection({ iceServers: { urls: 'stun:stun.l.google.com:19302' } })
        this.pc.addEventListener('signalingstatechange', this)
        this.pc.createDataChannel('data')
    }
    close() {
        this.pc.removeEventListener('signalingstatechange', this)
        this.pc.close()
    }
    handleEvent(evt) {
        console.log('Received event', evt)
    }
}

new Test()
```

## Expected results

See some logs from the `handleEvent()` method.

## Actual results

With webrtc-adapter, I get this error: `utils.js:43 Uncaught TypeError: cb is not a function`. The stack trace only contains one line - `wrappedCallback @ utils.js:43` - pointing at https://github.com/webrtcHacks/adapter/blob/v7.6.0/src/js/utils.js#L43

Without webrtc-adapter, it works as expected.

**Comment by fippo** [comment]
thanks. That looks like `wrapPeerConnectionEvent` needs to be smarter and do a dispatchEvent when the callback is not a function
