### ISSUE TITLE
Unable to get property 'getLocalParameters' of undefined or null reference

### ISSUE THREAD

**Issue by hthetiot** [webrtcHacks/adapter#1040]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Versions affected

**Browser name including version** Microsoft Edge 18.18363 (aka Edge Legacy)

**adapter.js** 7.2.1

## Description

When using Edge Legacy 18+ (the last one before they used Blink) and webrtc-adapter 7+ the call fail to fully establish, the remote peer can see the local stream but the local peer cannot see the remote streams.

The local peer throw the following error preventing to display remote stream:
- Unable to get property 'getLocalParameters' of undefined or null reference

## Steps to reproduce

NEED UPDATE (we deprecated Edge 18 on sylaps.com due this issue)

0. Download Microsoft Edge Legacy VM here https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
1. Open https://sylaps.com/r/adapter using Edge 18 (legacy).
2. Open  https://sylaps.com/r/adapter using one of the following Chrome/Firefox/Safari
3. Open Developer Console to catch Error on Edge 18
4. In both browser Select Video Call and enter username

Note: I will try to reproduce using  https://appr.tc/ Or the WebRTC sample https://webrtc.github.io/samples/src/content/peerconnection/pc1/ also and update the steps to reproduce on this issue once also confirmed on this sample.

## Expected results

Establish call with remote and local stream without the error.

## Actual results

The local peer throw the following error:
- Unable to get property 'getLocalParameters' of undefined or null reference
Source: https://github.com/webrtcHacks/adapter/blob/master/release/adapter.js#L2915

**Comment by fippo** [comment]
apprtc works fine, as do [the samples](https://webrtc.github.io/samples/src/content/peerconnection/pc1/) and there hasn't any change to the shim for 12+ months

**Comment by hthetiot** [comment]
I will try to reproduce, this may occur during renegotiate, but I'm not sure yet I have to analyze logs to reproduce steps.

(God Edge 10 Legacy is so slow on my PC)

**Comment by fippo** [comment]
edge support was removed so I assume this is obsolete
