### ISSUE TITLE
Chrome fires ONN outside stable

### ISSUE THREAD

**Issue by jan-ivar** [webrtcHacks/adapter#1043]
I'm wondering if we can mitigate [crbug 1085748](https://bugs.chromium.org/p/chromium/issues/detail?id=1085748) somehow.

Adapter used to prevent ONN firing outside of `"stable"` state, but the mitigation was removed in https://github.com/webrtcHacks/adapter/pull/1037, not sure why.

**Comment by fippo** [comment]
mostly because the adapter polyfill was hiding the chrome bug

**Comment by fippo** [comment]
also cc @henbos (you can't escape :-p)

**Comment by jan-ivar** [comment]
Adapter **_should_** hide the Chrome bug. That's its job. 😉

**Comment by fippo** [comment]
well, it ate too much, leaving poor @bradleythughes confused as to why webrtc-internals fired the event when his app code didn't :-)

**Comment by fippo** [comment]
That should be fixed now at least, right @henbos?

**Comment by henbos** [comment]
Yes, this should be fixed as part of the Perfect Negotiation work.

**Comment by henbos** [comment]
Chrome M87

**Comment by fippo** [comment]
no further action unless you want to make a PR
