### ISSUE TITLE
Rollback throws InvalidStateError on mobile Safari (iOS 13.4.1)

### ISSUE THREAD

**Issue by goekhancimsir** [webrtcHacks/adapter#1045]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Versions affected

**mobile Safari, iOS 13.4.1**

**adapter.js (latest)**

## Description
Rollback of the peer connection state by calling `pc.setLocalDescription({type: "rollback"})` throws an error of type InvalidStateError.

## Steps to reproduce
- Open [jsfiddle](https://jsfiddle.net/8eap2t9r/1/) in mobile Safari
- Click / Press "Run"

## Expected results
`pc.setLocalDescription({type: "rollback"})` should not throw any error and rollback the peer connections signaling state to "stable"

## Actual results
Rollback of the peer connections state to "stable" fails since an error is thrown.

**Comment by fippo** [comment]
How is that related to adapter?

**Comment by goekhancimsir** [comment]
Thought adapter might be responsible for it but now I see (after carefully reading adapters description) that it is more likely to be an issue on a lower level layer (maybe WebRTC directly?). I am going to close this issue and try to find help from somewhere else. Thanks!
