### ISSUE TITLE
Facing constraint doesnt work for Microsoft surface pro

### ISSUE THREAD

**Issue by rahul-modasia31** [webrtcHacks/adapter#1049]
```
constraint.video = { width: videoWidth, height: videoHeight, facingMode: 'user'};
navigator.mediaDevices.getUserMedia(constraint).then(successCameraAccess).catch(cameraAccessError);
```
I've added the above code to access get the front camera,works in mobile devices but not in Microsoft surface pro.
Browser - Chrome 83
Expected Output - Front camera should open.
Original Output - Rear camera is opening always.
Since we've option of selecting a particular camera in firefox,we can manually select there but in chrome there's no option for this.
Noted there's check for browser version < 61 for enumerating devices in the adapterjs library  for manually detecting front or rear camera.After removing the check of browser version for testing purpose i was able to get the desired camera.
Is this check necessary since this doesnt work for surface pro devices?

For now,we've added a workaround of enumerateDevices separately.
When we initialise the camera,then after getting the camera label from stream.getVideoTracks()[0],ive added this function
```
CheckCameraDevices = function (cameraLabel, callbackFn, recallFn) {
// Detecting if there are more than one camera devices and making sure rear camera does not get selected
if (navigator.mediaDevices && navigator.mediaDevices.enumerateDevices) {
	var cameras = [];
	var deviceIds = [];
	cameraLabel = cameraLabel && cameraLabel.toLowerCase();
	navigator.mediaDevices.enumerateDevices().then(function (devices) {
		devices.forEach(function (device) {
			if (device.kind === 'videoinput' && !deviceIds.includes(device.deviceId)) {
				cameras.push(device);
				//Check for duplicate device Id's for firefox
				deviceIds.push(device.deviceId);
			}
		});
		//Checking if there are more than one cameras and rear camera is not getting selected by default
		if (cameras.length > 1 && cameraLabel &&
			(cameraLabel.includes('rear') || cameraLabel.includes('back'))) {
			//First time getting camera permission to detect all camera available,then initializing again to get front camera
			recallFn();
			return;
		}
		callbackFn();
	}).catch(function () {
		callbackFn();
	});
} else {
	callbackFn();
}};
 
```
This code works along with removing the browser version check for surface pro device.
I thought this should not be needed after including adapter.Is there any other other workaround that should be added?

**Comment by fippo** [comment]
Known chrome issue sadly:
  https://bugs.chromium.org/p/chromium/issues/detail?id=1090754
I don't think adapter can meaningfully fix this -- there is no condition to stop doing this and this doesn't work before the user has allowed access to devices.

**Comment by fippo** [comment]
looks like Microsoft folks are on it, closing here.
