### ISSUE TITLE
WebRTC camera stream is crashing if embedded with YouTube video on the same page

### ISSUE THREAD

**Issue by Smithangshu** [webrtcHacks/adapter#1057]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Versions affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**
Chrome Android 86.0.4240.99(Latest)

**adapter.js (e.g. 6.1.0)**
7.7.0(Latest)

## Description
WebRTC camera feed is crashing and video element turn black after few seconds of playing embedded YouTube video on the same page.

## Steps to reproduce
1.First start the WebRTC camera stream feed
2.Then start embedded YouTube video
3.Video element showing WebRTC feed will turn black and on console it can be seen stream status turned inactive

## Expected results
It should play both the video like every other browser like Firefox Android, Opera etc.

## Actual results
WebRTC camera feed is crashing and video element turn black after few seconds of playing embedded YouTube video on the same page. After that on console I can see stream status is inactive.

***Note: Please try with this page https://codepen.io/smithangshu/pen/abZmZrR on Chrome Android 86.0.4240.99(Latest) and follow above steps you can reproduce the issue and if you start the YouTube video first and then the WebRTC feed then it will work perfectly but otherwise it wont. Moreover, I checked with Chrome Android 80.0.3987.99 and it works there correctly.

**Comment by hthetiot** [comment]
Not sure that help but work for me see attached, local stream from front camera stay active even if started first.

Mozilla/5.0 (Linux; Android 9; SM-G892U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.99 Mobile Safari/537.36
Via http://thismachine.info/


![Screenshot_20201020-161405_Chrome](https://user-images.githubusercontent.com/8635/96598674-68d1dd80-12ef-11eb-99dc-a0d64dc0cd6a.jpg)

**Comment by Smithangshu** [comment]
Hi,
Thank you for replying. Its very strange that its working there on your side(in fact that is expected). But still I can not get it working. Are you using Chrome Android V 86.0.4240.99?
As you can see here

Starting the camera here:
![f1](https://user-images.githubusercontent.com/30255929/96605494-e7d90d00-1313-11eb-8d3c-96a2289f7925.png)

Started the YouTube video and playing for couple of seconds
![f2](https://user-images.githubusercontent.com/30255929/96605693-1fe05000-1314-11eb-9b24-3d2616d386ae.png)

And then on very next moment Camera stream has turned black
![f3](https://user-images.githubusercontent.com/30255929/96605798-3e464b80-1314-11eb-9fc5-d3b1084d0b57.png)

This is for my device from https://thismachine.info
Mozilla/5.0 (Linux; Android 9; Redmi Note 5 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.99 Mobile Safari/537.36

Now if change the code like this
```javascript
navigator.mediaDevices.getUserMedia(constraints).then(stream => {
   window.stream = stream;
   document.getElementById('gum-local').srcObject = stream
}).catch(e => console.error(e));
```
 And run the page locally and inspect the device from PC then I can see the following

1. When Camera stream is playing but not the YouTube video
![image](https://user-images.githubusercontent.com/30255929/96606975-7ef29480-1315-11eb-8c20-7f1b65ce505e.png)

2. When Camera stream has stopped due to YouTube video
![image](https://user-images.githubusercontent.com/30255929/96607177-b7926e00-1315-11eb-8aa0-89616f1769dc.png)

It says MediaStream.active: false which was true earlier.

Please help me sort out the problem I am really in a huge trouble due to this. Please.

**Comment by fippo** [comment]
Does this also happen without adapter.js? It is unlikely this is caused by adapter.
I'd recommend adding a `stream.getTracks().forEach(t => t.onended = () => console.log('track ended', t))` which *might* allow detecting this.

**Comment by Smithangshu** [comment]
Hi
This is what I am getting after adding your recommended code

![image](https://user-images.githubusercontent.com/30255929/96613210-4e622900-131c-11eb-9d1f-57a9785d825c.png)

**Comment by Smithangshu** [comment]
Yes I just checked it and it seems its also not working without adapter.js. But still can you please help me. Since I was wandering to get help but could not get reply from anyone who is expert in WebRTC. 
Please.

**Comment by Smithangshu** [comment]
One thing interesting I have noticed is
1) I cleared all network log in console after youtube player is loaded with video poster.
2) Then I am trying to start the WebRTC camera feed.
3) Feed is started and being played since the youtube video is not yet started.
But 
On the exact moment I play the WebRTC video, at that very moment network log is logging the as following
![image](https://user-images.githubusercontent.com/30255929/96625160-6db48280-132b-11eb-86d9-c01007ddc1d5.png)
It seems youtube api is interfering with WebRTC. Otherwise how playing WebRTC video would generate event on youtube player to send a network request.
Is there anyway to isolate them? Please help me to figure this out.

**Comment by fippo** [comment]
This repository is not the support channel for issues which are not related to the js code herein.
Be patient and wait if someone replies to your question on the discuss-webrtc list.
