### ISSUE TITLE
video loaded data very slowly after receiving remote streams In chrome 53

### ISSUE THREAD

**Issue by zmeng9** [webrtcHacks/adapter#1074]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [ ] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [ ] This issue only happens when adapter.js is used

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Versions affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**
Chrome 53.0.2785.116

**adapter.js (e.g. 6.1.0)**
7.7.1

## Description
THe video loaded data very slowly after receiving remote streams In chrome 53, but fastly in chrome 54. Is there a way to solve this problem?

## Expected results
The video loaded data fastly in chrome 53

## Actual results
The video loaded data slowly in chrome 53

**Comment by fippo** [comment]
How is this a problem of adapter.js?

**Comment by zmeng9** [comment]
Sorry, I guess this is a problem of HTMLMediaElement probably, but I don't know how to solve it. I have seen that video is compatible in the historical version. Is there any way to solve this problem?

**Comment by fippo** [comment]
The first thing the template you filled out says is "Please use discuss-webrtc for general technical discussions and questions."
