### ISSUE TITLE
Releases no longer being published to cdnjs.cloudflare.com

### ISSUE THREAD

**Issue by tmatth** [webrtcHacks/adapter#1075]
- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Versions affected

All versions >= 7.5.0

**Browser name including version (e.g. Chrome 64.0.3282.119)**

Any

**adapter.js (e.g. 6.1.0)**

All versions >= 7.5.0

## Description

The last version of webrtc-adapter to be published to cdnjs was 7.4.0:

https://cdnjs.cloudflare.com/ajax/libs/webrtc-adapter/7.4.0/adapter.min.js

Subsequent releases (>= 7.5.0) 404 on cdnjs. Note that all releases are present on e.g., unpkg.com:
https://unpkg.com/browse/webrtc-adapter@7.7.1/

## Steps to reproduce

```
# or any browser...
curl -s -I https://cdnjs.cloudflare.com/ajax/libs/webrtc-adapter/7.5.0/adapter.min.js | head -n1
```
## Expected results
```
HTTP/2 200 
```

## Actual results
```
HTTP/2 404 
```

N.B. I'm not specifically looking for 7.5.0, latest would be fine. This blocks updating webrtc-adapter versions in Janus since I don't want to force users downstream to have to update their CSP rules etc. if there's a quick fix.

**Comment by fippo** [comment]
https://github.com/webrtc/adapter/tags only showed up to 7.4.0
I've pushed to that repo with tags, lets check in a few hours

**Comment by fippo** [comment]
no luck sadly. Didn't this come up before?

**Comment by tmatth** [comment]
> no luck sadly. Didn't this come up before?

Yeah I noticed this a while back.

**Comment by fippo** [comment]
@MattIPv4 you might know. I suspect cdnjs doesn't deal with the moving-around to a different org and then forking in the original location. Would updating https://github.com/cdnjs/packages/blob/master/packages/w/webrtc-adapter.json to point to webrtchacks/adapter instead of webrtc/adapter help?

**Comment by MattIPv4** [comment]
👋 Most likely yes -- if you could submit a PR to update the information in that so that it has the correct info for fetching versions, that'd be ace.

**Comment by fippo** [comment]
(assuming this is done now :tada:)
