### ISSUE TITLE
Direction set properly?

### ISSUE THREAD

**Issue by neilyoung** [webrtcHacks/adapter#1091]
https://github.com/webrtcHacks/adapter/blob/d10cf3194af90bc2f3c76e10f28286cad842a941/src/js/safari/safari_shim.js#L314

Wondering if this line and the following  `this.addTransceiver('video')` wouldn't be more properly specified with `{direction: 'recvonly'}` here...

**Comment by fippo** [comment]
No. The following two result in identical offers:
```
const pc1 = new RTCPeerConnection();
const offer1 = await pc1.createOffer({offerToReceiveAudio: true});
console.log(offer1.sdp);
```
```
const pc2 = new RTCPeerConnection();
pc2.addTransceiver('audio');
const offer2 = await pc1.createOffer();
console.log(offer2.sdp);
```

**Comment by neilyoung** [comment]
@fippo True, but with the shim applied it gives `sendrecv`

To be more specific: Your sample above gives `recvonly` in both cases. This shim applied (Chrome) gives `sendrecv`, even though there is no active audio or video send requested.

**Comment by ybandou** [comment]
@neilyoung I agree with you,  it is mentioned in webrtc spec https://w3c.github.io/webrtc-pc/#legacy-configuration-extensions
See this pull request https://github.com/webrtcHacks/adapter/pull/1094

**Comment by neilyoung** [comment]
@ybandou Thanks for confirmation. This was my patch too

**Comment by neilyoung** [comment]
Thanks and Happy New Year to HRO
