### ISSUE TITLE
Update registration on Bower

### ISSUE THREAD

**Issue by piranna** [webrtcHacks/adapter#11]
Currently Bower registry [still points](http://bower.io/search/?q=adapter.js) to GoogleChrome repo, it needs to be removed and re-registered again pointing to that repo.

You can also check that info by executing from command line `bower info adapter.js`:

``` bash
> bower info adapter.js
bower not-cached    git://github.com/GoogleChrome/webrtc.git#*
bower resolve       git://github.com/GoogleChrome/webrtc.git#*
bower checkout      adapter.js#master
bower resolved      git://github.com/GoogleChrome/webrtc.git#f21fef6177

{
  name: 'adapter.js',
  description: 'A shim to insulate apps from WebRTC spec changes and prefix differences',
  homepage: 'http://googlechrome.github.io/webrtc/',
  repository: {
    type: 'git',
    url: 'https://github.com/GoogleChrome/webrtc.git'
  },
  authors: [
    'The WebRTC project authors (http://www.webrtc.org/)',
    'Jesús Leganés Combarro "piranna" <piranna@gmail.com>'
  ],
  main: 'samples/web/js/adapter.js',
  moduleType: [
    'globals'
  ],
  keywords: [
    'WebRTC',
    'PeerConnection',
    'RTCPeerConnection',
    'getUserMedia',
    'Chrome',
    'Chromium',
    'Firefox'
  ],
  license: 'BSD-3-Clause',
  ignore: [
    '**/.*',
    'node_modules',
    'bower_components',
    'test',
    'tests',
    'Gruntfile.js',
    'index.html',
    'package.json',
    'samples/web/content',
    'samples/web/css',
    'samples/web/js/lib',
    'samples/web/js/videopipe.js'
  ]
}

No versions available.
```

**Comment by andresusanopinto** [comment]
The workflow to update registration fails since we move the original repository.
- https://github.com/bower/bower/issues/120

I have commented on that issue to get a manual update done. It seems they conform to the manual requests every few days.

**Comment by piranna** [comment]
> The workflow to update registration fails since we move the original repository.
> 
> bower/bower#120
> 
> I have commented on that issue to get a manual update done. It seems they conform to the manual requests every few days.

Only can un-register the ones that are owners of the original repo.
Anyway, the manual update should work.

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un
monton de sitios diferentes, simplemente escribe un sistema operativo
Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by desandro** [comment]
I have re-registered `adapter.js` to `git://github.com/webrtc/samples.git` :arrow_right:

**Comment by piranna** [comment]
Awesome, thanks! :-D

**Comment by andresusanopinto** [comment]
Thanks! Updated it now to point to webrtc/adapter.git

**Comment by piranna** [comment]
Wait... isn't that the renamed old repo?

**Comment by andresusanopinto** [comment]
@piranna .. yes that was the old repo... but now I was able to unregister and register on the new location.
Before unregistering failed since the old location no longer existed (so I could not be owner on it).

**Comment by piranna** [comment]
Ah, ok @andresusanopinto, I'll wait then a little bit to finish :-)
