### ISSUE TITLE
Firefox sendEncodings shim should support sendEncodings being undefined

### ISSUE THREAD

**Issue by bbaldino** [webrtcHacks/adapter#1106]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Versions affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**
Firefox v103.0

**adapter.js (e.g. 6.1.0)**
adapter js v8.0.0

## Description
The firefox addTransceiver shim to handle `sendEncodings` fails if `sendEncodings` is present but mapped to undefined.  Chrome appears to handle this fine, so thought it would be nice if adapter did as well (treated it as though it wasn't passed).

This is due to the check [here](https://github.com/webrtcHacks/adapter/blob/a44f23a1df7717701c48284727fe0eea47cf8b81/src/js/firefox/firefox_shim.js#L184), which checks that the `sendEncodings` key is present, but doesn't check that the value is truthy.

## Steps to reproduce
Go to the fiddle [here](https://jsfiddle.net/bbaldino/tocn4Lq3/4/)
Click start

## Expected results
addTransceiver should carry out as though sendEncodings wasn't passed

## Actual results
An exception is thrown.

**Comment by fippo** [comment]
@jan-ivar thoughts?
