### ISSUE TITLE
How to send constant resolution 640x480

### ISSUE THREAD

**Issue by nodirnavruzov** [webrtcHacks/adapter#1114]
Hi, I'm having trouble defining a video resolution in a video conferencing project. I need to always send 640x480 to SDK, I specify this in the getusermedia method. after reading the information in the forums, I realized that getusermedia will not give me what I want, since webrts itself determines the optimal resolution depending on the speed of the Internet and the CPU. My question is: 
1) is it possible to specify an resolution constant ?
2) if so, how to implement it?

**Comment by fippo** [comment]
as the template you deleted said: "Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions"
