### ISSUE TITLE
Why delete package-lock.json?

### ISSUE THREAD

**Issue by jzombie** [webrtcHacks/adapter#1124]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

------

Curious as to why the package-lock.json file is deleted here: https://groups.google.com/forum/#!forum/discuss-webrtc

**Comment by fippo** [comment]
#663 has some of the rationale. Whether it still applies is another question.
