### ISSUE TITLE
problems making a video call

### ISSUE THREAD

**Issue by ander2000** [webrtcHacks/adapter#1128]
hello. how is everything?
When making a call, I have this problem:{
    "from": "user22@xmpp.qultar.com",
    "id": "c8ec1582-d1c3-44c9-badc-202b97f327da",
    "lang": "",
    "to": "user21@xmpp.qultar.com/_WQnHb-MLTzm",
    "type": "error",
    "error": {
        "condition": "service-unavailable",
        "type": "cancel"
    },
    "jingle": {
        "contents": [
            {
                "creator": "initiator",
                "name": "0",
                "transport": {
                    "gatheringComplete": true,
                    "transportType": "urn:xmpp:jingle:transports:ice-udp:1",
                    "usernameFragment": "sovO"
                }
            }
        ],
        "sid": "17ed0000-94df-4624-86cb-d513a86ad0e7",
        "action": "transport-info"
    }
}
I am using the sample code "jingle.demo.html" from stanzaJS

**Comment by fippo** [comment]
This is the wrong repository for jingle (or general XMPP-related questions)
