### ISSUE TITLE
Is there an online testing website based on adapter.js ?

### ISSUE THREAD

**Issue by manyhelp** [webrtcHacks/adapter#1142]
Is there an online testing website based on adapter.js ?

**Comment by fippo** [comment]
There is https://webrtchacks.github.io/adapter/ but adapter is a polyfill so just fixes some things, not sure what you are looking for. The [samples](https://webrtc.github.io/samples/) still use adapter.js

**Comment by hori205** [comment]
unsubscribe

________________________________________
差出人: manyhelp ***@***.***>
送信日時: 2023年11月8日 18:18
宛先: webrtcHacks/adapter
CC: Subscribed
件名: Re: [webrtcHacks/adapter] Is there an online testing website based on adapter.js ? (Issue #1142)

Closed #1142<https://github.com/webrtcHacks/adapter/issues/1142> as completed.
