### ISSUE TITLE
unable to set frame rate on safari 

### ISSUE THREAD

**Issue by saikrishnanamburi** [webrtcHacks/adapter#1144]
frameRate is is not changing on safari even on getdisplaymedia() constraints 

this is the code 
async setFrameRate(frameRate: number){
    let senderList =await this.rtcPeerConnection.getSenders();
    senderList.forEach((sender: any) => {
     if(sender.track && sender.track.kind == 'video'){
       let ice = sender.transport.iceTransport;
       let pair = ice.getSelectedCandidatePair();
       if(pair.local.address == "xxx.xxx.xx.xx"){
         const parameters = sender.getParameters();
         console.log('track parameters',JSON.stringify(parameters.encodings));
         parameters.encodings[0].maxFramerate = frameRate;
         sender.setParameters(parameters);
         console.log('updated track parameters',JSON.stringify(parameters.encodings));
         console.log('local and remote ice candiate');
         console.log(pair.local);
         console.log(pair.remote);
       }else{
        console.log('sharing on local Network frame rate is set to default');
       }
     }
   });
  }

Expected behavior: Stream at 8 fps.
Observed behavior: No change in fps.

logs 

before updating video parameters

"[{\"rid\":\"\",\"active\":true,\"fec\":{\"ssrc\":257},\"maxBitrate\":0,\"maxFramerate\":0,\"networkPriority\":\"low\",\"priority\":\"low\",\"rtx\":{\"ssrc\":0},\"scaleResolutionDownBy\":1,\"ssrc\":838448214}]"

after updating video parameters

"[{\"rid\":\"\",\"active\":true,\"fec\":{\"ssrc\":257},\"maxBitrate\":0,\"maxFramerate\":3,\"networkPriority\":\"low\",\"priority\":\"low\",\"rtx\":{\"ssrc\":0},\"scaleResolutionDownBy\":1,\"ssrc\":838448214}]"

WEBRTC version : 8.2.3

safari version  : 17.1

**Comment by hori205** [comment]
unsubscribe

**Comment by bilibvivo** [comment]
unsubscribe

**Comment by hori205** [comment]
unsubscribe

**Comment by fippo** [comment]
As noted in the template that was deleted, this repository is not the place for generic WebRTC issues.

Folks who need to unsubscribe please find the button in the github ui.
