### ISSUE TITLE
Consider using precommit hook in favor of grunt githooks

### ISSUE THREAD

**Issue by KaptenJansson** [webrtcHacks/adapter#115]
grunt githooks requires to be executed once after npm install to be properly added as a hook which is pretty inconvenient.

Adding it as a postinstall step in npm breaks npm when installing it as a dependency in other projects.

As suggested by @fippo, [precommit hook](https://www.npmjs.com/package/precommit-hook) does not come with this caveat and also it can separate tasks in a clear way, test, validation etc.

I filed this as an adapter issue but we should consider it collectively, e.g. for all webrtc/ sub repos.

@samdutton @alvestrand @fippo WDYT?

**Comment by fippo** [comment]
probably https://www.npmjs.com/package/git-validate rather so we have more control over what is run.

**Comment by alvestrand** [comment]
I must admit to being lost here - can you explain what grunt githooks do, and where we use it (if we do)?

You're trapped in a maze of packaging systems, all different.....

**Comment by KaptenJansson** [comment]
grunt githooks current assigns a set of tasks to be run before a commit is committed, if it fails it's not commited, a precommit task handler basically.

**Comment by samdutton** [comment]
The aim of using githooks with validity/style checks is to make it
impossible to commit code that breaks the rules.

I'm in favour of alternatives to grunt-githooks — happy to take advice on
what's best:).
