### ISSUE TITLE
browserDetails.version returns string after PR#1150

### ISSUE THREAD

**Issue by xingri** [webrtcHacks/adapter#1151]
- [ ] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [X] I have provided browser name, version and adapter.js version
- [X] This issue only happens when adapter.js is used

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Versions affected 

**Chrome and Edge Browser all versions

**adapter.js after PR#1150

## Description
browserDetails.version returns string after PR#1150

**Comment by xingri** [comment]
Proposed patch
`
diff --git a/src/js/utils.js b/src/js/utils.js
index 17bd38b6..85ff96c2 100644
--- a/src/js/utils.js
+++ b/src/js/utils.js
@@ -167,7 +167,7 @@ export function detectBrowser(window) {
       return brand.brand === 'Chromium';
     });
     if (chromium) {
-      return {browser: 'chrome', version: chromium.version};
+      return {browser: 'chrome', version: parseIntchromium.version)};
     }
   }
`

**Comment by xingri** [comment]
Proposed patch:

'version: chromium.version' returns string instead of integer, so it should be 'version: parseIntchromium.version)'

**Comment by fippo** [comment]
Fixed in 9.0.1, thank you!
