### ISSUE TITLE
Question Regarding adapter.js Compatibility with Unified Plan SDP Format

### ISSUE THREAD

**Issue by rush2ranvijay** [webrtcHacks/adapter#1159]
**Context:** I'm using this adpater.js for my application, which uses WebRTC for video calling. Now, as part of the Google Unified Plan SDP format, the transition plan (https://webrtc.org/getting-started/unified-plan-transition-guide) is . in a standard conformant format (“Unified Plan," draft-ietf-rtcweb-jsep).

**Question:** I've just one simple question: if I used the latest version of the adapter, should it cater to this “Unified Plan” also, or do I need to make some changes? If yes, could you please provide me with some information around this, such as a document, discussion link, guide, etc.?. I also have a document from Google for the magration guide, as here: https://docs.google.com/document/d/1-ZfikoUtoJa9k-GZG1daN0BU3IjIanQ_JSscHxQesvU/edit?usp=sharing. Could you please, suggest , how can I use it with adapter.js , if required to be used?

**Comment by fippo** [comment]
adapter.js does not deal with this. Unless you have very special requirements you do not need to bother, unified-plan has been the  default for years and plan-b is not even an option anymore.

@alvestrand it would be great to add a "this is obsolete" to the website and hbos' document

**Comment by rush2ranvijay** [comment]
> adapter.js does not deal with this. Unless you have very special requirements you do not need to bother, unified-plan has been the default for years and plan-b is not even an option anymore.
> 
> @alvestrand it would be great to add a "this is obsolete" to the website and hbos' document

Thanks @fippo  for the quick reply. I just needed one small suggestion: I'm using the JxBrowser Java lib with version 7.31.1, which is using Chromium 112.0.5615.137 as per their release notes. So, this JxBrowser library should already be using 'unified-plan' or do I need to check with the JxBrowser team?

**Comment by fippo** [comment]
Anything after Chromium 80 will be using unified-plan by default
