### ISSUE TITLE
make adapter.js versions available on the gh-pages branch

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#116]
coming from here: https://github.com/MicrosoftEdge/Demos/issues/90#issuecomment-127363723

the "easy" way to do this is probably to put adapter.js onto the gh-pages branch so we'd have them available as https://webrtc.github.io/adapter/adapter-0.2.1.js etc

The samples can then include that (or a -latest if we dare).
@samdutton @KaptenJansson?

**Comment by KaptenJansson** [comment]
Regarding samples, not sure I want to edit 20+ samples when the version number changes (yes it's a simple replace all call but still)....I guess a solution would be having all samples point to the usual adapter.js file but it contains a symbolic link to the adapter-0.2.1.js file, if the linking works everywhere that is (github gh-pages, selenium etc). But then again NPM works fine for us? Why fix what ain't broke?

But for MS edge demos, I have no problem serving it on gh-pages with a version number.

**Comment by fippo** [comment]
uhm... just noticed that this repo has a gh-pages... can we get rid of it?

**Comment by KaptenJansson** [comment]
Done, gh-pages is removed.

**Comment by fippo** [comment]
hrm. github doesn't let me make a PR against an non-existing branch. Can you create an empty gh-pages from the github ui?

**Comment by KaptenJansson** [comment]
Its not empty but on par with master
