### ISSUE TITLE
tags for versioning

### ISSUE THREAD

**Issue by piranna** [webrtcHacks/adapter#12]
Bower use git tags to identify each one of the versions, adapter should add them.

**Comment by DamonOehlman** [comment]
:+1:

**Comment by rockneurotiko** [comment]
Please! :+1:

**Comment by KaptenJansson** [comment]
Tags have been added.

**Comment by piranna** [comment]
Tags needs to be in X.Y.Z format instead of the current one vX.Y.Z so they can be used by Bower. Please remove the leading "v" character.

**Comment by KaptenJansson** [comment]
https://www.npmjs.com/package/webrtc-adapter-test

**Comment by KaptenJansson** [comment]
> bower info webrtc-adapter
> bower cached        git://github.com/webrtc/adapter.git#0.2.0
> bower validate      0.2.0 against git://github.com/webrtc/adapter.git#*
> bower new           version for git://github.com/webrtc/adapter.git#*
> bower resolve       git://github.com/webrtc/adapter.git#*
> bower download      https://github.com/webrtc/adapter/archive/v0.2.1.tar.gz
> bower extract       webrtc-adapter#\* archive.tar.gz
> bower resolved      git://github.com/webrtc/adapter.git#0.2.1

{
  name: 'webrtc-adapter',
  version: '0.2.1',
  description: 'A shim to insulate apps from WebRTC spec changes and prefix differences',
  repository: {
    type: 'git',
    url: 'https://github.com/webrtc/adapter.git'
  },
  authors: [
    'The WebRTC project authors (http://www.webrtc.org/)'
  ],
  main: 'adapter.js',
  moduleType: [
    'globals'
  ],
  ignore: [
    'test/*'
  ],
  keywords: [
    'WebRTC',
    'PeerConnection',
    'RTCPeerConnection',
    'getUserMedia',
    'Chrome',
    'Chromium',
    'Firefox'
  ],
  license: 'BSD-3-Clause',
  homepage: 'https://github.com/webrtc/adapter'
}

Available versions:
- 0.2.1
- 0.2.0
- 0.1.9
- 0.1.6
- 0.1.5
- 0.1.4
- 0.1.3
- 0.1.2
- 0.1.1
- 0.1.0
  You can request info for a specific version with 'bower info webrtc-adapter#<version>'

**Comment by KaptenJansson** [comment]
Works as is due to correct version in bower.json.

**Comment by KaptenJansson** [comment]
What's the benefit of using git tags, and/or what's the use of the version in bower.json? From a bower perspective that is.

**Comment by piranna** [comment]
Bower currently ignore the version field in the bower.json file because they don't have a proper repository as npm does, but instead it uses the git tags in semver format.

https://github.com/bower/bower.json-spec#version

**Comment by KaptenJansson** [comment]
If so, why does it work currently?

**Comment by piranna** [comment]
Probably it's fetching master.

**Comment by KaptenJansson** [comment]
But if you look at the output here https://github.com/webrtc/adapter/issues/12#issuecomment-131083038 you can see that it lists all the versions even though they are prefixed with "v" in the git tags.

**Comment by KaptenJansson** [comment]
> bower install webrtc-adapter#0.1.0
> bower not-cached    git://github.com/webrtc/adapter.git#0.1.0
> bower resolve       git://github.com/webrtc/adapter.git#0.1.0
> bower download      https://github.com/webrtc/adapter/archive/v0.1.0.tar.gz
> bower extract       webrtc-adapter#0.1.0 archive.tar.gz
> bower resolved      git://github.com/webrtc/adapter.git#0.1.0

**Comment by KaptenJansson** [comment]
It does not have an issue with "v" at all as you can see above.

**Comment by piranna** [comment]
Don't know, maybe now they are filtering the initial "v", I've seen the vX.Y.Z format before... Anyway, it was not working in old versions.

**Comment by KaptenJansson** [comment]
In other words its fine then ;).

**Comment by piranna** [comment]
:+1:
