### ISSUE TITLE
throws exception on chrome device emulator

### ISSUE THREAD

**Issue by yocontra** [webrtcHacks/adapter#122]
Reproduce:
- Open chrome devtools
- Enable emulator
- Set device to "Apple iPhone 6"

Error:

```
Uncaught TypeError: Cannot read property '2' of null

/Users/chirp/node_modules/wildfire-client/node_modules/attachmediastream/node_modules/webrtc-adapter-test/adapter.js @ adapter.js:206

/Users/chirp/node_modules/wildfire-client/node_modules/getusermedia/node_modules/webrtc-adapter-test/adapter.js @ index-browser.js:80
```

Root of the problem: https://github.com/webrtc/adapter/blob/master/adapter.js#L232-L233

**Comment by KaptenJansson** [comment]
Thanks for reporting.

This is due to assuming navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)./) will always return something when window.chrome exists.

**Comment by KaptenJansson** [comment]
@calebboyd FYI

**Comment by KaptenJansson** [comment]
Basically we do not cover the case where the UserAgent is Safari (or anything else than Chrome/Chromium) and window.chrome exists, e.g. Chrome on iOS.

**Comment by calebboyd** [comment]
Perhaps the UA match should be used as the switch case. It would then most likely still break when emulating a device in a version of chrome that needed to be shimmed...

**Comment by KaptenJansson** [comment]
@contra #142 has landed which should improve the version checking in general, could you give it a try again? Thanks!

**Comment by KaptenJansson** [comment]
Ping?

**Comment by yocontra** [comment]
Ended up using something else, can't comment on if this fixed it or not

**Comment by calebboyd** [comment]
:hand: I'll confirm. This is fixed.
