### ISSUE TITLE
dont modify the window object

### ISSUE THREAD

**Issue by yocontra** [webrtcHacks/adapter#125]
When using this as a npm module, please don't modify the window object. This breaks encapsulation and makes this incompatible with other WebRTC tooling (temasys, iosrtc, others). Overriding globals is generally a bad idea, but doing it in an npm module on require is especially bad.

**Comment by xdumaine** [comment]
Dup of #8, night?

**Comment by fippo** [comment]
no, #8 is about the non-module version, not about modification of window.

I do not see how not exporting RTCSessionDescription et al helps writing spec-compliant code -- which is the requirement solved by adapter.

**Comment by yocontra** [comment]
@fippo You don't care that your library breaks compatibility with a whole suite of tools? Okay, cool. I'll make sure to check the packages I install to ensure they don't use this because it _breaks_ all of our other tooling the second it gets required.
