### ISSUE TITLE
Support Object RTC and Microsoft Edge

### ISSUE THREAD

**Issue by feross** [webrtcHacks/adapter#128]
Will adapter.js support Object RTC and Microsoft Edge?

http://dev.modern.ie/platform/changelog/10525-pc/

Or, is someone working on a shim in another repo?

**Comment by KaptenJansson** [comment]
I do not see why not, we already support MS edge (the parts they have implemented as of 1 month ago at least). Pull requests are welcome ;)

**Comment by fippo** [comment]
@feross: my stance on that is what @adambrault and I said at fluentconf: use simplewebrtc :-p

**Comment by juberti** [comment]
I don't think adapter should try to provide that level of polyfill. adapter.js is meant to be a thin polyfill; other polyfills for edge should appear shortly.

**Comment by KaptenJansson** [comment]
Closing as per last comments.
