### ISSUE TITLE
Reduce leaking globals and create an explicit function exposing the globals we need.

### ISSUE THREAD

**Issue by KaptenJansson** [webrtcHacks/adapter#130]

**Comment by juberti** [comment]
Is this the same as #8?

**Comment by alvestrand** [comment]
Christoffer and I talked about this last week. If adopted, it would ameliorate #8, but it's more of a specific approach than a generic.
We've got users depending on those globals now, so pulling them in requires at least a major version bump.

**Comment by fippo** [comment]
the samples are now ready for a version bump so let's do it along with Edge support.

**Comment by KaptenJansson** [comment]
Being done in #164.

**Comment by KaptenJansson** [comment]
Fixed in #164.
