### ISSUE TITLE
IE8 does not like catch function

### ISSUE THREAD

**Issue by sualko** [webrtcHacks/adapter#133]
IE8 throws "identifier expected" on [L222](https://github.com/webrtc/adapter/blob/master/adapter.js#L222).

Not sure, why it is evaluating this part and how to fix this.

**Comment by 4lejandrito** [comment]
Same problem here. I am currently trying to conditionally load the script only if webrtc is supported by the browser (for which I was using this script :D)

**Comment by 4lejandrito** [comment]
My guess is that catch is a reserved word (try...catch) and IE8 is not that permisive. I had this problem when one of they keys of an inline object was called "with" IE8 wouldn't like it.

**Comment by 4lejandrito** [comment]
would this be a hacky workaround?

``` js
orgEnumerateDevices()['catch'](function(e) {
```

**Comment by 4lejandrito** [comment]
I managed to support IE8 using my fork: https://github.com/4lejandrito/adapter

If someone maintaining the main repo is happy with it I could submit a pull request. For the time being you could switch to mine if you want. By the way I have only tested it including es5-shim/sham before my main bundle.

**Comment by jan-ivar** [comment]
A better workaround might be `.then(null, function(e) { });` which is the same.

**Comment by sualko** [comment]
In my opinion, both solutions have pros and cons, so it doesn't matter, which one is merged. But thanks for your work anyway. I think this is important if you concatenate all your js files.

**Comment by 4lejandrito** [comment]
Yeah @sualko that was my use case, I am using browserify. I am happy with my fork it has been live for a few days now in my personal project but will be happy to switch to the mainstream if this issue gets fixed.

By the way, I have seen the fix #134 only covers this specific problem for IE8. However I had to make one more fix to make it work which is in this commit https://github.com/4lejandrito/adapter/commit/2da3d0fffeb94240e6bb147e436a53cf23fd1fdd.

Cheers!

**Comment by alvestrand** [comment]
.catch is part of the ES6 specification of promises. If IE8 doesn't like it, IE8 has a bug.
(Can someone verify that this is indeed true, and not just that it parses "return functionReturningPromise().catch()" differently from all other browsers? If it's as simple as saying "return (functionReturningPrimise().catch()) that might be a better patch.)

that said, adapter.js is all about papering over browsers' bugs, so there's an argument to be made for making this fix.

**Comment by jan-ivar** [comment]
FWIW `promise.catch(r)` is [well-established sugar](https://github.com/domenic/promises-unwrapping/blob/master/docs/states-and-fates.md) for `promise.then(undefined, r)`, so no-one should be confused by the latter IMHO.
