### ISSUE TITLE
Requests from Chrome WebView no longer detected as Chrome

### ISSUE THREAD

**Issue by tednakamura** [webrtcHacks/adapter#135]
5c5fff7b8972a0871a2f023fcc00c34eb2605834 changed the Chrome detection logic from:

``` javascript
else if (navigator.webkitGetUserMedia)
```

to:

``` javascript
else if (navigator.webkitGetUserMedia && !!window.chrome)
```

Unfortunately, window.chrome is not present for WebView. This is mentioned in [this Chromium bug report](https://code.google.com/p/chromium/issues/detail?id=527483#c19), but I think it's view restricted, so here's the relevant text:

> is it expected that !!window.chrome returns false for WebView?
> Checked webview m39 and trunk. Nope, window.chrome is not there for webview.

I'm hoping that reverting just that part of 5c5fff7b8972a0871a2f023fcc00c34eb2605834 is enough to make WebView requests be detected as Chrome again, but I'm not certain.

Instructions to build WebView, and in particular the WebView shell app, are available [here](https://www.chromium.org/developers/how-tos/android-build-instructions#TOC-Build-WebView-shell).

**Comment by fippo** [comment]
#132 is about the same thing. I think there are some additional issues to consider like CEF and nw.
Not sure why we don't use the existence of window.RTCPeerConnection... will take a stab next week.

**Comment by KaptenJansson** [comment]
I believe #122 is also the same issue.

**Comment by alvestrand** [comment]
WebView should be detected as WebView, not chrome, in my opinion. They build from the same base, but have some different properties. Should be quick to say "do like Chrome".

**Comment by fippo** [comment]
@alvestrand opera is detected as chrome. It behaves like chrome for peerconnection purposes but getusermedia is different (which influences how you display GUM hints).

But let's figure that out as a potential breaking change for 1.0
