### ISSUE TITLE
shimming devicechange?

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#137]
I just noticed that the devicechange event would be trivial to shim by polling navigator.mediaDevices.enumerateDevices and counting the length.
The big question is: do we want to run a 1s (2s? 3s?) setInterval which polls enumerateDevices

@alvestrand @KaptenJansson -- you might be aware of the crbug tracking this.
@jan-ivar what is the firefox status re devicechange?

I can do do my own shim but that would require me to override adapter so... easier to solve here :-)

**Comment by jan-ivar** [comment]
It's on our roadmap. https://bugzil.la/1152383

I vote for 3+ seconds, and only if someone actually uses ondevicechange / addEventListener. Calling enumerateDevices is not cheap, especially the first time (~500 ms), though repeat calls seem faster (5-40 ms).

**Comment by fippo** [comment]
good point, subscribing to the event listener allows detection whether this is used at all.

**Comment by KaptenJansson** [comment]
@fippo https://code.google.com/p/chromium/issues/detail?id=388648 for ondevicechange event.

**Comment by KaptenJansson** [comment]
I agree with @jan-ivar that it should only be running when used.

**Comment by KaptenJansson** [comment]
Still a need for this?

**Comment by fippo** [comment]
yeah -- unless guido beats me to it [here](https://bugs.chromium.org/p/chromium/issues/detail?id=388648). I need a clone or two. Can you assign me so I don't forget it?

**Comment by fippo** [comment]
so @guidou beat me to it  :-)
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/wdSV0zUuvJQ
