### ISSUE TITLE
ConstraintSet produces malformed constraints in Chrome 45

### ISSUE THREAD

**Issue by igracia** [webrtcHacks/adapter#138]
We've run into an issue using the [ConstraintSet](http://www.w3.org/TR/mediacapture-streams/#dictionary-mediatrackconstraintset-members) from the specification, under Chrome 45. With the latest version of adapter.js, we issue the following constraints to `getUserMedia()`

``` JSON
var MEDIA_CONSTRAINTS = {
    "audio": true,
    "video": {
        "width": {
            "max": 640
        },
        "frameRate": 15,
        "advanced": [
            {
                "width": {
                    "max": 1024
                },
                "frameRate": {
                    "min": 10,
                    "ideal": 15,
                    "max": 30
                }
            }
        ]
    }
};
```

Which get translated into this (from the development console log)

``` JSON
{
    "audio": true,
    "video": {
        "optional": [
            {
                "minWidth": 1024
            },
            {
                "maxWidth": 1024
            },
            {
                "minFrameRate": 15
            },
            {
                "maxFrameRate": 15
            },
            {
                "width": {
                    "max": 1024
                },
                "frameRate": {
                    "min": 10,
                    "ideal": 15,
                    "max": 30
                }
            }
        ]
    }
}
```

Which yields this:

```
adapter.js:406 Uncaught TypeError: Failed to execute 'webkitGetUserMedia' on 'Navigator': Malformed constraints object.
```

The same `MEDIA_CONSTRAINTS` object works well in FF 41. Is the `advanced` block not supported by Chrome, or is it the adapter not translating the constraints correctly when the ConstraintSet is used?

**Comment by jan-ivar** [comment]
It's a bug in the constraints polyfill. Chrome chokes on the new `width` and `height` etc. keys, and as you can see, the polyfill back-converts these when found outside of `advanced` and stuffs them into `advanced`. It forgets, however to back-convert anything already found in `advanced`.

I'm curious though why you think you need `advanced`, as your use-case seems doable without it, using `ideal` in the non-advanced section. Note that `ideal` inside `advanced` is a no-op.

It's sort of why we half-deprecated `advanced`: it's no longer needed for anything sane, and it's really hard to read the intent of an `advanced` sequence.

**Comment by igracia** [comment]
Thanks for the reply. In the beginning, we were passing this

``` JSON
{
    "audio": true,
    "video": {
        "width": {
            "max": 640
        },
        "frameRate": {
            "min": 10,
            "ideal": 15,
            "max": 20
        }
    }
}
```

And found out that, in Ubuntu, the max framerate of 20 was working on Chrome 45 but not on FF 41. We were checking if we could keep that framerate limitation of 20 (it works with 25), and have a fallback constraint valid if the browser was not able to cope with that. We were basically playing around with that, and have finally opted for the more sane

``` JSON
{
    "audio": true,
    "video": {
        "width": 640,
        "frameRate": 15
    }
}
```

which works pretty well everywhere.

If you are going to deprecate that, I think we can just close this issue.
