### ISSUE TITLE
Add support for upcoming navigator.mediaDevices.enumerateDevices()

### ISSUE THREAD

**Issue by KaptenJansson** [webrtcHacks/adapter#14]
Original tracked in this [crbug](https://code.google.com/p/chromium/issues/detail?id=340606&q=reporter%3Ame&colspec=ID%20Pri%20M%20Iteration%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified#makechanges)

MediaStreamTrack.getSources() will soon be deprecated.

**Comment by alvestrand** [comment]
Note: getMediaDevices() didn't make the cut. It is now navigator.mediaDevices.enumerateDevices().

**Comment by jan-ivar** [comment]
I believe PR #23 covers this?

**Comment by KaptenJansson** [comment]
Looks like it

**Comment by alvestrand** [comment]
Done in #32
