### ISSUE TITLE
Migrate requestUserMedia to be an overload of getUserMedia

### ISSUE THREAD

**Issue by juberti** [webrtcHacks/adapter#15]
If the first argument is not a function, you get the promise version.

**Comment by KaptenJansson** [comment]
Do we still want to do this? Currently requestGetUserMedia will always return a promise even though the underlying getUserMedia() function do not. You can however explicitly choose getUserMedia variant as per below:

navigator.getUserMedia() = callback version
navigator.mediaDevices.getUserMedia() = promise version

@fippo @alvestrand @jan-ivar WDYT?

**Comment by fippo** [comment]
let's get rid of this once the native navigator.mediaDevices.getUserMedia is available. The current code path is confusing.

I think the only requestUserMedia directly this is apprtc.

**Comment by jan-ivar** [comment]
Why wait? Both the `getUserMedia` function and `requestUserMedia` seem redundant already. People should be using `navigator.getUserMedia` and (preferably) `navigator.mediaDevices.getUserMedia` respectively instead IMHO.

**Comment by KaptenJansson** [comment]
@juberti @alvestrand what do you think?

**Comment by KaptenJansson** [comment]
In #164 it's removed, only the shimmed versions of the original API's are available.

**Comment by KaptenJansson** [comment]
Ooops, did not mean to close this yet.

**Comment by KaptenJansson** [comment]
requestGetUserMedia is left with a deprecation notice however getUserMedia is gone.
