### ISSUE TITLE
dont rely on prefixed mozGetUserMedia and mozRTCPeerConnection for Firefox detection

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#151]
from the Firefox 44 release notes: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/discuss-webrtc/C7rTpqdAQ6o/Ig86CPxxAgAJ it looks like we need another way to detect Firefox in https://github.com/webrtc/adapter/blob/0f06144afc30ac5e92de3c47955ecb835524ee79/adapter.js#L91

@mreavy @jan-ivar: do you have a recommended way for detection? I suppose we could snoop on the UA string and also check for the unprefixed versions but there might be a better way.

We are also using mozRTCPeerConnection and mozGetUserMedia inside the wrappers:
https://github.com/webrtc/adapter/blob/0f06144afc30ac5e92de3c47955ecb835524ee79/adapter.js#L130
https://github.com/webrtc/adapter/blob/0f06144afc30ac5e92de3c47955ecb835524ee79/adapter.js#L198

**Comment by jan-ivar** [comment]
Note that we unprefixed everything _but_ `navigator.mozGetUserMedia`. This was intentional, as we want people to use `navigator.mediaDevices.getUserMedia` instead.

**Comment by jan-ivar** [comment]
In addition, the prefixed versions will continue to exist for a couple of releases, but now is a good time to prepare. We should probably refactor things in a way that works for both old and new.

**Comment by fippo** [comment]
#164 only uses navigator.mozGetUserMedia -- see also https://github.com/webrtc/adapter/pull/164#discussion_r52477419
