### ISSUE TITLE
Edge to Chrome: InvalidAccessError in RTCPeerConnection.prototype._transceive

### ISSUE THREAD

**Issue by saxx** [webrtcHacks/adapter#165]
I'm using the latest version of adapter.js (`94fd14d`) and I'm trying to get WebRTC video communication working on Microsoft Edge.

It already works fine in Firefox and Chrome, but I get an `InvalidAccessError` in Microsoft Edge (25.10586, Windows 10, tested on two different machines). According to the browser console, the error is thrown in 

```
window.RTCPeerConnection.prototype._transceive = function(transceiver,
[....]
```

at the bottom, where it says

```
 transceiver.rtpReceiver.receive(params);
```

(line 1156 in the version mentioned above). Any ideas? Thanks.

**Comment by fippo** [comment]
what SDP are you passing in?

**Comment by saxx** [comment]
This is the the SDP that Edge receives (from Chrome), and that I try to pass into `setRemoteDescription`.

```
v=0
o=- 2752502633284210002 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE video
a=msid-semantic: WMS WIHcP5GdIwOaQRxMi1MgIUOAsqA2d8SQTbJr
m=video 9 UDP/TLS/RTP/SAVPF 100 116 117 96
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:MAMhLeMiwVgab5+3
a=ice-pwd:hB9e9HqW0+a0IUuFxZ2fjqey
a=fingerprint:sha-256 A7:1A:BB:79:3A:52:E8:5D:0F:C7:F3:39:2F:A0:49:E0:18:12:52:39:B4:2C:74:FB:2A:B9:F9:B2:70:3D:2B:71
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=sendrecv
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtpmap:116 red/90000
a=rtpmap:117 ulpfec/90000
a=rtpmap:96 rtx/90000
a=fmtp:96 apt=100
a=ssrc-group:FID 1956990217 1694205409
a=ssrc:1956990217 cname:SV9iRb9YNwxKplzg
a=ssrc:1956990217 msid:WIHcP5GdIwOaQRxMi1MgIUOAsqA2d8SQTbJr 320480e5-814e-41f7-a9e6-1a4571b1fe6f
a=ssrc:1956990217 mslabel:WIHcP5GdIwOaQRxMi1MgIUOAsqA2d8SQTbJr
a=ssrc:1956990217 label:320480e5-814e-41f7-a9e6-1a4571b1fe6f
a=ssrc:1694205409 cname:SV9iRb9YNwxKplzg
a=ssrc:1694205409 msid:WIHcP5GdIwOaQRxMi1MgIUOAsqA2d8SQTbJr 320480e5-814e-41f7-a9e6-1a4571b1fe6f
a=ssrc:1694205409 mslabel:WIHcP5GdIwOaQRxMi1MgIUOAsqA2d8SQTbJr
a=ssrc:1694205409 label:320480e5-814e-41f7-a9e6-1a4571b1fe6f
```

**Comment by KaptenJansson** [comment]
Thanks for reporting.

I think we haven't tested MS edge to other browsers to much yet, sorry should have added that to the release info. When we last tested using apprtc, edge to edge worked fine (https://10-dot-apprtc.appspot.com/).

**Comment by saxx** [comment]
OK, thanks for the info.
Is it okay if I'll leave this issue open for now, until it is resolved at a later time?

**Comment by KaptenJansson** [comment]
Yes lets keep it open and keep filing issues, appreciate the help, especially cross browser testing. Just make sure to include Browser name, version and some logs.

Thanks!

**Comment by fippo** [comment]
Chrome and Edge are not interoperable with video yet (Edge only supports H264UC, Chrome only VP8 and VP9). Quite likely this leads to the intersection of common codecs being empty and receive() errors on that.

**Comment by KaptenJansson** [comment]
Closing this for now as @fippo said, browsers aren't compatible with each other yet.

**Comment by fix2015** [comment]
is they still aren't compatible with each other?

**Comment by fippo** [comment]
Edge supports both VP8 and H264 since the creators update earlier this year. With that, video is interoperable too.

**Comment by fix2015** [comment]
so is it work for you edge vs FF or chrome?
