### ISSUE TITLE
module.exports.getUserMedia != navigator.mediaDevices.getUserMedia

### ISSUE THREAD

**Issue by eddiemonge** [webrtcHacks/adapter#170]
Why does `module.exports.getUserMedia` not equal `navigator.mediaDevices.getUserMedia`? I know this isn't really a valid use of `module` but its the easiest way to quiet all the logging going on for now. 

I'd expect getUserMedia to be the same in both (Chrome).

```
<script>var module={};</script>
<script src="/javascripts/adapter.js"></script>
<script>
  console.log(module.exports.getUserMedia)
  console.log(navigator.mediaDevices.getUserMedia)
</script>
```

Outputs:

```
function (constraints, onSuccess, onError) {
    if (constraints.audio) {
      constraints.audio = constraintsToChrome(constraints.audio);
    }
    if (constraints.video) {
      constraints.video =…
------------------------------------------------------------------------------------------
function (constraints) {
      return requestUserMedia(constraints);
    }
```

**Comment by jan-ivar** [comment]
IMHO we should get rid of the `getUserMedia` export.

**Comment by KaptenJansson** [comment]
Yes I agree we should remove the export, we should just shim the API, not exposing wrappers and internal functions.

I've started on Adapter2.0 by separating the shims by browser and expose shim methods for each api, PTAL at https://github.com/webrtc/adapter/pull/164.

**Comment by KaptenJansson** [comment]
Removed in #164.
