### ISSUE TITLE
Move from JSHint and JSCS to ESLint

### ISSUE THREAD

**Issue by samdutton** [webrtcHacks/adapter#176]
As per samples.

**Comment by KaptenJansson** [comment]
I do not want to scare anyone but eslint gave me 400+ errors ;) I will take a look soonish.

**Comment by samdutton** [comment]
:^O

Command line ESLint can autofix _some_ errors:

http://eslint.org/blog/2015/09/eslint-v1.4.0-released

**Comment by KaptenJansson** [comment]
Thanks for the tip!

**Comment by fippo** [comment]
_bump_ -- i'd note that jshint and jscs are currently not checking all files. But fixing that is futile if we move to eslint anyway.

@KaptenJansson we can do it next week with coffee!
