### ISSUE TITLE
Minification breaks Underscore/PhoneFormat

### ISSUE THREAD

**Issue by gregor** [webrtcHacks/adapter#177]
When I minifiy `adapter.js` using [grunt-contrib-uglify](https://github.com/gruntjs/grunt-contrib-uglify) into one vendor file to be used in my project together with e.g. [Underscore](https://github.com/jashkenas/underscore) and [PhoneFormat](https://github.com/albeebe/phoneformat.js) these libraries break and are unavailable.

**Comment by KaptenJansson** [comment]
Currently working on improving adapter in #164 which should take care of leaking globals etc. You could either checkout that branch and build adapter.js targets and try to uglify those or you could give me your uglifiy config and I can try.

**Comment by KaptenJansson** [comment]
#164 has now landed, could you try again? If not, please read my last comment.

**Comment by gregor** [comment]
@KaptenJansson Totally missed you initial comment. Will take a look at this and give it a try sometime today.

**Comment by gregor** [comment]
@KaptenJansson  Have tried to make it work to no avail. Ran the grunt task to create the adapter and implemented the `adapter_no_edge_no_global.js` file but that does not seem to fly.

**Comment by KaptenJansson** [comment]
Could you provide the uglify options you use in Gruntfile.js?

**Comment by KaptenJansson** [comment]
Also could you elaborate what doesn't fly mean? I just tried and it works fine, I get a minified version of adapter.js and adapter_no_edge_no_global.js.

**Comment by KaptenJansson** [comment]
Reading up on the original comments in this issue, I assume it still breaks other modules?

**Comment by KaptenJansson** [comment]
Ping

**Comment by KaptenJansson** [comment]
Ping

**Comment by gregor** [comment]
@KaptenJansson Excuse the late reply. I enjoyed a monthlong vacation :) My co-worker, who took over, was blocked by the broken bower integration: https://github.com/webrtc/adapter/issues/206. I tried again with the workaround provided in that issue. Minification properly works now.

**EDITED** I edited my comment as jetlag caused me to depend on the formerly leaking global `window.getUserMedia` instead of the expected `navigator.mediaDevices.getUserMedia`

**Comment by fippo** [comment]
window.getUserMedia is not a thing (anymore). use navigator.getUserMedia or preferably navigator.mediaDevices.getUserMedia

**Comment by gregor** [comment]
@fippo Thanks for the hint. You were faster in posting than I was editing my post.

**Comment by KaptenJansson** [comment]
Awesome, could you clarify that adapter now plays nice with other modules as well?

**Comment by KaptenJansson** [comment]
Yes, adapter.js should now be a proper shim (replaces/modifies/adds API's silently), i.e. you should use the standardized API's, not wrappers.

**Comment by gregor** [comment]
Yes, it does not cause any problems with Underscore and PhoneFormat when minifying anymore (or the roughly 50 other dependencies we have for that matter).

**Comment by KaptenJansson** [comment]
Good stuff!
