### ISSUE TITLE
test failure: impossible GUM constraints test broken in Canary

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#180]
@alvestrand: travis builds of canary (which has the experimental web platform flag on) fail in the 

```
Call getUserMedia with impossible constraints
```

test. I suspect that is because you recently added support for that but this bogus case is not rejected (yet). Can you check if the test makes sense to you and fix it before unflagging the feature?

(another issue caught by tests \o/)

**Comment by alvestrand** [comment]
This is interesting .... I found code in Chrome that treated mandatory framerate 0 specially (setting it to 1 instead of failing). I made it accepted without comment and marked it as "needs investigation to see if anyone uses this".
I'll have to look at what the errors are.

**Comment by KaptenJansson** [comment]
I think that code might have something to do with fractional framerates.

**Comment by KaptenJansson** [comment]
Closing. We should consider unit tests instead.
