### ISSUE TITLE
adapter.js versioning policy + minimum required versions

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#19]
In order to make adapter.js dependable, there needs to be some kind of versioning system.

Currently, it is rather unclear what you need to do when upgrading adapter which keeps even me from using it. In the past, things have been removed without notice. And I want to do that in this PR https://github.com/webrtc/adapter/pull/18#discussion_r26180825 as well, so this is not a theoretic problem.

Let's use [semver](http://semver.org) as follows:
Patch version: backward compatible fixes you absolutely want to pull in and that don't break anything.
Minor version: addition of new features.
Major version: removal of old APIs/functionality/workarounds in adapter.js.

The major version is a little tricky. We use adapter to shim functionality that is yet there or only exist newer versions of Chrome and Firefox. But we don't want to keep "old cruft" around forever. For example the shim of MediaStream.prototype.getAudioTracks (mid-2013)... 

On talky, I am seeing chrome versions which do not support DTLS and some other ... interesting... errors. I do not want to support those versions anymore. If you use a 6+ month old browser you are probably getting an experience which is worse than what you should get...
Chromium 37 (possibly older versions of Chrome as well) seem to have an [issue with opusfec](https://code.google.com/p/webrtc/issues/detail?id=4378).

Hence we should also require a minimum browser version (both FF and Chrome) and bump the major version if we change that.

thoughts @samdutton? (cc @bemasc @damonoehlman)
The final version will be an empty file because we don't need a shim anymore! Not sure if that is a realistic goal but... :-)

**Comment by samdutton** [comment]
SGTM, with semver versioning: starting with adapter-1.0.0.js?

Would we keep old versions or just rename?

@juberti @jiayliu WDYT?

**Comment by fippo** [comment]
@samdutton yes. Unless you want a fancy name that requires you to start at 2.0.0 :-)

Using npm for versioning automagically creates git tags which appear as releases on github (but only if one pushes with --tags...). I suppose bower can do something similar.

**Comment by samdutton** [comment]
I think annotated git tags are probably the way to go, using the mechanism described [here](https://help.github.com/articles/creating-releases/). Creating the tags manually is probably OK.

@juberti @jiayliu If no objections, I'll go ahead and add tag/release semver versioning, starting with 1.0.0.

**Comment by fippo** [comment]
@samdutton I can do a PR with the minimum version thing over the weekend

**Comment by samdutton** [comment]
SGTM

**Comment by fippo** [comment]
done as part of #18 -- I don't like breaking my own PRs :-)

**Comment by fippo** [comment]
@samdutton ping? I want #23 without writing the code myself :-)

**Comment by kashifshamaz21** [comment]
This is an important piece to add to this library, as the spec is still evolving, and to develop stable apps using webrtc-adapter would need locking down on some specific release versions to not get trapped with removal/change in APIs :)

**Comment by bklang** [comment]
Adding my voice in support of this. Adding a version number would make it easy for downstream automated packagers, such as https://rails-assets.org, to distribute this as a gem.

**Comment by alvestrand** [comment]
There seems to be an npm published already, which is currently at version 0.7.0.
npm owner ls gives bemasc and willscott as owners. Do @bemasc @willscott  work as tags?

**Comment by alvestrand** [comment]
I have now pushed a version-tagged version of _this_ repo as version 0.1.0. Expect the last digit to be increasing often for a while.

I'll write an interpretation of the semver requirements on the README - basically, I think we should increase the minor version every time we have a version with a change, the middle version every time we add some new shim so that something that used to not work now works, and the major version only when we do incompatible changes.

I want to wrap the whole adapter.js in (function(){...})() before I go to version 1.0, as that seems to be the standard Javascript construct for rendering module-local variables invisible to the rest of the world.

**Comment by willscott** [comment]
You could also consider having a browserify'ed build process, which would do that wrapping for you, and allow the shim to be compiled as part of a larger code base.

**Comment by fippo** [comment]
I think we are done here for now.
