### ISSUE TITLE
bump minversion and get rid of legacy code

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#192]
if we do a major bump anyway we should update the minimum versions supported. Currently this is 
- Firefox 31(released 2014-07-21)
- Chrome 38 (released 2014-10-07)
- Edge 10547 (insider-only version I think? 10587 is from Nov 2015 and the first stable version with ORTC support)

I think we can remove a fair amount of code that is no longer needed.
@jan-ivar: thoughts on a better Firefox version? Last ESR version maybe?
@KaptenJansson @alvestrand same for Chrome? Chrome 43 with the srcObject shim would be good imo

I don't think there are relevant changes in Edge between 10547 and 10587 which is the current stable so no need to bump that.

**Comment by KaptenJansson** [comment]
+1 for removing old code ;). Let's settle on latest Chrome stable and FF esr then?

**Comment by jan-ivar** [comment]
Discussed with @fippo, even though Firefox ESR 45 shipped yesterday, I agree we should probably support 38 (the previous ESR) for at least another month.

**Comment by fippo** [comment]
fab. Will go for chrome 48 as min version. I don't see any shim code that was obsoleted between 38 and 48 unfortunately. Looking forward to the constraints changes.

**Comment by fippo** [comment]
little point in doing this. Lets just remove adapter.js alltogether one day ;-)
