### ISSUE TITLE
Call to RTCSessionDescription not working on Edge

### ISSUE THREAD

**Issue by GitDaf** [webrtcHacks/adapter#195]
Calling new RTCSessionDescription() generates an error in Edge. Would need to use new window.RTCSessionDescription() instead.

**Comment by KaptenJansson** [comment]
I believe we do https://github.com/webrtc/adapter/blob/master/src/js/edge/edge_shim.js#L28?

**Comment by GitDaf** [comment]
Yes, indead, and calling the function from console works fine, but it fails on this line https://github.com/webrtc/adapter/blob/master/src/js/edge/edge_shim.js#L50

**Comment by KaptenJansson** [comment]
Aha well spotted ;).

**Comment by KaptenJansson** [comment]
I just tried and it works fine. What version of Edge?

**Comment by KaptenJansson** [comment]
Ping

**Comment by GitDaf** [comment]
Sorry for the response delay. I figured out after some tracking what was wrong. adapter.js was referenced 2 times at different levels, this is what led to this issue (only happened with Edge though!). Everything is fine now. I'm closing the issue.
