### ISSUE TITLE
Bower version does not match latest release

### ISSUE THREAD

**Issue by laurent-le-graverend** [webrtcHacks/adapter#199]
Bug when installing with bower.

```
bower install
bower webrtc-adapter#1.0.1     ENORESTARGET No tag found that was able to satisfy 1.0.1
Available versions in git://github.com/webrtc/adapter.git: 0.2.9, 0.2.8, 0.2.7, 0.2.6, 0.2.5, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.9, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1.0
```

New release needed.

**Comment by KaptenJansson** [comment]
Thanks for reporting this. I know it doesn't but that's because I have not figured out if the need is different for bower users. 

Do you only need a commonJS/requireJS module (require('webrtc-adapter')) or do you also need a browserified version?

**Comment by dansullivan86** [comment]
@KaptenJansson Looks like you just need to tag the release, same issue for NPM users.

**Comment by KaptenJansson** [comment]
Release made.

Still need to know for Bower users:  do you need a commonJS/requireJS module (require('webrtc-adapter')) or do you also need a browserified version?

**Comment by dansullivan86** [comment]
The norm for bower is to include a compiled version

**Comment by KaptenJansson** [comment]
I thought so. Will try to fix that.
