### ISSUE TITLE
attachMediaStream on ChromeBeta mobile(android) is returning error

### ISSUE THREAD

**Issue by mbellezi** [webrtcHacks/adapter#200]
When I call:

`attachMediaStream(element, '');
`

or

`attachMediaStream(element, null);
`

on Chrome Beta 49 on Android 5.1.1 I have the error:

> deps.js:13307 TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
>     at TypeError (native)
>     at HTMLVideoElement.Object.defineProperty.set (https://192.168.0.105:3000/js/deps.js:76464:26)
>     at attachMediaStream (https://192.168.0.105:3000/js/deps.js:76887:25)

Any thoughts?

**Comment by KaptenJansson** [comment]
You should provide a MediaStream as a 2nd argument.

**Comment by KaptenJansson** [comment]
FYI we plan to remove this method shortly.
