### ISSUE TITLE
adapter.js bower setup

### ISSUE THREAD

**Issue by s-silva** [webrtcHacks/adapter#206]
Guys,

`bower install adapter.js` stopped working today and I tried changing it to `bower install webrtc-adapter` and including `src/js/adapter_core.js` but it fails without require.js.

And http://webrtc.github.io/adapter/adapter-latest.js is no longer working.

I got everything working with an older version or adapter.js, please close this issue if the changes were intentional.

**Comment by rbenitez** [comment]
Hi, 

In addition, if you execute that command, the adapter.js browserify isn't in the folder.

When will it be?

Thanks

**Comment by KaptenJansson** [comment]
Yes sorry for this, I've fixed the adapter-latest link.

I will look into adding browserified versions to the bower releases without adding it to the source.

In the meanwhile I suggest that you install an older version of adapter (0.2.9).

**Comment by KaptenJansson** [comment]
If anyone has a suggestion on how to publish a bower package with browserified artifacts not part of the source please let me know. I do not want to have two repos/branches for this. npm is a lot easier since it uploads the package to npmjs where we can include browserified artifacts without having them stored in github while bower downloads directly from github.

**Comment by s-silva** [comment]
@KaptenJansson thanks!

Isn't adding browserify into bower dependencies an option?

**Comment by KaptenJansson** [comment]
I'm not that familiar with bower but AFAIK browserify does not exist in bower registry. Also how would it install and execute it? If it uses node, you might as well just use NPM.

**Comment by KaptenJansson** [comment]
I have a suggestion, what about using gh-pages for bower instead of master? To me it seems that most people using adapter as a module uses node while the people using bower wants precompiled versions.

To boil it down, do you require a bower setup with both a AMD module and a precompiled version or will just the precompiled version do? 

cc @laurent-le-graverend

**Comment by laurent-le-graverend** [comment]
I guess the precompiled version should be enough, not minified.

Most of project's build process are handling the vendors libraries concatenation and minification.

I guess most people would expect to have bower file indexing the non-minified precompiled version in a folder like like `/dist/adapter.js`

**Comment by rbenitez** [comment]
I agree with @laurent-le-graverend, before the re-factory, this library was in adapter.js/adaper.js. It was like for bower and node.

**Comment by maxwellium** [comment]
**current workaround** in your bower.json is to alter entry to 

```
"webrtc-adapter": "gh-pages"
```

and then include bower_components/webrtc-adapter/adapter-1.0.4.js

don't forget to revert, once this is fixed ;)

**Comment by xdumaine** [comment]
Hitting this as well.

**Comment by dansullivan86** [comment]
Also seeing this using NPM, in addition attempting to use the "gh-pages" branch results in a Permission denied error

**Comment by KaptenJansson** [comment]
Sorry I've been traveling, will look into this later this week.

**Comment by KaptenJansson** [comment]
@dansullivan86 could you elaborate what issue you see using NPM? This is a bower workaround.  It should work on NPM, if not could you file a new issue with the details.

**Comment by KaptenJansson** [comment]
I've now added the workaround as an official way of doing it for now.

Instructions [here](https://github.com/webrtc/adapter/blob/master/README.md).

Please let me know how it works out for you.

**Comment by KaptenJansson** [comment]
Fixed
