### ISSUE TITLE
Current latest link is misspelled

### ISSUE THREAD

**Issue by AlexCline** [webrtcHacks/adapter#207]
**Browsers and versions affected**
All

**Description**
The link in the Github pages branch to the latest release (1.0.2) is titled 'lastest', not 'latest'.

http://webrtc.github.io/adapter/adapter-lastest.js

**Steps to reproduce**
Go to http://webrtc.github.io/adapter/adapter-latest.js

**Expected results**
http://webrtc.github.io/adapter/adapter-latest.js, see latest release

**Actual results**
http://webrtc.github.io/adapter/adapter-lastest.js is a valid link,
http://webrtc.github.io/adapter/adapter-latest.js is not a valid link

**Comment by KaptenJansson** [comment]
Thanks for reporting, fixed.
