### ISSUE TITLE
adapter.js npm install errors

### ISSUE THREAD

**Issue by hagnanfaces** [webrtcHacks/adapter#231]
Hello. I tried to install web-rtc-adapter from https://www.npmjs.com/package/webrtc-adapter-test
- bower install webrtc-adapter
- npm install webrtc-adapter

But when I did npm install webrtc-adapter it gives me errors like this 

```
npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "webrtc-adapter"
npm ERR! node v0.10.43
npm ERR! npm  v3.8.1
npm ERR! code ENOSELF

npm ERR! Refusing to install webrtc-adapter as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pachou/bower_components/webrtc-adapter/npm-debug.log
```

Please, need help...

**Comment by KaptenJansson** [comment]
It's now named "webrtc-adapter", https://www.npmjs.com/package/webrtc-adapter. 

You might want to uninstall https://www.npmjs.com/package/webrtc-adapter-test.

**Comment by hagnanfaces** [comment]
It is the same problem with webrtc-adapter..

**Comment by KaptenJansson** [comment]
It looks like you are running npm install from /home/pachou/bower_components/webrtc-adapter/, i.e. the bower package.

You should run it from the root of the github checkout.

You use either NPM or Bower, and they should be run from within the root of the repo.

**Comment by snobear** [comment]
I'm having issues using webrtc-adapter on npm as well (v1.3.0). I can successfully install it with

```
npm install --save webrtc-adapter
```

and then I include the module with

```
require('webrtc-adapter')
```

but in the Chrome console I get

```
Uncaught ReferenceError: getUserMedia is not defined
```

Seems like its including the lib OK because when I log it with

```
console.log(require('webrtc-adapter'));
```

I get

```
Object {browserDetails: Object, browserShim: Object}
browserDetails: Object
browserShim: Object
disableLog: function (bool)
extractVersion: function (uastring, expr, pos)
__proto__: Object
```

Any ideas?

**Comment by fippo** [comment]
@snobear did you try window.navigator.getUserMedia or window.navigator.mediaDevices.getUserMedia?

**Comment by snobear** [comment]
I'm actually working on getting Kurento working and the call that triggered `getUserMedia` was

```
kurentoUtils.WebRtcPeer.WebRtcPeerSendonly
```

Let me take a look at the source behind that and see what its doing.

**Comment by snobear** [comment]
The `getUserMedia()` call is made [here](https://github.com/Kurento/kurento-utils-js/blob/cf4aa9a690a0e1b1d51f7a291e3e2e8d29aa8d6e/lib/WebRtcPeer.js#L603) and looks like its just calling `getUserMedia` straight up with no prefix.

**Comment by snobear** [comment]
I'm seeing a lot of chatter online about needing to use the older adapter 0.x.x version due to various issues with npm and/or Kurento.  Instead of using npm I just went with this in my index html and its working well:

```
<script type='text/javascript' src='http://webrtc.github.io/adapter/adapter-0.2.9.js'></script>
```

**Comment by KaptenJansson** [comment]
Re getUserMedia(), it should be updated and use the standard method (window.navigator.mediaDevices.getUserMedia, which should be shimmed now anyway by adapter.js, in the early days of adapter.js we created a global getUserMedia method instead of shimming the original API).
