### ISSUE TITLE
adapter-latest.js throws a 404

### ISSUE THREAD

**Issue by srnarayanan** [webrtcHacks/adapter#237]
**Browsers and versions affected**
Chrome M49, 50, 51

**Description**
https://github.com/webrtc/adapter#usage mentions http://webrtc.github.io/adapter/adapter-latest.js, but the latter throws a 404 Not found.
Specific / numbered branch versions like http://webrtc.github.io/adapter/adapter-1.0.5.js works as expected 

**Steps to reproduce**
I found this while verifying a webrtc bug fix https://bugs.chromium.org/p/webrtc/issues/detail?id=5624

(Open https://jsfiddle.net/vdr3at78/ and try running the script/open JS console. 
Replacing the HTML script with `<script src="https://webrtc.github.io/adapter/adapter-1.0.5.js"></script>` worked)

**Comment by srnarayanan** [comment]
@KaptenJansson please have a look. Thanks!

**Comment by alvestrand** [comment]
Fix #235 merged.
