### ISSUE TITLE
Shimming RTCPeerConnection.getStats() does not fix Chrome reports when using Promises

### ISSUE THREAD

**Issue by gregor** [webrtcHacks/adapter#243]
**Browsers and versions affected**
Chrome

**Description**
If you implement RTCPeerConnection.getStats() using promises, webRTC adapter fails to map the reports Chrome returns into standards compliant ones.

**Steps to reproduce**

``` coffeescript
pc = new window.RTCPeerConnection pcConfig
pc.getStats()
.then (track_stats) => console.log track_stats
```

**Expected results**
This should return key, value pairs.

**Actual results**
 Instead you get the non-compliant Chrome reports with track_stats.result() etc.

The broken code can be found in:
https://github.com/webrtc/adapter/blob/c3a32562ecbf5b0e7cfb76807a3b522d60b42028/src/js/chrome/chrome_shim.js#L140-L149

The stats will be shimmed if you pass in 1 argument and that argument (the selector) is null. Workaround would be:

``` coffeescript
pc = new window.RTCPeerConnection pcConfig
pc.getStats null
.then (track_stats) => console.log track_stats
```

If you want to make use of a selector, it will currently not work.

**Comment by fippo** [comment]
yeah, the behaviour is bad but somewhat consistent with the chrome behaviour of returning the old stats unless a track selector (or null) is passed

**Comment by gregor** [comment]
Problem is that that it will only return new stats if you pass in null as the selector. If you do pass in a selector it will return Chrome style stats.

**Comment by fippo** [comment]
IIRC the reason for not shimming this was that chrome [doesn't accept a track as first argument anyway](https://bugs.chromium.org/p/webrtc/issues/detail?id=2031). Just returning full stats without looking at the selector is probably going to lead to confusion as well but probably better than the current behaviour.

@alvestrand WDYT?

**Comment by alvestrand** [comment]
That makes no sense. If you're shimming, you can pass the first argument to the shimmed function as the second argument to the built-in function.

It looks as if it is actually being done for the callback case on line 135, but not for the promise case. Why not?

https://github.com/webrtc/adapter/blob/master/src/js/chrome/chrome_shim.js

IDL for Chrome's current getstats:

https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/modules/mediastream/RTCPeerConnection.idl&q=GetStats%20file:.*.idl&sq=package:chromium&type=cs&l=111

**Comment by KaptenJansson** [comment]
I guess we could do as @alvestrand suggest and make the promise and callback behavior consistent?

**Comment by fippo** [comment]
wasn't that done in #244?

**Comment by KaptenJansson** [comment]
haha yes it was ;) He forgot to add fixed in front of the issue number and I totally did not connect the two for some reason. Thanks for pointing this out.
