### ISSUE TITLE
Graceful degradation if user disables webRTC

### ISSUE THREAD

**Issue by gregor** [webrtcHacks/adapter#260]
**Browsers and versions affected**
Firefox where the user manually disabled webRTC

**Description**
We use adapter.js shim in [Wire for web](https://app.wire.com) to simplify the webRTC implementation across browsers. Now a user reported the following problem, which obviously defeats the purpose of adapter.js but because you fail in this case our whole app does not load anymore.

He disabled webRTC manually in his browser settings. As you currently expect webRTC capabilities solely based on browser and version detection, adapter.js thows an error.

**Steps to reproduce**
1. manually disable webRTC in Firefox browser settings
2. go to https://app.wire.com and try to log in (or any other app that relies on apdater.js)

**Expected results**
adapter.js should smoothly degrade and recognize the missing APIs

**Actual results**
ReferenceError: mozRTCPeerConnection is not defined

Loading of adapter.js fails and thus subsequent vendor files in our minified version are not instantiated

**Comment by fippo** [comment]
ah... right. We had an additional check for mozRTCPeerConnection because of that in the past but that got removed. I think returning early in Firefox's shimPeerConnection is the right thing to do. Probably along with something the browser detection.

**Comment by KaptenJansson** [comment]
I agree, thanks for filing this. We should have this safeguard in one place. Browser detection is probably a good place!

**Comment by gijsk** [comment]
I _think_ this library is included by airbnb (but I'm having to divine it from minified code, so I could be wrong!), and this issue caused https://bugzilla.mozilla.org/show_bug.cgi?id=1271430 . Easily fixed by re-enabling webrtc, of course, but it seems that the issue from the initial comment is now affecting production sites. :-(

**Comment by gregor** [comment]
Thanks for moving forward with this. @gijsk It's been affecting our production site since I initially uncovered and filed it after end user feedback.
