### ISSUE TITLE
Linter should enforce concatenation of strings longer than 80 rather than \

### ISSUE THREAD

**Issue by KaptenJansson** [webrtcHacks/adapter#273]
**Browsers and versions affected**

**Description**

**Steps to reproduce**

**Expected results**

**Actual results**

**Comment by dandv** [comment]
Without more context, this seems unrelated to WebRTC?

**Comment by KaptenJansson** [comment]
This is basically a todo for myself. We have linters (they are not all the same yet, eslint and jslint I believe) in all webrtc/ sub repos and they should enforce the style that we want rather than us providing feedback on it.
