### ISSUE TITLE
Make adapter a npm module.

### ISSUE THREAD

**Issue by andresusanopinto** [webrtcHacks/adapter#3]
The previous existent package.json was just to manage dependencies for apprtc for travis and not a real package.json for this project.

**Comment by DamonOehlman** [comment]
Yes, I think this will take a bit of thought to make happen (well), but I'd be more than happy to help out where appropriate to get the adapter code to a point where it was genuinely npm + browserify friendly if that was desired.

Not something that would be too hard to do, but all the direct patching of functions into the `window` global would definitely have to be addressed.

**Comment by juberti** [comment]
@fippo does your PR #13 resolve this?

**Comment by fippo** [comment]
Partially. It doesn't add a package.json nor does it publish to npm.

**Comment by DamonOehlman** [comment]
This looks like a good start, but I'd advocate going with a [UMD](https://github.com/umdjs/umd) approach rather than addressing just a single module pattern and attacking the problem piecemeal.   I think while it isn't as good as doing a refactoring along the lines of #6 it will make adapter.js a potential building block in any application using a module system.

**Comment by juberti** [comment]
Can you spell out exactly what you have in mind?

**Comment by DamonOehlman** [comment]
I'll do a PR which demonstrates what I mean. I'll need to check a few things with NICTA before signing the CLA but it should serve a demonstration even if it can't be merged immediately.

cc @silviapfeiffer

**Comment by DamonOehlman** [comment]
Okay - I've done what I can to illustrate the beginning of what I think is required:

https://github.com/DamonOehlman/adapter/commit/cc9938733819250f4b0048f365904a17f3d4f20d

**NOTE:** There's some intentionally bad indentation here to try and keep the diff as useful as possible for digesting how the file has been written to be compatible with CommonJS, AMD and also traditional window globals.

Also, to try and provide clarity on how this can be used once the various module patterns are supported I've tried to provide some lightweight examples also:

https://github.com/DamonOehlman/adapter/tree/module-pattern-compatibility/examples

Now, I haven't ensured that what I have done is compatible with the current webrtc samples, nor have I fixed any linting errors.  It is, however, what I think makes sense as a starting point for facilitating #8 and #6 as well as this issue.

Have a good weekend all :)

**Comment by alvestrand** [comment]
(picking up the bug list after a long quiet)
what I see missing in the module patterning is the actual polyfilling - writing into navigator and all the other places where polyfill is needed.

Is there a pattern that would let us write a proper, noninvasive module, have a single function "install" that scribbles all over the place, and have the "install" function be called if adapter.js is just included "plain" in a page, but not when it's imported by a package manager?

**Comment by JacopoDaeli** [comment]
Any news?

**Comment by KaptenJansson** [comment]
See #38.

**Comment by KaptenJansson** [comment]
Fixed in #38.
