### ISSUE TITLE
Issue :Edge to Edge -DTLS handshake failed

### ISSUE THREAD

**Issue by sowmyan18** [webrtcHacks/adapter#306]
**Browsers and versions affected**
MS Edge 

**Description**

I tried MS Edge to MS Edge RTC peer communication  by manually exchanging Offer sdp and answer sdp in severless peer connection application https://cjb.github.io/serverless-webrtc/serverless-webrtc.html  using latest adapter shim js but getting  following error  
“ORTC18615: ORTC RTCDtlsTransport : DTLS handshake failed .hr=c004e00f “ 
when I checked with  this error I did the changes by referring  http://stackoverflow.com/questions/27932853/dtls-handshake-not-completing-ortc-prototype but still the error persist. Please help me out in resolving this error .

**Steps to reproduce**
Use latest adapter shim js in the application https://cjb.github.io/serverless-webrtc/serverless-webrtc.html to establish peer connection .Using the latest adapter shim js in the above mentioned application was able establish connection in chrome, firefox but facing problem in MS Edge.
Using  same adapter.js was able create offer Sdp in Microsoft Edge.  Tried  by manually exchanging Offer sdp and answer sdp b/w the peers in two different MS edge browser not able to establish the peer connection on edge and encounter the error.
“ORTC18615: ORTC RTCDtlsTransport : DTLS handshake failed .hr=c004e00f “

**Expected results**
Peer connection should establish on MS Edge and video should appear 

**Actual results**
Encountered error 
“ORTC18615: ORTC RTCDtlsTransport : DTLS handshake failed .hr=c004e00f “

**Comment by KaptenJansson** [comment]
Thanks for reporting, could you also include the MS edge build number? Thanks!

**Comment by sowmyan18** [comment]
I am using  Microsoft Windows 10 of OS build 10586.218 and Microsoft Edge 25.10586.0.0

**Comment by fippo** [comment]
That page doesn't let me join/create a room in Edge 14316... @sowmyan18 can you paste the offer/answer SDPs?

**Comment by sowmyan18** [comment]
I am able  to create room and join room in https://cjb.github.io/serverless-webrtc/serverless-webrtc.html using latest adapter shim js ..  with two web cam  and two Edge browsers with version 25.10586.0.0. I am attaching adapter.js used  in above demo as adapter.txt as not able to upload as js file and also offer and answer SDPs
[adapter.txt](https://github.com/webrtc/adapter/files/273967/adapter.txt)

[edge_answer.txt](https://github.com/webrtc/adapter/files/273960/edge_answer.txt)
[edge_offer.txt](https://github.com/webrtc/adapter/files/273961/edge_offer.txt)

**Comment by fippo** [comment]
I can't really reproduce, even after making modifications to the script. I saw a missing a=end-of-candidates in the answer but that seems unrelated and does not happen in your SDP

**Comment by sowmyan18** [comment]
I wanted attach my source folder but not able to attach .zip nor .war file  to share with you in order to reproduce the issue. pl let me how can I share my source folder

**Comment by sowmyan18** [comment]
I have two source code folders "serverless" and "serverless_edge"" .   https://github.com/sowmyan18/Edge-WebRTC

```
In serverless I have used latest adapter.js and in js/serverless-webrtc.js I have disable the creation of data channel which works for chrome and firefox.It works fine in chrome but in Edge it throws ORTC RTCDtlsTransport : DTLS handshake failed .hr=c004e00f “. and remote video stream is empty

In serverless_edge I have used latest adapter.js and in js/serverless-webrtc.js I have implemented addIcecandidate to add ice candidate to other peer by using "RTCIceCandidate(event.candidate)" on onicecandidate event . This I refered by https://webrtc.github.io/samples/src/content/peerconnection/pc1/ implementation which establishes the peer connection in Edge browser also. Using this it throws error in chrome for adding Ice candidate and doesn't work .
In Edge I don't get error of adding ice candidate but still persist with "ORTC RTCDtlsTransport : DTLS handshake failed .hr=c004e00f “. error. and remote video stream is empty
```

Please find the logs 
[edge_answer_log.txt](https://github.com/webrtc/adapter/files/279539/edge_answer_log.txt)

[edge_offer_log.txt](https://github.com/webrtc/adapter/files/279537/edge_offer_log.txt)

**Comment by fippo** [comment]
I could reproduce locally. Looks like ice succeeds but DTLS fails for some reason. Odd...

**Comment by fippo** [comment]
@sowmyan18 can you check if https://fippo.github.io/paste/ works for you (open answer.html in second tab, paste offer to answer.html, paste answer back to original tab)

**Comment by sowmyan18** [comment]
@fippo I am still getting the same Dtls handshake error when I tested https://fippo.github.io/paste/ in Edge and didn't work for me. I got the local video only in offer page but in answer.html I didn't even get local video ..

**Comment by fippo** [comment]
are you testing this on a machine with at least two webcams? edge can't share cameras between tabs

**Comment by sowmyan18** [comment]
ya I tested with machine with 2 web cam
