### ISSUE TITLE
Package Babel presets conflict with local Babel presets

### ISSUE THREAD

**Issue by dansullivan86** [webrtcHacks/adapter#309]
My build system (Gulp), throws the error ' Couldn't find preset "es2015" ', as a result of the babel preset specified in package.json og adapter.js . It can't be found because I am using es2015-without-strict.

I am using NPM to get the package, and only want to use a prebuilt version.

I don't use grunt so haven't been able to test but think this could be resolved by moving the preset declaration inline.  e.g. transform: [['babelify', {"presets": ["es2015"]}]]

**Comment by KaptenJansson** [comment]
@davies147 WDYT?

**Comment by davies147** [comment]
Finally had a chance to look at this - perfectly good idea.

In fact I was not aware that the package.json settings in the adapter
 project could "leak" like that :(

I've submitted a patch in case it helps.
Steve

**Comment by davies147** [comment]
I cancelled the pull request because a) I made the same single-quotes
mistake as everyone else and b) Looks like someone else beat me to it.

:)

Cheers,
Steve

**Comment by KaptenJansson** [comment]
Thanks for the attempt;) Yeah I thought I would do it among a couple of other things, and yes the quotes bit me too since I just copied ;) and we do not have linting on the Gruntfile.js due to some strange failures seen there. Maybe can re enable it in the future.

**Comment by dansullivan86** [comment]
Looking at the new tagged version 1.3.0, it appears my suggestion of inline transforms was implemented however the babel block in package.json wasn't actually removed so the issue persists.
