### ISSUE TITLE
Edge error when setting iceTransportPolicy to "relay"

### ISSUE THREAD

**Issue by oooookk7** [webrtcHacks/adapter#323]
**Browsers and versions affected**
Microsoft Edge browser

**Description**
When setting the `iceTransportPolicy` to `"relay"` in Edge. I noticed the following error:

> ORTC18614: ORTC RTCIceGatherer: Transport endpoint allocation failed. hr=c004e00e.

I was trying to setup a `"relay"` (or forced TURN connections) for Chrome and Edge in an audio only environment.

**Steps to reproduce**
- Edge has to be the offerer and Chrome the answerer.
- At which step the error above was exactly thrown was unknown.

I simply did the following steps:

1) Get audio local MediaStream (Both Edge and Chrome):

```
getUserMedia({ audio: true, video: false })
```

2) Create RTCPeerConnection object (Both Edge and Chrome):

```
var pc = new RTCPeerConnection({
   iceServers: turnIceServersWithCredentials,
   iceTransportPolicy: "relay"
}, {
   // For older fallback
   optional: [{
      DtlsSrtpKeyAgreement: true
   }]
});
```

3) Edge creates local offer and sets local offer:

```
pc.createOffer({
  offerToReceiveAudio: true,
  offerToReceiveVideo: false
}).then(function (offer) {
  pc.setLocalDescription(offer).then(..).catch(..)
}).catch(...);
```

4) Chrome sets remote offer, creates answer and sets

```
pc.setRemoteDescription(offer, function () {
  pc.createAnswer(function (answer) {
    pc.setLocalDescription(answer, ..., ...);
  }, ...);
}, ...);
```

5) Edge sets remote answer 

```
pc.setRemoteDescription(answer).then(...).catch(...);
```

**Expected results**
Edge does an error when setting `iceTransportPolicy` to `"relay"` and generate `"relay"` candidates.

**Actual results**
Edge throws an error when configuration for `iceTransportPolicy` is `"relay"` and does not generate `"relay"` candidates.

**Comment by oooookk7** [comment]
Without setting the `iceTransportPolicy`, I tried forcing TURN connections by filtering out non-`"relay"` candidates manually using the following method:

```
pc.onicecandidate = function (evt) {
  if (evt.candidate) {
    if (evt.candidate.candidate.indexOf("relay") > 0) {
      // Send candidate
    }
  }
```

I noticed that `"relay"` candidates were not generated as well.

**Comment by fippo** [comment]
are you passing proper turn servers with _full_ urls like

```
turn:host:3478?transport=udp
```

**Comment by oooookk7** [comment]
@flippo, here is my example `iceServers` configuration url I am passing in:

```
iceServers: [{
  urls: ['turn:turnurl:<port>?transport=udp'],
  username: 'xxxxx',
  credential: 'xxxxx'
}]
```

**Comment by oooookk7** [comment]
@fippo I managed to get relay candidates with `?transport=udp` with specific port `3478`. Thanks! awesome.

It seems like `?transport=tcp` didn't work. Is there any reasons for using `transport=udp' and the specific port`3478`?

**Comment by fippo** [comment]
Edge's RTCIceGatherer requires this (the Edge team is aware of this issue). TURN/TCP is not supported yet. adapter filters out any urls which would throw an error to make deployment easier.

I think some of this is mentioned over at [webrtchacks](https://webrtchacks.com/working-to-make-edge-dull-extended-qa-for-rtc-devs/)

**Comment by oooookk7** [comment]
Thanks. This was informative.

**Comment by xdumaine** [comment]
@fippo does Edge support IP addresses as host? I'm getting this error as well.

**Comment by fippo** [comment]
@xdumaine it does, make sure you have both port and ?transport=udp specified
