### ISSUE TITLE
sourceId not used on Chrome when mandatory/optional constraints are specified

### ISSUE THREAD

**Issue by paleozogt** [webrtcHacks/adapter#325]
**Browsers and versions affected**
Chrome, any version

**Description**
If you use a constraint that has `mandatory` or `optional` fields, `constraintsToChrome_` will not correct `deviceId` to Chrome-compatible `sourceId`.

For example, if you do this:

```
navigator.mediaDevices.getUserMedia({
    audio: {
        deviceId: {exact: myDeviceId}
    }
  });
```

it will get properly corrected to
`{
    "audio":{
        "mandatory":{
            "sourceId":"..."
        }
    }
}`

However, if you do this:

```
navigator.mediaDevices.getUserMedia({
    audio: {
        mandatory: {echoCancellation: false},
        deviceId: {exact: myDeviceId}
    }
  })
```

it essentially won't get modified:
`{
    "audio":{
        "mandatory":{
            "echoCancellation":false
        },
        "deviceId":{
            "exact":"..."
        }
    }
}`

**Steps to reproduce**

I've created a branch of the webrtc samples that shows the bug in the "Choose camera, microphone and speaker" demo:
   https://github.com/paleozogt/samples/tree/deviceId_bug/src/content/devices/input-output

**Expected results**

Using the new style `deviceId` constraint should get corrected to be `sourceId` on Chrome, no matter what other constraints are present.

**Actual results**

If a `mandatory` or `optional` field is already in the constraints, `constraintsToChrome_` will not correct `deviceId` to Chrome-compatible `sourceId`.

**Comment by fippo** [comment]
@jan-ivar can you take a look? I suspect mixing new and legacy constraints is what is unsupported here.

**Comment by jan-ivar** [comment]
This is intentional. Mixing doesn't drive convergence. @paleozogt why aren't you using spec constraints? Please use:

``` js
navigator.mediaDevices.getUserMedia({
    audio: {
        echoCancellation: {exact: false},
        deviceId: {exact: myDeviceId}
    }
  })
```

**Comment by paleozogt** [comment]
I guess I got a stale tutorial (e.g., [here](https://www.sitepoint.com/introduction-getusermedia-api/)) and thought that we were supposed to use `mandatory`.

**Comment by jan-ivar** [comment]
@paleozogt No worries. We're definitely guilty of changing things. Hopefully, once Chrome Canary lands with new syntax it'll simplify things.

**Comment by fippo** [comment]
that is the reason I typically refer people to https://webrtc.github.io/samples/
Those samples are curated to show the right thing and frequently updated when things change.

**Comment by hktalent** [comment]
me too
in desktop chrome
```
can not work
1、mandatory: {echoCancellation:'system'}

2、ios：chrome
 undefined is not an object (evaluating 'navigator.mediaDevices.getUserMedia 
```
@jan-ivar @paleozogt

**Comment by jan-ivar** [comment]
This is an old closed issue about outdated constraints syntax. Please see [MDN](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Syntax) for the latest syntax. `echoCancellation` is a boolean. For browser support see https://caniuse.com/#feat=stream
