### ISSUE TITLE
Edge not supporting `filter`

### ISSUE THREAD

**Issue by ngauthier** [webrtcHacks/adapter#327]
**Browsers and versions affected**

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586

**Description**

Above user agent causes JS error:

```
Object doesn't support property or method 'filter'
```

At this line:

https://github.com/webrtc/adapter/blob/d6e8b1a45add33f382fed872f32908ea225a1996/src/js/edge/edge_shim.js#L97

**Steps to reproduce**

Create webrtc peer connection with an edge browser and give it ice servers.

**Expected results**

No js error. Perhaps a for loop?

**Actual results**

JS error thrown above.

p.s. thank you very much for this library! If you need anything else, let me know.

**Comment by fippo** [comment]
what are you passing into the config? iceServers is supposed to be an array.

**Comment by ngauthier** [comment]
```
    iceServers: [
      {urls: [
        "stun:xxx.xxx.xxx.xxx:3478"
      ]},
      {
        urls: [
          "turn:yyy.yyy.yyy.yyy:3478",
          "turns:yyy.yyy.yyy.yyy:5439"
        ],
        "username": "redacted",
        "credential": "redacted",
        "credentialType": "password"
      },
      { urls: "stun:stun.l.google.com:19302" }
    ]
```

**Comment by ngauthier** [comment]
perhaps the third urls which is a string?

**Comment by fippo** [comment]
ah... right, this doesn't cover that .urls can be a string. Let me see if I can fix that...

**Comment by ngauthier** [comment]
Cool! thank you. It is part of the spec to be able to pass a string :)

https://www.w3.org/TR/webrtc/#idl-def-rtciceserver
