### ISSUE TITLE
Test adapter.js on latest Chrome canary which has unprefixed getUserMedia and new constraints

### ISSUE THREAD

**Issue by KaptenJansson** [webrtcHacks/adapter#335]
**Browsers and versions affected**
M53

Details in https://bugs.chromium.org/p/chromium/issues/detail?id=607439 and https://bugs.chromium.org/p/chromium/issues/detail?id=543997.

**Comment by fippo** [comment]
do all tests pass? Lets see in #336

**Comment by dandv** [comment]
M53 is now stable and has unprefixed getUserMedia.
