### ISSUE TITLE
mediaDevices.getUserMedia  - Fails in Explorer 11.

### ISSUE THREAD

**Issue by alikuli** [webrtcHacks/adapter#356]
**Browsers and versions affected**
Internet Explorer 11
version 11.0.9600.17801
update Versions: 11.0.19

**Description**

**Steps to reproduce**

javascript code

```
      var canvas = document.getElementById("canvas")
      var ctx = canvas.getContext("2d");
      var videoObj = { audio: true, video: true }

      var p = navigator.mediaDevices.getUserMedia(videoObj); 
```

**Expected results**

var p = navigator.mediaDevices.getUserMedia(videoObj); 

**Actual results**
//fails: Unable to get property 'getUserMedia' of undefined or null reference

![getusererror](https://cloud.githubusercontent.com/assets/8050476/17552370/0a9feb5a-5f19-11e6-9407-c1a61c26ceea.png)

**Comment by jan-ivar** [comment]
@alikuli Try one of these http://iswebrtcreadyyet.com/

**Comment by KaptenJansson** [comment]
Internet explorer is not supported (as you can see in the link in the previous comment). This shim should however work in MS Edge.
