### ISSUE TITLE
addIceCandidate fails on FF/Chrome for Edge's ICE candidates

### ISSUE THREAD

**Issue by mansch** [webrtcHacks/adapter#358]
**Browsers and versions affected**
Edge 38.14393.0.0
Firefox 48.0.1 (and also other Versions)
Chrome 53.0.2785.70 beta-m (64-bit) (and also other Versions)
Latest adapter.js version (#357)

**Description**
Its not possible to setup a connection between Microsoft Edge and Firefox or Chrome.
Looks like Firefox / Chrome are no longer supporting Edge's ICE candidates?

**Steps to reproduce**
Try to setup a RTC (video/audio) between Firefox or Chrome on the one side, Edge 38 on the other.
Firefox or Chrome throwing an error after receiving the ICE candidates from Edge and wont setup a RTC.
No difference if the Edge client is caller.

**Expected results**
It should work as with Microsoft Edge 25 (previous released version).
It works too between Edge 38 and Edge 38.

**Actual results**
Forefox or Chrome throwing error on the ICE candiates.
Caller Firefox 48.0.1 <-> Callee Edge 38.14393.0.0, (ICE stringified):
{"type":"candidate","label":0,"id":"sdparta_0","candidate":"candidate:1 1 UDP 2130706431 172.16.101.218 18796 typ host"}
{"type":"candidate","label":0,"id":"sdparta_0","candidate":"candidate:2 1 TCP 1684798975 172.16.101.218 18796 typ srflx raddr 172.16.101.218 rport 18796 tcptype active"}
{"type":"candidate","label":0,"id":"sdparta_0","candidate":"candidate:1 1 udp 1 0.0.0.0 9 typ endOfCandidates"}
ICE failed, see about:webrtc for more details

The FireFox about:webrtc connection log (all in the same LAN, including STUN server):

(registry/INFO) insert 'ice' (registry) succeeded: ice
(registry/INFO) insert 'ice.pref' (registry) succeeded: ice.pref
(registry/INFO) insert 'ice.pref.type' (registry) succeeded: ice.pref.type
(registry/INFO) insert 'ice.pref.type.srv_rflx' (UCHAR) succeeded: 0x64
(registry/INFO) insert 'ice.pref.type.peer_rflx' (UCHAR) succeeded: 0x6e
(registry/INFO) insert 'ice.pref.type.host' (UCHAR) succeeded: 0x7e
(registry/INFO) insert 'ice.pref.type.relayed' (UCHAR) succeeded: 0x05
(registry/INFO) insert 'ice.pref.type.srv_rflx_tcp' (UCHAR) succeeded: 0x63
(registry/INFO) insert 'ice.pref.type.peer_rflx_tcp' (UCHAR) succeeded: 0x6d
(registry/INFO) insert 'ice.pref.type.host_tcp' (UCHAR) succeeded: 0x7d
(registry/INFO) insert 'ice.pref.type.relayed_tcp' (UCHAR) succeeded: 0x00
(registry/INFO) insert 'stun' (registry) succeeded: stun
(registry/INFO) insert 'stun.client' (registry) succeeded: stun.client
(registry/INFO) insert 'stun.client.maximum_transmits' (UINT4) succeeded: 7
(registry/INFO) insert 'ice.trickle_grace_period' (UINT4) succeeded: 5000
(registry/INFO) insert 'ice.tcp' (registry) succeeded: ice.tcp
(registry/INFO) insert 'ice.tcp.so_sock_count' (INT4) succeeded: 0
(registry/INFO) insert 'ice.tcp.listen_backlog' (INT4) succeeded: 10
(registry/INFO) insert 'ice.tcp.disable' (char) succeeded: \001
(ice/WARNING) ICE(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/)): peer (PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default) has no stream matching stream 0-1471930374563000 (id=57 url=https://172.16.101.179:8443/) aLevel=1
(ice/NOTICE) ICE(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/)): peer (PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default) no streams with non-empty check lists
(ice/NOTICE) ICE(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/)): peer (PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default) no streams with pre-answer requests
(ice/NOTICE) ICE(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/)): peer (PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default) no checks to start
(ice/INFO) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default)/CAND-PAIR(hzOJ): setting pair to state FROZEN: hzOJ|IP4:172.16.101.179:55585/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:172.16.101.179:55585/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)
(ice/INFO) ICE(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/))/CAND-PAIR(hzOJ): Pairing candidate IP4:172.16.101.179:55585/UDP (7e7c00ff):IP4:172.16.101.218:23094/UDP (7effffff) priority=9114160845369114622 (7e7c00fffdfffffe)
(ice/INFO) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default)/ICE-STREAM(0-1471930374563000 (id=57 url=https://172.16.101.179:8443/) aLevel=0): Starting check timer for stream.
(ice/INFO) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default)/CAND-PAIR(hzOJ): setting pair to state WAITING: hzOJ|IP4:172.16.101.179:55585/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:172.16.101.179:55585/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)
(ice/INFO) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default)/CAND-PAIR(hzOJ): setting pair to state IN_PROGRESS: hzOJ|IP4:172.16.101.179:55585/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:172.16.101.179:55585/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)
(ice/NOTICE) ICE(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/)): peer (PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default) is now checking
(ice/INFO) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default)/CAND-PAIR(AKnR): setting pair to state FROZEN: AKnR|IP4:192.168.56.1:55586/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:192.168.56.1:55586/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)
(ice/INFO) ICE(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/))/CAND-PAIR(AKnR): Pairing candidate IP4:192.168.56.1:55586/UDP (7e7f00ff):IP4:172.16.101.218:23094/UDP (7effffff) priority=9115005270299246590 (7e7f00fffdfffffe)
(ice/INFO) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default)/CAND-PAIR(YvcK): setting pair to state FROZEN: YvcK|IP4:192.168.10.1:55587/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:192.168.10.1:55587/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)
(ice/INFO) ICE(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/))/CAND-PAIR(YvcK): Pairing candidate IP4:192.168.10.1:55587/UDP (7e7b00ff):IP4:172.16.101.218:23094/UDP (7effffff) priority=9113879370392403966 (7e7b00fffdfffffe)
(ice/INFO) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default)/CAND-PAIR(LSWV): setting pair to state FROZEN: LSWV|IP4:192.168.194.1:55588/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:192.168.194.1:55588/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)
(ice/INFO) ICE(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/))/CAND-PAIR(LSWV): Pairing candidate IP4:192.168.194.1:55588/UDP (7e7e00ff):IP4:172.16.101.218:23094/UDP (7effffff) priority=9114723795322535934 (7e7e00fffdfffffe)
(ice/INFO) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default)/CAND-PAIR(3tz+): setting pair to state FROZEN: 3tz+|IP4:192.168.164.1:55589/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:192.168.164.1:55589/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)
(ice/INFO) ICE(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/))/CAND-PAIR(3tz+): Pairing candidate IP4:192.168.164.1:55589/UDP (7e7d00ff):IP4:172.16.101.218:23094/UDP (7effffff) priority=9114442320345825278 (7e7d00fffdfffffe)
(ice/INFO) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default)/CAND-PAIR(AKnR): setting pair to state WAITING: AKnR|IP4:192.168.56.1:55586/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:192.168.56.1:55586/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)
(ice/INFO) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default)/CAND-PAIR(AKnR): setting pair to state IN_PROGRESS: AKnR|IP4:192.168.56.1:55586/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:192.168.56.1:55586/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)
(ice/INFO) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default)/CAND-PAIR(LSWV): setting pair to state WAITING: LSWV|IP4:192.168.194.1:55588/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:192.168.194.1:55588/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)
(ice/INFO) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default)/CAND-PAIR(LSWV): setting pair to state IN_PROGRESS: LSWV|IP4:192.168.194.1:55588/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:192.168.194.1:55588/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)
(ice/INFO) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default)/CAND-PAIR(3tz+): setting pair to state WAITING: 3tz+|IP4:192.168.164.1:55589/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:192.168.164.1:55589/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)
(ice/INFO) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default)/CAND-PAIR(3tz+): setting pair to state IN_PROGRESS: 3tz+|IP4:192.168.164.1:55589/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:192.168.164.1:55589/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)
(ice/INFO) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default)/CAND-PAIR(YvcK): setting pair to state WAITING: YvcK|IP4:192.168.10.1:55587/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:192.168.10.1:55587/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)
(ice/INFO) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default)/CAND-PAIR(YvcK): setting pair to state IN_PROGRESS: YvcK|IP4:192.168.10.1:55587/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:192.168.10.1:55587/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)
(ice/WARNING) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default): no pairs for 0-1471930374563000 (id=57 url=https://172.16.101.179:8443/) aLevel=0
(ice/INFO) ICE(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/)): peer (PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default) Trickle grace period is over; marking every component with only failed pairs as failed.
(stun/INFO) STUN-CLIENT(hzOJ|IP4:172.16.101.179:55585/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:172.16.101.179:55585/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)): Timed out
(ice/INFO) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default)/CAND-PAIR(hzOJ): setting pair to state FAILED: hzOJ|IP4:172.16.101.179:55585/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:172.16.101.179:55585/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)
(stun/INFO) STUN-CLIENT(AKnR|IP4:192.168.56.1:55586/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:192.168.56.1:55586/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)): Timed out
(ice/INFO) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default)/CAND-PAIR(AKnR): setting pair to state FAILED: AKnR|IP4:192.168.56.1:55586/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:192.168.56.1:55586/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)
(stun/INFO) STUN-CLIENT(LSWV|IP4:192.168.194.1:55588/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:192.168.194.1:55588/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)): Timed out
(ice/INFO) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default)/CAND-PAIR(LSWV): setting pair to state FAILED: LSWV|IP4:192.168.194.1:55588/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:192.168.194.1:55588/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)
(stun/INFO) STUN-CLIENT(3tz+|IP4:192.168.164.1:55589/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:192.168.164.1:55589/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)): Timed out
(ice/INFO) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default)/CAND-PAIR(3tz+): setting pair to state FAILED: 3tz+|IP4:192.168.164.1:55589/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:192.168.164.1:55589/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)
(stun/INFO) STUN-CLIENT(YvcK|IP4:192.168.10.1:55587/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:192.168.10.1:55587/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)): Timed out
(ice/INFO) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default)/CAND-PAIR(YvcK): setting pair to state FAILED: YvcK|IP4:192.168.10.1:55587/UDP|IP4:172.16.101.218:23094/UDP(host(IP4:192.168.10.1:55587/UDP)|candidate:1 1 UDP 2130706431 172.16.101.218 23094 typ host)
(ice/INFO) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default)/STREAM(0-1471930374563000 (id=57 url=https://172.16.101.179:8443/) aLevel=0)/COMP(1): All pairs are failed, and grace period has elapsed. Marking component as failed.
(ice/INFO) ICE-PEER(PC:1471930374563000 (id=57 url=https://172.16.101.179:8443/):default): all checks completed success=0 fail=1
+++++++ END ++++++++

**Comment by fippo** [comment]
still working fine on https://simplewebrtc.com/video.html here (which has a slightly outdated adapter.js I think). There is no Edge 38 afaik

**Comment by fippo** [comment]
just checking: are you calling addIceCandidate with the null candidate? If you don't Edge won't start ICE

**Comment by mansch** [comment]
Microsoft anniversary update comes with the new Edge 38 (and experimental H264 support), see [https://s15.postimg.org/qa99r5rmz/Microsoft_Edge.png](url)

No, I don't try it with a null candidate. As far I see Edge doesn't send a null candidate, the last one is:
candidate: "candidate:1 1 udp 1 0.0.0.0 9 typ endOfCandidates"
I already tried to suppress this one w/o any success.

Maybe not the ice candidates but the connection itself is the problem. I'm not very comfortable with the ICE logs of the FireFox (see above).

**Comment by fippo** [comment]
you need to call addIceCandidate(null) when the other end gets the onicecandidate with no candidate. How you signal that is up to you. The endOfCandidates candidate is an ugly hack for https://github.com/webrtc/samples -- you can ignore that not being liked by Chrome or Firefox, that is expected.

see https://github.com/webrtc/adapter/blob/master/src/js/edge/edge_shim.js#L989 and https://github.com/webrtc/adapter/blob/master/src/js/edge/edge_shim.js#L267

**Comment by mansch** [comment]
Mhm, the ICE exchange seems to work properly, only the connection fails.
Firefox <-> Firefox working:
local candidate ||| remote candidate
172.16.101.179:51904/udp(host)   |||   172.16.101.218:65235/udp**(peerreflexive)** 

But with Edge:
Firefox <-> Edge fails:
local candidate ||| remote candidate
172.16.101.179:54794/udp(host)   |||   172.16.101.218:16900/udp(host)

I don't see any prflx in the connection protocol between FF and Edge, only with Firefox or Chrome.
May this be the problem why edge cannot connect to one of the other browsers, only to another Edge?

Does this still belong to adapter.js? Maybe? ;)

**Comment by fippo** [comment]
i have seen edge having issues when you run without turn servers (even locally where those shouldn't be required) -- in those cases it needed to relay via the TURN servers or failed.
Do you have a wireshark dump?

**Comment by mansch** [comment]
Thanks fippo for your help :) I will try it later within another network with different workstations.
I already set up a local TURN server but no success in getting it into, trying harder at home ;)

**Comment by aboba** [comment]
I am seeing the same Edge <-> FF/Chrome interop issue running with a turn server.  I am running Edge Windows 10 Anniversary update (and later Windows Preview builds).  Also have encountered addIceCandidate failures even in FF <-> Chrome interop cases (looking into this to make sure it is not due to some other problem).

**Comment by aboba** [comment]
@mansch  If you need a TURN server for testing, you can try this one: 
{'iceServers': [{'urls': 'turn:turn-testdrive.cloudapp.net:3478?transport=udp', 'username': 'redmond', 'credential': 'redmond123'}],
