### ISSUE TITLE
Edge to Firefox: InvalidAccessError in RTCPeerConnection.prototype._transceive

### ISSUE THREAD

**Issue by ghost** [webrtcHacks/adapter#359]
**Browsers and versions affected**
Firefox 48 and Edge 25.10586

**Description**
Error in adapter.js on line 1413 (SCRIPT5022: InvalidAccessError). I tested Firefox-Firefox and Firefox-Chrome. It works just fine. Firefox-Edge has this issue.

Error when hit following line: 
`transceiver.rtpReceiver.receive(params);`

Here is my offer SDP from Firefox : 
`v=0
o=mozilla...THIS_IS_SDPARTA-48.0.1 1018416525462593934 0 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 28:9D:EE:63:5E:8A:C1:2B:13:5A:5B:4E:72:95:22:01:C0:88:69:01:38:1B:FA:7F:BF:F6:10:3D:6F:BC:76:E9
a=group:BUNDLE sdparta_0 sdparta_1
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8
c=IN IP4 0.0.0.0
a=sendrecv
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=fmtp:109 maxplaybackrate=48000;stereo=1
a=ice-pwd:fa5cb7d93eb144d2928ae0dae688c88f
a=ice-ufrag:258b6a05
a=mid:sdparta_0
a=msid:{4c65289a-324c-c84d-8129-96936a9b3d7c} {c8c73d30-0709-544e-9402-40fe09643267}
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=setup:actpass
a=ssrc:1163496559 cname:{b0b5f73a-c244-de4b-847b-2c1a63c677e1}
m=video 9 UDP/TLS/RTP/SAVPF 120 126 97
c=IN IP4 0.0.0.0
a=sendrecv
a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
a=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1
a=fmtp:120 max-fs=12288;max-fr=60
a=ice-pwd:fa5cb7d93eb144d2928ae0dae688c88f
a=ice-ufrag:258b6a05
a=mid:sdparta_1
a=msid:{4c65289a-324c-c84d-8129-96936a9b3d7c} {ed4d422e-ab96-9641-903c-b0c678ddeb82}
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 ccm fir
a=rtcp-fb:126 nack
a=rtcp-fb:126 nack pli
a=rtcp-fb:126 ccm fir
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 ccm fir
a=rtcp-mux
a=rtpmap:120 VP8/90000
a=rtpmap:126 H264/90000
a=rtpmap:97 H264/90000
a=setup:actpass
a=ssrc:3362416113 cname:{b0b5f73a-c244-de4b-847b-2c1a63c677e1}
`

**Comment by fippo** [comment]
Edge 10586 does not support H264 so there are no common video codecs so this is probably https://github.com/fippo/adapter/issues/34

**Comment by KaptenJansson** [comment]
@fippo do you want to keep this open?

**Comment by fippo** [comment]
@KaptenJansson nah, tracking this over in my issue tracker
