### ISSUE TITLE
Edge generates ICE candidates with only private IP

### ISSUE THREAD

**Issue by ekzobrain** [webrtcHacks/adapter#364]
**Browsers and versions affected**
Edge 38.14393
EdgeHTML 14.14393
webrtc-adapter 2.0.2
Sip.js 0.7.5

**Description**
I am trying to make Sip.js calls to FreeSwitch PBX work in Edge. So I include webrtc-adapter before Sip.js. When making a call Edge generates only ICE candidates with local IP and does no generate any cadidates with my public IP (Edge always sits behind home Router with nat), so FreeSwitch (located in internet, not local network) fails to find any appropriate rtp/rtcp candidates and throws media negotiation error. SDP generated by Sip.js in Edge:
v=0
o=thisisadapterortc 8169639915646943137 2 IN IP4 127.0.0.1
s=-
t=0 0
m=audio 9 UDP/TLS/RTP/SAVPF 104 9 106 0 8 103 97 13 118 101
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=rtpmap:104 SILK/16000
a=rtcp-fb:104 x-message app send:dsh recv:dsh
a=rtpmap:9 G722/8000
a=rtcp-fb:9 x-message app send:dsh recv:dsh
a=rtpmap:106 opus/48000/2
a=rtcp-fb:106 x-message app send:dsh recv:dsh
a=rtpmap:0 PCMU/8000
a=rtcp-fb:0 x-message app send:dsh recv:dsh
a=rtpmap:8 PCMA/8000
a=rtcp-fb:8 x-message app send:dsh recv:dsh
a=rtpmap:103 SILK/8000
a=rtcp-fb:103 x-message app send:dsh recv:dsh
a=rtpmap:97 RED/8000
a=rtpmap:13 CN/8000
a=rtpmap:118 CN/16000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 events=0-16
a=rtcp-mux
a=ice-ufrag:lMIR
a=ice-pwd:iaoF4yNFKRfTt0I4UaOKja0i
a=setup:actpass
a=fingerprint:sha-256 2F:6C:A6:D5:3F:C5:D1:0E:FE:B1:83:87:CF:8F:34:56:EA:2F:E7:6C:51:14:B6:99:38:FA:14:DB:61:8C:E0:30
a=mid:rkl5gwhdno
a=sendrecv
a=msid:DFCDD8B4-2697-4E07-815C-380832529923 D99D7D25-B1DC-4959-8A03-3A894A54F5C4
a=ssrc:1001 msid:DFCDD8B4-2697-4E07-815C-380832529923 D99D7D25-B1DC-4959-8A03-3A894A54F5C4
a=ssrc:1001 cname:t30c3fiwoa
a=candidate:1 1 UDP 2130706431 192.168.0.106 5520 typ host
a=candidate:2 1 UDP 33553919 2001:0:5ef5:79fd:c56:3960:3f57:ff95 28208 typ host
a=candidate:3 1 TCP 1684798463 192.168.0.106 5520 typ srflx raddr 192.168.0.106 rport 5520 tcptype active
a=end-of-candidates

As you see - thereare only local IPs. iceServers: [{urls: "stun:stun.l.google.com:19302"}]
Also on test page https://appr.tc/ I get this error in Edge:
Create PeerConnection exception: error: unable to finish ation. error c004e001

**Steps to reproduce**
You can use this test page: https://test.322.su You need to press a green phone button in the bottom right corner (appeares 5 seconds after page load) and a call to PBX will start. Watch the console to get all available logs and  siptrace with SDP. Russian voice that starts and then teminates is just an Audio() sound played locally in browser. It terminates almost immediatelly becase call to PBX fails.

**Expected results**
Edge generates ICE candidates with my public IP as Firefox and Chrome do. And you listen to IVR up to the end and then talk with operator starts.

**Actual results**
Only my private network IPs appear in ICE candidates, so FreeSwitch

**Comment by fippo** [comment]
Edge doesn't support stun urls yet -- you need a TURN server (see also [this](https://bloggeek.me/turn-public-ip-address/) even though Edge doesn't do turn/tcp et  al right now)

apprtc still doesn't fully support Edge (@kaptenjansson did you bump adapter there?)

**Comment by ekzobrain** [comment]
Hi.

Thanks, I configured TURN server (from issue #358 ) and now ICE candidates are gathered normally.
As I understand I also have to modify Sip.js library so it sets NULL ICE candidate after retrieving last candidate from FS? It is required for Edge to start ICE?

**Comment by KaptenJansson** [comment]
@fippo sorry I dropped this again. I've got my win 10 machine up again and Edge 38.14393. 

When I try I get a peerConnection exception (c004e001) with the latest adapter 2.0.3. This could be that the peerconnection config contains non supported data. And yes, the STUN URL is passed in there which could be it, I thought that was supposed to be filtered out in adapter? I will try to filter it out myself and see if it works.

**Comment by KaptenJansson** [comment]
It does work (creating a PC) when I filter out STUN. But the call is not setup, could it be the null candidate thing?

**Comment by KaptenJansson** [comment]
aaand blue screen.....:(

**Comment by ekzobrain** [comment]
@fippo ?

**Comment by fippo** [comment]
yes, see the interop note @ http://internaut.com:8080/~baboba/ms/msortc-rs.html#rtcicetransport-overview*

If you're using freeswitch... ping @freeswitch -- it works fine with verto

**Comment by ekzobrain** [comment]
Hi.

I am trying to add null ICE candidate, but get "InvalidAccessError" DOMException.
The scenario is:
1. pc.setRemoteDescription() with all ICE candidates listed in SDP
2. pc.addIceCandidate(null) - throws DOMException

You can check it out yourself here: https://test.322.su. Press the blue phone button in the bottom right corner and search console for "Adding NULL ICE candidate for MS Edge" message.

**Comment by ekzobrain** [comment]
@fippo ...

**Comment by fippo** [comment]
if you use pc.setRemoteDescription with candidates _and_ end-of-candidates (or ice-lite) then you don't need addIceCandidate(null)

**Comment by ekzobrain** [comment]
@fippo

Hm, seems that Freeswitch sends end-of-candidates candidate back (so null candidate is automatically applied), but not at the end - is this OK? Also is this SDP generally OK for Edge? Recieved SDP:

v=0
o=FreeSWITCH 1475227483 1475227484 IN IP4 185.123.165.23
s=FreeSWITCH
c=IN IP4 185.123.165.23
t=0 0
a=msid-semantic: WMS 1dBXktBhjb6myBmh2MhYyYy3orcgc9V3
a=end-of-candidates
m=audio 17150 UDP/TLS/RTP/SAVPF 106 101
a=rtpmap:106 opus/48000/2
a=fmtp:106 useinbandfec=1; minptime=10; maxptime=40
a=rtpmap:101 telephone-event/8000
a=ptime:20
a=fingerprint:sha-256 BD:BF:05:2A:67:AB:AA:05:48:7A:BA:8A:0B:F3:DA:82:DA:59:9C:31:64:CF:F1:E1:CE:0D:43:A5:20:EF:73:3A
a=setup:active
a=rtcp-mux
a=rtcp:17150 IN IP4 185.123.165.23
a=ice-ufrag:SWzgLX9Zfc6hcRbf
a=ice-pwd:4RtC0Oib5bJOhppZcP6ND6DI
a=candidate:4206296867 1 udp 659136 185.123.165.23 17150 typ host generation 0
a=ssrc:3556507560 cname:dnQnHivQkr3ISfPL
a=ssrc:3556507560 msid:1dBXktBhjb6myBmh2MhYyYy3orcgc9V3 a0
a=ssrc:3556507560 mslabel:1dBXktBhjb6myBmh2MhYyYy3orcgc9V3
a=ssrc:3556507560 label:1dBXktBhjb6myBmh2MhYyYy3orcgc9V3a0

**Comment by ekzobrain** [comment]
Also, does Edge currently support renegotiation?

**Comment by fippo** [comment]
Edge does but adapter.js does not. That SDP looks ok, i'm pretty sure it worked at cluecon

**Comment by ekzobrain** [comment]
Ah, SIP.js uses renegotiation a lot: early media/call/hold/unhold/transfer/etc. SIP wont work without support for it. Do you have any plans on implementing renegotiation?

**Comment by ekzobrain** [comment]
I have removed any renegotiation logic from the call, removed addIceCandidate(null), because SDP comes with "a=end-of-candidates" as i've shown, but media still does not work. In Firefox/Chrome, for example, I see in FS console:

```
2016-09-30 19:20:44.945594 [INFO] switch_core_media.c:6690 Skipping RTCP ICE (Same as RTP)
2016-09-30 19:20:44.945594 [INFO] switch_rtp.c:3328 Activate RTP/RTCP audio DTLS client
2016-09-30 19:20:44.945594 [INFO] switch_rtp.c:3459 Changing audio DTLS state from OFF to HANDSHAKE
...
2016-09-30 19:20:45.125595 [INFO] switch_rtp.c:3119 Changing audio DTLS state from HANDSHAKE to SETUP
2016-09-30 19:20:45.145603 [INFO] switch_rtp.c:3028 audio Fingerprint Verified.
2016-09-30 19:20:45.145603 [INFO] switch_rtp.c:3644 Activating Audio Secure RTP SEND
2016-09-30 19:20:45.145603 [INFO] switch_rtp.c:3622 Activating Audio Secure RTP RECV
2016-09-30 19:20:45.145603 [INFO] switch_rtp.c:3068 Changing audio DTLS state from SETUP to READY
```

but with Edge last five lines (after ...) do not appear, so something is probable wrong with handshake, but there are no any other messages nor in FS console, neither Edge console. Is there anything else that I can check?

**Comment by ekzobrain** [comment]
@fippo ?

**Comment by fippo** [comment]
i'm not running freeswitch. Have you tried asking on their support channels?

I have no plans to implement renegotiation any time soon.

**Comment by ekzobrain** [comment]
I'll try to ask, thanks. Do not close this issue for now, please...

**Comment by KaptenJansson** [comment]
Any updates?

**Comment by ekzobrain** [comment]
It seems that the problem is related to SSL chiphers in Edge/Freeswitch default configuration, so they are unable to succeed in SSL handshake. But I have not had time to try and come up with a working configuration for now. I think this issue may be closed, because initial question is already solved. Thanks.
