### ISSUE TITLE
bower invalid-meta  webrtc-adapter is missing "ignore" entry in bower.json

### ISSUE THREAD

**Issue by KaptenJansson** [webrtcHacks/adapter#37]
bower update complains about the following for adapter:
- bower invalid-meta  webrtc-adapter is missing "ignore" entry in bower.json

Will fix it soonish.

**Comment by alvestrand** [comment]
Warning: turns out the npm "webrtc-adapter" is not our "webrtc-adapter". Trying to figure out how to resolve this.

**Comment by alvestrand** [comment]
Correction: the bower webrtc-adapter is our webrtc-adapter. the npm webrtc-adapter isn't.

**Comment by alvestrand** [comment]
Fixed in https://github.com/webrtc/adapter/commit/dbfbb1f34dfca0344c72f933b854b7245546a51f
