### ISSUE TITLE
Chrome 53 broke facingMode polyfill

### ISSUE THREAD

**Issue by jan-ivar** [webrtcHacks/adapter#370]
**Browsers and versions affected**
Chrome 53-56

**Description**
Chrome 53+ returns true for `navigator.mediaDevices.getSupportedConstraints().facingMode` even though it's not supported. This confuses adapter, which tests for support before polyfilling.

**Steps to reproduce**
- In Chrome for Android, click [Back] button in https://jsfiddle.net/j2oe36eL/

**Expected results**
Back camera

**Actual results**
Front camera.

**Comment by KaptenJansson** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=656920

**Comment by bradisbell** [comment]
This change gets the right camera for me.  Thanks!  However, using your branch, I am unable to get a 16:9 video from any camera.  Front camera works fine in 16:9 on the main fork of adapter.js 2.0.6.

Using the following constraints on a Galaxy S6 with Chrome:

```
    {
      "audio": {
        "echoCancellation": false,
        "channelCount": 2
      },
      "video": {
        "width": { "min": 640, "ideal": 1280, "max": 1920 },
        "height": { "min": 480, "ideal": 720, "max": 1080 },
        "frameRate": { "ideal": 30, "max": 30 },
        "facingMode": "environment"
      }
    }
```

**Comment by jan-ivar** [comment]
@bradisbell This patch also turns off the polyfilling of constraints in Chrome 54 and on (which is what's breaking the test atm). Can you test to see if you have success with your constraints in Chrome 54+ _without_ adapter?

**Comment by jan-ivar** [comment]
For 16:9 video I mean.

**Comment by bradisbell** [comment]
No.  Chrome v54.0.2840.85, with no adapter.js and the constraints above gives me 4:3 video from the front-facing camera on the Galaxy S6.

**Comment by Patrick-Vogt** [comment]
Did you found a solution for this problem?
I tried to enumerate the devices and and used sourceid = foundDeviceWithBackCamera, but it seems not to be a proper solution...
