### ISSUE TITLE
[question] Possibilities in debugging Edge internal events

### ISSUE THREAD

**Issue by aszmyd** [webrtcHacks/adapter#375]
I've been told on [stackoverflow](http://stackoverflow.com/a/40167895/1433658) that @fippo is working on some `WEBRTC-on-ORTC shim` that could help in debugging Windows Edge internal events when developing. Is there something i can use right now? If not, are there any schedule for this kind of stuff? How will it work in general?
Thanks for answer

**Comment by fippo** [comment]
the shim is what is in https://github.com/webrtc/adapter/tree/master/src/js/edge
If you need to debug things I recommend checkig the JS console for exceptions, checking the peerconnections localDescription, remoteDescription, signalingState and iceConnectionState.
If all that looks good you might need to dig down into pc.transceivers which offers raw access to the ORTC objects. And sprinkling console.log everywhere...

**Comment by aszmyd** [comment]
Thanks
