### ISSUE TITLE
Support for Node 6, npm 3.10.3

### ISSUE THREAD

**Issue by sfarthin** [webrtcHacks/adapter#383]
**Steps to reproduce**
install node v6.5.0/npm 3.10.3
npm install webrtc-adapter --save ... fails

**Expected results**
To install webtc-adapter

**Actual results**
npm ERR! notsup Not compatible with your version of node/npm: webrtc-adapter@2.0.7
npm ERR! notsup Not compatible with your version of node/npm: webrtc-adapter@2.0.7
npm ERR! notsup Required: {"npm":"~3.0.0"}
npm ERR! notsup Actual:   {"npm":"3.10.3","node":"6.5.0"}

**Comment by KaptenJansson** [comment]
Please try again and see if #384 fixes the issue.

**Comment by sfarthin** [comment]
Thanks, I believe that will do it, once you publish to npm.

**Comment by KaptenJansson** [comment]
Done

**Comment by KaptenJansson** [comment]
ping
