### ISSUE TITLE
Investigate if we can use bowser for browser detection

### ISSUE THREAD

**Issue by KaptenJansson** [webrtcHacks/adapter#397]
https://github.com/webrtc/adapter/pull/242#r91831740

**Comment by KaptenJansson** [comment]
@fippo @jan-ivar do you think it's worth spending more time on browser detection and in that case maybe use the bowser library as suggested in the comment in the description?

**Comment by fippo** [comment]
that would detect opera as opera and i would like it to be detected as Chrome because the chrome/webrtc detection is what really matters.

**Comment by KaptenJansson** [comment]
Yeah I guess it's more flexible we can control how the browsers are detected ourselves for the reason you just pointed out.

**Comment by KaptenJansson** [comment]
Closing as we need full control over the detection logic.
