### ISSUE TITLE
Add a section on README.md showing how to use bower to depend on this.

### ISSUE THREAD

**Issue by andresusanopinto** [webrtcHacks/adapter#4]

**Comment by juberti** [comment]
How do we want this to work? Looks like we can either pull stuff with bower or requirejs. 
@jiayliu @andresusanopinto @samdutton suggestions?

**Comment by jiayliu** [comment]
My understanding is:

Using bower can pull in adapter.js at build time, and we should be able to
easily make it work for apprtc/testrtc. But I don't see how it will work
for samples.

Requirejs should work for samples, but will need an extra JS file (2K lines
un-minimized) and load the adapter.js in the run time, so slow down page
load. I think we should avoid it for apprtc/testrtc.

On Thu, Feb 5, 2015 at 12:20 PM, Justin Uberti notifications@github.com
wrote:

> How do we want this to work? Looks like we can either pull stuff with
> bower or requirejs.
> @jiayliu https://github.com/jiayliu @andresusanopinto
> https://github.com/andresusanopinto @samdutton
> https://github.com/samdutton suggestions?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/webrtc/adapter/issues/4#issuecomment-73119150.

## 

Jiayang Liu

**Comment by juberti** [comment]
OK. So Bower for apprtc/testrtc, and requireJS for samples? That makes sense to me.

**Comment by andresusanopinto** [comment]
Done on #17
