### ISSUE TITLE
renameIceURLs causes issue on firefox

### ISSUE THREAD

**Issue by smcardle** [webrtcHacks/adapter#40]
Hi.

The renameIceURLs call causes issues on firefox in the following code:

  config.iceServers.forEach(function (server) {
    server.url = server.urls;
    delete server.urls;
  });

Basically, if the iceServers ALREADY only has server.url then this is wiped out and is set to undefined.

To put it another way, if the entry does not have 'urls' but is already defined as 'url' in the config then this buggers it up..

The correct way to do this should have been server.usr = server.url || server.urls where server.url take precedence

Regards

**Comment by fippo** [comment]
iceServers shouldn't have a no-longer-spec .url set.

Possibly the code could warn there but Chrome would still accept it without warning so I am not sure how useful that is.

**Comment by KaptenJansson** [comment]
I do not follow here, where is renameIceURLs call made and where does the code live? I'm lost....

**Comment by KaptenJansson** [comment]
Ping?

**Comment by smcardle** [comment]
This was in an older version of adapter.js but can now be closed as it's no longer relevant

Regards

**Comment by KaptenJansson** [comment]
I see, thanks for your response!
