### ISSUE TITLE
Need to support static methods on RTCPeerConnection

### ISSUE THREAD

**Issue by alvestrand** [webrtcHacks/adapter#41]
In implementing generateCertificate, which is a static method on RTCPeerConnection, we discovered that defining RTCPeerConnection as a function (and doing no more) hid the static method in Chrome (if the RTCPeerConnection class declaration was made visible).

Is it enough / correct to add "RTCPeerConnection.prototype = webkitRTCPeerConnection.prototype" to get static functions to work, or do we need to do something more complex?
We don't have any static functions so far, so I have nothing to test on.

Asking @fippo @jan-ivar for advice.

**Comment by henbos** [comment]
So far while testing on a forked version of samples, I changed this in adapter.js to make it work locally:
  // old code (line 182)
  RTCPeerConnection = function(pcConfig, pcConstraints) {
    return new webkitRTCPeerConnection(pcConfig, pcConstraints);
  };
  // new code
  RTCPeerConnection.generateCertificate = webkitRTCPeerConnection.generateCertificate;

**Comment by jan-ivar** [comment]
@alvestrand - There's [Object.setPrototypeOf](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf) but see performance warnings.

Why did we need a wrapper again (rather than modifying the prototype directly?)

**Comment by fippo** [comment]
I tried fiddling with the constructor in Firefox -- http://jsfiddle.net/zx7a95w1/1/ -- but that didn't work (doesn't for chrome either). Since currently we only need to do that for Firefox <38 to fiddle with the RTCIceServers let's just remove the wrapper for Chrome and hope that by the time it is necessary for Firefox, pre-38 versions will be gone?

**Comment by jan-ivar** [comment]
Or you could restore the `createIceServer` function. ;)

What's the version range that adapter.js tried to cover?

FWIW got a question from someone using Firefox 22 [just the other day](http://stackoverflow.com/questions/30581417/ns-error-unexpected-in-firefox-on-mozrtcpeerconnection/30600209#30600209).

**Comment by jan-ivar** [comment]
@fippo - re-reading your response I think what you suggest is ok (removing it for Chrome only). You could remove it on Firefox 38+ as well.

**Comment by fippo** [comment]
I think the answer is to use Object.defineProperty, i.e. 

```
Object.defineProperty(RTCPeerConnection, 'generateCertificate', {
  get: function() { return webkitRTCPeerConnection.generateCertificate(arguments); }
})
```

**Comment by KaptenJansson** [comment]
So the latest is that we do not need this for Firefox 38+ (which is stable hence can be removed for firefox all together)? What's the latest for Chrome, I assume we still need it? Also who wants to add this to adapter? I can take a look unless someone else is on it.
