### ISSUE TITLE
Capture screen in FF37-OSX not working: constraintsToFF37 mess up the constraints

### ISSUE THREAD

**Issue by igracia** [webrtcHacks/adapter#42]
I've run into an issue trying to capture the screen in FF37. When I invoke getUserMedia, no screen or window is shared, no dialogue is shown, and this appears in the logs

```
spec: {"audio":false,"video":{"mandatory":{"maxWidth":640,"maxFrameRate":15,"minFrameRate":15},"mozMediaSource":"screen","mediaSource":"screen"}}
ff37: {"audio":false,"video":{"mandatory":{"maxWidth":640,"maxFrameRate":15,"minFrameRate":15},"advanced":[{"mozMediaSource":{"min":"screen","max":"screen"}},{"mediaSource":{"min":"screen","max":"screen"}}]}}
TypeError: 'mediaSource' member of MediaTrackConstraintSet '[object Object]' is not a valid value for enumeration MediaSourceEnum.
```

It looks like the mangling done by the function _constraintsToFF37_ is not working/needed for FF37, as commenting out the call to the function allows me to share the screen again. I've finally changed the code from

```
  getUserMedia = (webrtcDetectedVersion < 38)
```

to 

```
  getUserMedia = (webrtcDetectedVersion < 37) 
```

and so far it's working fine. Could you please confirm this issue?

Thanks,

**Comment by jan-ivar** [comment]
Confirmed. Thanks for reporting this! I'm working on a fix now. facingMode is likely affected as well.

A side-note on your example: The constraints you're passing in for everything but mediaSource are not to spec and [don't work on Firefox](http://stackoverflow.com/questions/28282385/webrtc-firefox-constraints/28911694#28911694), even with the adapter. That's probably why you don't notice a difference with your workaround, which effectively disables adapter's spec-translation for 37.

**Comment by jan-ivar** [comment]
2nd side-note: it's just `mediaSource`. No implementation ever used `mozMediaSource` fwiw (I checked).

**Comment by igracia** [comment]
Thanks for confirming this, and for the prompt reply! Also thanks for the tips about the constraints. I'll check them against the specs to have them according to that. Thanks also for spotting the `mozMediaSource` issue, I'll fix that right away.

**Comment by KaptenJansson** [comment]
@igracia does this work for you now?

**Comment by igracia** [comment]
Yes, we have some automated tests running in Saucelabs and it's working.

I tried to have the constraints according to spec, as @jan-ivar pointed out, but it in fact made Chrome unable to share the screen (webcam was working fine) I still need to devote some time to test that correctly.

**Comment by KaptenJansson** [comment]
Chrome does screensharing it a little differently I believe and you have to execute it from an extension (you can enable getUserMedia desktop sharing via command line but that is for dev purposes only, also it can only do the whole screen, not just a window.)

**Comment by igracia** [comment]
Yes, I'm using my own extension for that. As I said, I need to give it a more thorough test. At the moment I checked with the spec constraints, it was a bit hectic around here so I couldn't double check that everything was in order. I'll check next week, and if it doesn't work I'll post again in a different issue.

Thanks!

**Comment by KaptenJansson** [comment]
Cool, sample extension [here](https://github.com/webrtc/samples/tree/master/src/content/extensions/desktopcapture) if you want some pointers.
