### ISSUE TITLE
`Edge 40.15025.1000.0` : `SCRIPT438: Object doesn't support property or method 'createDataChannel'`

### ISSUE THREAD

**Issue by arputcu** [webrtcHacks/adapter#428]
**Browsers and versions affected**
`Edge 40.15025.1000.0

**Description**
cannot create a DataChannel with Edge 

**Steps to reproduce**

https://webrtc.github.io/samples/src/content/datachannel/datatransfer/
**Expected results**
create a DataChannel 

**Actual results**
`Edge 40.15025.1000.0` : `SCRIPT438: Object doesn't support property or method 'createDataChannel'`

**Comment by fippo** [comment]
Edge does not support datachannels. The sample should probably check whether createDataChannel is a thing. @KaptenJansson wdyt?

**Comment by arputcu** [comment]
oh i read WebRTC 1.0 is now enabled by default in edge  and RTCDatachannels are webrtc 1.0 not ? 
https://developer.microsoft.com/en-us/microsoft-edge/platform/changelog/desktop/15019/

**Comment by fippo** [comment]
adapter overwrites the native 1.0 implementation. But data channels don't seem to be supported in the native 1.0 implementation either.

**Comment by aboba** [comment]
@fippo  Correct.  data channel is "under consideration" in Edge.  See: 
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/?filter=f3f0000bf&q=rtc
http://internaut.com:8080/~baboba/iit-tutorial/slides/edge.pdf

**Comment by ekzobrain** [comment]
@fippo Hm, if Edge now natively supports WebRTC - does it mean that it can do renegotiation (which is not supported by adapter)?

**Comment by arputcu** [comment]
everyone should vote for this here 
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/17929639-rtc-data-channels
