### ISSUE TITLE
Edge: Legacy mandatory/optional constraints not supported.

### ISSUE THREAD

**Issue by zdila** [webrtcHacks/adapter#437]
**Browsers and versions affected**
AdapterJS 0.14.0

Edge 38 on Windows 10

**Description**

Exteption with message "Legacy mandatory/optional constraints not supported." when calling `createOffer`

**Comment by fippo** [comment]
Those constraints are chrome-specific. What constraints are you trying to pass?

**Comment by zdila** [comment]
Thank you. You were right. After fixing that problem we are getting ` SCRIPT5022: InvalidAccessError` at line marked with `XXX`:
```
  } else if (navigator.mediaDevices && navigator.userAgent.match(/Edge\/(\d+).(\d+)$/)) {
    // Attach a media stream to an element.
    attachMediaStream = function(element, stream) {
      element.srcObject = stream; // XXX
      return element;
    };
```

So far we are trying to do audio-only call.

**Comment by fippo** [comment]
that looks like a very, very old version of adapter...

**Comment by zdila** [comment]
It is 0.14.0, latest in the npm repository.

https://github.com/Temasys/AdapterJS/blob/master/publish/adapter.debug.js

**Comment by fippo** [comment]
this npm package for this adapter is https://www.npmjs.com/package/webrtc-adapter

**Comment by zdila** [comment]
Thanks. But does that one support MSIE and Safari? Because this one "provides support for WebRTC in Internet Explorer and Safari on Mac and Windows through the available Temasys Browser Plugins.".

**Comment by zdila** [comment]
Oh sorry. I reported this issue to wrong project then :-O

**Comment by AndriiDronDiachuk** [comment]
zdila, how exactly did you fix "Legacy mandatory/optional constraints not supported"?

**Comment by fippo** [comment]
@AndriiDronDiachuk replace any createOffer({mandatory: {OfferToReceiveAudio: true}}) or similar with createOffer({offerToReceiveAudio: true}). Firefox should complain a lot about this already.
