### ISSUE TITLE
consider testharness.js

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#445]
we should consider porting the tests to https://github.com/w3c/testharness.js
 -- mainly because it is used in the web-platform-tests and we might be able to cross-pollinate between the tests here and the webrtc/mediacaptuer tests there.

**Comment by KaptenJansson** [comment]
To clarify, that's instead of tape/chai? Webdriver/mocha will still drive the test? 

@alvestrand @foolip wdyt?

**Comment by fippo** [comment]
instead of tape for running in-browser tests. The mocha/chai stuff is unit tests

**Comment by foolip** [comment]
testharness.js works well for things other than testing built-in browser APIs, and I personally enjoy using it. Getting more people using it decreases the barrier to contributing to web-platform-tests, which obviously would be great :)

**Comment by fippo** [comment]
I have a PR in [wpt](https://github.com/w3c/web-platform-tests/pull/5021) which does one of the tests I have in mind. Now I need to figure out how to
1) sync tests between wpt and adapter (copy paste?)
2) run the wpt tests from our CI after inserting adapter

**Comment by KaptenJansson** [comment]
NPM all the things!

**Comment by fippo** [comment]
I ported some tests [here](https://github.com/fippo/adapter/commit/14f0fe8df1a48a6152578eee2ff4dcbc33778e90)

Feels ok to use. Now I need to figure out how the wpt run on travis... that looks neat!

**Comment by fippo** [comment]
the karma/mocha/chai combo was more attractive (#597)
