### ISSUE TITLE
The MediaStreamTrack provided is not an element of a MediaStream that's currently in the local streams set

### ISSUE THREAD

**Issue by voiceactivity** [webrtcHacks/adapter#447]
**Browsers and versions affected**
Chrome, Firefox

**Description**
Updated to the latest version of the adapter.js (master). Run the app and it fails during the following call: pc.addStream(localStream);

I found that this code responsible for that:
adapter.js:

chromeShim.shimGetSendersWithDtmf(); // line 550
...
  shimGetSendersWithDtmf: function() {
    if (typeof window === 'object' && window.RTCPeerConnection &&
        !('getSenders' in RTCPeerConnection.prototype) &&
        'createDTMFSender' in RTCPeerConnection.prototype) {
      RTCPeerConnection.prototype.getSenders = function() {
        return this._senders;
      };
      var origAddStream = RTCPeerConnection.prototype.addStream;

      RTCPeerConnection.prototype.addStream = function(stream) {
        var pc = this;
        pc._senders = pc._senders || [];
        origAddStream.apply(pc, [stream]);
        stream.getTracks().forEach(function(track) {
          pc._senders.push({
            track: track,
            get dtmf() {
              if (!this._dtmf) {
                this._dtmf = pc.createDTMFSender(track); //line 670 Error
              }
              return this._dtmf;
            }
          });
        });
      };
    }
  }, 

**Steps to reproduce**
Create the real peer connection between two peers with signaling (not the toy from the example page).
Try to establish connection between peers. 

When I commented out the aforementioned code, the error gone.

**Expected results**
1. LocalStream assigned to the localVideo.
2. PeerConnection create with all required callbacks.
3. pc.addStream(localStream) should start the negotiation between peers.
4. pc.onaddstream -> add the remote stream to the remoteVideo
5. Video chat started.

**Actual results**
1. UserMedia assigned to the local video.
2. During adding the localStream to the pc (pc.addStream(localStream)) the following error occurs: 

Failed to execute 'createDTMFSender' on 'RTCPeerConnection': The MediaStreamTrack provided is not an element of a MediaStream that's currently in the local streams set.
...Error: Failed to execute 'createDTMFSender' on 'RTCPeerConnection': The MediaStreamTrack provided is not an element of a MediaStream that's currently in the local streams set.
    at Object.get dtmf [as dtmf] (adapter.js:670)
    ...

3. Remote peer doesn't receive oncandidate request. All communication chain between peers broken.

**Comment by jan-ivar** [comment]
I can't reproduce, but I get this error if I try to access sender.dtmf on a video track sender. dtmf should be `null` in that case, which is my patch's fault. Patch coming up.

It sounds like some library is examining the sender returned from pc.getSenders. Even just enumerating the properties of it would access the .dtmf getter, which would cause this patch to call createDTMFSender, which is unavoidable for audio, wrong for video.

**Comment by voiceactivity** [comment]
Hi Jan-Ivar,
That is exactly right. I saw it in a debugger. 
I was wondering why the audio track from the stream had no problem with that, but the video track failed when the pc.createDTMFSender(track) being called!

Thank you for that.

**Comment by KaptenJansson** [comment]
@voiceactivity 3.1.5 has been published with this fix, can you please verify and if it works, close the bug?

**Comment by voiceactivity** [comment]
Hi Christoffer, the fix did the job. 
It is all fixed now. I tested it on Mac and Windows, works great. 
Thank you!

**Comment by KaptenJansson** [comment]
Awesome, thanks @jan-ivar!

**Comment by claire33000** [comment]
Hello one and all, I have a new mistake on mi laptop and I have tried many things but it doesn't work to manage it .... I use to link to a streaming radio using tinychat support with camera available. When I try to cam up I have that message : "failed to execute addtrack on mediastream: parameter 1 is not of type "Mediastreamtrack""... I don't know if I am in the right place to ask but that was the only website I have found talking about that terms. I really not an expert so I don't really understand everything upside ... do you have an option to help me to understand that new issue I have right now? cheers 
![mediastream](https://user-images.githubusercontent.com/35893785/35482866-410b7682-043b-11e8-95e0-4d67444e9bf6.JPG)

**Comment by claire33000** [comment]
Hello one and all, I have a new mistake on mi laptop and I have tried many things but it doesn't work to manage it .... I use to link to a streaming radio using tinychat support with camera available. When I try to cam up I have that message : "failed to execute addtrack on mediastream: parameter 1 is not of type "Mediastreamtrack""... I don't know if I am in the right place to ask but that was the only website I have found talking about that terms. I really not an expert so I don't really understand everything upside ... do you have an option to help me to understand that new issue I have right now? cheers
![streammedia issue](https://user-images.githubusercontent.com/35893785/35482877-7f64a124-043b-11e8-9bf7-07bcb1c92236.jpg)

**Comment by fippo** [comment]
@claire33000 how are you calling addTrack? Calling it without a stream as the second parameter is not supported in the shim or the native Chrome implementation (@henbos do you have a tracking bug?)
