### ISSUE TITLE
Type definition (typings) for TypeScript

### ISSUE THREAD

**Issue by ZoolWay** [webrtcHacks/adapter#464]
Are there any official type definitions for use with this shim? DefinitelyTyped shows a package data 2016-07-19 but that is webrtc/rtcpeerconnection.

The repository does not contain a .d.ts file, neither does a bower-supplied download of the package.

**Comment by benbro** [comment]
Maybe this?
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/webrtc
https://www.npmjs.com/package/@types/webrtc

**Comment by ZoolWay** [comment]
As far as I understand it that one does not cover the adapter.

**Comment by ZoolWay** [comment]
It might be possible that the `es6` library definitions of the typescript compiler (`node_modules/typescript/lib/lib.es6.d.ts`) match but it would be great to get an official confirmation on this.

**Comment by timhurkmans** [comment]
Not an official statement, but the lib.d.ts definitions do work. Most things are present. However they are not entirely up to date with all the capabilities. You will miss some types and replacements for deprecated methods are not always present. A proper webrtc definition file would be nice.

**Comment by notedit** [comment]
+1

**Comment by KaptenJansson** [comment]
No official type definitions exists for this repo.
