### ISSUE TITLE
Add tests for all public functions in adapter.js to detect interop issues

### ISSUE THREAD

**Issue by KaptenJansson** [webrtcHacks/adapter#47]
https://github.com/webrtc/samples/issues/523 was caused by webrtc/adapter@04af828 where window.createIceServer was removed.

We should add tests for this, just a rudimentary check like "typeof foo !== undefined" for all expected public api functions/methods is better than nothing.

Also its easier then to make sure that when we do break something we properly update the version number to indicate it's incompatible.

**Comment by kashifshamaz21** [comment]
+1, this would be very helpful as webrtc apis are still under changes and lot of interop issues are expected for now.

**Comment by KaptenJansson** [comment]
Believe this has been solved in the refactoring of adapter.
