### ISSUE TITLE
test: getStats broken in Chrome 58+

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#476]
https://github.com/webrtc/adapter/blob/master/test/test.js#L1661-L1699 is currently broken in beta. Likely because we are running with the experimental web platform features flag enabled and therefore get new stats.

**Comment by fippo** [comment]
if Chrome 58 enables the new style getStats by default this will also be broken in stable. 😢 😢 😢

**Comment by geigev** [comment]
+1

**Comment by danbriggs5** [comment]
The issue definitely appears to be a result of the new getStats as mentioned above. I've been getting the "Aw snap" error message on chrome 58 approximately every few minutes when calling getStats on a 1 second interval. The older version of getStats still appears to be supported and function correctly in Chrome 58 as can be proven by commenting out https://github.com/webrtc/adapter/blob/master/src/js/chrome/chrome_shim.js#L230-L233.

Interestingly, the issue doesn't appear to occur on Canary (version 60).

**Comment by fippo** [comment]
that sounds like https://bugs.chromium.org/p/webrtc/issues/detail?id=7505 -- @henbos probably knows the status of this better.

This issue is about the selenium test being broken.

**Comment by KaptenJansson** [comment]
ping @henbos

**Comment by henbos** [comment]
There was a race where new getStats would sometimes crash on callback. It was fixed by https://codereview.chromium.org/2772283002 for M59, which hit stable last week. I think we can try to re-enable the test.

@danbriggs5 Do you still get the "Aw snap" on latest stable?

**Comment by danbriggs5** [comment]
@henbos Stable looks good! Tested for several hours without any issues.

**Comment by djalmaaraujo** [comment]
I am having problems to getStats.. my RTCStatsReport is returning empty. Is that related? Chrome: 58.0.3029.110

**Comment by danbriggs5** [comment]
@djalmaaraujo I don't imagine so. This issue will cause a crash once in awhile but the majority of calls to getStats() should succeed without issue. Your issue is likely a result of the fact that Chrome 58 is the first version to implement the spec'd version of getStats() and so it behaves differently than previous versions. Trying running the following on your peer connection to ensure it works.
```
			pc.getStats()
				.then(report => {
	        		report.forEach(stat => {
	        			console.log(stat);
		        	})
	        	})
	        	.catch(err => { 
	        		console.log(err) 
	        	});
```

**Comment by djalmaaraujo** [comment]
@danbriggs5 I was passing null as the argument for getStats(). Now it's working. thanks for your help and support.

**Comment by djalmaaraujo** [comment]
@danbriggs5 Actually sorry about the message aboce, if you test with chrome 58+, here's the result of your code above:

![screenshot 2017-06-19 16 20 51](https://user-images.githubusercontent.com/3402/27301907-5617a080-550b-11e7-8926-2f7c2f542b69.png)

**Comment by djalmaaraujo** [comment]
@fippo any ideas why not getting 58+ with this example? There's not report for the receive/sent bytes.

@danbriggs5 This would be the expected response:

![screenshot 2017-06-19 18 04 58](https://user-images.githubusercontent.com/3402/27305875-d93f853c-5519-11e7-96e1-1acaec10eb5f.png)

**Comment by fippo** [comment]
@djalmaaraujo "googCertificate" is legacy stats. Are you using getStats(null, callback) or getStats(callback) by chance? That is legacy

**Comment by djalmaaraujo** [comment]
@fippo I am using webrtc adapter. Here's the example of part of my code:

```js
      Promise.all([
        navigator.mediaDevices.enumerateDevices(),
        pc.getStats()
      ]).then(function ([devices, reports]) {
        console.log(devices);
        console.log(reports);
      });
```

Is there a new way to get the ssrc and recv stats?

**Comment by djalmaaraujo** [comment]
@fippo @danbriggs5 Figured out. Thanks. Issue with getting information after the "stream" was removed from the peer.

**Comment by danbriggs5** [comment]
Is this something that should still be addressed for Chrome 58 users? That is, should we add a conditional that prevents Chrome 58 from using the new getStats()? Or is it ideal to use the new getStats even if it causes a crash in rare circumstances?

**Comment by fippo** [comment]
if you want legacy stats you will need to downgrade to adapter 2.x, see [here]
(https://groups.google.com/forum/#!topic/discuss-webrtc/OXqm0tjg8hs). You could still use a monkeypatched version of adapter with https://github.com/webrtc/adapter/blob/master/src/js/chrome/chrome_shim.js#L315-L317 commented out.

If there are still chrome crashes go to chrome://crashes, submit a crash report and mention hbos@ but if they were severe the fix would probably have been uplifted

**Comment by djalmaaraujo** [comment]
@fippo Might not be related to this topic but in the new spec, the Outbound objects don't have jitter, only the incoming. Chrome used to have the googJitterReceived. Asking this because transitioning from Chrome 57+ to 58+ has a lack of stats compared to "goog" objects.

inbound-rtp jas ['jitter'], outbound-rtp doesn't.

Is there a new way to get this kind of information?

**Comment by fippo** [comment]
the selenium tests are now gone which makes this issue no longer relevant.
