### ISSUE TITLE
NPM install warns about unmet dependencies

### ISSUE THREAD

**Issue by KaptenJansson** [webrtcHacks/adapter#48]
npm WARN unmet dependency /home/test/dev/adapter/node_modules/testling/node_modules/browserify/node_modules/derequire/node_modules/esrefactor requires estraverse@'~0.0.4' but will load
npm WARN unmet dependency /home/test/dev/adapter/node_modules/testling/node_modules/browserify/node_modules/derequire/node_modules/estraverse,
npm WARN unmet dependency which is version 1.5.1

**Comment by KaptenJansson** [comment]
I can add that this is happens when doing a fresh install.

**Comment by alvestrand** [comment]
Filed https://github.com/ariya/esrefactor/issues/11 - this seems like a dependency problem far down the chain.
