### ISSUE TITLE
Cannot find standard constraints for screen capture

### ISSUE THREAD

**Issue by enricop89** [webrtcHacks/adapter#499]
**Browsers and versions affected**
Chrome, Firefox - All version with WebRTC

**Description**
Hello guys, this is not a issue of adapter, it's just a request of a Wiki or Repository in which I can find the standard constraints for the screen capture in Chrome and Firefox. 
In this example ([link](https://github.com/webrtc/samples/blob/22541207b2c6c7afbbe9697ed01c6bfe8ce19516/src/content/extensions/desktopcapture/app.js)) I see the code:
```
video: {
      mandatory: {
        chromeMediaSource: 'desktop',
        chromeMediaSourceId: streamId,
        maxWidth: window.screen.width,
        maxHeight: window.screen.height
      }
    }

```

The same doubts are for Firefox, in which I have the following working code:
`video: {mediaSource: 'window' || 'screen'}`

Is that the unique constraints for the screen capture? Is it correct to use them with adapter.js? Is there any reference that explains the specific constrains for the screen capture in Chrome or Firefox?

**Comment by oooookk7** [comment]
There seems to be a spec for this: https://w3c.github.io/mediacapture-screen-share/, and if possible, I wish that adapter.js would consider this as well :)

**Comment by KaptenJansson** [comment]
Not sure if we want to get into the constraints mess more than we already have, feel free to publish a PR and we can take from there.
