### ISSUE TITLE
Provide a unified stats interface in adapter.js

### ISSUE THREAD

**Issue by juberti** [webrtcHacks/adapter#5]
Currently, adapter.js makes no attempt to unify the getStats behavior between different browsers. Now that the standard seems to be settling on a stats format, adapter.js should attempt to provide it.

This work item does not include munging the names of any stats keys. The goal is only to provide a unified, browser-independent access method.

fippo commented on Oct 8, 2014
something like https://github.com/HenrikJoreteg/RTCPeerConnection/blob/master/rtcpeerconnection.js#L431
? Ignores the track argument though.
Benjamin M. Schwartz

bemasc commented on Nov 6, 2014
I was thinking of something like bemasc/webrtc-adapter@71a5837

**Comment by andresusanopinto** [comment]
webrtc/testrtc#74 is bitten by this :/

**Comment by milkypostman** [comment]
Will have to move webrtc/samples#484 to here when I get a chance...

**Comment by KaptenJansson** [comment]
What's the latest here? @fippo

**Comment by fippo** [comment]
basically this is done -- #76 remains and I might just do parts of it instead of writing code that works around it.

**Comment by KaptenJansson** [comment]
Did we give this up?

**Comment by KaptenJansson** [comment]
Closing this for now.
