### ISSUE TITLE
Firefox Unstable doesn't complete tests

### ISSUE THREAD

**Issue by alvestrand** [webrtcHacks/adapter#50]
Travis runs on Firefox Unstable end like this:
# call enumerateDevices

ALSA lib control.c:951:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib control.c:951:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib control.c:951:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM 
ALSA lib control.c:951:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM 
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

Firefox version is 41.0a1.

**Comment by alvestrand** [comment]
Tagging @jan-ivar (can't assign)

**Comment by jan-ivar** [comment]
Investigating here https://bugzil.la/1171947

**Comment by KaptenJansson** [comment]
@jan-ivar Is this the same failure as https://travis-ci.org/webrtc/adapter/jobs/70575019 ?

**Comment by jan-ivar** [comment]
The ALSA-specific output is missing, but otherwise it seems to be hanging in the same place. At mozilla we have a way to turn on fake devices in our test harness. Do you have something like this? How do you test of device-probing APIs reliably?

**Comment by jan-ivar** [comment]
We haven't had any luck reproducing this. Since this is running on some test server, probably without properly configured hardware, the solution here may be to find a way to turn on "fake" devices from travis. Constraints wont work unfortunately, since enumerateDevices takes no arguments.

Another solution would be to rebind enumerateDevices somehow in the test, since the purpose of these tests is to test the adapter code, not the firefox code.

**Comment by alvestrand** [comment]
Isn't Travis CI opensource?
I think it's running on some virtual machine - not sure which one. I'm pretty sure hardware access just isn't there.
We've had great response when we suggested new flags to Chrome for travis-multirunner, so if Firefox command line flags are an easy solution, let's just do that.

**Comment by KaptenJansson** [comment]
WRT to travis-multirunner + cmd line flags:

Chrome cmd flags are here https://github.com/DamonOehlman/travis-multirunner/blob/master/start-chrome.sh

Firefox cmd flags can be added here https://github.com/DamonOehlman/travis-multirunner/blob/master/start-firefox.sh

Also you can test flags already by just adding adding the flags to the BVER variable (i.e BVER="unstable--enable-logging").

**Comment by jan-ivar** [comment]
ALSA errors turned out to be a red herring. Embarassing fix in https://bugzil.la/1186209, though using fake devices avoids it too.

**Comment by KaptenJansson** [comment]
So I guess we should turn on fake devices for the enumerateDevices test, we are not testing the browser here, rather adapter.js. Question is if we still want to test it returning no devices (from an adapter.js perspective)? If so we can create an additional test not using fake devices.

**Comment by jan-ivar** [comment]
I thought https://github.com/DamonOehlman/travis-multirunner/pull/7 was supposed to turn on fake devices in Firefox. Do we need to do something to get Travis multi runner 2.6.0?

**Comment by jan-ivar** [comment]
I don't think we need to test zero devices in adapter.

**Comment by KaptenJansson** [comment]
https://github.com/DamonOehlman/travis-multirunner/blob/master/firefox-prefs.js

**Comment by KaptenJansson** [comment]
user_pref("media.navigator.streams.fake", true) is there.

**Comment by KaptenJansson** [comment]
The reason is in package.json,  "travis-multirunner": "^2.5.0", your fix made it in to 2.6.0.

I will bump the version.
