### ISSUE TITLE
Unable to get property 'id' of undefined or null reference in Edge

### ISSUE THREAD

**Issue by oooookk7** [webrtcHacks/adapter#510]
**Browsers and versions affected**
Edge 15.15063
Chrome 58.0.3029.68

**Description**
Upon setting the remote answer from Chrome, here is the error received:

> SCRIPT5007: Unable to get property 'id' of undefined or null reference

And clicking on the line points to this:
```
receiverList.forEach(function(item) {
 var track = item[0];
 var receiver = item[1];
 if (stream.id !== item[2].id) { // Points to here
      return;
   }
  var trackEvent = new Event('track');
  trackEvent.track = track;
  trackEvent.receiver = receiver;
  trackEvent.streams = [stream];
  self.dispatchEvent(trackEvent);
  if (self.ontrack !== null) {
   window.setTimeout(function() {
     self.ontrack(trackEvent);
   }, 0);
  }
});
```

**Steps to reproduce**
1. Go to [appear.in](appear.in) on Chrome and on Edge 15.15063 with video and audio enabled
2. Open the console on Edge and notice the errors. Notice that Edge receives the video stream but Chrome doesn't.

**Comment by fippo** [comment]
I see... thank you!
