### ISSUE TITLE
Save the original native RTCPeerConnection in Edge 15.15019+

### ISSUE THREAD

**Issue by oooookk7** [webrtcHacks/adapter#512]
**Browsers and versions affected**
Edge 15.15019

**Description**
Request to allow webrtc/adapter to save the original RTCPeerConnection object to msRTCPeerConnection or any prefix name so that users can decide to use the ORTC shim or the native legacy WebRTC implementation.

**Comment by fippo** [comment]
can you use webkitRTCPeerConnection? I'd rather avoid polluting window even more.

**Comment by oooookk7** [comment]
Actually I suggest "ms" because I was referencing the vendor prefix rules: https://developer.mozilla.org/en-US/docs/Glossary/Vendor_Prefix.

**Comment by KaptenJansson** [comment]
cc @fippo

**Comment by fippo** [comment]
I think the best way to do add this is to extend the factory to be called with a list of browsers that should be shimmed
