### ISSUE TITLE
Chrome not receiving video stream from Edge

### ISSUE THREAD

**Issue by oooookk7** [webrtcHacks/adapter#514]
**Browsers and versions affected**
Edge 15.16179, Windows 10.0.16179 Build 16179 (Home)
Chrome 58.0.3029.81, Mac OSX 10.11.6 (El Capitan)

**Description**
It seems like Chrome doesn't receive any video stream from Edge even though ssrc sources are provided, and direction is `a=sendrecv`, the m= line is active and not rejected.

Here are the SDPs. The SDPs seems correct but pasting here as extra information.

Native RTCPeerConnection:
- Chrome answer: [native-chrome-answer.txt](https://github.com/webrtc/adapter/files/946276/native-chrome-answer.txt)
- Edge offer: [native-edge-offer.txt](https://github.com/webrtc/adapter/files/946275/native-edge-offer.txt)

Polyfill RTCPeerConnection:
- Chrome answer: [chrome-answer.txt](https://github.com/webrtc/adapter/files/946279/chrome-answer.txt)
- Edge offer: [edge-offer.txt](https://github.com/webrtc/adapter/files/946278/edge-offer.txt)

Some notes:
- TURN ICE servers was provided.
- When testing with the native RTCPeerConnection in Edge, the video stream is received, but not with the ORTC API polyfill in v3.3.3. I'm not sure this should also be raised issue in Edge as their bug since it seems like a browser issue, but opening here to be sure since it works on the native RTCPeerConnection but not the polyfill.
- ICE was connected, although sometimes with failures.
- Once Chrome had completed gathering, Chrome sends the end-of-candidate signal to Edge. I've tried with sending the end-of-candidate signal once there is no response from `.onicecandidate` handle on Chrome's end for 2s after the previous ICE candidate generated as well, but I doubt it might be the cause of the issue as well.

**Steps to reproduce**
1. Chrome opens Peer connection.
2. Edge opens Peer connection.
3. Edge sends remote offer with `{ offerToReceiveAudio: true, offerToReceiveVideo: true }`
4. Chrome sends remote answer.
5. Noticed that in `peerConnection.getStats()`, only audio packets is received from Edge. Attached `<video>` element `.srcObject` with MediaStream is blank.

**Expected results**
Video stream should be rendered on attached `<video>` element.

**Actual results**
Video stream not appearing or rendering on `<video>` element

**Comment by fippo** [comment]
looks like Edge is not sending any data. The ICE and DTLS transports are up but nothing gets sent. Will bisect, thanks.

**Comment by ShijunS** [comment]
We will take a look on the Edge side.  It could be a regression in the Insider builds.

**Comment by fippo** [comment]
@letchoo where are you testing? I can reproduce on appear.in but not locally with adapter@3.3.3

**Comment by oooookk7** [comment]
@fippo I tested locally. I just went to check and test again but with Edge `15.15063` and I get this:

> ORTC18614: ORTC RTCIceGatherer: Transport endpoint allocation failed. hr=c004e00e.

To ensure that it isn't an application issue, I'll upload the demo code I made:
[webrtc-edge-demo.zip](https://github.com/webrtc/adapter/files/949041/webrtc-edge-demo.zip)

In case there are any errors I made, please feel free to point it out. If you want to run the demo, it uses socket.io server and node.js but please do modify it to point to your own socket server if required. The demo has some query parameters which you can define for testing additional cases:
- `uselegacy`: Uses the pre-1.0 RTCPeerConnection API.
- `forceofferer`: Enforces a peer to be offerer.

**Comment by fippo** [comment]
the transport allocation error failed error is because of passing iceTransports:relay with an empty array of servers.

This looks like the peer that is not sending video does not have an rtp sender. This seems to be because you are calling addStream after setRemoteDescription in the 'offer' callback. I'll see if I can come up with a fix.

**Comment by oooookk7** [comment]
@fippo my bad I forgot to clarify. Actually I tested with my own custom TURN servers username and credentials (it's long-term) hence I didn't append that to the demo. Here's an example I added:
```
iceServers: [{
  urls: ['turn:xxxxx']
  username: xxxx,
  credential: xxxx
}]
```

**Comment by fippo** [comment]
I have a potential fix for one problem. The video freezes on appear.in seem to be related to the getStats API. Will talk to @ShijunS about what causes them and potentially deactivate the component that causes this.
