### ISSUE TITLE
Assignment to read-only properties is not allowed in strict mode

### ISSUE THREAD

**Issue by oooookk7** [webrtcHacks/adapter#519]
**Browsers and versions affected**
Edge `15.16179`

**Description**
It seems like in `strict mode` it'll cause a problem if you tried to set the `RTCDtlsTransport` object, when DTLS handshake failed. It throws the following error:

> SCRIPT5045: Assignment to read-only properties is not allowed in strict mode

Expanding the line, it points to [at here](https://github.com/webrtc/adapter/blob/master/src/js/edge/rtcpeerconnection_shim.js#L409).

**Comment by fippo** [comment]
hrm. @shijuns what is the state of RTCDtlsTransport.state? http://internaut.com:8080/~baboba/ms/msortc.html#rtcdtlstransport-interface-definition* shows it so this code might be obsolete by now.

**Comment by ShijunS** [comment]
@Fippo, we have not implemented the "failed" state yet, however in the meanwhile, app can't set the readonly attribute either.

**Comment by fippo** [comment]
Hrm... i'll figure something out then. Thanks!

**Comment by oooookk7** [comment]
Should be resolved in: https://github.com/webrtc/adapter/pull/520. Closing.
