### ISSUE TITLE
UglifyJs Error in safari_shim

### ISSUE THREAD

**Issue by adamweeks** [webrtcHacks/adapter#536]
With the release of v3.4.0, we can no longer build with webpack. The arrow function on this line seems to be the issue: https://github.com/webrtc/adapter/blob/master/src/js/safari/safari_shim.js#L20

```
ERROR in bundle.js from UglifyJs
Unexpected token: operator (>) [~/webrtc-adapter/src/js/safari/safari_shim.js:20,0][bundle.js:215090,42]
```

This error does not happen with any previous versions.

**Browsers and versions affected**
Version 3.4.0
Webpack 2 with babel-loader

**Comment by fippo** [comment]
fix PR is up.

Looks like eslint is configured for ES6 but we don't want that actually. I'll see if I can come up with a more long-term fix.
