### ISSUE TITLE
Disconnected Event Appears as 'new' on _updateConnectionState

### ISSUE THREAD

**Issue by dcreey** [webrtcHacks/adapter#545]
**Browsers and versions affected**
Edge shim.

**Description**
RTCPeerConnection.prototype._updateConnectionState states object does not define a disconnected property. When the transceiver.iceTransport.state or transceiver.dtlsTransport.state is 'disconnected' it results in a value of NaN which therefore emits the default state of 'new'.

**Expected results**
'disconnected' event should be emitted.

**Actual results**
'new' event is emitted.

**Comment by fippo** [comment]
Thank you, i've just seen the effect of this too. PR to fix this is in #566
