### ISSUE TITLE
Bundled Tracks with Candidates with the same Foundation Number Inline on SDP Results in InvalidAccessError

### ISSUE THREAD

**Issue by dcreey** [webrtcHacks/adapter#546]
**Browsers and versions affected**
Edge Shim

**Description**
End-of-candidates notification fails (pc.addIceCandidate()) due to no remote candidates on iceTransport object. Candidates from the first track section should be added to the iceTransport remoteCandidates:

a=group:BUNDLE audio video
a=ice-options:trickle
...
m=audio 1 RTP/SAVPF 111 0
a=candidate:0 1 udp 2130379007 10.xx.x.xxx 5xxxx typ host generation 0
...
m=video 2 RTP/SAVPF 100 101 116 117
a=candidate:0 1 udp 2130379008 10.xx.x.xxx 5xxxx typ host generation 0
...

**Steps to reproduce**
Use sdp similar to above and pass to setRemoteDescription. Then pc.addIceCandidate() to notify 'end-of-candidates'.

**Expected results**
IceTransport object should contain a single candidate.

**Actual results**
IceTransport object contains no candidates. This results in an InvalidAccessError when attempting to send 'end-of-candidates' notification.

**Comment by fippo** [comment]
Your foundations are different above, is that intentional?

Right before the iceTransport.addRemoteCandidate({}) what does iceTransport.getRemoteCandidates() return? I suspect it contains the same candidate twice which will cause things to fail when trying to start the  transport.

The problem is that both m-lines share the same transport and addIceCandidate calls addRemoteCandidate with the candidates for the second m-line even if bundle is used. It probably shouldn't do that, will need to check the spec.

Thanks!

**Comment by dcreey** [comment]
On setRemoteDescription the candidates aren't added to the list of remote candidates unless 'a=end-of-candidates' is in the section. However, 'a=ice-options:trickle' would suggest that we may want to add other candidates after we setRemoteDescription via addIceCandidate. 

If I add 'a=end-of-candidates' the  iceTransport.getRemoteCandidates() correctly returns a single candidate. However, 'a=end-of-candidates' on Chrome yields "Failed to parse SessionDescription. a=end-of-candidates Invalid SDP line." (even without 'a=ice-options:trickle'). 

What is the expected configuration for someone with my use case?

Also,  I believe both candidates share the same foundation of 0.

**Comment by fippo** [comment]
ah.... the candidates in the sdp without end-of-candidates was never asked for. Filed https://github.com/fippo/adapter/issues/46 for an enhancement, I should be able to do this soon-ish. After looking at the other issue...

**Comment by KaptenJansson** [comment]
Closing as it´s fixed in the forked RTCPeerconnection shim, will be usable once the #581 PR is merged.
