### ISSUE TITLE
Chrome implements getSenders

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#552]
Chrome 60+ implements getSenders behind the experimental web platform features flag.
Currently the only attribute on the sender is its track.

This breaks shimGetSendersWithDtmf in the chrome shim as well as addTrack.
@jan-ivar @henbos can we find a way make this work?

**Comment by henbos** [comment]
If getSenders exists can we update adapter.js to shim adding dtmf to each sender?

**Comment by fippo** [comment]
only 50% resolved, addTrack still needs to be fixed.

**Comment by KaptenJansson** [comment]
Auto close :)
