### ISSUE TITLE
peerconnection/pc1/ Demo Does Not Work on Edge

### ISSUE THREAD

**Issue by dcreey** [webrtcHacks/adapter#554]
**Browsers and versions affected**
Edge

**Description**
peerconnection/pc1 demo does not work on Edge. Error is thrown: "SCRIPT16387: Could not complete the operation due to error c0044003.". 

Candidates are manually added to the paired peer connection via addIceCandidate. Before sending the 'end-of-candidates' (null) the remote candidates list contains duplicate candidates (foundation numbers 1,2,3 appear twice for a total of 6 candidates).

Perhaps either duplicate candidates (same foundation number) should be filtered out, or an error should be thrown if attempting to add a candidate with the same foundation number to the peer connection.

**Steps to reproduce**
Click Start, then Call in the peerconnection/pc1 demo on Edge.

**Expected results**
Peer connections successfully establish a connection and video displays in the remote video element.

**Actual results**
Error is thrown in the console and the remote video element remains black.

**Comment by fippo** [comment]
looks like a regression between 3.4.1 and 3.4.2.
Can you downgrade to 3.3.x? (not for the samples obviously)

**Comment by fippo** [comment]
alternatively deactivate https://github.com/webrtc/adapter/blob/master/src/js/adapter_core.js#L104
-- this shouldn't have ended in this release and it seems to cause onicecandidate to fire twice

**Comment by dcreey** [comment]
Version 3.4.0 works.
