### ISSUE TITLE
No logs are printed for Firefox

### ISSUE THREAD

**Issue by KaptenJansson** [webrtcHacks/adapter#56]
Open a new tab and open the javascript console.
Enter https://test.webrtc.org and check the console output.

This appears to be Chrome
(index):20 spec:   {"audio":{"optional":[{"sourceId":""}]},"video":{"optional":[{"sourceId":""}]}}
(index):20 chrome: {"audio":{"optional":[{"sourceId":""}]},"video":{"optional":[{"sourceId":""}]}}

While Firefox (38) prints
"This appears to be Firefox" 
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

@jan-ivar any ideas? I've not had a chance to dig into why yet.

Note I noticed the SHA1 ssl certificate warnings FF also prints, will follow that up separately (create a new certificate perhaps using SHA-256).

**Comment by jan-ivar** [comment]
The "spec"/"chrome" thing in the log is from the constraints conversion code, so you need to run FF37 or older to see it (FF 38 implements the spec so there's no conversion happening and nothing to log).

Is "mutating the prototype" warning new? Is there a better way to do that?

**Comment by KaptenJansson** [comment]
Aha that explains it, I find the logging useful regardless but I guess it's up to each web app to add their logging. 

I've seen the mutating prototype warning for a while I believe.

**Comment by KaptenJansson** [comment]
Also Firefox is awfully slow loading test.webrtc.org when running locally on localhost (GAE python), 15 seconds compared to 1.5 seconds on Chrome. Not sure if that has anything to do with the prototype error though.

**Comment by jan-ivar** [comment]
Hmm that doesn't sound good. When you say "loading" do you mean running the test to completion or something else? @fippo  are you seeing this?

**Comment by KaptenJansson** [comment]
By loading I mean the initial loading of the webpage. But now I cannot repro, seems to be an intermittent issue. I will file a separate issue regarding that if it appears again with logs, network traces from the developer console etc.

I guess we can close this then as you answered why FF < 38 does not produce any logs.

**Comment by jan-ivar** [comment]
FF >= 38 does not produce logs, you mean.

**Comment by KaptenJansson** [comment]
Yes sorry, I was not thinking clearly there :(.
