### ISSUE TITLE
RTCP Receiver Report Extensions being sent from Edge without any corresponding extmap entries in the SDP

### ISSUE THREAD

**Issue by pjosep** [webrtcHacks/adapter#562]
**Browsers and versions affected**
Edge Shim

**Description**
RTCP Receiver Reports being generated by Edge contain the following extension, but there is no corresponding extmap in the SDP to indicate this extension will be present.

Edge Extension Spec: https://msdn.microsoft.com/en-us/library/dd950523(v=office.12).aspx

(For a little more background, see this issue report on Microsoft's site:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12054804/)

**Steps to reproduce**
Set-up a PeerConnection between 2 Peers and inspect both the SDPs and the RTCP Receiver Reports that come out of Edge.

Neither CreateOffer nor CreateAnswer contain any extmap's indicating the extension in the Receiver Reports.

**Expected results**
I expect the SDPs to contain an extmap that corresponds to the extension in the Receiver Reports

**Actual results**
No such extmap's exist

**Comment by fippo** [comment]
that sounds familiar... can you provide an unencrypted RR as a pcap?

**Comment by pjosep** [comment]
Unfortunately, I am unable to successfully create an unencrypted Peer Connection with my current setup, but you can find an unencrypted binary RR packet in the MS issue that I referenced above (https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12054804/)

**Comment by fippo** [comment]
ah... I had encountered this before:  [rr.pcap.zip](https://github.com/webrtc/adapter/files/1020955/rr.pcap.zip) and had to fix my rtcp parser to ignore it.

This probably comes from the fast_bandwidth_feedback extension that Edge announces in RTCRtpReceiver.getCapabilities().headerExtensions. I'll need to check if .send and .receive are called without this when an answer from Chrome or Firefox comes that does not contain this.

**Comment by fippo** [comment]
IIRC that was in a situation where that extmap was not used in the SDP. So this doesn't seem like something that goes wrong in adapter but a native layer issue.
