### ISSUE TITLE
Conflict with external JS librairies

### ISSUE THREAD

**Issue by FredLuart** [webrtcHacks/adapter#569]
**Browsers and versions affected**
Tested on Chrome with latest adapter.js

**Description**
When deploying adapter.js on customer site, it happen that there is conflicts between existing JS librairies on the web site and adapter.js
I have two example with requireJs and browser.js

**Steps to reproduce**
I have prepared some simple page to show the issues :

Issue 1 :
http://www.apizee.com/Demo/testAdapter/testAdapterRequireJS.html
Error : Uncaught Error: Mismatched anonymous define() module: function (){var define,module,exports;return (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function" [...]

Issue 2 : http://www.apizee.com/Demo/testAdapter/testAdapterBrowser.html
Error : Uncaught TypeError: Cannot read property 'bind' of undefined
    at Object.shimCreateObjectURL (adapter-latest.js:3445)
    at adapter-latest.js:657 [...]

**Expected results**
Would expect adapter.js to have no conflict / impact with other librairies

**Actual results**
Conflict cause that adapter.js script cannot be executed

**Comment by fippo** [comment]
you might not want to use the bundled version together with either of these frameworks.

**Comment by FredLuart** [comment]
In fact, we don't manage JS librairies that are used on customer website and we want to able to use the same application on every webSite

**Comment by KaptenJansson** [comment]
We hope that this will be solved by #574.

**Comment by Victorystick** [comment]
@FredLuart I took the liberty to look into your errors.

1. The version of Adapter you're fetching is a UMD module, with an anonymous AMD module. Loading it via a plain script tag with requirejs loaded does not work. Instead, import it using `require`, or bundle it with your application.
```html
<script>
require(['https://webrtc.github.io/adapter/adapter-latest.js'], function (adapter) {
  console.log(adapter);
});
</script>
```

2. The second issue is caused by the `browser.js` script overriding the `URL` global. You cannot expect libraries like Adapter to work if the global namespace is polluted and important references destroyed.

**Comment by FredLuart** [comment]
@Victorystick Thank your for your feedback on the issue. I totally understand your point.
The issue is that we don't manage what is present on customer web site : we are used to load our application with plain script tag everywhere and when there is requirejs already loaded we have error with adapter.js

Concerning browser.js, I also totally agree with you but we don't manage what is installed on website and the issue is quite new in adapter.js : it used to work : I will try to find a working version of Adapter to complete the issue

**Comment by fippo** [comment]
the browser.js issue sounds like shimCreateObjectURL should check if URL.createObjectURL is a thing. @jan-ivar do you want to take a look?

**Comment by Victorystick** [comment]
@FredLuart Do you need to access the `adapter` global, or are you just looking to have the WebRTC APIs shimmed? In that case it you could load `release/adapter_no_global.js` instead which won't interact with requirejs.

While you may not control what's running on a customer's website, you can still let them know that their script is breaking your application.

**Comment by FredLuart** [comment]
@Victorystick Thank you, I think this is the solution for requirejs

**Comment by FredLuart** [comment]
Issue with browser.js is linked with shimCreateObjectURL

Adding following checkings solve the issue :
    if (URL.createObjectURL === undefined || URL.revokeObjectURL === undefined) {
        return undefined;
    }
