### ISSUE TITLE
Edge: Function "filterIceServers" does not allow TCP turn servers

### ISSUE THREAD

**Issue by Germain67** [webrtcHacks/adapter#573]
**Browsers and versions affected**
Microsoft Edge, any version.

**Description**
Function filterIceServers is filtering every of our TCP turn servers instead of keeping them.
Without this small fix we cannot establish a connection.

Actual code
```
var validTurn = url.indexOf('turn:') === 0 &&
url.indexOf('transport=udp') !== -1 &&
url.indexOf('turn:[') === -1 &&
!hasTurn;
```

Code that would fix the issue
```
var validTurn = url.indexOf('turn:') === 0 &&
(url.indexOf('transport=tcp') !== -1 || url.indexOf('transport=udp') !== -1) &&
url.indexOf('turn:[') === -1 &&
!hasTurn;
```

**Steps to reproduce**
Provide a configuration with iceServers that are only TCP turn servers.

**Expected results**
The function should return the same list (not filtering any of them).

**Actual results**
The list returned by the function is empty.

**Comment by fippo** [comment]
Have you successfully tried passing a TURN/TCP server to an RTCIceGatherer?
AFAIK this is still not supported, @shijuns please correct if I'm wrong.

**Comment by Germain67** [comment]
@fippo With the change suggested above, the TURN/TCP server was successfully passed to the RTCIceGatherer and I was able to stream video/audio between Edge and Chrome with this connection. So I guess it's supported !

Another issue we've met was with a stun server, which is normally supported by Edge right ?
When adapter.js initialize the iceGatherer, it throws an InvalidAcessError.
`var iceGatherer = new window.RTCIceGatherer(self.iceOptions); `

**Comment by ShijunS** [comment]
Edge doesn't support STUN and standard TURN/TCP.  The latest ORTC engine ignores them internally.  @Germain67, could you share details of the iceOptions?  I can check whether there is any bug on our end.

**Comment by Germain67** [comment]
Okay, that explains why STUN wasn't working, I was not sure about that.

@ShijunS I was able to use webrtc with a TURN/TCP server on Edge 40.15046, so I don't understand why you say it isn't supported... 
Maybe the support is only partial or I missed something ?

EDIT : With our config (actually one STUN server and several TURN/TCP servers), I had only the stun server in the iceOptions, as you can see on the following [screenshot](http://i.imgur.com/w529OvZ.png). I guess that's why it gave me an error.

**Comment by ShijunS** [comment]
One way to verify relay server options is to turn off all the host candidates.  Go to the "about:flags" page in Edge, check the box for "Hide my local IP address over WebRTC connections", and re-launch Edge.  Make sure though flip that back after testing.  

BTW, you might want to upgrade to newer Win10 build, at least to 15063.

**Comment by Germain67** [comment]
@ShijunS You were right, after hiding my local IP I was no more able to establish a connection. 
So it was effectively not using the TURN (certainly internally filtered by Edge).
I will try to find test servers TURN w/ UDP, given that it's the only way to use webRTC with edge.

Edit : Done update and tried with a UDP server, it worked.

**Comment by Germain67** [comment]
@fippo @ShijunS I have tried with a TURN server using UDP and it worked !

However, I'm pretty sure there is something that should be modified in the filterIceServers function.
In latest version of adapter.js , STUN servers that meet the following requirements aren't filtered.
`return url.indexOf('stun:') === 0 && edgeVersion >= 14393;` 

But as you said before : STUN isn't supported yet on Edge (even after 14393), thus causing an error when trying to initialize the iceGatherer (it throws an InvalidAcessError) :
`var iceGatherer = new window.RTCIceGatherer(self.iceOptions);`

I think stun servers should be filtered to prevent this error until it is supported on a newer version of Edge.

**Comment by fippo** [comment]
@Germain67 what is the exact 'stun:...' you're passing?

**Comment by Germain67** [comment]
Our stun is the following "stun:stun1.ourdomain.com:80" (ourdomain is replaced by our domain name).
It works great on chrome, but it is causing an error on Edge as I explained in my previous post.

**Comment by thedracle** [comment]
Is this still a thing on Edge 15+?

**Comment by KaptenJansson** [comment]
Closing due to age.

**Comment by justinIs** [comment]
Does anyone know if this is still a thing? 
Also is some sort of error thrown or at least logged if the adapter detects an iceServer that's being filtered out?

Was pulling my hairs out until I decided to go through this code. I originally thought it was the webrtc library that I was using that prevented us from doing a STUN lookup

**Comment by fippo** [comment]
@justinIs good catch at version not being passed. Note that stun still isn't supported though.

**Comment by aisnote** [comment]
any update for Edge18 which will support turn over TCP? anyone know that?
