### ISSUE TITLE
[Chrome] Please don't force users to just set pc.ontrack but also allow pc.addEventListener('track')

### ISSUE THREAD

**Issue by ibc** [webrtcHacks/adapter#575]
The Chrome shim provides [pc.ontrack](https://github.com/webrtc/adapter/blob/master/src/js/chrome/chrome_shim.js#L19), but if the app uses a proper `pc.addEventListener('track', fn)` it's ignored (because the shim just react on `pc.ontrack` being set).

Well, I do know that many people just rely on `pc.onxxxx` setters, but probably most of them don't even know what a [EventHandler](https://html.spec.whatwg.org/multipage/webappapis.html#eventhandler) is.

So my proposal is that the Chrome PeerConnection shim calls to `dispatchEvent(event)` (as in lines 46 and 61) without requiring that the user sets `pc.ontrack` before.

**Comment by fippo** [comment]
i also wonder why we did not have a test for that... this needs to work:
```
var pc = new RTCPeerconnection();
pc.addEventListener('track', ...);
pc.setRemoteDescription(...)
```
and the track listener fires.

**Comment by ianwremmel** [comment]
Ran into the same thing. I think I may have seen it in a few other places as well. `onicecandiate` and `onnegotiationneeded` may be worth a look at the same time (I may also be making that up at this point)

**Comment by fippo** [comment]
hrm. This is actually somethat tricky because either the shim needs to be added in the constructor (which is not wrapped in current versions) or I need the addEventListener wrapper from https://github.com/webrtc/adapter/pull/560/files in a modified form (simple pass through without modification)

@ianwremmel yeah, ONN is very broken in Chrome :-/

**Comment by ibc** [comment]
I don't think a full `addEventListener` wrapper is required at all. The exact problem reported in this issue is that `ontrack` is just called if the app sets `pc.ontrack = fn` before.

The shim should dispatch a `track` event when appropriate, regardless the app assigned a function to `pc.ontrack` or not. If so, the shim should also honor the given `ontrack` listener.

**Comment by fippo** [comment]
see the updated second comment about what must work. This means we need to install the polyfill either in the constructor or in addEventListener. Neither is pretty.

**Comment by ibc** [comment]
```js
var pc = new RTCPeerconnection();
pc.addEventListener('track', ...);
pc.setRemoteDescription(...)
```

The shim (when in Chrome) must add a `addstream` listener. It will be called on `pc.setRemoteDescription()`. When called, get all the tracks, create a `new Event('track')` with all the corresponding fields, and call `pc.dispatchEvent('track')` (and also `pc.ontrack()` if set).

What is the exact problem?

**Comment by ibc** [comment]
Ok, I think I get your point. Somewhere the shim needs to become a middleware for every created `RTCPeerConnection` so it can listen for `addstream` events and dispatch fake `track` events. But the shim is not providing the user with a wrapper class but, instead, it just mangles the prototype. Mmmmm.

How about overriding the `RTCPeerConnection.prorotype.setRemoteDescription` so, when invoked, the shim attaches its `addstream` event listeners?

**Comment by fippo** [comment]
I like that idea! Will give it a try, much better than doing it addEventListener

**Comment by ibc** [comment]
Remember to just set addstream listeners just the first time sRD is called ;)

**Comment by youennf** [comment]
Safari shim has probably the same issue with onaddstream.
