### ISSUE TITLE
`pc.removeTrack()` not implemented in chrome shim

### ISSUE THREAD

**Issue by ianwremmel** [webrtcHacks/adapter#577]
**Browsers and versions affected**

Chrome 58

**Description**

`pc.removeTrack()` not implemented.

**Steps to reproduce**

call `pc.removeTrack(sender)`

**Expected results**
track gets removed. 

**Actual results**
Reference Error

**Possible Solution**

I went down a pretty gnarly path before discovering that the following seems to do the trick.

```js
function removeTrack(pc, track)
  if (pc.removeTrack) {
    pc.removeTrack(pc.getSenders().find((s) => s.track === track));
  } 
  else {
    pc.getLocalStreams()[0].removeTrack(track);
  }
}
```

**Comment by fippo** [comment]
testing this is a bit tricky... the best assertion I have seen so far is that a subsequent call to createOffer on a one-way connection has a=inactive after this. I should have a PR some time next week

**Comment by fippo** [comment]
note: we need to port some tests to removeTrack too -- once #597 has landed

**Comment by kherock** [comment]
This needs implemented for Edge as well!

For the solution given to work in Edge, `pc.addStream` has to be called or else `pc.getLocalStreams()` will give an empty array.
