### ISSUE TITLE
pc.removeStream() has no effect when using addTrack shim

### ISSUE THREAD

**Issue by benbro** [webrtcHacks/adapter#586]
**Browsers and versions affected**
Chrome 59.0.3071.86
Chrome 61.0.3124.10 (Canary)

adapter.js v4.0.1

**Description**
pc.removeStream(localStream) has no effect after using pc.addTrack(track) to add the local tracks.
When using pc.addStream(localStream) it works.

**Steps to reproduce**
1. go to https://webrtc.github.io/samples/src/content/peerconnection/pc1/
2. Click 'Start' and 'Call'
3. Paste the following in the console:
```javascript
pc1.removeStream(localStream);
pc1.createOffer(
    offerOptions
  ).then(
    onCreateOfferSuccess,
    onCreateSessionDescriptionError
);
```

**Expected results**
The local stream should be removed from the sdp and the remote video display should freeze.
**Actual results**
The new sdp still has the local stream. The remote video continue to show the webcam.

**Comment by fippo** [comment]
so removeStream doesn't do any lookup of the mapped stuff. Fixed in an update to #559

**Comment by fippo** [comment]
should work again, can you check please and close when its fixed? Thanks!

**Comment by benbro** [comment]
Can't reproduce with the steps above.
Thanks
