### ISSUE TITLE
removing a mediastream from an element

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#59]
from https://github.com/MicrosoftEdge/Demos/pull/68
-- removing a stream from an element works differently in different browsers.

The easiest solution which doesn't increase the API surface of adapter seems to pass null or false to attachMediaStream. Thoughts @alvestrand @KaptenJansson?

**Comment by alvestrand** [comment]
First thing to do is to file a bug against the spec to make sure it's well defined what it SHOULD do... you or I?

Passing null to attachMediaStream seems like a good approach to giving at  least one way to reset it. I like explicit values (null) rather than depending on Javascript truthiness.

**Comment by fippo** [comment]
Setting srcObject to null seems to be the spec way to do it -- https://w3c.github.io/mediacapture-main/getusermedia.html#direct-assignment-to-media-elements

For the src attribute I am not sure what to do even. Setting it to null or undefined loads triggers a request for that path which is ugly but doesn't do any harm. videoEl.removeAttribute('src') doesn't seem to work in either Chrome or Firefox.

**Comment by fippo** [comment]
setting srcObject = null solves this I think.
