### ISSUE TITLE
{facingMode: "environment"} video constraint doesn't work

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [webrtcHacks/adapter#594]
**Browsers and versions affected**

Chrome for Android >=61 (Dev and Canary channels).

_All is ok on Chrome for Android <60 (Stable and Beta)._

_All is ok on any (all) versions without WebRTC adapter._

**Steps to reproduce**

```js
var constraints = {video: {facingMode: "environment"}}
navigator.mediaDevices.getUserMedia(constraints)
```

or

```js
var constraints = {video: {facingMode: {exact: "environment"}}}
navigator.mediaDevices.getUserMedia(constraints)
```

**Expected results**

Get the back-facing camera stream.

**Actual results**

Get the front-facing camera stream (the first code sample) or nothing — the browser does not request the permission (the second code sample).

**Comment by FluorescentHallucinogen** [comment]
I've also tried a workaround — connect only to a FullHD camera (because the front-facing camera doesn't support FullHD):

```js
{video: {"mandatory": {width: 1920, height: 1080}}}
```

and

```js
{video: {width: {exact: 1920}, height: {exact: 1080}}}
```

but without success. Both code samples doesn't work at all (the browser does not request the camera permission) in any (all) versions Chrome for Android with and without WebRTC adapter.

**Comment by Lucassifoni** [comment]
Hey, did you manage to solve this ?

**Comment by holgermertens** [comment]
Same here. Any solutions?

**Comment by Lucassifoni** [comment]
I "sort of" solved it, but instead of switching between back/front cameras, I cycle through available cameras **by constraining on deviceId** (to this day, most devices have either one or two, so it's not really a problem) :

(Sorry, this is a WIP and formatted with prettier defaults) 

### utility class to paint on a canvas, with a switch method to cycle through cameras
```js
import Loop from "./../loop"; // utility for requestanimationframe

class GumUtils {
  constructor(canvas, video) {
    /*
               redacted for clarity
    */
    this.devices = [];
    this.currentDevice = 0;
  }

  fitImage(image) {
    /*
               redacted for clarity
    */
  }

  boot() {
      return new Promise((resolve, reject) => {
          navigator.mediaDevices.enumerateDevices().then((devices) => {
              this.devices = devices.filter(dev => dev.kind === 'videoinput');
              resolve(this.devices);
          }).catch((err) => {
              reject(err);
          });
      });
  }

  start() {
    this.boot().then((devices) => {
        navigator.mediaDevices
            .getUserMedia({
                video: {
                    deviceId: this.devices[this.currentDevice].deviceId,
                },
                audio: false,
            })
            .then(stream => {
                this.streamRef = stream;
                this.video.srcObject = stream;
                this.video.play();
                this.loop = new Loop(
                    { fps: 60, frameskip: 17},
                    frame => {
                        if (this.video.readyState === this.video.HAVE_ENOUGH_DATA) {
                            this.fitImage(this.video);
                        }
                    },
                    frame => {}
                );
                this.loop.start();
            })
            .catch(err => {        
    /*
               redacted for clarity
    */
            });
    });
  }

  stop() {
    this.streamRef.getTracks().forEach(track => {
      track.stop();
    });
    this.loop.stop();
  }

  export() {
    return this.canvas.toDataURL("image/jpeg", 0.75);
  }

  switch() {
    this.stop();
    const i = this.currentDevice;
    if (!!this.devices.length && i < this.devices.length - 1) {
      this.currentDevice += 1;
    } else {
      this.currentDevice = 0;
    }
    this.start();
  }
}

export default GumUtils;
```

**Comment by Pymous** [comment]
This is still an issue to this day.

I reproduced the issue on all of our android devices (5 different models, from a Wiko Freddy to a Honor 8) with Chrome.

Android Firefox works, Safari 11 on iOS works.

Here is a snippet which reproduce the issue with minimal coding : https://jsfiddle.net/s74zvc8n/4/

**Comment by Lucassifoni** [comment]
Well, after updating my iOs devices I'm facing the exact same issues, and my previously posted solution using enumerateDevices isn't working with Firefox or Safari.

I'm targeting chrome on Android since this is a project where I control the devices using it, bit that's still frustrating. We should be beyond this era of multi-browser code..

**Comment by Pymous** [comment]
Fixed in https://github.com/webrtc/adapter/pull/692
It seems

**Comment by heqiang100** [comment]
ios is suport set size?
example
{video: {"mandatory": {width: 1920, height: 1080}}}
it's ios bug?

**Comment by neilyoung** [comment]
@Lucassifoni Your "loop" thing looks promising. Would you mind to share?

**Comment by Lucassifoni** [comment]
@neilyoung 
Hey, sure, but it isn't really "something". Just a frame counter to set a callback every X frame.
Here's a gist : https://gist.github.com/Lucassifoni/9db36a678586d6803d4257c9bcf25d1f

To others : sorry for the noise in this discussion, I didn't know where else to answer !

**Comment by neilyoung** [comment]
@Lucassifoni Nice. Thanks for sharing. I'm doing something similar, but drawing with each `requestAnimationFrame` and taking the resulting image timer based. Maybe your approach is less resource hungry, will give it a try.
