### ISSUE TITLE
Video not working between Chrome/Firefox and Edge

### ISSUE THREAD

**Issue by blkwtkns** [webrtcHacks/adapter#596]
**Browsers and versions affected**

Microsoft Edge 40.15063.0.0 (Running in Windows 10 pro Creator's Update)
Chrome Version 57.0.2987.98 (64-bit) (running in Debian Wheezy)
Firefox 53.0.3 (Running in Debian Wheezy)
Latest adapter

**Description**

Not sure if this is really an adapter issue but I'm hoping that I could get some help here. I am using adapter.js in our RTC project, and things work great except between the given version of Edge and Chrome/FF. Everything seems to work but the videos don't display. I've given a bit more detail here: 

https://stackoverflow.com/questions/44708692/webrtc-differing-stream-ids-and-formatting-between-chrome-ff-and-edge

Here are the main issues:
1) The call can only be initiated by the Edge user, otherwise the transfer of sdp information doesn't complete.

2) When initiated by Edge user, the full exchange happens, but remote videos can't be seen, which I thought I had narrowed down to a discrepancy in stream ids between the two clients, but I was then informed that stream identification didn't matter much. What I can say further about this is that stream ids produced locally in Chrome are a full 36 character length string, restricted letters and numbers, while the stream produced by edge has dashes incorporated in its stream ids. Remote ids in chrome to chrome have dashes as well, so I'm assuming that there's some conversion of this id when transferred from chrome browsers if it's not in the dashed representation. 

One ancilliary issue that I've noticed with Edge is that when the success function fires from the navigator.mediaDevices.getUserMedia function, the video camera starts up, but then immediately shuts down. I have to enable it afterwards through javascript and then obtain stream ids, otherwise chrome/other client won't even get correct stream information of edge's running stream. I was told in my SO post that this is expected behavior in Edge.

I also am not able to get the appr.tc site to work between either Chrome/FF and Edge client.

**Steps to reproduce**

RTC application between either Chrome/FF and Edge
Currently unable to test Edge to Edge...

**Expected results**

Remote video display between clients

**Actual results**

Video element has black screen, no errors given through whole process (after adjusting for Edge's distaste for data channel)

**Comment by fippo** [comment]
Do you have a chrome://webrtc-internals JSON dump from the failure case? (remember to open that page before making the call)

What I am looking for (see [here](https://testrtc.com/webrtc-api-trace/) is whether the full offer-answer cycle completes and the correct ice candidates are exchanged.

Does [appear.in](https://appear.in/) work in the same setup?

**Comment by blkwtkns** [comment]
I had no idea about these tools, I'll get a dump and go through the testing tomorrow at work and see if there's some info worth posting back. 

appear.in does work in the same setup, I tested it today, I was really happy to see some proof of rtc working between edge and everything else. Thanks for the tips again!

**Comment by blkwtkns** [comment]
I've gotten edge to work now, I believe the biggest issue is that edge doesn't support data channels, and I don't think the adapter accommodates for this, for I kept getting error from the adapter for the 'addRemoteCandidate can't be accessed from undefined'. 

I'm now struggling a little with edge's handling of video resolution. On the same setups as stated in my first post, when communicating from Edge to browser to any other client, the non Edge client's remote stream's resolution is quite bad... anyone dealt with this before? Both systems are using the same camera, and drivers have been installed for the camera on both.

Edit: I think the resolution IS a drivers issue, just tested between the windows 10 system and another windows 10 system running on a thinkpad - the thinkpad's resolution was fine, so it should be a driver issue.

**Comment by fippo** [comment]
do you remember the line where the exception happens? addIceCandidate could be a bit more robust here, I think the following piece of code shows the problem:
```
var sdp = "v=0\r\no=- 166855176514521964 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=msid-semantic:WMS *\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:someufrag\r\na=ice-pwd:somelongpwdwithenoughrandomness\r\na=fingerprint:sha-256 8C:71:B3:8D:A5:38:FD:8F:A4:2E:A2:65:6C:86:52:BC:E0:6E:94:F2:9F:7C:4D:B5:DF:AF:AA:6F:44:90:8D:F4\r\na=setup:actpass\r\na=mid:data\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n";

var pc = new RTCPeerConnection();
pc.setRemoteDescription({type: 'offer', sdp: sdp})
.then(() => {
  return pc.addIceCandidate({sdpMid: 'data', 
    candidate: 'candidate:702786350 1 udp 41819902 8.8.8.8 60769 typ host'})
})
.then(() => {
  console.log('yay')
}, (e) => {
  console.error(e);
});
```
shouldn't be fatal but this needs to check the m-line is not rejected :-/
