### ISSUE TITLE
Edge failing when receiving sendonly audio+video offer

### ISSUE THREAD

**Issue by lminiero** [webrtcHacks/adapter#605]
Before filling the fields, let me anticipate that I'm not 100% sure this is adapter related, but I thought I'd share this here as I know of no way to debug issues in Edge (not aware of any webrtc-internals equivalent), and just in case it is indeed caused by the adapter.

**Browsers and versions affected**
Edge 40.15063.0.0

**Description**
Apparently Edge fails to setup a PeerConnection whenever the peer sends an offer with sendonly audio and video, which means Edge should answer with recvonly audio+video (a plain viewer, basically, with the session originated by a server, Janus in this case). I don't see any issue in the SDP (I've created a [gist](https://gist.github.com/lminiero/866d5f7d4ab373181afa5b1023b2bf5e) showing the offer and the answer), but from what I can see in the Janus logs and Wireshark, Edge never answers our connectivity checks, and doesn't generate any either. This makes me think it's stuck in some inconsistent state, but not caused by the remote SDP as it does indeed answer. No exception on the JS console to be seen, so no idea what may be going wrong there.

**Steps to reproduce**
Visit https://janus.conf.meetecho.com/streamingtest with Edge, and start the Opus/VP8 sample stream. Notice that this page uses version 3.4.3 of the adapter from cdnjs, but I tried locally using 4.0.2 instead, and the result was the same (the gist above comes from a local test with 4.0.2). I haven't tried master yet, as I have to rely on a colleague with an Edge to test against, and he's not always available.

**Expected results**
Streaming should start, and media should start flowing.

**Actual results**
The setup fails, and we get an "ICE Failed" error after a few seconds. As anticipated, Edge never answers the ICE connectivity checks, so ICE eventually fails. Trying one of the other streams in the same page works, instead, but in that case they're both audio-only. Other demos work as well (apart, again, when there's a PeerConnection setup where Janus offers sendonly audio+video and Edge answers with recvonly). Haven't tried a generic remote offer yet (so not strictly sendonly), will do that tomorrow just for the sake of completeness.

**Comment by fippo** [comment]
quick guess (edge laptop already packed up): try adding a=end-of-candidates

**Comment by lminiero** [comment]
Will try, thanks! But that wouldn't explain why it works when I only offer a single medium, and not when I offer both, wouldn't it? At first I thought it could be because of the different ICE credentials for the two streams, but even using the same for both nothing changed.

I'll try the `a=end-of-candidates` thing and let you know.

**Comment by lminiero** [comment]
Actually, looking at the code, it looks I'm already doing this before doing a `setRemoteDescription`... https://github.com/meetecho/janus-gateway/blob/master/html/janus.js#L1375
The reason why it's missing from the dump I linked, is that those are the SDPs I collected from the Janus Admin API, and so are the SDPs as seen from the Janus perspective. Sorry for the noise!

**Comment by ShijunS** [comment]
@lminiero did you add the a=end-of-candidates line to both audio and video sections?

**Comment by lminiero** [comment]
@ShijunS no, I only add the `a=end-of-candidates` at the end, as I always saw this as a way to say "no more candidates after this one". This seems to work as expected for all scenarios except the one I described. Is this actually needed for each m-line, in Edge?

**Comment by ShijunS** [comment]
@lminiero it works fine for your audio-only scenarios. it looks like we have issue when you put both audio and video in the SDP. 

@fippo is this required based on the adapter implementation?

**Comment by lminiero** [comment]
@ShijunS by other scenarios, I also meant cases where Edge would offer sendonly audio+video, and Janus would answer recvonly audio+video: that works and doesn't fail, and we also only put a single a=end-of-candidates at the end, rather than one per media stream.

That said, checking what the Trickle draft says about end-of-candidates, especially in the half trickle case (which is what Janus does), the behaviour you described may indeed be the correct one (one per media stream), although it's not 100% clear in the text (it sometimes talks of media stream, and others of media session).

**Comment by fippo** [comment]
if you add a=end-of-candidates on the second m-line and use bundle on the first that is not going to work.

How does one access the peerconnection object in the demo (which fails in the latest windows insider build in janus.js line 68... probably not accessing any code after that so click does not work).

I'd check pc.getReceivers()[0].transport.transport.state -- if it is still "new" then its end of candidates missing

**Comment by fippo** [comment]
hrm... I managed to reproduce the issue: http://jsfiddle.net/oe34qq11/2/
You don't add end-of-candidates to the first m-line so candidates in the SDP won't be processed which means even the default timeout won't help.

The upcoming new shim version should fix that but i'd still recommend a=end-of-candidates in the first m-line.

**Comment by lminiero** [comment]
Thanks for confirming that's the cause of the issue. I'll change the
JavaScript code to add it for all media streams, and update the online
demos to use that (unfortunately I don't have an Edge machine to test with
by myself).

Il 14 lug 2017 9:27 PM, "Philipp Hancke" <notifications@github.com> ha
scritto:

**Comment by lminiero** [comment]
Worked on a simple function to munge SDP for Edge: https://jsfiddle.net/2d3600vc/1/
Seems to work fine with the sample SDP from your fiddle, I'll check if it's the same with some real SDPs generated by Janus too, and in case update the demos too.

**Comment by lminiero** [comment]
@ShijunS @fippo I just updated the online demos, could you check if the Streaming demo now works with Edge? As anticipated, I can't test myself unfortunately, as I'm abroad and don't have access to the machine with Edge installed... https://janus.conf.meetecho.com/streamingtest

Philipp, if it does, and you believe the method is not too ugly, feel free to incorporate it for the adapter if you feel it could be useful for the next version :slightly_smiling_face:

**Comment by fippo** [comment]
works here (apart from the error with the console.log.bind)  -- I should really expose https://github.com/fippo/sdp somewhere so you don't have to parse all the SDP yourself ;-)

**Comment by lminiero** [comment]
Thanks for testing so quickly! I wasn't aware of those SDP utilities you wrote, I'll definitely have a look at that to see if I can use them somehow :+1:

**Comment by fippo** [comment]
with the utils your function would roughly look like this: https://jsfiddle.net/2d3600vc/4/ (but the module can currently not be included via rawgit so i had to copy-paste :-/)

**Comment by lminiero** [comment]
I don't see the `a=end-of-candidates` attributes in the SDP in the `<pre>` on the right, though, maybe a typo somewhere?

Edit: see it now! (I guess I was looking at a temporary version of the fiddle, sorry)

**Comment by lminiero** [comment]
Ops, forgot to close this, as it is indeed working as expected with the attribute added to all m-lines. Thanks for the help!

**Comment by kekkokk** [comment]
Hi guys!
I'm having the same exact issue. I use Licode as SFU.
When I publish or subscribe at one stream only (audio or video) everything's work fine.
But when I try to subscribe or publish both ICE fails. 
I followed your suggestion to add a=end-of-candidates but still can't get the ICE work.

this is sdp generated by the server when subscribing to a video only stream:

> v=0
> o=- 0 0 IN IP4 34.252.48.203
> s=BandyerMCU
> t=0 0
> a=msid-semantic: WMS O98gVKJ830
> a=group:BUNDLE ecmgaihvg4
> m=video 1 UDP/TLS/RTP/SAVPF 100
> c=IN IP4 34.252.48.203
> b=AS:3000
> a=rtpmap:100 VP8/90000/2
> a=rtcp:1 IN IP4 34.252.48.203
> a=rtcp-fb:100 nack
> a=rtcp-fb:100 nack pli
> a=rtcp-fb:100 goog-remb
> a=extmap:1 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
> a=setup:active
> a=mid:ecmgaihvg4
> a=sendonly
> a=ice-ufrag:5he7
> a=ice-pwd:6lbeHhuVnId0G3bU2o8Cbh
> a=fingerprint:sha-256 13:36:FF:40:A3:A2:66:C3:9D:AF:1A:A4:85:41:D7:D9:21:87:9F:65:68:59:AD:A2:29:8E:87:B8:CC:6A:95:2E
> a=candidate:4 1 udp 2013266430 34.252.48.203 48863 typ host generation 0
> a=candidate:6 1 udp 1010827775 34.252.48.203 55712 typ host generation 0
> a=end-of-candidates
> a=ssrc:338405507 cname:o/i14u9pJrxRKAsu
> a=ssrc:338405507 msid:O98gVKJ830 ecmgaihvg4
> a=ssrc:338405507 mslabel:O98gVKJ830
> a=ssrc:338405507 label:O98gVKJ830
> a=rtcp-mux

and these are the candidates sent by edge:

> candidate: "a=candidate:1 1 UDP 2130706431 192.168.1.171 63972 typ host"
> sdpMid: "ecmgaihvg4"
> sdpMLineIndex: 0
> 
> candidate: "a=candidate:2 1 UDP 33553919 2001:0:9d38:6abd:3c8d:82ea:a2d5:d127 59986 typ host"
> sdpMid: "ecmgaihvg4"
> sdpMLineIndex: 0
> 
> candidate: "a=candidate:3 1 UDP 184548351 5.153.29.243 57724 typ relay raddr 93.42.46.216 rport 31974"
> sdpMid: "ecmgaihvg4"
> sdpMLineIndex: 0
> 
> candidate: "a=candidate:4 1 UDP 1694235135 93.42.46.216 31974 typ srflx raddr 192.168.1.171 rport 61950"
> sdpMid: "ecmgaihvg4"
> sdpMLineIndex: 0
> 
> candidate: "a=candidate:5 1 TCP 1684797439 93.42.46.216 31974 typ srflx raddr 192.168.1.171 rport 61950 tcptype active"
> sdpMid: "ecmgaihvg4"
> sdpMLineIndex: 0
>
> END CANDIDATE

and it works. (note that I had to filter out empty candidates since they were sent by edge between each candidate (which I think is a bug since the empty candidate should be sent only on ice gathering complete)

These are sdps generated when both audio and video are present: 

> v=0
> o=- 0 0 IN IP4 34.252.48.203
> s=BandyerMCU
> t=0 0
> a=msid-semantic: WMS YCsCQH3u6T
> a=group:BUNDLE sy2bkxel43 3fc9add9oo
> m=audio 1 UDP/TLS/RTP/SAVPF 102
> c=IN IP4 34.252.48.203
> a=rtpmap:102 opus/48000/2
> a=rtcp:1 IN IP4 34.252.48.203
> a=extmap:1 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
> a=setup:active
> a=mid:sy2bkxel43
> a=sendonly
> a=ice-ufrag:WoIA
> a=ice-pwd:HVaQ1rCdqKvFhSNfkfeDBR
> a=fingerprint:sha-256 7A:5B:50:4E:4B:15:49:AC:48:75:03:1B:33:82:AC:95:B2:88:75:6D:98:04:08:D0:D7:81:2F:02:1B:E9:4B:DE
> a=candidate:4 1 udp 2013266430 34.252.48.203 33593 typ host generation 0
> a=candidate:6 1 udp 1010827775 34.252.48.203 40878 typ host generation 0
> a=end-of-candidates
> a=ssrc:2173138652 cname:o/i14u9pJrxRKAsu
> a=ssrc:2173138652 msid:YCsCQH3u6T sy2bkxel43
> a=ssrc:2173138652 mslabel:YCsCQH3u6T
> a=ssrc:2173138652 label:YCsCQH3u6T
> a=rtcp-mux
> m=video 1 UDP/TLS/RTP/SAVPF 100
> c=IN IP4 34.252.48.203
> b=AS:3000
> a=rtpmap:100 VP8/90000/2
> a=rtcp:1 IN IP4 34.252.48.203
> a=rtcp-fb:100 nack
> a=rtcp-fb:100 nack pli
> a=rtcp-fb:100 goog-remb
> a=extmap:1 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
> a=setup:active
> a=mid:3fc9add9oo
> a=sendonly
> a=ice-ufrag:WoIA
> a=ice-pwd:HVaQ1rCdqKvFhSNfkfeDBR
> a=fingerprint:sha-256 7A:5B:50:4E:4B:15:49:AC:48:75:03:1B:33:82:AC:95:B2:88:75:6D:98:04:08:D0:D7:81:2F:02:1B:E9:4B:DE
> a=candidate:4 1 udp 2013266430 34.252.48.203 33593 typ host generation 0
> a=candidate:6 1 udp 1010827775 34.252.48.203 40878 typ host generation 0
> a=end-of-candidates
> a=ssrc:1751204421 cname:o/i14u9pJrxRKAsu
> a=ssrc:1751204421 msid:YCsCQH3u6T 3fc9add9oo
> a=ssrc:1751204421 mslabel:YCsCQH3u6T
> a=ssrc:1751204421 label:YCsCQH3u6T
> a=rtcp-mux

and these are candidates generated:

> candidate: "a=candidate:1 1 UDP 2130706431 192.168.1.171 62990 typ host"
> sdpMid: "sy2bkxel43"
> sdpMLineIndex: 0
> 
> candidate: "a=candidate:2 1 UDP 33553919 2001:0:9d38:6abd:3c8d:82ea:a2d5:d127 57068 typ host"
> sdpMid: "sy2bkxel43"
> sdpMLineIndex: 0
> 
> candidate: "a=candidate:3 1 UDP 184548351 5.153.29.243 50617 typ relay raddr 93.42.46.216 rport 32014"
> sdpMid: "sy2bkxel43"
> sdpMLineIndex: 0
> 
> candidate: "a=candidate:4 1 UDP 1694235135 93.42.46.216 32014 typ srflx raddr 192.168.1.171 rport 50318"
> sdpMid: "sy2bkxel43"
> sdpMLineIndex: 0
> 
> candidate: "a=candidate:5 1 TCP 1684797439 93.42.46.216 32014 typ srflx raddr 192.168.1.171 rport 50318 tcptype active"
> sdpMid: "sy2bkxel43"
> sdpMLineIndex: 0

but this I can't make it to works.
I noticed that only candidates for one stream are sent
Do you see something strange in there? Have any suggestion on where to start debugging?
@lminiero @fippo 
Have a nice day!

ps. Edge  41.16299.15.0 and latest dev 42.17083.1000.0

**Comment by fippo** [comment]
how does pc.iceConnectionState change in edge? Wireshark is usually the go-to tool for this kind of thing

> I noticed that only candidates for one stream are sent

you are offering bundle so that is somewhat expected (in most of the 40+ interpretations of that spec).

**Comment by kekkokk** [comment]
thanks for your help @fippo !
So, doing a wireshark probe that comes to me:

![screen shot 2018-02-08 at 4 14 59 pm](https://user-images.githubusercontent.com/15072723/35980549-3f6c4ce4-0ceb-11e8-98f3-53129aa72faa.png)

It seems that it is using 2 different ufrags, so analyzing the offer created from edge (thru adapter) this is the result:

> v=0
> o=thisisadapterortc 4244563420969587 0 IN IP4 127.0.0.1
> s=-
> t=0 0
> a=group:BUNDLE 3yqjqdeo1b 1ivmeygukt
> a=ice-options:trickle
> m=audio 9 UDP/TLS/RTP/SAVPF 104 102 9 0 8 103 97 13 118 101
> c=IN IP4 0.0.0.0
> a=rtcp:9 IN IP4 0.0.0.0
> a=rtpmap:104 SILK/16000
> a=rtcp-fb:104 x-cinfo
> a=rtcp-fb:104 x-bwe
> a=rtcp-fb:104 x-message app send:dsh recv:dsh
> a=rtpmap:102 opus/48000/2
> a=rtcp-fb:102 x-cinfo
> a=rtcp-fb:102 x-bwe
> a=rtcp-fb:102 x-message app send:dsh recv:dsh
> a=rtpmap:9 G722/8000
> a=rtcp-fb:9 x-cinfo
> a=rtcp-fb:9 x-bwe
> a=rtcp-fb:9 x-message app send:dsh recv:dsh
> a=rtpmap:0 PCMU/8000
> a=rtcp-fb:0 x-cinfo
> a=rtcp-fb:0 x-bwe
> a=rtcp-fb:0 x-message app send:dsh recv:dsh
> a=rtpmap:8 PCMA/8000
> a=rtcp-fb:8 x-cinfo
> a=rtcp-fb:8 x-bwe
> a=rtcp-fb:8 x-message app send:dsh recv:dsh
> a=rtpmap:103 SILK/8000
> a=rtcp-fb:103 x-cinfo
> a=rtcp-fb:103 x-bwe
> a=rtcp-fb:103 x-message app send:dsh recv:dsh
> a=rtpmap:97 RED/8000
> a=rtpmap:13 CN/8000
> a=rtpmap:118 CN/16000
> a=rtpmap:101 telephone-event/8000
> a=fmtp:101 events=0-16
> a=maxptime:100
> a=rtcp-mux
> a=extmap:1 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
> a=extmap:3 http://skype.com/experiments/rtp-hdrext/fast_bandwidth_feedback#version_2
> a=ice-ufrag:nSke
> a=ice-pwd:ax6oUMArDMreBm1qK6J1RaXs
> a=setup:actpass
> a=fingerprint:sha-256 BD:B0:77:E9:B9:8C:C2:EC:40:D2:00:21:C6:38:A9:67:AB:E9:D2:4C:32:8E:F5:2C:80:50:DA:E3:76:E7:09:2B
> a=mid:3yqjqdeo1b
> a=recvonly
> a=ssrc:1001 cname:ukg6gq5puk
> a=rtcp-rsize
> m=video 9 UDP/TLS/RTP/SAVPF 122 107 100 99 96 123
> c=IN IP4 0.0.0.0
> a=rtcp:9 IN IP4 0.0.0.0
> a=rtpmap:122 X-H264UC/90000
> a=fmtp:122 packetization-mode=1;mst-mode=NI-TC
> a=rtcp-fb:122 x-cinfo
> a=rtcp-fb:122 x-bwe
> a=rtcp-fb:122 x-message app send:src,x-pli recv:src,x-pli
> a=rtpmap:107 H264/90000
> a=fmtp:107 profile-level-id=42C02A;packetization-mode=1;level-asymmetry-allowed=1
> a=rtcp-fb:107 x-cinfo
> a=rtcp-fb:107 x-bwe
> a=rtcp-fb:107 nack
> a=rtcp-fb:107 nack pli
> a=rtcp-fb:107 goog-remb
> a=rtpmap:100 VP8/90000
> a=rtcp-fb:100 x-cinfo
> a=rtcp-fb:100 x-bwe
> a=rtcp-fb:100 nack
> a=rtcp-fb:100 nack pli
> a=rtcp-fb:100 goog-remb
> a=rtpmap:99 rtx/90000
> a=fmtp:99 apt=107;rtx-time=3000
> a=rtpmap:96 rtx/90000
> a=fmtp:96 apt=100;rtx-time=3000
> a=rtpmap:123 x-ulpfecuc/90000
> a=rtcp-mux
> a=extmap:1 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
> a=extmap:3 http://skype.com/experiments/rtp-hdrext/fast_bandwidth_feedback#version_2
> a=ice-ufrag:59RO
> a=ice-pwd:UO1L7WImXeWuQahUWz3aMoM3
> a=setup:actpass
> a=fingerprint:sha-256 E9:51:D7:A9:3F:10:AD:02:B2:69:F2:BA:B0:A4:47:B0:C2:DB:89:82:14:68:E9:7B:27:06:C5:54:DE:13:91:45
> a=mid:1ivmeygukt
> a=recvonly
> a=ssrc:3003 cname:ukg6gq5puk
> a=rtcp-rsize

the ice ufrag and pwd for audio and video are different!
So I managed to manually munge the offer and set the second ufrag and pwd equals to the firsts.
This worked fine. both audio and video are present.

But why this is happening? on chrome and Firefox the generated ufrag is identical for both audio/video.

So I did a comparison between plain edge Sdps:

> v=0
> o=- 2766125983088397507 0 IN IP4 127.0.0.1
> s=-
> t=0 0
> a=msid-semantic: WMS 
> a=group:BUNDLE audio video
> m=audio 9 UDP/TLS/RTP/SAVPF 102 9 0 8 97 13 118 101
> c=IN IP4 0.0.0.0
> a=rtpmap:102 opus/48000/2
> a=rtpmap:9 G722/8000
> a=rtpmap:0 PCMU/8000
> a=rtpmap:8 PCMA/8000
> a=rtpmap:97 RED/8000
> a=rtpmap:13 CN/8000
> a=rtpmap:118 CN/16000
> a=rtpmap:101 telephone-event/8000
> a=rtcp:9 IN IP4 0.0.0.0
> a=rtcp-fb:102 x-bwe
> a=rtcp-fb:102 x-cinfo
> a=rtcp-fb:9 x-bwe
> a=rtcp-fb:9 x-cinfo
> a=rtcp-fb:0 x-bwe
> a=rtcp-fb:0 x-cinfo
> a=rtcp-fb:8 x-bwe
> a=rtcp-fb:8 x-cinfo
> a=extmap:1 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
> a=setup:actpass
> a=mid:audio
> a=maxptime:60
> a=recvonly
> a=ice-ufrag:KknK
> a=ice-pwd:lMXGRFNRfbnT4UayOVKw+a/x
> a=fingerprint:sha-256 0B:D5:9D:66:F5:BC:A0:90:E6:B3:F8:BC:6E:C1:D1:AA:46:1E:F5:99:20:64:33:A9:51:55:8C:B4:AF:96:1B:86
> a=rtcp-mux
> a=rtcp-rsize
> m=video 9 UDP/TLS/RTP/SAVPF 99 107 96 100
> c=IN IP4 0.0.0.0
> a=rtpmap:99 rtx/90000
> a=rtpmap:107 H264/90000
> a=rtpmap:96 rtx/90000
> a=rtpmap:100 VP8/90000
> a=fmtp:99 apt=107;rtx-time=3000
> a=fmtp:107 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42c02a
> a=fmtp:96 apt=100;rtx-time=3000
> a=fmtp:100 packetization-mode=1;mst-mode=NI-TC
> a=rtcp:9 IN IP4 0.0.0.0
> a=rtcp-fb:107 x-bwe
> a=rtcp-fb:107 x-cinfo
> a=rtcp-fb:107 nack
> a=rtcp-fb:107 nack pli
> a=rtcp-fb:107 goog-remb
> a=rtcp-fb:100 x-bwe
> a=rtcp-fb:100 x-cinfo
> a=rtcp-fb:100 nack
> a=rtcp-fb:100 nack pli
> a=rtcp-fb:100 goog-remb
> a=extmap:1 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
> a=setup:actpass
> a=mid:video
> a=recvonly
> a=ice-ufrag:KknK
> a=ice-pwd:lMXGRFNRfbnT4UayOVKw+a/x
> a=fingerprint:sha-256 0B:D5:9D:66:F5:BC:A0:90:E6:B3:F8:BC:6E:C1:D1:AA:46:1E:F5:99:20:64:33:A9:51:55:8C:B4:AF:96:1B:86
> a=rtcp-mux
> a=rtcp-rsize

and they are identical!
Is there something that adapter maybe is doing at my ufrags? or I am doing something wrong?

I mean, it's a BUNDLE shouldn't be the same?

**Comment by fippo** [comment]
that should not happen and there a unit test covering [that case](https://github.com/otalk/rtcpeerconnection-shim/blob/master/test/rtcpeerconnection.js#L705-L725)

What is pc.usingBundle here https://github.com/otalk/rtcpeerconnection-shim/blob/master/rtcpeerconnection.js#L1448 ?

**Comment by kekkokk** [comment]
I'm currently using adapter 6.1.1
It's a bit different, where can I find this information?
It's correct to place a console log in line 1328?

![screen shot 2018-02-08 at 5 48 37 pm](https://user-images.githubusercontent.com/15072723/35986037-52f23492-0cf8-11e8-9a87-bd9a48e60ec0.png)

**Comment by fippo** [comment]
https://github.com/webrtc/adapter/blob/gh-pages/adapter-6.1.1.js#L1409

**Comment by kekkokk** [comment]
ok so I figured out how to force the max-bundle policy and the ufrags now are the same and everything seems working.

Notice that I'm doing an offer to receive audio and video to my server, I'm not creating an answer.
And if I don't specify the max-bundle policy it generates a BUNDLED sdp but with ufrag different. 

Could this be a bug?

**Comment by fippo** [comment]
if the offer from Edge contains bundle and the answer from your server contains bundle as well the second ufrag should not be used. The logic for that is around here: https://github.com/webrtc/adapter/blob/gh-pages/adapter-6.1.1.js#L910
