### ISSUE TITLE
Recorded video in chrome not playing in Firefox.

### ISSUE THREAD

**Issue by trevordowdle** [webrtcHacks/adapter#607]
**Browsers and versions affected**
this particular Chrome recording was done in version 3.3.4.

**Description**
WebM video recorded through Chrome not playing in Firefox.

**Steps to reproduce**

1.  Recorded a video in Chrome (getUserMedia - video/webm) uploaded video to amazon s3 storage.
2.  Load the video using firefox using the direct url to the video/webm file.
See:
https://s3-us-west-2.amazonaws.com/boldvue-video-dev/VideoBlob/6ECCgXnZYC9cujaat/6c6caa44f60f56ce027b0ae3.webm

**Expected results**
I would expect firefox to play the the video/webm file generated by chrome.

Load the same url in chrome and it plays:
https://s3-us-west-2.amazonaws.com/boldvue-video-dev/VideoBlob/6ECCgXnZYC9cujaat/6c6caa44f60f56ce027b0ae3.webm

**Actual results**

I get an error.

1.  from the logs:
Media resource https://s3-us-west-2.amazonaws.com/boldvue-video-dev/VideoBlob/6ECCgXnZYC9cujaat/6c6caa44f60f56ce027b0ae3.webm could not be decoded.

2.  In the browser I see the following:
No Video with supported format and MIME type found.
or 
Video format or MIME type is not supported.

**Comment by trevordowdle** [comment]
So I just got some feedback on my chrome recording, I was told the following:

This isn't a valid webm, it has a h264 track.
Per spec, webm is to contain only opus, vorbis, vp8, vp9 (and now av1)
http://www.webmproject.org/docs/container/

Can I get feedback is this strictly a Chrome issue or something that the adapter could potentially address?

**Comment by KaptenJansson** [comment]
Adapter cannot address this, it's an API shim/polyfill. 

Make recordings using the open source codec supported by webm or transcode h264 to VP8 using ffmpeg.

**Comment by trevordowdle** [comment]
Can I get a link to the "the open source codec supported by webm"?

Thank you!

**Comment by mayuraggarwal** [comment]
hello @trevordowdle, have you got the answer, please help me in this issue...I am stucking so much.... thank you

**Comment by trevordowdle** [comment]
@mayuraggarwal, well one solution (far from ideal) but mentioned above is to use ffmpeg to transcode or convert the file to VP8.  So that's a road you may want to go down.
