### ISSUE TITLE
Video behavior not consistent among webm files.

### ISSUE THREAD

**Issue by trevordowdle** [webrtcHacks/adapter#608]
**Browsers and versions affected**
Chrome - webrtc 3.4.3

**Description**
If I record a video in chrome and then load the video into a **<video>** tag there is no buffer or indication of buffering.

If you go to webm.land they have a number of webm videos that show this buffer behavior in chrome.

See the following link in chrome: http://webm.land/w/X0nS/

Notice how the buffering indicator shows up and keeps increasing while the video is being played.  This same behavior can be seen when loading the video externally.

`<video src="http://webm.land/media/X0nS.webm" type="video/webm" autoplay="autoplay" controls="controls"></video>`

Doing the same thing using a webrtc recording in chrome.

`<video src="/chromeRecording.webm" type="video/webm" autoplay="autoplay" controls="controls"></video>`

Doesn't behave the same (no buffer indicator)

**Steps to reproduce**
   Record video in chrome.
   Play video with controls and autoplay attributes in <video> tag

**Expected results**
  Expecting webm files to have some uniform behavior.

**Actual results**
  webm files on webmland behave differently from my recorded webm files.

**Comment by KaptenJansson** [comment]
This is not related to adapter. Please file a bug in crbug.com.
