### ISSUE TITLE
Shim MediaStream.ended attribute until all apps have caught up?

### ISSUE THREAD

**Issue by KaptenJansson** [webrtcHacks/adapter#62]
[Implement MediaStream.active/inactive attribute. (ended is deprecated)](https://code.google.com/p/chromium/issues/detail?id=445084)

**Comment by KaptenJansson** [comment]
@alvestrand @fippo @jan-ivar WDYT?

**Comment by jan-ivar** [comment]
My view is still that adapter is for browsers that aren't caught up, not for apps that aren't caught up. I.e. that it enables the spec on platforms that don't have it, not non-spec on platforms that do. And once all browsers are caught up, in theory, adapter.js would cease to be (I'm ever the optimist).

I tend to consider backwards compatibility the job of the browsers (though others may disagree). For instance, even though Firefox supports element.srcObject, it still tolerates element.mozSrcObject (for a while), and isn't leaning on adapter for this.

FYI Firefox currently supports neither `ended` or `active`, but I don't know of any good way to shim this core functionality.

**Comment by KaptenJansson** [comment]
Closing as per last comment.
