### ISSUE TITLE
OnTrack event is not fired sometimes

### ISSUE THREAD

**Issue by rbenitez** [webrtcHacks/adapter#622]
**Browsers and versions affected**
Chrome: Version 59.0.3071.104 (Official Build) (64-bit)
Adapter.js : Version 4.0.1 from www.webjars.org

**Description**
The ontrack event is not fired sometimes in remote stream, although if I type in the browser: `peerConnection.getRemoteStreams()[0].getVideoTracks()` I can see all video tracks. Notice I have only one stream.

Notice I added :
`pc.ontrack = function(event) { ... }`

**Steps to reproduce**
I add video tracks, sometimes first time fails and sometimes after 10 o 12 times.

**Expected results**
ontrack event works properly always that there is a new track

**Actual results**
Sometimes ontrack event is not fired

Thank you! 
Raul.

**Comment by vardius** [comment]
Same issue here
**Chrome 59.0.3071.115 (Official Build) (64-bit)**

Tested with Adapter.js from npm
**Version 4.2.0**
**Version 4.1.1**
**Version 4.1.0**

Only one side of peer connection gets remote stream.

The side creating offer is able to see other peer's stream but the one creating answer does not get the stream `ontrack` function is not being dispatch on PeerConnection object. Data channels are working.

More infom offer/asnwer sdp here:
https://stackoverflow.com/questions/44814005/why-only-one-side-of-peer-connection-gets-remote-stream

**Comment by fippo** [comment]
https://jsfiddle.net/eLwxtLod/ works here. If you can reproduce this can you check if onaddstream fires?

**Comment by rbenitez** [comment]
@fippo In my case, the problem is when you repeat the operations several times and flowing media between two peerconnections.

**Comment by fippo** [comment]
@rbenitez do you have the sdp for each step? preferably in JSON stringify form which makes it easier to paste into a fiddle/test

**Comment by rbenitez** [comment]
@fippo yes, I will get that sdps during this morning. 

Thanks!

**Comment by vardius** [comment]
In my case the peer.ontrack is dispatched only for one side the one creating offer. The other one does not get the remote stream.

@fippo If you want i can upload not working demo to free heroku server.

**Comment by rbenitez** [comment]
For example @fippo  with this remote SDP onTrack didn't work

v=0
o=- 3709266412 3709266415 IN IP4 0.0.0.0
s=VM62f04a422544a2b55c7200f64c48ac6b
c=IN IP4 0.0.0.0
t=0 0
a=ice-lite
a=msid-semantic: WMS *
a=group:BUNDLE audio video
m=audio 1 UDP/TLS/RTP/SAVPF 111 0
a=rtpmap:111 opus/48000/2
a=rtpmap:0 PCMU/8000
a=fmtp:111 minptime=10;useinbandfec=1
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:1 1 UDP 2013266431 fe80::c1a:80ff:fed5:c8b4 19536 typ host
a=candidate:2 1 UDP 2013266431 XX.XX.XX.XX 19284 typ host
a=candidate:1 2 UDP 2013266430 fe80::c1a:80ff:fed5:c8b4 16108 typ host
a=candidate:2 2 UDP 2013266430 XX.XX.XX.XX 16468 typ host
a=rtcp-mux
a=setup:actpass
a=mid:audio
a=recvonly
a=ice-ufrag:Yoyp
a=ice-pwd:1AbbwSj4irE6sQIOylVZtG
a=fingerprint:sha-256 52:DC:DE:DA:90:F2:DB:CF:46:70:B3:ED:F9:33:88:77:27:6B:A4:53:FF:F9:E9:44:0E:06:5C:AA:A1:FE:26:74
m=video 1 UDP/TLS/RTP/SAVPF 96 100
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=rtpmap:96 VP8/90000
a=rtpmap:100 H264/90000
a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 ccm fir
a=candidate:1 1 UDP 2013266431 fe80::c1a:80ff:fed5:c8b4 19536 typ host
a=candidate:2 1 UDP 2013266431 XX.XX.XX.XX 19284 typ host
a=candidate:1 2 UDP 2013266430 fe80::c1a:80ff:fed5:c8b4 16108 typ host
a=candidate:2 2 UDP 2013266430 XX.XX.XX.XX 16468 typ host
a=rtcp-mux
a=setup:actpass
a=mid:video
a=sendrecv
a=ice-ufrag:Yoyp
a=ice-pwd:1AbbwSj4irE6sQIOylVZtG
a=fingerprint:sha-256 52:DC:DE:DA:90:F2:DB:CF:46:70:B3:ED:F9:33:88:77:27:6B:A4:53:FF:F9:E9:44:0E:06:5C:AA:A1:FE:26:74
a=ssrc:877753122 cname:user1658449303@host-11632368
a=ssrc:877753122 msid:454b0397-37ec-4a22-8f75-66e45c2c7dfb 3664bd8c-d037-40d0-80f0-c03134bbedd6

**Comment by fippo** [comment]
@rbenitez https://jsfiddle.net/4kmmbcr6/ works here. Is that part of a larger sequence which involves a lot of adding and removing track?

**Comment by rbenitez** [comment]
Yes, the steps are the next:
I have two browsers: 
1. Browser A starts only with Audio
2. Browser B stars only with Audio
3 Browser A removes Audio track and Add Video Track
4. Browser B removes Audio tracks and Add Video Track
5 In Browser B the event is not dispatched

**Comment by fippo** [comment]
can you paste all sdps for browser B in the setRemoteDescription calls? I wonder how the underlying native stream object behaves...

**Comment by rbenitez** [comment]
setRemoteDescription when BrowserB starts only with Audio 
v=0
↵o=- 3709269121 3709269121 IN IP4 0.0.0.0
↵s=VM23acaa8d819ff0895e1ce04b4590e75f
↵t=0 0
↵a=ice-lite
↵a=msid-semantic: WMS *
↵a=group:BUNDLE audio video
↵m=audio 10582 UDP/TLS/RTP/SAVPF 111 0
↵c=IN IP4 172.22.13.19
↵a=rtcp:10582 IN IP4 172.22.13.19
↵a=rtpmap:111 opus/48000/2
↵a=rtpmap:0 PCMU/8000
↵a=fmtp:111 minptime=10;useinbandfec=1
↵a=candidate:1 1 UDP 2013266431 fe80::c1a:80ff:fed5:c8b4 13631 typ host
↵a=candidate:2 1 UDP 2013266431 54.242.91.135 10582 typ host
↵a=candidate:1 2 UDP 2013266430 fe80::c1a:80ff:fed5:c8b4 18210 typ host
↵a=candidate:2 2 UDP 2013266430 54.242.91.135 11753 typ host
↵a=rtcp-mux
↵a=setup:active
↵a=mid:audio
↵a=recvonly
↵a=ice-ufrag:8cYc
↵a=ice-pwd:1Rbd8QJBvyMHzNrZMPTx0L
↵a=fingerprint:sha-256 FA:18:B6:8C:41:2C:8A:E0:4B:40:F0:D4:32:9F:90:79:1B:7D:7F:A1:22:D3:F2:DB:7F:AC:FB:29:B1:41:AC:50
↵m=video 10582 UDP/TLS/RTP/SAVPF 96 100
↵c=IN IP4 172.22.13.19
↵a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
↵a=rtcp:10582 IN IP4 172.22.13.19
↵a=rtpmap:96 VP8/90000
↵a=rtpmap:100 H264/90000
↵a=rtcp-fb:96 ccm fir
↵a=rtcp-fb:96 nack
↵a=rtcp-fb:96 nack pli
↵a=rtcp-fb:96 goog-remb
↵a=rtcp-fb:100 ccm fir
↵a=rtcp-fb:100 nack
↵a=rtcp-fb:100 nack pli
↵a=rtcp-fb:100 goog-remb
↵a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
↵a=candidate:1 1 UDP 2013266431 fe80::c1a:80ff:fed5:c8b4 13631 typ host
↵a=candidate:2 1 UDP 2013266431 54.242.91.135 10582 typ host
↵a=candidate:1 2 UDP 2013266430 fe80::c1a:80ff:fed5:c8b4 18210 typ host
↵a=candidate:2 2 UDP 2013266430 54.242.91.135 11753 typ host
↵a=rtcp-mux
↵a=setup:active
↵a=mid:video
↵a=inactive
↵a=ice-ufrag:8cYc
↵a=ice-pwd:1Rbd8QJBvyMHzNrZMPTx0L
↵a=fingerprint:sha-256 FA:18:B6:8C:41:2C:8A:E0:4B:40:F0:D4:32:9F:90:79:1B:7D:7F:A1:22:D3:F2:DB:7F:AC:FB:29:B1:41:AC:50
↵"


setRemoteDescription after Browser A removes Add Audio track and Add Video Track

v=0
↵o=- 3709269121 3709269124 IN IP4 0.0.0.0
↵s=VM23acaa8d819ff0895e1ce04b4590e75f
↵c=IN IP4 0.0.0.0
↵t=0 0
↵a=ice-lite
↵a=msid-semantic: WMS *
↵a=group:BUNDLE audio video
↵m=audio 1 UDP/TLS/RTP/SAVPF 111 0
↵a=rtcp:9 IN IP4 0.0.0.0
↵a=rtpmap:111 opus/48000/2
↵a=rtpmap:0 PCMU/8000
↵a=fmtp:111 minptime=10;useinbandfec=1
↵a=candidate:1 1 UDP 2013266431 fe80::c1a:80ff:fed5:c8b4 13631 typ host
↵a=candidate:2 1 UDP 2013266431 54.242.91.135 10582 typ host
↵a=candidate:1 2 UDP 2013266430 fe80::c1a:80ff:fed5:c8b4 18210 typ host
↵a=candidate:2 2 UDP 2013266430 54.242.91.135 11753 typ host
↵a=rtcp-mux
↵a=setup:active
↵a=mid:audio
↵a=inactive
↵a=ice-ufrag:8cYc
↵a=ice-pwd:1Rbd8QJBvyMHzNrZMPTx0L
↵a=fingerprint:sha-256 FA:18:B6:8C:41:2C:8A:E0:4B:40:F0:D4:32:9F:90:79:1B:7D:7F:A1:22:D3:F2:DB:7F:AC:FB:29:B1:41:AC:50
↵m=video 1 UDP/TLS/RTP/SAVPF 96 100
↵a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
↵a=rtcp:9 IN IP4 0.0.0.0
↵a=rtpmap:96 VP8/90000
↵a=rtpmap:100 H264/90000
↵a=rtcp-fb:96 ccm fir
↵a=rtcp-fb:96 nack
↵a=rtcp-fb:96 nack pli
↵a=rtcp-fb:96 goog-remb
↵a=rtcp-fb:100 ccm fir
↵a=rtcp-fb:100 nack
↵a=rtcp-fb:100 nack pli
↵a=rtcp-fb:100 goog-remb
↵a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
↵a=candidate:1 1 UDP 2013266431 fe80::c1a:80ff:fed5:c8b4 13631 typ host
↵a=candidate:2 1 UDP 2013266431 54.242.91.135 10582 typ host
↵a=candidate:1 2 UDP 2013266430 fe80::c1a:80ff:fed5:c8b4 18210 typ host
↵a=candidate:2 2 UDP 2013266430 54.242.91.135 11753 typ host
↵a=rtcp-mux
↵a=setup:active
↵a=mid:video
↵a=sendrecv
↵a=ice-ufrag:8cYc
↵a=ice-pwd:1Rbd8QJBvyMHzNrZMPTx0L
↵a=fingerprint:sha-256 FA:18:B6:8C:41:2C:8A:E0:4B:40:F0:D4:32:9F:90:79:1B:7D:7F:A1:22:D3:F2:DB:7F:AC:FB:29:B1:41:AC:50
↵a=ssrc:2088122199 cname:user1469704444@host-d33a8060
↵a=ssrc:2088122199 msid:139b4823-02d3-4e80-8ed7-d8a18799219c 85d78b87-1682-415d-9685-04a1f9bfddca
↵"

getRemoteStreams() -> getVideoTrack() ->
MediaStreamTrack
enabled : true
id: "85d78b87-1682-415d-9685-04a1f9bfddca"
kind:"video"
label:"85d78b87-1682-415d-9685-04a1f9bfddca"
muted:false
readyState:"live"


The video track is present in the peerConnection but the event onAddTrack wasn't dispatched

**Comment by fippo** [comment]
still can't reproduce: https://jsfiddle.net/qrb4yLab/ :-(
Note that the event name is 'track' or ontrack, not onAddTrack

**Comment by rbenitez** [comment]
Yes, I use peerConnection.ontrack = function ....

**Comment by rbenitez** [comment]
The problem is that it does not always happens ... I'll try to use your example to simulate

**Comment by dnish** [comment]
I'm having the same issue, especially when I try to establish a video chat between Chrome Desktop and Chrome Mobile. Most of the time, only one side receives a remote stream. Chrome Desktop <-> Chrome Desktop is working fine (both on local machine).

I don't know if this helps, but I need to add a timeout to make it work between mobile and desktop the whole time:

        RTCConnection.requestMediaAccess(() => {
            setTimeout(() => {
                RTCConnection.acceptParticipationRequest(this.participantId(), this.userPreferences());
            },5000);

        });

Without that timeout, it's just working sometimes on both sides. The function is called on the receivers side. We're using RTCMultiConnection.

**Comment by blkwtkns** [comment]
I have been experiencing something similar, I believe, but instead of the ontrack method not firing, it's delayed. This only happens to me for mobile chrome client to mobile chrome client, and the initiator of the communication is the one who is subject to the delayed ontrack method. In my logic, this has the effect of rendering no video for the initiator, mostly because I have the remote stream being set to another object when ontrack occurs, and then another method accesses the new pointer to the stream at the end of the whole process (it's a server triggered method, it's supposed to be the last thing that occurs in the process so that end of process UX and timers can begin). Anyways, this very well may be a specific feature to my logic, but I just wanted to post it up in case it may be helpful at all.

**Comment by rbenitez** [comment]
Hello? Do you have any information about this bug? Now I have the problem after adding one track in  other point. I mean, we have two browsers, after starting if I try to add one track in some of both browser, the onTrack event is not fired, but I can see information in chrome://webrtc.

The last SDP is the next:

>  v=0
o=- 3715922726 3715922728 IN IP4 0.0.0.0
s=VM0bc1e3f30f6c4a7718f1d06d1643af73
c=IN IP4 0.0.0.0
t=0 0
a=ice-lite
a=msid-semantic: WMS *
a=group:BUNDLE audio video
m=audio 1 UDP/TLS/RTP/SAVPF 111 0
c=IN IP4 0.0.0.0
a=rtpmap:111 opus/48000/2
a=rtpmap:0 PCMU/8000
a=fmtp:111 minptime=10;useinbandfec=1
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:1 1 UDP 2013266431 fe80::84e:80ff:fe8c:378 11586 typ host
a=candidate:2 1 UDP 2013266431 34.224.91.233 18911 typ host
a=candidate:1 2 UDP 2013266430 fe80::84e:80ff:fe8c:378 14226 typ host
a=candidate:2 2 UDP 2013266430 34.224.91.233 16311 typ host
a=rtcp-mux
a=setup:actpass
a=mid:audio
a=sendrecv
a=ice-ufrag:W+kF
a=ice-pwd:p8BxG+lyjhxvsrJVcKCh5l
a=fingerprint:sha-256 BE:03:FC:06:04:F0:AE:D3:FA:85:4E:30:00:D8:CA:93:78:EA:38:4A:91:0C:6E:EB:B1:20:E1:A7:71:55:EC:A4
a=ssrc:667425079 cname:user2545074420@host-e00747f7
a=ssrc:667425079 msid:a4402893-9430-4732-a6f6-53044403c3a5 4928ca23-9123-4405-a47b-4c75b6c1802f
m=video 1 UDP/TLS/RTP/SAVPF 96 100
c=IN IP4 0.0.0.0
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=rtpmap:96 VP8/90000
a=rtpmap:100 H264/90000
a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 ccm fir
a=candidate:1 1 UDP 2013266431 fe80::84e:80ff:fe8c:378 11586 typ host
a=candidate:2 1 UDP 2013266431 34.224.91.233 18911 typ host
a=candidate:1 2 UDP 2013266430 fe80::84e:80ff:fe8c:378 14226 typ host
a=candidate:2 2 UDP 2013266430 34.224.91.233 16311 typ host
a=rtcp-mux
a=setup:actpass
a=mid:video
a=sendrecv
a=ice-ufrag:W+kF
a=ice-pwd:p8BxG+lyjhxvsrJVcKCh5l
a=fingerprint:sha-256 BE:03:FC:06:04:F0:AE:D3:FA:85:4E:30:00:D8:CA:93:78:EA:38:4A:91:0C:6E:EB:B1:20:E1:A7:71:55:EC:A4
a=ssrc:2069265179 cname:user2545074420@host-e00747f7
a=ssrc:2069265179 msid:a4402893-9430-4732-a6f6-53044403c3a5 11cd951a-1bf9-454f-b820-783754e06e93
a=ssrc:3222426762 cname:user2545074420@host-e00747f7
a=ssrc:3222426762 msid:a4402893-9430-4732-a6f6-53044403c3a5 1a07877e-7ff2-4454-832b-3143194c06d4


Thanks!

**Comment by rbenitez** [comment]
@fippo any idea? Thanks!

**Comment by fippo** [comment]
I can't reproduce.

**Comment by rbenitez** [comment]
I'm going to debug adapter.js in my case, because I'm not sure and maybe the problem is in the addTrack event of the MediaStream, because although the event isn't fired, the track is present in webrtc-internals.

Regards

**Comment by fippo** [comment]
the only thing I can think of is #698 -- do you remove the stream? see the other report for full details and link to the chrome CL

**Comment by rbenitez** [comment]
Hi, after removing all tracks and stream in Browser A, and start adding tracks again in Browser A, Browser B receives ontrack event, but only once.

I'm implementing my own ontrack, when setRemoteDescription is called.

Looks like event "addTrack" is not fired in adapter.js

**Comment by danmux** [comment]
same issue here

**Comment by KaptenJansson** [comment]
Is this still an issue?

**Comment by rbenitez** [comment]
Hi, In my case I implemented my own ontrack, so... I'm not sure if the problem continue. @kapetan?? Do you have still the problem?

**Comment by nitin-** [comment]
participants.on('track',....)     is not getting called for current particiant.

**Comment by flamurhbreznica** [comment]
I have VideoCall System developed through Ionic Cordova with PeerJS, it works properly on Android.
Now that I deployed to iOS from cordova, whenever I make second call, it always set an error: The PluginMediaStream with this id "any id" already exists, and cannot join to calls anymore, also the events from peerjs does not trigger

for example:

peer.on('stream') does not trigger at all, I used this plugin to handle the MediaStreams, but for some reasons, after the first video call it says MediaStream already exists,

How i can I trigger some events if I get a call from peer, onstream, onremove,

I tried to remove streams, tracks, and other stuff after ending video call, but it did not work.

**Comment by icguanyu** [comment]
I have same issue while:  **Desktop** (Chrome) (get answer)<--> **Mobile** or Safari (get offer) 
At first I struggled with **why the ontrack was not triggered** but later found two possible problems...

After the fix, the problem seems to be solved.

**1. I didn't use `new RTCSessionDescription(description)`**
replace
```
myPeerConnection.setRemoteDescription(new RTCSessionDescription(description)).then(() => ...);
```
with
```
myPeerConnection.setRemoteDescription(description).then(() => ...);
```

**2. Mind the async problem when the socket receive signal to `setRemoteDescription/setLocalDescription`.**

The following code for reference only

before
```
// incorrect vesrion
receiveSignal(signal){
  if (signal.sdp) {
    pc.setRemoteDescription(new RTCSessionDescription(signal.sdp), () => {
        const type = pc.remoteDescription.type;
        if (type == "offer") {
          pc.createAnswer().then((answer) => {
            pc.setLocalDescription(answer);
            sendSignalToAgent(answer)
          });
        } else if (type == "answer") {
          // get answer...
        }
     });
  } else if (signal.candidate) {
    pc.addIceCandidate(new RTCIceCandidate(signal.candidate));
  }
}
```
after
```
async receiveSignal(signal){
  if (signal.sdp) {
    await pc.setRemoteDescription(signal.sdp);
    const type = pc.remoteDescription.type;
    if (type == "offer") {
      pc.createAnswer().then(async (answer) => {
        await pc.setLocalDescription(answer);
        sendSignalToAgent(answer)
      });
    } else if (type == "answer") {
       // get answer...
    }
 } else if (signal.candidate) {
    pc.addIceCandidate(new RTCIceCandidate(signal.candidate));
 }
}
```
**The code is for reference only. The point I want to express is "may be an asynchronous problem". I hope I can provide a little help.**
