### ISSUE TITLE
Chrome: MSID does not match MediaStream passed to addStream or addTrack

### ISSUE THREAD

**Issue by markandrus** [webrtcHacks/adapter#634]
**Browsers and versions affected**

Google Chrome 59, 60

**Description**

adapter.js appears to be changing MSID values when `addStream` or `addTrack` is used.

**Steps to reproduce**

* [JSFiddle using `addStream` without adapter.js](https://jsfiddle.net/7sh3oc28/) (Chrome, Firefox)
* [JSFiddle using `addStream` with adapter.js (latest)](https://jsfiddle.net/cs22nvjL/) (Chrome, Firefox)
* [JSFiddle using `addTrack` without adapter.js](https://jsfiddle.net/3e2t3wzv/1/) (Firefox)
* [JSFiddle using `addTrack` with adapter.js (latest)](https://jsfiddle.net/1nbr1u7m/1/) (Chrome, Firefox)

**Expected results**

I get these expected results when adapter.js is not used in both Chrome and Firefox.

```
stream.id $STREAM_ID
track.id $TRACK_ID
$OFFER
msid $STREAM_ID $TRACK_ID
stream.id === msid[0] true
track.id === msid[1] true
```

**Actual results**

I get these results when adapter.js is used in Chrome.

```
stream.id $STREAM_ID
track.id $TRACK_ID
$OFFER
msid $RANDOM_ID $TRACK_ID
stream.id === msid[0] false
track.id === msid[1] true
```

**Comment by markandrus** [comment]
I think the `_streams`/`_reverseStreams` code introduced in https://github.com/webrtc/adapter/pull/611 may be the reason? One option might be to update the SDP attributes to match the mapping. EDIT: A bit more research, and it looks like https://github.com/webrtc/adapter/pull/503 introduced this?

**Comment by markandrus** [comment]
The MSID will also change between Steps 2 and 5 if you do the following:

1. `addStream(stream)`
2. negotiate
3. `removeStream(stream)`
4. `addStream(stream)`
5. negotiate

In Chrome, this causes the original MediaStreamTrack(s) to stop, and a new MediaStreamTrack event will be raised. (This scenario is actually how I noticed the issue.)

**Comment by fippo** [comment]
yeah, addTrack is not shim-able without that. Can you give https://github.com/fippo/adapter/tree/munge-sdp a try? I'm somewhat hesitant to merge since mangling SDP means crossing the rubicon and it will still be incomplete unless the mangling happens in getStats as well.

**Comment by markandrus** [comment]
Thanks, @fippo. At a glance the change looks correct, and testing looks good. I understand the hesitation, but I think this is an important property to maintain. I hope this can be shipped even before a `getStats` update. Currently, users of adapter.js will not be able to correlate MediaStreamTracks by MediaStream ID, as described [here](https://blog.mozilla.org/webrtc/the-evolution-of-webrtc/).
