### ISSUE TITLE
Cannot send stream object URL to another page via PostMessage

### ISSUE THREAD

**Issue by mzji** [webrtcHacks/adapter#636]
**Browsers and versions affected**
Firefox 54.0.1 Win10-x64 (maybe affect all browsers)

**Description**
The shim of `URL.createObjectURL` in webRTC adapter will return a string instead of a real object URL, which doesn't work in other pages

**Steps to reproduce**
```
\\ In the first page
window.stream = ....;
\\
\\ After something is done...
\\
window.large_window = window.open("/large.html", window.location.origin);
window.postMessage(URL.createObjectURL(window.stream), window.location.origin);

\\ In the 'large' page
window.addEventListener("message", streamHandler, false);

function streamHandler(event) {
    if (event.origin !== window.location.origin) {
        return false;
    }
    docReady(() => {
        let remote = document.getElementById('remote');
        remote.src = event.data;
    });
    window.removeEventListener("message", streamHandler);
}
```

**Expected results**
The video stream will be available and played in the 'remote' video element in page 'large'

**Actual results**
The 'remote' video element is blank, and the `src` attribute is set to 'polyblob:1', which is a string

**Comment by KaptenJansson** [comment]
I believe you should get a warning that this is deprecated and should use srcObject = stream instead? Have you tried to just pass the stream object (not sure if that is possible via postMessage)?

**Comment by mzji** [comment]
Sending stream object via postMessage() is not possible, see: https://stackoverflow.com/questions/30731277/webkitmediastream-object-type-lost-while-using-sendmessage-in-chrome-extension

**Comment by fippo** [comment]
@jan-ivar wdyt?

**Comment by KaptenJansson** [comment]
Ping

**Comment by jan-ivar** [comment]
If there's a legitimate use-case here (like resuming a conversation in a popup), then it might mean we were too rash in retiring `URL.createObjectURL`.

That said, there may be security implications and other problems with using the stream object outside of its context like this. Like, where does the user go to revoke permission? @martinthomson WDYT?

I'm a bit hoping there are problems here, since it feels wrong, but I don't have a good workaround either, at least with Firefox's permission model.

**Comment by martinthomson** [comment]
We had a long discussion about making MediaStream(Track) transferable at one point.  Whatever the conclusion to that discussion is now, we should consider to apply here.  At the time it was considered both difficult to implement transference and also not entirely necessary.  Transferring a MediaStreamTrack and transfering a URL have the same effect.

Reviving `URL.createObjectURL()` probably isn't the right answer, or even the right question.  The question is whether the use case is valid and how we might support that use case.  Keep in mind that popups and iframes can run in different processes, so the implementation of a feature like this could be challenging.

**Comment by foolip** [comment]
There's an [Intent to Deprecate and Remove : URL.createObjectURL with MediaStream](https://groups.google.com/a/chromium.org/d/msg/blink-dev/tWzutytXsqc/lGaWCFdHAgAJ) on blink-dev by @Orphis now.

@mzji, were you trying to do this on a real web site for real users, or just experimenting a bit? This is a use case for which there won't be a solution if `URL.createObjectURL()` is removed, and if we know it's already being done on some sites, that's valuable information.

**Comment by Orphis** [comment]
@foolip @mzji Even worse, Safari removed URL.createObjectURL() already for MediaStreams.

**Comment by jan-ivar** [comment]
They probably never added it?

**Comment by youennf** [comment]
There used to be code in WebKit supporting URL.createObjectURL() for MediaStreams.
It is now removed and I don't think it either shipped in Safari.

**Comment by foolip** [comment]
Aha, actually reading the original code, it looks like this was really about a same-origin case, notice the "/large.html" URL and `window.location.origin` as the second argument for postMessage...

So, in this case it should be possible to just reach into the other window and hand over the MediaStream object.

**Comment by mzji** [comment]
We uses `URL.createObjectURL()` in our production code to split video window for our remote conference system. Since passing stream between windows of the same-origin can be achieved by other more elegant solutions, I'm fine to close this issue.

@foolip Yes, the MediaStream are always passed between pages within one site in our system.

**Comment by Orphis** [comment]
I've tried passing streams directly between same-origin windows and I confirm it worked just fine.
It is certainly more elegant than using `URL.createObjectURL`. Let's close this for now.

**Comment by Ajeey** [comment]
@Orphis Can you tell me how did you succeed to pass streams between same origin windows?

**Comment by mzji** [comment]
@Ajeey Get the object of another same origin window and manipulate the DOM directly:
```
other_window.document.getElementById('videoElement').srcObject = SOME_STREAM;
```

**Comment by amiregelz** [comment]
Thanks @mzji  @Orphis 
I was struggling to understand why it won't work for me - and the reason was that I needed to add the `muted` attribute to the popup's video element in order to make it auto play.
Here's the snippet: [https://codepen.io/amiregelz/pen/OJRvoPp](https://codepen.io/amiregelz/pen/OJRvoPp?editors=1010)

**Comment by mzji** [comment]
> 
> 
> Thanks @mzji @Orphis
> I was struggling to understand why it won't work for me - and the reason was that I needed to add the `muted` attribute to the popup's video element in order to make it auto play.
> Here's the snippet: [https://codepen.io/amiregelz/pen/OJRvoPp](https://codepen.io/amiregelz/pen/OJRvoPp?editors=1010)

Well your question doesn't really have an relationship with this topic (or issue?), however I think I've found something maybe useful for you: https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide
