### ISSUE TITLE
IE and Safari(<11) support

### ISSUE THREAD

**Issue by Cheedoong** [webrtcHacks/adapter#639]
Temasys is a great plugin that brings support for WebRTC to desktop versions of IE and Safari(<11):
https://confluence.temasys.com.sg/display/TWPP

I suggest merging their modifications of Adapter.js to this official one. 

Ref:
https://confluence.temasys.com.sg/display/TWPP/How+to+integrate+the+Temasys+WebRTC+Plugin+into+your+website
https://github.com/Temasys/AdapterJS

Declaration: I have no conflict of interest in Temasys or any party related to it.

**Comment by KaptenJansson** [comment]
For now we will not be merging their modifications, simply there is no time and I do not seen the need at this moment.
