### ISSUE TITLE
Chrome: receiver.track can be null, causing issue with "track" event shim

### ISSUE THREAD

**Issue by markandrus** [webrtcHacks/adapter#640]
**Browsers and versions affected**

Chrome Canary 62

**Description**

In Chrome, RTCRtpReciever's `track` can be `null`. This causes an error in the "track" event shim.

1. Offer with `offerToReceiveAudio: true`
2. Answer with `a=msid:stream track1`
3. Offer with `offerToReceiveAudio: true`
4. Answer, replacing `a=msid:stream track1` with `a=msid:stream track2`

**Steps to reproduce**

See [JSFiddle](https://jsfiddle.net/kbg8149n/)

**Expected results**

Two "track" events for `track1` and `track2` (`track1` should end)

**Actual results**

```
adapter-latest.js:827 Uncaught TypeError: Cannot read property 'id' of null
    at https://webrtc.github.io/adapter/adapter-latest.js:827:34
    at Array.find (native)
    at MediaStream.<anonymous> (https://webrtc.github.io/adapter/adapter-latest.js:826:46)
```

**Comment by fippo** [comment]
@henbos looks like pc.getReceivers() has a single element whose track is null. Can you take a look?

**Comment by fippo** [comment]
a variant: https://jsfiddle.net/sxy2khzo/ -- pc.getReceivers() is empty in the .then after the second remoteDescription. This does not look good.

**Comment by fippo** [comment]
https://jsfiddle.net/sxy2khzo/2/ -- and e.receiver is undefined in the first ontrack. That looks like a timing issue.

**Comment by fippo** [comment]
also an issue in 61.0.3163.13

**Comment by fippo** [comment]
filed https://bugs.chromium.org/p/chromium/issues/detail?id=751785
