### ISSUE TITLE
Screen sharing banner isn't removed in Chrome

### ISSUE THREAD

**Issue by benbro** [webrtcHacks/adapter#643]
**Browsers and versions affected**
Chrome 60.0.3112.90
adapter 4.2.1

**Description**
When stopping a screen sharing track, the track is removed locally and from the remote peer but the screen sharing extension still think the track/stream is alive and showing the banner on the bottom:

> X is sharing a window with example.com. Stop sharing / Hide

**Steps to reproduce**
1. Share your screen.
2. Stop the local track and remove the sender from the peer connection:
```javascript
pc.getSenders().forEach((sender) => {
  sender.track.stop;
  pc.removeTrack(sender);
});
```

**Expected results**
The track should end and the screen sharing banner should be removed.

**Actual results**
The screen sharing banner is still visible after stopping the track.

This old way with using streams does work but is deprecated so we shouldn't use it:
```javascript
pc.removeStream(localStream);
localStream.getTracks().forEach(function (track) {
  track.stop();
});
```

If there is other way to stop the track and remove it from the peer connection please share. I'm struggling with this basic operation for years.

**Comment by fippo** [comment]
can't reproduce. There is a typo: sender.track.stop which should be sender.track.stop() -- otherwise you will just remove the track without stopping it locally

**Comment by benbro** [comment]
You are right.
Sorry for the noise.
