### ISSUE TITLE
InvalidAccessError for new RTCIceGatherer(self.iceOptions) in Edge

### ISSUE THREAD

**Issue by icysapphire** [webrtcHacks/adapter#645]
**Browsers and versions affected**
Edge 40.15063

**Description**
Problem occurs at the line
`var iceGatherer = new window.RTCIceGatherer(self.iceOptions);`
with self.iceOptions as
`"{"gatherPolicy":"all","iceServers":[{"urls":"stun:global.stun.twilio.com:3478?transport=udp"},{"username":"692f7632e086fc9cbff8213e4aa0b84620dxxxxxxxxxxxxxxxxx","credential":"Xnl7qOnIJHs0oHzezgo21T6B8eSrZ22xxxxxxxx","urls":"turn:global.turn.twilio.com:3478?transport=udp"}]}"`. This object identifies valid stun/turn server (it just works in other browsers). The issue probably has a lot in common with #446 opened by @santanu-brahma and #451 opened by @kapetan , but in this case servers are fully qualified and aren't multiple. The issue still happens with stun-only iceOptions or turn-only iceOptions.

**Steps to reproduce**
Use new RTCPeerConnection on Microsoft Edge.

**Expected results**
Success or failure with exact debug information.

**Actual results**
Getting console error on edge as 'InvalidAccessError'.

**Comment by fippo** [comment]
see https://github.com/webrtc/adapter/issues/446#issuecomment-325003550

**Comment by KaptenJansson** [comment]
@icysapphire can you confirm that this now works for you based on @fippo's comment?

**Comment by icysapphire** [comment]
Confirmed, thanks @fippo.

Il 11/ott/2017 10:39, "Christoffer Jansson" <notifications@github.com> ha
scritto:
