### ISSUE TITLE
Shim RTCPeerConnection current and pending descriptions

### ISSUE THREAD

**Issue by kherock** [webrtcHacks/adapter#648]
**Browsers and versions affected**
Firefox (55 and below)
Edge (latest)
Chrome (not sure, it has had them implemented for some time)

**Description**
https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Connectivity#Pending_and_current_descriptions

The following properties are missing in some browsers:
`RTCPeerConnection.currentLocalDescription`  
`RTCPeerConnection.currentRemoteDescription`

`RTCPeerConnection.pendingLocalDescription`  
`RTCPeerConnection.pendingRemoteDescription`

**Expected results**
I should have a way of accessing the most recently set (pending) local/remote descriptions. The spec says that `RTCPeerConnection.localDescription` first prefers the description actively being used (the current description) and falls back to the pending description.

**Actual results**
Apps relying on these properties won't work since they are always `undefined`.

**Comment by KaptenJansson** [comment]
Pull requests are welcome, the adapter projects need more contributors!

**Comment by KaptenJansson** [comment]
Closing due to age and lack of resources, but as my last comment stated, PR's are welcome.
