### ISSUE TITLE
Implement RtpTransceivers, is planned?

### ISSUE THREAD

**Issue by uasan** [webrtcHacks/adapter#649]
What’s been added

```JS
pc.addTransceiver('video', {send: true, receive: true});
```

Media before signalling example
```JS
var audio = pc.addTransceiver('audio');
var video = pc.addTransceiver('video');

videoTag.srcObject = new MediaStream(audio.track, video.track);

// We are ready to receive media even before an answer comes back
pc.createOffer();
```

https://www.w3.org/2011/04/webrtc/wiki/images/archive/d/de/20151029000646!RtpTransceivers_at_TPAC_2015.pdf

Safari 11 - this supported.

Thanks.

**Comment by KaptenJansson** [comment]
Are you asking if this is planned to be supported in Adapter or Safari?

**Comment by uasan** [comment]
> Are you asking if this is planned to be supported in Adapter or Safari?

Yes.

**Comment by fippo** [comment]
Firefox is shipping transceivers in FF59. In the Edge shim this is work in progress.
I don't think this is possible to shim in Chrome currently so no plans in that direction.
