### ISSUE TITLE
Bump package version to 1.3 and publish to npm

### ISSUE THREAD

**Issue by xdumaine** [webrtcHacks/adapter#65]
Would love to see an npm update with the latest fixes from @fippo @KaptenJansson

**Comment by byronclark** [comment]
Same here for the RequireJS fix.

**Comment by KaptenJansson** [comment]
@alvestrand Could you do this?

**Comment by KaptenJansson** [comment]
Currently OOO but can do it later today if you cannot.

**Comment by alvestrand** [comment]
0.1.4 of webrtc-adapter-test published as npm.
