### ISSUE TITLE
Safari cannot receive webrtc Peer Connection event "removeStream"

### ISSUE THREAD

**Issue by betimer** [webrtcHacks/adapter#650]
**Browsers and versions affected**
Safari 11

**Steps to reproduce**
The remote PC calls `pc.removeStream`
Safari only receive 'signallingstatechange' event but not `removeStream`

**Expected results**
Safari should also receive event 'removeStream' just as chrome does

**Actual results**
No event `removeStream`

**Comment by youennf** [comment]
Safari does not support the removeStream event.
WebRTC stream-based APIs are in the process of being deprecated.
