### ISSUE TITLE
Need publishing procedure for NPM packages

### ISSUE THREAD

**Issue by alvestrand** [webrtcHacks/adapter#66]
Discovered today "the hard way" that "npm publish" grabs everything in the homedir by default and includes it as part of the package, whether it's junk or not. This needs to not happen - one can use "files" in package.json and/or an ".npmignore" file, or one can use a procedure / script that does a clean checkout before the "npm publish".

**Comment by alvestrand** [comment]
Note - we already have an .npmignore file that eliminates node_modules and *~

**Comment by KaptenJansson** [comment]
We could use grunt build for this? Like I added for testrtc in https://github.com/webrtc/testrtc/pull/96.

**Comment by KaptenJansson** [comment]
I've updated .gitignore which is used if .npmignore does not exists which should suffice, at least it looks fine the last few pushed I've done. Closing this.
