### ISSUE TITLE
pc.setLocalDescription after createOffer not add candidates on Safari Technology preview 38

### ISSUE THREAD

**Issue by mizoRC** [webrtcHacks/adapter#660]
**Browsers and versions affected**
Safari Technology Preview

**Description**
Hi! I created an application using kurento, that uses this library to connect browsers clients with kurento java server. I'm not shure if you can help me because kurento is independent of this library, but I would appreciate it very much.

Trying to connect a participant with a room, when generate an offer (with pc.createOffer()) this previous offer hasn't candidates in sdp. Then when I execute pc.setLocalDescription() off this first offer, should return an offer with the candidates in sdp. Instead of this, the sdp don't have candidates.

Finally, when execute pc.setRemoteDescription() of this second offer, an error is catched. The error is:
![webrtc-adapter-error](https://user-images.githubusercontent.com/17248343/29922391-b3e33f70-8e55-11e7-8c06-58fe4e7aa26b.png)

**Steps to reproduce**
setLocalDescription with Safari Technology preview and show if the response generates an offer with candidates in sdp.

**Expected results**
Generated offer with candidates lines in SDP
[chrome_sdp.txt](https://github.com/webrtc/adapter/files/1266952/chrome_sdp.txt)

**Actual results**
Offer without candidates in SDP.
[safari_sdp.txt](https://github.com/webrtc/adapter/files/1266954/safari_sdp.txt)

**Comment by iclems** [comment]
Also, per this thread https://bugs.webkit.org/show_bug.cgi?id=176157#c1 Safari will not support createOffer with offerToReceiveAudio: 1

**Comment by fippo** [comment]
the safari offer seems to include the necessary mlines though. Do you get onicecandidate with a null candidate? Do you have getUserMedia permissions?

cc @youennf

**Comment by mizoRC** [comment]
Yes, I have getUserMediaPermissions. 
I get this candidates:

```
Request [ICE_CANDIDATE] endpoint=Sala candidate=candidate:1106113138 1 udp 2113937151 192.168.1.169 54753 typ host generation 0 ufrag hTzH network-cost 50 sdpMLineIdx=0 sdpMid=audio (bifb21vefnm1sgavadpj0b0ftr)

Request [ICE_CANDIDATE] endpoint=Sala candidate=candidate:1106113138 1 udp 2113937151 192.168.1.169 54886 typ host generation 0 ufrag hTzH network-cost 50 sdpMLineIdx=1 sdpMid=video (bifb21vefnm1sgavadpj0b0ftr)
```

**Comment by KaptenJansson** [comment]
Does https://github.com/webrtc/adapter/commit/ee197f1b07ae502f48026d832dd0cd952846a78b solve your issue (available in the latest 5.0.5)?

**Comment by iclems** [comment]
Looks like there's still never onicecandidate with a null candidate

**Comment by KaptenJansson** [comment]
@youennf do you have any idea on how to proceed with this?
