### ISSUE TITLE
Safari will not support createOffer with (offerToReceiveAudio: 1)

### ISSUE THREAD

**Issue by iclems** [webrtcHacks/adapter#661]
**Browsers and versions affected**
Safari ≥ TP 38

**Description**
Per this thread https://bugs.webkit.org/show_bug.cgi?id=176157#c1 - Safari will not support createOffer with (offerToReceiveAudio: 1). Existing apps do use this successfully with Chrome today though.

**Steps to reproduce**
Following test not working in Safari TP: https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

**Expected results**
Ice gathering completes successfully 

**Actual results**
Ice gathering never completes

**Comment by tgabi333** [comment]
here is a snipplet to fix this until its fixed in adapter.js

```
function createOffer(offer) {
 if (compatibility.isSafari && compatibility.major >= 11) {
      if (offer.offerToReceiveAudio) {
        this.pc.addTransceiver('audio')
      }
      if (offer.offerToReceiveVideo) {
        this.pc.addTransceiver('video')
      }
    }

    return this.pc.createOffer(offer)
}
```

**Comment by fippo** [comment]
@tgabi333 I have a [branch](https://github.com/fippo/adapter/tree/offerToReceive) with something similar but ran into https://bugs.webkit.org/show_bug.cgi?id=176665 which makes it... somewhat tricky to shim the right behaviour.

**Comment by SebastianSchenk** [comment]
I just added the snippet from @tgabi333. Before that, I only got a minimal SDP like described here (https://bugs.webkit.org/show_bug.cgi?id=176157#c1) with no ice candidate gathering. After I added the snipped I got a full blown SDP, but still no ice candidate gathering. After I removed adapter everything worked, I got the right SDP and ice candidates. 

So maybe there is more work to do than just integrate this snippet into adapter?

**Comment by KaptenJansson** [comment]
What's the latest here?

**Comment by miniruwan** [comment]
I think it is fixed in https://github.com/webrtc/adapter/releases/tag/v5.0.5

**Comment by KaptenJansson** [comment]
I see, looks like https://github.com/webrtc/adapter/commit/ee197f1b07ae502f48026d832dd0cd952846a78b specifically. Closing.
