### ISSUE TITLE
Edge vs chrome or FF

### ISSUE THREAD

**Issue by fix2015** [webrtcHacks/adapter#666]
bugs

**Comment by fippo** [comment]
you need to call pc.addIceCandidate(nullOrUndefined) on the remote end once the local end emits a onicecandidate event with event.candidate being undefined.

**Comment by fix2015** [comment]
now its work, but have one bug, if edge will be send offer first all work fine, if chrome first send offer i get error 
![img_05092017_091751_0-1](https://user-images.githubusercontent.com/3988392/30069312-11c083ac-9269-11e7-8569-ffb6e9d7394a.png)

**Comment by fippo** [comment]
when that happens (it should not) what is the value of self.localDescription?

**Comment by fix2015** [comment]
null

**Comment by fix2015** [comment]
<img width="1139" alt="2017-09-05 19 49 58" src="https://user-images.githubusercontent.com/3988392/30072584-75234cfe-9273-11e7-9790-cb198b268d5b.png">
