### ISSUE TITLE
TypeError: window.RTCTrackEvent is undefined 

### ISSUE THREAD

**Issue by MartinRamm** [webrtcHacks/adapter#669]
**Browsers and versions affected**
Firefox ESR 45.9.
Other versions are likely to be affected as well, but this was not tested. (i.e.: versions before ESR 45.9, versions before Firefox 52 etc.)

**Description/Steps to reproduce**
When loading the adapter.js file of version 5.0.0 or above in the affected browsers, the error message `TypeError: window.RTCTrackEvent is undefined ` is thrown.

**Expected results**
No runtime errors are thrown when loading/initializing the library.

**Actual results**
`TypeError: window.RTCTrackEvent is undefined ` is thrown.

**Update:**
Here is a fiddle to test: https://jsfiddle.net/yLu6opqz/
Here is the console output of running this on ESR 45.9: 
![webrtc-adapter-error-ffesr45-9](https://user-images.githubusercontent.com/31626748/30033975-d6a8c0e2-919e-11e7-9675-01a0e8019856.png)

**Comment by benbro** [comment]
Maybe the same issue?
https://bugs.chromium.org/p/chromium/issues/detail?id=761612

**Comment by MartinRamm** [comment]
Not sure, but I don't think so. I have updated the description of the ticket to explain the situation a little better.

**Comment by fippo** [comment]
@jan-ivar ^^
