### ISSUE TITLE
[Edge] It broken when I receive a video at packet loss

### ISSUE THREAD

**Issue by codejs-kr** [webrtcHacks/adapter#673]
**Browsers and versions affected**
- Edge 15063

**Description**
I use Mux Server. (connected Edge to MUX server)
I want to know the difference below. 

case 1. include adapter.js
- It intermit when I receive a video at packet loss

case 2. not include adapter.js
- It broken when I receive a video at packet loss

Where in the adapter.js does this control?
I want to solve this symptom, not include adpater.js

**Comment by fippo** [comment]
This is not a support forum for Edge. My hunch would be that something is wrong with your https://tools.ietf.org/html/rfc4585 -- in particular NACK handling.
