### ISSUE TITLE
Firefox send a=ssrc in an receive only sdp

### ISSUE THREAD

**Issue by kekkokk** [webrtcHacks/adapter#674]
Hi guys, I don't know if is the right place to start this discussion but I'm facing a strange behavior and I don't know if it's a Chrome or Firefox bug.

**Browsers and versions affected**
Chrome 61/62 but maybe also the older 
Firefox 49 to current (55)

**Description**
I create a simple p2p session from Chrome (publisher) to Firefox (receiver).
Chrome is a sendonly ({offerToReceiveVideo: false, offerToReceiveAudio: false})
Firefox is a recveonly ({offerToReceiveVideo: true, offerToReceiveAudio: true})

The call works as expected but analyzing webrtc-internals in chrome we can see that both send and recv graphics are created.
Digging more, seems that firefox, reply with a recv only sdp but also includes both audio and video a=ssrc: cname lines. 

Filtering out these 2 lines from the firefox answer everything's correct.

**Steps to reproduce**
Chrome sendonly:

`options: {offerToReceiveVideo: 0, offerToReceiveAudio: 0, voiceActivityDetection: true, iceRestart: false}

type: offer, sdp: v=0
o=- 8061924013999730021 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS 1Zmc6Pwq0OnJyyC98aaah1wErZeHdrDlz5gx
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:ihdT
a=ice-pwd:U392D2TXN87s0g5THA9hXtYw
a=fingerprint:sha-256 E0:80:3A:1D:AB:52:6C:62:60:76:BA:73:9F:FD:A6:39:E1:60:A0:2D:7D:0B:55:A5:18:30:CF:5D:D9:86:03:8A
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:2434097004 cname:qA6lZ4oCNfZeO23P
a=ssrc:2434097004 msid:1Zmc6Pwq0OnJyyC98aaah1wErZeHdrDlz5gx c0379d8f-3272-4218-813e-bf79365ccae1
a=ssrc:2434097004 mslabel:1Zmc6Pwq0OnJyyC98aaah1wErZeHdrDlz5gx
a=ssrc:2434097004 label:c0379d8f-3272-4218-813e-bf79365ccae1
m=video 9 UDP/TLS/RTP/SAVPF 96 98 100 102 127 97 99 101 125
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:ihdT
a=ice-pwd:U392D2TXN87s0g5THA9hXtYw
a=fingerprint:sha-256 E0:80:3A:1D:AB:52:6C:62:60:76:BA:73:9F:FD:A6:39:E1:60:A0:2D:7D:0B:55:A5:18:30:CF:5D:D9:86:03:8A
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=sendonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtpmap:100 H264/90000
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:102 red/90000
a=rtpmap:127 ulpfec/90000
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:125 rtx/90000
a=fmtp:125 apt=102
a=ssrc-group:FID 2064403822 225134800
a=ssrc:2064403822 cname:qA6lZ4oCNfZeO23P
a=ssrc:2064403822 msid:1Zmc6Pwq0OnJyyC98aaah1wErZeHdrDlz5gx 5ef7ab1d-6d92-44a7-a3cb-a44a27d69b51
a=ssrc:2064403822 mslabel:1Zmc6Pwq0OnJyyC98aaah1wErZeHdrDlz5gx
a=ssrc:2064403822 label:5ef7ab1d-6d92-44a7-a3cb-a44a27d69b51
a=ssrc:225134800 cname:qA6lZ4oCNfZeO23P
a=ssrc:225134800 msid:1Zmc6Pwq0OnJyyC98aaah1wErZeHdrDlz5gx 5ef7ab1d-6d92-44a7-a3cb-a44a27d69b51
a=ssrc:225134800 mslabel:1Zmc6Pwq0OnJyyC98aaah1wErZeHdrDlz5gx
a=ssrc:225134800 label:5ef7ab1d-6d92-44a7-a3cb-a44a27d69b51
`

Firefox RecvOnly:

`options: {offerToReceiveVideo: 0, offerToReceiveAudio: 0, voiceActivityDetection: true, iceRestart: false}

type: answer, sdp: v=0
o=mozilla...THIS_IS_SDPARTA-55.0.3 4483214647518060316 0 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 72:36:C5:65:63:02:A4:D3:0C:46:A3:24:08:B3:72:45:90:59:EB:F1:C2:A7:11:73:A4:1C:BC:64:CF:F9:F0:17
a=group:BUNDLE audio video
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 9 UDP/TLS/RTP/SAVPF 111 126
c=IN IP4 0.0.0.0
a=recvonly
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=fmtp:111 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=fmtp:126 0-15
a=ice-pwd:78d6acd5074efc2b9c908070a4823a74
a=ice-ufrag:6fa46bb7
a=mid:audio
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtpmap:126 telephone-event/8000/1
a=setup:active
a=ssrc:714580049 cname:{1a4e2f2c-c384-4fc8-b1e6-669f04cc7074}
m=video 9 UDP/TLS/RTP/SAVPF 96
b=AS:3000
c=IN IP4 0.0.0.0
a=recvonly
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=fmtp:96 max-fs=12288;max-fr=60
a=ice-pwd:78d6acd5074efc2b9c908070a4823a74
a=ice-ufrag:6fa46bb7
a=mid:video
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 goog-remb
a=rtcp-mux
a=rtpmap:96 VP8/90000
a=setup:active
a=ssrc:2525390681 cname:{1a4e2f2c-c384-4fc8-b1e6-669f04cc7074}
`

**Expected results**
In both webrtc internals we must see only the send graphs in chrome and only the recv graphs in firefox.

**Actual results**
In Chrome, also the recv channels are created
![screen shot 2017-09-07 at 4 03 13 pm](https://user-images.githubusercontent.com/15072723/30167268-180b6e4c-93e6-11e7-8712-adb791dcb4c1.png)

If we try to make the same test on chrome, we can see the recv only answer similar to the Firefox one but without the two a=ssrc lines.

Am I doing something wrong? 

If this is a bug we could filter out these unattended cname lines in adapter until firefox/chrome fix this issue

**Comment by fippo** [comment]
There is a series of chrome bugs on this matter:
https://bugs.chromium.org/p/webrtc/issues/detail?id=8203
(and the two linked issues). Star those.

I dont think adapter can or should do something about it.

**Comment by kekkokk** [comment]
So it's correct for Firefox announcing two ssrc even if it's receive only? 
what are these used for? 
It's the source of the Rtcp RRs?

**Comment by fippo** [comment]
yes. RTCP needs those ssrcs. Chrome is simply hardcoding certain values here.

**Comment by kekkokk** [comment]
Ok, many thanks
