### ISSUE TITLE
IOS group call

### ISSUE THREAD

**Issue by fix2015** [webrtcHacks/adapter#678]
Hi, is someone tried do group call with ios 11, i tried with 2 desctop on win 10 and iphone 6s with ios11, and it work good, but after reload one of desctop device i can't see ios camera on this device, but after reload ios device all fine. Is someone know where the pb?

**Comment by youennf** [comment]
Hi,
If you are using adapter.js+Safari on iOS, you might want to file a bug on https://bugs.webkit.org.
If you can share a repro case, that would be great too.
