### ISSUE TITLE
Safari 11 -> Chrome 60.0.3112.113

### ISSUE THREAD

**Issue by fix2015** [webrtcHacks/adapter#679]
**Browsers and versions affected**
Safari 11 -> Chrome 60.0.3112.113

**Steps to reproduce**
1 step - Load Safari page
2 Chrome create offer and send 
3 Safari set remote offer and create answer and send
4 Chrome set remote answer
result Safari show 2 cameras but Chrome 1 local camera and empty stream from safari
But
1 step - Load Chrome page
2 Safari create offer and send 
3 Chrome set remote offer and create answer and send
4 Safari set remote answer
result 2 cameras on both browser

**Expected results**
2 cameras on both browser

**Actual results**
 Safari show 2 cameras but Chrome 1 local camera and empty stream from safari

********
not sure that its depend on offer but anyway i will attach maybe it will help

**attach offer from chrome (not success variant)- >**
v=0
o=- 6053319083829837730 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS b116e0ab-4c41-4620-98db-a7ef29119cc7
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:syLK
a=ice-pwd:NiCEGDq0J8lfNmSzGKRpOIvS
a=ice-options:trickle
a=fingerprint:sha-256 3B:78:25:EC:B2:AC:AF:0B:E8:EB:C9:D3:B9:70:D9:FD:DB:35:A8:CF:0B:77:DD:ED:D7:52:2B:1B:BF:51:9C:80
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
m=video 9 UDP/TLS/RTP/SAVPF 96 98 100 102 127 97 99 101 125
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:syLK
a=ice-pwd:NiCEGDq0J8lfNmSzGKRpOIvS
a=ice-options:trickle
a=fingerprint:sha-256 3B:78:25:EC:B2:AC:AF:0B:E8:EB:C9:D3:B9:70:D9:FD:DB:35:A8:CF:0B:77:DD:ED:D7:52:2B:1B:BF:51:9C:80
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=sendonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtpmap:100 H264/90000
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:102 red/90000
a=rtpmap:127 ulpfec/90000
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:125 rtx/90000
a=fmtp:125 apt=102
a=ssrc-group:FID 3643689837 3781485445
a=ssrc:3643689837 cname:Q4RWge8wpuPmUQGJ
a=ssrc:3643689837 msid:b116e0ab-4c41-4620-98db-a7ef29119cc7 f2f5dc21-84ab-4e57-a977-6a30587ead7d
a=ssrc:3643689837 mslabel:b116e0ab-4c41-4620-98db-a7ef29119cc7
a=ssrc:3643689837 label:f2f5dc21-84ab-4e57-a977-6a30587ead7d
a=ssrc:3781485445 cname:Q4RWge8wpuPmUQGJ
a=ssrc:3781485445 msid:b116e0ab-4c41-4620-98db-a7ef29119cc7 f2f5dc21-84ab-4e57-a977-6a30587ead7d
a=ssrc:3781485445 mslabel:b116e0ab-4c41-4620-98db-a7ef29119cc7
a=ssrc:3781485445 label:f2f5dc21-84ab-4e57-a977-6a30587ead7d

**attach offer from chrome (success variant)- >**
v=0
o=- 4848364883809851782 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS 41c49950-72bc-4eaf-b0a7-81ecd7ccdc7c
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:EOTh
a=ice-pwd:POhRcE2I10MjPfMR1H/S5tNo
a=ice-options:trickle
a=fingerprint:sha-256 3F:E4:5A:70:2B:60:28:89:38:F6:F7:BF:5E:B9:A2:F5:6E:F7:24:4D:CA:C6:40:3C:45:8C:C9:D0:01:82:86:8D
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:95878599 cname:7YmUw3Mm9zT3/VJw
a=ssrc:95878599 msid:41c49950-72bc-4eaf-b0a7-81ecd7ccdc7c 2adfcbd1-0d13-43f3-aeb0-0ff510b21fd2
a=ssrc:95878599 mslabel:41c49950-72bc-4eaf-b0a7-81ecd7ccdc7c
a=ssrc:95878599 label:2adfcbd1-0d13-43f3-aeb0-0ff510b21fd2
m=video 9 UDP/TLS/RTP/SAVPF 96 98 99 97 100
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:EOTh
a=ice-pwd:POhRcE2I10MjPfMR1H/S5tNo
a=ice-options:trickle
a=fingerprint:sha-256 3F:E4:5A:70:2B:60:28:89:38:F6:F7:BF:5E:B9:A2:F5:6E:F7:24:4D:CA:C6:40:3C:45:8C:C9:D0:01:82:86:8D
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 red/90000
a=rtpmap:98 ulpfec/90000
a=rtpmap:99 H264/90000
a=rtcp-fb:99 ccm fir
a=rtcp-fb:99 nack
a=rtcp-fb:99 nack pli
a=rtcp-fb:99 goog-remb
a=rtcp-fb:99 transport-cc
a=fmtp:99 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:100 rtx/90000
a=fmtp:100 apt=99
a=ssrc-group:FID 2216332053 843461020
a=ssrc:2216332053 cname:7YmUw3Mm9zT3/VJw
a=ssrc:2216332053 msid:41c49950-72bc-4eaf-b0a7-81ecd7ccdc7c 1e43de19-ee61-409b-ae7d-cbbb97c6cc11
a=ssrc:2216332053 mslabel:41c49950-72bc-4eaf-b0a7-81ecd7ccdc7c
a=ssrc:2216332053 label:1e43de19-ee61-409b-ae7d-cbbb97c6cc11

**Comment by KaptenJansson** [comment]
Are you testing on the same machine? Does Chrome show 2 cameras when safari is not using any cameras?

**Comment by KaptenJansson** [comment]
See #685 for details.
