### ISSUE TITLE
Remove console.logs

### ISSUE THREAD

**Issue by tgabi333** [webrtcHacks/adapter#68]
Please remove console calls

**Comment by KaptenJansson** [comment]
Please provide some info backing your issue (use case, pros/cons etc).

**Comment by tgabi333** [comment]
I think polluting console is not acceptable from any library. We use console to collect errors and logs from user side. Other libraries use debug flag and/or custom loggers defaultly connected to console to log.

**Comment by eddiemonge** [comment]
Why was this closed? It only removes the console.logs when this is included as a module. I don't want to include it as a module but do want to turn off logging in production as it is just noise there.

**Comment by fippo** [comment]
if you are not using this as a dependency, can't you simply remove the single console.log.apply line?

**Comment by eddiemonge** [comment]
@fippo I could. But then I'd have to do that everytime I updated this (which I'm including through bower).

**Comment by jan-ivar** [comment]
My 2 cents: I find some of the logging useful (how constraints are translated on an older browser), and other logging not so useful (This is firefox? get out).

How about adapter.js only emit to console when it actually does something? That way, one can silence it by being spec compliant.

**Comment by eddiemonge** [comment]
I'd still prefer an option to completely silence it if I wanted, even if it did do something.

**Comment by KaptenJansson** [comment]
I will add a logging switch to Adapter.js 2.0.

**Comment by sjdemartini** [comment]
@KaptenJansson Thanks for committing to fixing this. I think this issue should be re-opened (and not closed till actually addressed). 

Can this be done in a release sooner than adapter.js 2.0? A polyfill that is intended to be included in the browser should absolutely not `console.log` by default. I would love to be able to include `adapter.js` as a dependency in an npm project, without having to fork it.
