### ISSUE TITLE
safari onaddstream

### ISSUE THREAD

**Issue by kimilpyoung** [webrtcHacks/adapter#680]
**Browsers and versions affected**
safari 11.1(Technology preveiw) R39

**Description**
var ICEConfigure = {
  'iceServers': [{
    'url': 'stun:stun.l.google.com:19302'
  }, {
    'url': 'turn:50.7.74.178:3478',
    'username': 'dynamic',
    'credential': 'dynamic1234',
    'credentialType': "password"
  }]
};
**/////////////////////////////////////////**
var gpc = new RTCPeerConnection(ICEConfigure);
    pc.addTransceiver('audio');
    pc.addTransceiver('video');
    pc.onicecandidate = function()    // i do defined
    pc.onaddstream = function(e){   //
      remoteVideo.srcObject = e.stream;
    }
  var a = gpc.createOffer(offerOptions).then(function(sessionDescription) {
    gpc.setLocalDescription(sessionDescription);
    sendMessage({
      user:'viewer',
      type: 'sdp',
      sdpOffer: sessionDescription.sdp
    })
  },handleCreateOfferError);
**///////////////////////////////////////////////////**
var answer = new RTCSessionDescription({
                  type: 'answer',
                  sdp: oo.sdpAnswer
              });
        gpc.setRemoteDescription(answer).then(function(){
          console.log('remote success');
          if (candidatesQueue.length > 0) {
            while (candidatesQueue.length) {
              var candidate = candidatesQueue.shift();
              gpc.addIceCandidate(candidate);
            }
          }
        },function(error){
          console.log(error);
        });

peer received onaddstream but cant play video stream
just show me blackscreen
i used adapter.js and webrtc legacyAPI enable in safari option

**Steps to reproduce**

**Expected results**

**Actual results**

**Comment by youennf** [comment]
A link might be good.
I am guessing it might be due to autoplay restrictions.
Can you try muting the video to which you are setting srcObject to the received stream?
Or clicking on the play button of the video element with controls activated

**Comment by youennf** [comment]
> A link might be good.

Link to the website or a relevant test case.

**Comment by KaptenJansson** [comment]
Ping

**Comment by kimilpyoung** [comment]
sorry but not have test webpage, and i cant resolve this problem...

this problem just to occur in kurento server
