### ISSUE TITLE
Regression in 4.2.0 onward: Calling addTrack/removeTrack on local MediaStream does not trigger onaddtrack/onremovetrack events on remote end

### ISSUE THREAD

**Issue by isnumanagic** [webrtcHacks/adapter#681]
[This commit](https://github.com/webrtc/adapter/commit/c7570e40c5cdc4a4d3db79ef750c96cf002a09dd) changed the way addStream in Chrome shims works in such a way that stream supplied to origAddStream method is not the one supplied to shim - but rather it's copy which does not propagate addTrack/removeTrack calls from original stream. Thus calling addTrack/removeTrack on stream has no effect since PeerConnection has different stream stored and will changes in stream's tracks won't get reflected to SDP, causing remote to be oblivious to track changes.

[Working JSFiddle with 4.1.1](https://jsfiddle.net/jsf_isaac/rhpLt54b/)
[Broken JSFiddle with 4.2.0](https://jsfiddle.net/jsf_isaac/rhpLt54b/16/)
[Broken JSFiddle with latest](https://jsfiddle.net/jsf_isaac/rhpLt54b/17/)

**Comment by fippo** [comment]
the behaviour you're relying on does not work in Firefox at all. See also https://bugs.chromium.org/p/webrtc/issues/detail?id=7815

If you want to send the track over the peerconnection you'll need to call pc.addTrack.

**Comment by isnumanagic** [comment]
It doesn't work in Firefox because it does not support legacy stream WebRTC API, while Chrome currently only supports legacy (and track API behind flag), and this breaks it.

**Comment by fippo** [comment]
firefox does support addStream -- it does not support the behaviour you rely on. If you want this behaviour then don't use adapter.js.

**Comment by jan-ivar** [comment]
Confirming Firefox supports `addStream`. It just doesn't support `removeStream`.
