### ISSUE TITLE
RTCPeerConnection.getStats(mediaStreamTrack, callback) does not work correct

### ISSUE THREAD

**Issue by Keksinautin** [webrtcHacks/adapter#683]
**Browsers and versions affected**
Chrome

**Description**
I call `RTCPeerConnection.getStats(mediaStreamTrack, callback)` and I expect to get result in the callback. But my callback will be called without arguments.
Because of this code:
```
      // When spec-style getStats is supported, return those when called with
      // either no arguments or the selector argument is null.
      if (origGetStats.length === 0 && (arguments.length === 0 ||
          typeof arguments[0] !== 'function')) {
        return origGetStats.apply(this, []);
      }
```
As we can see the comment contradicts the code.  
`or the selector argument is null.` and `typeof arguments[0] !== 'function'`

p.s. I can do a merge request if you confirm it as a bug.
**Steps to reproduce**
Just call the `RTCPeerConnection.getStats(mediaStreamTrack, callback)` and see the empty arguments inside the callback.

**Expected results**
Stats as an argument inside the callback

**Actual results**
There are no any arguments (because of `return origGetStats.apply(this, []);`)

**Comment by fippo** [comment]
From what I know, getStats with a selector never worked in chrome. See https://jsfiddle.net/nuskopqd/ which throws an error.

**Comment by fippo** [comment]
@henbos ^^

**Comment by henbos** [comment]
https://jsfiddle.net/nuskopqd/1/ doesn't throw an error but the report is empty

**Comment by henbos** [comment]
No it's not empty, it's working
https://jsfiddle.net/nuskopqd/2/

**Comment by henbos** [comment]
The optional selector is the second argument, not the first.
https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/peerconnection/RTCPeerConnection.idl?q=RTCPeerConnection.idl&sq=package:chromium&dr&l=108

Try with signature getStats(callback, mediaStreamTrack).

**Comment by fippo** [comment]
or just use the promise version :-)

**Comment by jan-ivar** [comment]
First off, `getStats(mediaStreamTrack, callback)` shouldn't work, because it is missing a failure callback argument. Firefox correctly fails with `"TypeError: Not enough arguments to RTCPeerConnection.getStats."`. And that was [before](https://w3c.github.io/webrtc-pc/archives/20161123/webrtc.html#legacy-interface-extensions) it got completely removed from the spec.

Generally, legacy support is the responsibility of browsers, not adapter.js. The goal of adapter.js is to drive convergence toward the spec, so I'm inclined to say not fix here. Use the promise API.

**Comment by Keksinautin** [comment]
Hi to all, first of all, thank you for answers.
1. @henbos 
> The optional selector is the second argument, not the first.

Ok, but why do we see in the adapter the signature of `getStats` as 
`function(selector, successCallback, errorCallback)` ?

Ok, we check that `typeof selector === 'function'` and if it is true we call 
`return origGetStats.apply(this, arguments);`  
But then in the "else" we already know, that the first argument is not a function. Why do we check it again in another terms: `typeof arguments[0] !== 'function'` ?
And why is the comment: 
```
// When spec-style getStats is supported, return those when called with
// either no arguments or the selector argument is null.
```
We does not see any checks whether selector is null or not. Why?

2. I can use `Promise`, but it will require much more workarounds then the "callbacks" interface, because I am using Dart... So, yes, I can, but I just wanted to use it the same way I used it in the previous version of the "adapter.js".
If my merge request is not a fix, can you please describe for what reason and how should this code work:
```js
      // When spec-style getStats is supported, return those when called with
      // either no arguments or the selector argument is null.
      if (origGetStats.length === 0 && (arguments.length === 0 ||
          typeof arguments[0] !== 'function')) {
        return origGetStats.apply(this, []);
      }
```
?

**Comment by jan-ivar** [comment]
> why do we see in the adapter the signature of getStats as
function(selector, successCallback, errorCallback) ?

As I mentioned because that's what [used to be](https://w3c.github.io/webrtc-pc/archives/20161123/webrtc.html#legacy-interface-extensions) in the spec.

> it will require much more workarounds then the "callbacks" interface

Have you tried this?
```js
pc.getStats().then(successCallback, errorCallback);
```

**Comment by heqiang100** [comment]
the master version still has this problem?

**Comment by jan-ivar** [comment]
Adapter.js polyfills the spec, and `pc.getStats(mediaStreamTrack, callback)` is incorrect usage according to the spec. Use `pc.getStats(mediaStreamTrack).then(success, failure)`.

**Comment by heqiang100** [comment]
i get a empty return all the time by this way.

code:
var selector = pc.getRemoteStreams()[0].getTracks()[0];
		        	pc.getStats(selector).then(function (report) {
		        	    console.log(JSON.stringify(report));
		        	    alert(JSON.stringify(report));
		        	}, function(err){
		        		console.log(JSON.stringify(err));
		        		alert(JSON.stringify(err));
		        	});

**Comment by heqiang100** [comment]
it's not work in the safari
![image](https://user-images.githubusercontent.com/7948078/33593251-946c62e2-d9c9-11e7-8971-0f5694d601b2.png)

**Comment by lquanyang** [comment]
Is there a solution now? excuse me

**Comment by fippo** [comment]
as jan-ivar said above, use `pc.getStats(mediaStreamTrack).then(success, failure)`
