### ISSUE TITLE
Compatibility between adapter.js versions

### ISSUE THREAD

**Issue by ghost** [webrtcHacks/adapter#690]
We are working on a WebRTC project, but for a few month, we did not update the "adapter.js".
The starting version was 3.4.3 and we wanted to use the 5.0.4 but our application is not working anymore. 

Is backward compatibility guaranteed between different majors versions?

**Comment by fippo** [comment]
major versions are used for intentional breaking changes. Even though in general I would strongly recommend not upgrading adapter without running an extensive test suite as it fiddles with the core of webrtc.

**Comment by ghost** [comment]
Ok, that's what I thought, just wanted to be sure. Thank you :) Have a nice day
