### ISSUE TITLE
Chrome: removing and re-adding the same stream doesn't work

### ISSUE THREAD

**Issue by Lebuin** [webrtcHacks/adapter#698]
**Browsers and versions affected**

Chrome (tested with 61 and 62)

This bug was introduced in #3b1c6f1f5 and first released in v4.2.0. It persists in the current master branch. Chrome is not at fault: when removing the adapter.js library the problem does not occur.

**Description**

Peer A is streaming two tracks (audio + video) to Peer B. Peer A removes the video track from the RTCPeerConnection. When negotiation is done, Peer A adds the video track back to the RTCPeerConnection.

**Expected results**

After re-adding the video stream, Peer B can see the video.

**Actual results**

After re-adding the video stream, Peer B sees only a black screen. The video track has `readyState == 'ended'`. In chrome://webrtc-internals the video data seems to be streaming correctly.

**Steps to reproduce**

I have created a [minimal demo](https://jsfiddle.net/Lfe5nzty/5/).

* Click on "Start". You should see the video in both `video` elements, and hear audio.
* Click on "Restart video". The audio keeps streaming, but the lower `video` turns black

The problem is not 100% reproducible, so you may have to click "Restart video" more than once.

When the screen has turned black, you can wait for 1 minute and click "Restart video" again. Sometimes the video starts streaming successfully again. This doesn't always work though.

**Comment by fredericnavarre** [comment]
Not reproduced on PC/Chrome 62, but easily reproduced on Mac/Chrome 61, using provided minimal demo code.

**Comment by henbos** [comment]
Chrome-wise, this was fixed in https://chromium-review.googlesource.com/c/chromium/src/+/641870.

Removing and re-adding in a setTimeout() is a total hack though, doing that type of things requires renegotiation or else you're relying on unsafe assumptions.

**Comment by Lebuin** [comment]
My bad, I can confirm that this is also fixed in Chrome 62 on my Linux machine.

(@henbos My demo does renegotiate both after removing and adding the stream, as you can see in the console. I added the timeout so that the stream would only be added after renegotiation was finished, to make sure the demonstrated problem is not caused by adding streams during negotiation. Or do you mean something else?)

**Comment by henbos** [comment]
Oh yeah, it does renegotiate correctly, assuming renegotiation has finished within a second is fine for a repro fiddle.

Shall I close this issue then?

**Comment by fippo** [comment]
I still do not understand what difference adapter makes here... this is happening on the remote side (where there is not much done) and *sometimes* it works.

**Comment by Lebuin** [comment]
I still consider this a bug that needs fixing. This is a problem in the currently stable branch of Chrome, and I have demonstrated that the issue is caused by adapter.js.

**Comment by henbos** [comment]
Chrome 62 is about to hit stable, rolling out tomorrow I think, so I think it's not worth fixing adapter.js assuming this goes not occur in 62.
