### ISSUE TITLE
navigator.mediaDevices.getUserMedia video track "ended" on first load of new tab

### ISSUE THREAD

**Issue by yogaboy** [webrtcHacks/adapter#699]
**Browsers and versions affected**
Safari on iOS v11.0.2

**Description**
The video track in the stream of the Promise return reports as readyState="ended" . Not sure if this is a load sequence error. If I reload the page though it works reliably, both audio and video active.

**Steps to reproduce**
1. call a page in a new tab
2. add navigator.mediaDevices.getUserMedia with {audio:true,video:{facingMode:'user'}}call to a window.onload event
3. check the readystate of the returned tracks - video is shown as "ended"

I've also tried adding an alert before the getUserMedia call to see if there's a background event that needs to complete. No amount of waiting changes the result and there are no errors reported in console.

**Expected results**
Tracks should appear in readyState active. Reload should not be required.

**Actual results**
No video stream visible on attached video tag. Must reload to see the video and audio attached.

**Comment by fippo** [comment]
you might want to move over to the [webkit bugtracker](https://bugs.webkit.org/).

cc @youennf

**Comment by yogaboy** [comment]
will do

**Comment by fippo** [comment]
@youennf you might want to check https://bugs.chromium.org/p/chromium/issues/detail?id=574041 -- I bet the code responsible is old enough to be still shared with webkit.

**Comment by youennf** [comment]
Thanks!
I updated https://bugs.webkit.org/show_bug.cgi?id=178218 with that information.
