### ISSUE TITLE
Firefox ontrack is not received two video tracks

### ISSUE THREAD

**Issue by kimilpyoung** [webrtcHacks/adapter#703]
**Browsers and versions affected**
Chrome to Firefox

**Description**
First,  add Track video and audio tracks ( local) and negotiation, then firefox receives ontrack
Second, add otherStream videoTrack( ex: screen share stream) and renogtiation
but firefox cant receives ontrack. 
just I see a screen share screen that has been paused for a while

Can not firefox received multistream? 

Another issue is safari can receive two videotrack, but he cant receive onremovestream
and onended
Even though I remove the track.

**Steps to reproduce**
The same as above

**Expected results**
firefox add two video track in ontrack

**Actual results**
firefox not receive two track, just he receive one video,audio track.

**Comment by alvestrand** [comment]
can you include the SDP exchanged and the versions of Chrome and Firefox involved?

**Comment by kimilpyoung** [comment]
Chrome is 62.0.3202.75 lastest release and Firefox is 56.0.2 lastest release too.
**first firefox receive sdp is**

"v=0
↵o=- 3512811135255868180 2 IN IP4 127.0.0.1
↵s=-
↵t=0 0
↵a=group:BUNDLE audio video
↵a=msid-semantic: WMS DNwWYI18UAwvrWMchHLFUhlrH5muayhhIZza
↵m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
↵c=IN IP4 0.0.0.0
↵a=rtcp:9 IN IP4 0.0.0.0
↵a=ice-ufrag://Om
↵a=ice-pwd:0+WMxwYGnTnRcGNwz4LjFArR
↵a=ice-options:trickle
↵a=fingerprint:sha-256 B1:28:3B:32:34:9B:69:19:38:42:AA:A9:5D:65:FD:07:37:A5:65:10:53:B0:64:CD:AB:C1:51:85:20:83:CA:26
↵a=setup:actpass
↵a=mid:audio
↵a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
↵a=sendrecv
↵a=rtcp-mux
↵a=rtpmap:111 opus/48000/2
↵a=rtcp-fb:111 transport-cc
↵a=fmtp:111 minptime=10;useinbandfec=1
↵a=rtpmap:103 ISAC/16000
↵a=rtpmap:104 ISAC/32000
↵a=rtpmap:9 G722/8000
↵a=rtpmap:0 PCMU/8000
↵a=rtpmap:8 PCMA/8000
↵a=rtpmap:106 CN/32000
↵a=rtpmap:105 CN/16000
↵a=rtpmap:13 CN/8000
↵a=rtpmap:110 telephone-event/48000
↵a=rtpmap:112 telephone-event/32000
↵a=rtpmap:113 telephone-event/16000
↵a=rtpmap:126 telephone-event/8000
↵a=ssrc:1750151663 cname:1/byvGa5L29O1p0M
↵a=ssrc:1750151663 msid:DNwWYI18UAwvrWMchHLFUhlrH5muayhhIZza 8efbd260-7804-4265-9a80-1d4ea72791ba
↵a=ssrc:1750151663 mslabel:DNwWYI18UAwvrWMchHLFUhlrH5muayhhIZza
↵a=ssrc:1750151663 label:8efbd260-7804-4265-9a80-1d4ea72791ba
↵m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 124 127 125 123
↵c=IN IP4 0.0.0.0
↵a=rtcp:9 IN IP4 0.0.0.0
↵a=ice-ufrag://Om
↵a=ice-pwd:0+WMxwYGnTnRcGNwz4LjFArR
↵a=ice-options:trickle
↵a=fingerprint:sha-256 B1:28:3B:32:34:9B:69:19:38:42:AA:A9:5D:65:FD:07:37:A5:65:10:53:B0:64:CD:AB:C1:51:85:20:83:CA:26
↵a=setup:actpass
↵a=mid:video
↵a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
↵a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
↵a=extmap:4 urn:3gpp:video-orientation
↵a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
↵a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
↵a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
↵a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
↵a=sendrecv
↵a=rtcp-mux
↵a=rtcp-rsize
↵a=rtpmap:96 VP8/90000
↵a=rtcp-fb:96 ccm fir
↵a=rtcp-fb:96 nack
↵a=rtcp-fb:96 nack pli
↵a=rtcp-fb:96 goog-remb
↵a=rtcp-fb:96 transport-cc
↵a=rtpmap:97 rtx/90000
↵a=fmtp:97 apt=96
↵a=rtpmap:98 VP9/90000
↵a=rtcp-fb:98 ccm fir
↵a=rtcp-fb:98 nack
↵a=rtcp-fb:98 nack pli
↵a=rtcp-fb:98 goog-remb
↵a=rtcp-fb:98 transport-cc
↵a=rtpmap:99 rtx/90000
↵a=fmtp:99 apt=98
↵a=rtpmap:100 H264/90000
↵a=rtcp-fb:100 ccm fir
↵a=rtcp-fb:100 nack
↵a=rtcp-fb:100 nack pli
↵a=rtcp-fb:100 goog-remb
↵a=rtcp-fb:100 transport-cc
↵a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
↵a=rtpmap:101 rtx/90000
↵a=fmtp:101 apt=100
↵a=rtpmap:102 red/90000
↵a=rtpmap:124 rtx/90000
↵a=fmtp:124 apt=102
↵a=rtpmap:127 ulpfec/90000
↵a=rtpmap:125 H264/90000
↵a=rtcp-fb:125 ccm fir
↵a=rtcp-fb:125 nack
↵a=rtcp-fb:125 nack pli
↵a=rtcp-fb:125 goog-remb
↵a=rtcp-fb:125 transport-cc
↵a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=420032
↵a=rtpmap:123 rtx/90000
↵a=fmtp:123 apt=125
↵a=ssrc-group:FID 3272604184 3217491005
↵a=ssrc:3272604184 cname:1/byvGa5L29O1p0M
↵a=ssrc:3272604184 msid:DNwWYI18UAwvrWMchHLFUhlrH5muayhhIZza ef31c904-1c53-4b67-be17-32eaba926c7e
↵a=ssrc:3272604184 mslabel:DNwWYI18UAwvrWMchHLFUhlrH5muayhhIZza
↵a=ssrc:3272604184 label:ef31c904-1c53-4b67-be17-32eaba926c7e
↵a=ssrc:3217491005 cname:1/byvGa5L29O1p0M
↵a=ssrc:3217491005 msid:DNwWYI18UAwvrWMchHLFUhlrH5muayhhIZza ef31c904-1c53-4b67-be17-32eaba926c7e
↵a=ssrc:3217491005 mslabel:DNwWYI18UAwvrWMchHLFUhlrH5muayhhIZza
↵a=ssrc:3217491005 label:ef31c904-1c53-4b67-be17-32eaba926c7e
↵"


**and secondly sdp(include screenShare Stream)**

"v=0
↵o=- 3512811135255868180 3 IN IP4 127.0.0.1
↵s=-
↵t=0 0
↵a=group:BUNDLE audio video
↵a=msid-semantic: WMS LwsspBo5HljuwWKUp8pbnZAJbLGbX15RZ24f DNwWYI18UAwvrWMchHLFUhlrH5muayhhIZza
↵m=audio 57339 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
↵c=IN IP4 123.142.71.182
↵a=rtcp:9 IN IP4 0.0.0.0
↵a=candidate:6817020 1 udp 2122260223 192.168.2.174 57339 typ host generation 0 network-id 1 network-cost 10
↵a=candidate:2166358600 1 udp 1686052607 (my ip) 57339 typ srflx raddr 192.168.2.174 rport 57339 generation 0 network-id 1 network-cost 10
↵a=candidate:1324087308 1 tcp 1518280447 192.168.2.174 9 typ host tcptype active generation 0 network-id 1 network-cost 10
↵a=ice-ufrag://Om
↵a=ice-pwd:0+WMxwYGnTnRcGNwz4LjFArR
↵a=ice-options:trickle
↵a=fingerprint:sha-256 B1:28:3B:32:34:9B:69:19:38:42:AA:A9:5D:65:FD:07:37:A5:65:10:53:B0:64:CD:AB:C1:51:85:20:83:CA:26
↵a=setup:actpass
↵a=mid:audio
↵a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
↵a=sendrecv
↵a=rtcp-mux
↵a=rtpmap:111 opus/48000/2
↵a=rtcp-fb:111 transport-cc
↵a=fmtp:111 minptime=10;useinbandfec=1
↵a=rtpmap:103 ISAC/16000
↵a=rtpmap:104 ISAC/32000
↵a=rtpmap:9 G722/8000
↵a=rtpmap:0 PCMU/8000
↵a=rtpmap:8 PCMA/8000
↵a=rtpmap:106 CN/32000
↵a=rtpmap:105 CN/16000
↵a=rtpmap:13 CN/8000
↵a=rtpmap:110 telephone-event/48000
↵a=rtpmap:112 telephone-event/32000
↵a=rtpmap:113 telephone-event/16000
↵a=rtpmap:126 telephone-event/8000
↵a=ssrc:1750151663 cname:1/byvGa5L29O1p0M
↵a=ssrc:1750151663 msid:DNwWYI18UAwvrWMchHLFUhlrH5muayhhIZza 8efbd260-7804-4265-9a80-1d4ea72791ba
↵a=ssrc:1750151663 mslabel:DNwWYI18UAwvrWMchHLFUhlrH5muayhhIZza
↵a=ssrc:1750151663 label:8efbd260-7804-4265-9a80-1d4ea72791ba
↵m=video 64236 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 124 127 125 123
↵c=IN IP4 123.142.71.182
↵a=rtcp:9 IN IP4 0.0.0.0
↵a=candidate:6817020 1 udp 2122260223 192.168.2.174 64236 typ host generation 0 network-id 1 network-cost 10
↵a=candidate:2166358600 1 udp 1686052607 (my ip) 64236 typ srflx raddr 192.168.2.174 rport 64236 generation 0 network-id 1 network-cost 10
↵a=candidate:1324087308 1 tcp 1518280447 192.168.2.174 9 typ host tcptype active generation 0 network-id 1 network-cost 10
↵a=ice-ufrag://Om
↵a=ice-pwd:0+WMxwYGnTnRcGNwz4LjFArR
↵a=ice-options:trickle
↵a=fingerprint:sha-256 B1:28:3B:32:34:9B:69:19:38:42:AA:A9:5D:65:FD:07:37:A5:65:10:53:B0:64:CD:AB:C1:51:85:20:83:CA:26
↵a=setup:actpass
↵a=mid:video
↵a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
↵a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
↵a=extmap:4 urn:3gpp:video-orientation
↵a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
↵a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
↵a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
↵a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
↵a=sendrecv
↵a=rtcp-mux
↵a=rtcp-rsize
↵a=rtpmap:96 VP8/90000
↵a=rtcp-fb:96 ccm fir
↵a=rtcp-fb:96 nack
↵a=rtcp-fb:96 nack pli
↵a=rtcp-fb:96 goog-remb
↵a=rtcp-fb:96 transport-cc
↵a=rtpmap:97 rtx/90000
↵a=fmtp:97 apt=96
↵a=rtpmap:98 VP9/90000
↵a=rtcp-fb:98 ccm fir
↵a=rtcp-fb:98 nack
↵a=rtcp-fb:98 nack pli
↵a=rtcp-fb:98 goog-remb
↵a=rtcp-fb:98 transport-cc
↵a=rtpmap:99 rtx/90000
↵a=fmtp:99 apt=98
↵a=rtpmap:100 H264/90000
↵a=rtcp-fb:100 ccm fir
↵a=rtcp-fb:100 nack
↵a=rtcp-fb:100 nack pli
↵a=rtcp-fb:100 goog-remb
↵a=rtcp-fb:100 transport-cc
↵a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
↵a=rtpmap:101 rtx/90000
↵a=fmtp:101 apt=100
↵a=rtpmap:102 red/90000
↵a=rtpmap:124 rtx/90000
↵a=fmtp:124 apt=102
↵a=rtpmap:127 ulpfec/90000
↵a=rtpmap:125 H264/90000
↵a=rtcp-fb:125 ccm fir
↵a=rtcp-fb:125 nack
↵a=rtcp-fb:125 nack pli
↵a=rtcp-fb:125 goog-remb
↵a=rtcp-fb:125 transport-cc
↵a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=420032
↵a=rtpmap:123 rtx/90000
↵a=fmtp:123 apt=125
↵a=ssrc-group:FID 3272604184 3217491005
↵a=ssrc:3272604184 cname:1/byvGa5L29O1p0M
↵a=ssrc:3272604184 msid:DNwWYI18UAwvrWMchHLFUhlrH5muayhhIZza ef31c904-1c53-4b67-be17-32eaba926c7e
↵a=ssrc:3272604184 mslabel:DNwWYI18UAwvrWMchHLFUhlrH5muayhhIZza
↵a=ssrc:3272604184 label:ef31c904-1c53-4b67-be17-32eaba926c7e
↵a=ssrc:3217491005 cname:1/byvGa5L29O1p0M
↵a=ssrc:3217491005 msid:DNwWYI18UAwvrWMchHLFUhlrH5muayhhIZza ef31c904-1c53-4b67-be17-32eaba926c7e
↵a=ssrc:3217491005 mslabel:DNwWYI18UAwvrWMchHLFUhlrH5muayhhIZza
↵a=ssrc:3217491005 label:ef31c904-1c53-4b67-be17-32eaba926c7e
↵a=ssrc-group:FID 3960203713 986472091
↵a=ssrc:3960203713 cname:1/byvGa5L29O1p0M
↵a=ssrc:3960203713 msid:LwsspBo5HljuwWKUp8pbnZAJbLGbX15RZ24f d157984c-9e5e-47b3-9658-6d9459399bd7
↵a=ssrc:3960203713 mslabel:LwsspBo5HljuwWKUp8pbnZAJbLGbX15RZ24f
↵a=ssrc:3960203713 label:d157984c-9e5e-47b3-9658-6d9459399bd7
↵a=ssrc:986472091 cname:1/byvGa5L29O1p0M
↵a=ssrc:986472091 msid:LwsspBo5HljuwWKUp8pbnZAJbLGbX15RZ24f d157984c-9e5e-47b3-9658-6d9459399bd7
↵a=ssrc:986472091 mslabel:LwsspBo5HljuwWKUp8pbnZAJbLGbX15RZ24f
↵a=ssrc:986472091 label:d157984c-9e5e-47b3-9658-6d9459399bd7
↵"

Show second Sdp, Wms has two streamid but firefox cant receive ontrack
just firefox repleace videotrack a moment

**Comment by raja1990** [comment]
We Faced the same problem(peerconnection between chrome and firefox).Please Help Me!

**Comment by fippo** [comment]
see https://bugs.chromium.org/p/chromium/issues/detail?id=465349

Firefox will for obvious reasons not implement the deprecated "Plan B" that Chrome uses. If you really need it i'd suggest rewriting the SDP using something like https://github.com/jitsi/sdp-interop
