### ISSUE TITLE
adapter.js using require.js breaks with HTML tag id 'global'

### ISSUE THREAD

**Issue by thehunmonkgroup** [webrtcHacks/adapter#706]
**Browsers and versions affected**

Assuming all, definitely broken on Safari and Chrome.

**Description**

Using require.js, if I have, say, a div tag like so in my HTML:

```html
  <div id="global"></div>
```
Then the ```global``` variable in the main require.js callback gets interpreted as that DOM node, and not the global window object.

While it's trivial to change the ID of the HTML element, what's *not* trivial is the three hours it took me to figure out why adapter.js wasn't working properly :)

**Steps to reproduce**

Place the above-mentioned div tag in the HTML of a page that loads adapter.js, load the page, inspect the ```global``` variable in the main require callback.

**Expected results**
```global``` should be the window object.

**Actual results**
```global``` is a DOM node.

**Comment by KaptenJansson** [comment]
Could you try the adapter_no_global.js build instead?

**Comment by thehunmonkgroup** [comment]
Lots of strangeness going on. I replaced adapter_no_edge.js with adapter_no_edge_no_global.js, then with adapter_no_global.js.

With both of the _no_global variants, adapter was undefined inside my require.js callback. The 'global' div made no difference either way in this case.

Digging further into the logic at the top of the files that detects environments, I discovered that the one with the global has a very different detection logic.

Bundle with global included:

```javascript
(function(f) {
  if (typeof exports === "object" && typeof module !== "undefined") {
    module.exports = f()
  } else if (typeof define === "function" && define.amd) {
    define([], f)
  } else {
    var g;
    if (typeof window !== "undefined") {
      g = window
    } else if (typeof global !== "undefined") {
      g = global
    } else if (typeof self !== "undefined") {
      g = self
    } else {
      g = this
    }
    g.adapter = f()
  }
})
```

Bundle without global included:

```javascript
(function e(t, n, r) {
  function s(o, u) {
    if (!n[o]) {
      if (!t[o]) {
        var a = typeof require == "function" && require;
        if (!u && a) return a(o, !0);
        if (i) return i(o, !0);
        var f = new Error("Cannot find module '" + o + "'");
        throw f.code = "MODULE_NOT_FOUND", f
      }
      var l = n[o] = {
        exports: {}
      };
      t[o][0].call(l.exports, function(e) {
        var n = t[o][1][e];
        return s(n ? n : e)
      }, l, l.exports, e, t, n, r)
    }
    return n[o].exports
  }
  var i = typeof require == "function" && require;
  for (var o = 0; o < r.length; o++) s(r[o]);
  return s
})
```

The code compaction makes the logic a bit hard to reason about, but, stepping through the code in the second case listed above, it doesn't appear to properly detect a require.js environment. However, the detection logic in the global bundle does properly detect it.

I'll note that this was all tested against the latest 5.x release, but I did check the latest 6.x release, and the files seem to be structured the same way.

**Comment by fippo** [comment]
This looks like an issue in browserify. If you use require.js you probably don't want the pre-bundled (using [browserify](https://www.npmjs.com/package/browserify)) version of adapter.

**Comment by thehunmonkgroup** [comment]
I think we can probably close up this issue. It's been well documented, and the fix I mentioned at the top (don't include any HTML elements w/ an id of ```global```) is pretty straightforward.
