### ISSUE TITLE
wrapPeerConnectionEvent function prototype variable is undefined

### ISSUE THREAD

**Issue by k13elle** [webrtcHacks/adapter#707]
**Browsers and versions affected**
iOS11 Safari Webview in Cordova

**Description**
In `wrapPeerConnectionEvent` function
`proto` defining is work (it refer `RTCPeerConnection.prototype`)
`nativeAddEventListener` defining is not work, it's undefined.

**Steps to reproduce**
Use `RTCPeerConnection` function

**Expected results**
`wrapPeerConnectionEvent` function return the return of `nativeAddEventListener.apply()`.

**Actual results**
`wrapPeerConnectionEvent` not return, is catched error.

[reference issue](https://github.com/BasqueVoIPMafia/cordova-plugin-iosrtc/issues/317)

**Comment by KaptenJansson** [comment]
It's using adapter 4.0.1 according to the reference issue, closing this. Please a file a new issue if the issue persists in the latest release.
