### ISSUE TITLE
Include support for iOS cordova-plugin-iosrtc?

### ISSUE THREAD

**Issue by calebboyd** [webrtcHacks/adapter#71]
The implementation: [iosrtc](https://github.com/eface2face/cordova-plugin-iosrtc) is (afaik) following spec. the adapter is able to work by altering the UA check [here](https://github.com/webrtc/adapter/blob/master/adapter.js#L205) but that is less than ideal when the actual browser is indeed a WebView.

**Comment by alvestrand** [comment]
What platforms does the iosrtc plugin run on? (apart from IOS, which I assume..)
We should support it to the same level as we support EDGE - but we need a PR with code that detects the plugin and the browser, and it's likely not possible to run that under our unit tests....

**Comment by calebboyd** [comment]
Just iOS > 7. I'll see about submitting a PR

However, There are several issues that @ibc points out [here](https://groups.google.com/forum/?#!topic/cordova-plugin-iosrtc/_QS5oT0pJjU)...

**Comment by ibc** [comment]
adapter.js seems to be JS loaders' friendly (at the bottom of the script it does some checks for "module" and "require") but the fact is that, anyhow, it still exposes `window.RTCPeerConnection` and so on regardless the script is loaded when a JS loader is present. That is not the polite way at all but the old/legacy one in which for every JS library a separate `<script>` tag is required and a global exported to the `window` namespace (not cool in 2015).

Said that, adapter.js may still be loaded within a Cordova app + cordova-plugin-iosrtc if the whole JavaScript code uses a module loader (browserify, requireJS, etc) and the adapter.js module is loaded once Cordova's "deviceready" event is fired. But yes, it needs some work in adapter.js to detect the environment. It should be easy: just check whether `window.cordova.plugins.iosrtc` exists and, if so, call to `cordova.plugins.iosrtc.registerGlobals()` so the code running after that will find the WebRTC globals in the `window` namespace.

The problem (in Cordova) is when a library try to detect WebRTC global classes/functions at the time the JS script itself is loaded.

**Comment by ibc** [comment]
BTW this throws an error when adapter.js is loaded in Cordova + cordova-plugins-iosrtc:

``` js
 // the detected chrome version.
  webrtcDetectedVersion =
    parseInt(navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./)[2], 10);
```

Yes, the plugin exports `navigator.webkitGetUserMedia` (just if `registerGlobals()` is called), and it does it because Safari is also webkit. But it is not Chrome! and the regexp above returns `null` so calling `[2]` on it fails.

**Comment by calebboyd** [comment]
Yeah, That was my original issue. It'd be wonderful If I didn't need to maintain a fork. But providing a detection synchronously is problematic.

**Comment by ibc** [comment]
> But providing a detection synchronously is problematic.

How is your Cordova JS app code? do you use any JS loader? or do you load all the JS files with a `<script>` tag?

**Comment by calebboyd** [comment]
That statement was aimed at detecting cordova and exporting iosrtc interface via adapter.js. I have no issues in my own project. (when handling the `null` value from the user agent match, using registerGlobals()) It'd be great if there were less side-effects of loading adapter.js.

**Comment by calebboyd** [comment]
Closed via #120

**Comment by alvestrand** [comment]
Hm. We closed #95 in favor of #119 in favor of #120 - but in the process, we lost the code for checking that we had the iosrtc plugin loaded. I'd actually like to have that.

Since @calebboyd closed this issue, I'm not sure if he's happy with the situation or whether just the main problem he had was solved, and we should reopen this issue to remember to do the rest.

**Comment by calebboyd** [comment]
Ahh Yes, I suppose that may have been unclear. With the changes in #120, adapter.js will work transparently when  loaded in an environment that supports (or has been previously shimmed to support) webrtc -- the case with `window.cordova.plugins.iosrtc.registerGlobals()`. So all is well iff adapter.js is loaded after the registerGlobals is called for the plugin. The alternative mechanism is to have an adapter like @ibc [wrote](https://github.com/eface2face/rtcninja.js/blob/master/lib/Adapter.js) that requires initialization, (generally only needed for the plugin case where the api's differ, or are not available at js parse-time)

As for my happiness, I'm quite happy as I can now use adaper.js' dependents. : )
By "the rest" do you mean browser detection?

**Comment by k13elle** [comment]
I also use `adapter.js` with `cordova-iosrtc`, but I have problem in `adapter.js` file

In RTCPeerConnection wrapper function
`nativeAddEventListener` defining is not work. (line 3310) and error occured (line 3319)
