### ISSUE TITLE
DTLS handshake failed when 2 Edge clients attampt to connect each other

### ISSUE THREAD

**Issue by ghost** [webrtcHacks/adapter#711]
**Browsers and versions affected**
Browser: Edge 41 for both clients

Version: latest adapter.js (`https://webrtc.github.io/adapter/adapter-latest.js`)

**Description**
We were unable to establish connection with Edge - Edge in [a demo page of manual SDP exchange](https://mganeko.github.io/webrtcexpjp/basic2016/hand_signaling_adapter.html)  (Chrome - Chrome works fine). When it fails, a `DTLS handshake failed` message is shown in Edge console.

The cause of DTLS fail is still unknown to us. It would be great to hear your idea about these questions:

- Is it more likely an issue of that page, or adapter.js?
- What can possibly cause DTLS handshake to fail in edge?

Our issue is similar to #306, but we are using latest adapter.js including fix in that issue.

**Steps to reproduce**
1. Open [this page](https://mganeko.github.io/webrtcexpjp/basic2016/hand_signaling_adapter.html) with 2 Edge (A and B) windows running on same PC.
2. In both A and B, click "start media"
3. In A, click "connect".
4. Copy from "SDP to send" in A to "SDP to receive" in B, and click "Receive remote SDP" in B.
5. Copy from "SDP to send" in B to "SDP to receive" in A, and click "Receive remote SDP" in A.

**Expected results**
Connect get established, A and B can see video stream from the other.

**Actual results**
No stream is displayed. The following error is shown in console:

    ORTC18615: ORTC RTCDtlsTransport: DTLS handshake failed. hr=c004e00f

**Comment by KaptenJansson** [comment]
Does any other demo page work? Not sure if our samples like https://webrtc.github.io/samples/src/content/peerconnection/pc1/ works on Edge.

**Comment by LionelCapiez** [comment]
FWIW: This sample does work for me with Edge 41.

**Comment by ghost** [comment]
I'd like to know how to solve DTLS handshake problem.
Not only the page I presented, my product has same promlem.

I don’t know which of this page or adaptor.js cause DTLS handshake to fail.

**Comment by fippo** [comment]
do those failures happen on the local network?
Do ICE candidates get exchanged and can you see STUN messages going back and forth when using Wireshark?
Are there any DTLS packets showing up in Wireshark?

**Comment by lgrahl** [comment]
I can imagine this being a DTLS role conflict where both sides think they take the server role. A pcap trace would help.
