### ISSUE TITLE
Chrome will be identified as Safari if webkitGetUserMedia and/or webkitRTCPeerConnection are removed

### ISSUE THREAD

**Issue by foolip** [webrtcHacks/adapter#712]
The problematic code is here:
https://github.com/webrtc/adapter/blob/2f9ba8c9125cc6e79eaa416c177a60ce213d0a7c/src/js/utils.js#L99

By two different fallback paths, if either or both are removed, Chrome would be identified as Safari, and that will likely have some other consequences.

These are the Chromium issues for removing these aliases:
https://bugs.chromium.org/p/chromium/issues/detail?id=690582
https://bugs.chromium.org/p/chromium/issues/detail?id=692736

When I looked into this a month or so ago, I gave up as soon as I noticed this pattern in adapter.js.

What would need to happen is that either detectBrowser is removed entirely so that nothing anywhere assumes that the combination of certain APIs implies that it's any particular browser. This is likely difficult, if feature detection worked for everything then presumably this mechanism wouldn't be there.

Once fixed, does anyone have an idea of the half-life of adapter.js in the wild? How many years would one have to wait until usage of current versions has dropped to 1% of the current usage, for example?

**Comment by fippo** [comment]
What is the alternative? (granted, Safari did not ship with webkitRTCPeerConnection; note that Edge does)

UA sniffing (and anything based on it is even worse, see [here](https://github.com/ESTOS/strophe.jingle/issues/51). Using something like [platform](https://www.npmjs.com/package/platform) would pretend opera is different from Chrome which it isn't as far as webrtc is concerned.

The number of ugly hacks required outside adapter that deal with browser-specific behaviour (or working around bugs in specific versions) is huge. I've built that around the version detection in adapter.

Exposing the implementation on RTCPeerConnection would be a solution (see [here](https://lists.w3.org/Archives/Public/public-webrtc/2016Dec/0006.html)) but probably has very nasty privacy implications for people who change the UA.

> Once fixed, does anyone have an idea of the half-life of adapter.js in the wild? How many years would one have to wait until usage of current versions has dropped to 1% of the current usage, for example?

I wonder if NPM allows splitting the download statistics by package version.

**Comment by benbro** [comment]
Edge is [pretending](https://msdn.microsoft.com/en-us/library/hh869301(v=vs.85).aspx) to be Chrome.
Safari [stopped changing](https://developer.apple.com/safari/technology-preview/release-notes/) the UA for minor version.
Feature detection is probably better.

**Comment by KaptenJansson** [comment]
@foolip anything to add here or can we close this?

**Comment by fippo** [comment]
we still need to get rid of webkitGetUserMedia

**Comment by foolip** [comment]
Yep. I can file a new issue though to make it less confusing.

**Comment by foolip** [comment]
Filed https://github.com/webrtc/adapter/issues/764.
