### ISSUE TITLE
Support for WKWebView? 

### ISSUE THREAD

**Issue by pdxwebdev** [webrtcHacks/adapter#720]
**Browsers and versions affected**
WKWebView on ios 11

**Description**
I see that ios Safari 11 is now supported but I have an ionic app that I believe uses WKWebView. So I am still unable to get getUserMedia which also causes PeerJS to fail. I'm not super savvy in this area but I'm wondering if there is currently support, a workaround, or plans to support WKWebView. 

**Steps to reproduce**
Open inspector on ionic app. Trying to find getUserMedia on navigator. 

**Expected results**
See getUserMedia

**Actual results**
getUserMedia is not a member of navigation.

**Comment by fippo** [comment]
getUserMedia is not supported in WKWebView right now: https://bugs.chromium.org/p/chromium/issues/detail?id=783220

**Comment by agouaillard** [comment]
While safari just added support to it, Apple gives usually one release (one year) before releasing the corresponding framework. Do not expect the web view framework to support webrtc before fall next year.

**Comment by KaptenJansson** [comment]
Closing this since this will take a while to land in WKWebView....

**Comment by zaxy78** [comment]
Done and added on #783 
getUserMedia isn't supported yet. BUT - all else works :)
