### ISSUE TITLE
RTCPeerConnection.prototype.addStream throwing "Unspecified error."

### ISSUE THREAD

**Issue by justinIs** [webrtcHacks/adapter#725]
**Browsers and versions affected**
Microsoft Edge 41.16299.15.0

**Description**
When trying to add an audio stream to an RTCPeerConnection by calling RTCPeerConnection.addStream, it eventually calls  RTCPeerConnection.prototype._createIceAndDtlsTranspor, which causes the exception. 
Specifically on line:
var dtlsTransport = new window.RTCDtlsTransport(iceTransport);
which looks like native code.

**Steps to reproduce**
Create an RTCPeerConnection and try to add an audio stream

**Expected results**
RTCPeerConnection should successfully add the stream

**Actual results**
RTCPeerConnection fails when adding the stream and throws the following error:
"Unspecified error."

Not sure how to debug this.

**Comment by fippo** [comment]
do you have a fiddle that reproduces this? What is iceTransport before the error happens?

**Comment by justinIs** [comment]
iceTransport seems to have been created successfully:
```

iceTransport




[object RTCIceTransport]: {component: "RTP", iceGatherer: null, oncandidatepairchange: null, onicestatechange: function () { self._updateConnectionState(); }, role: "unknownRole"...}
component: "RTP"
iceGatherer: null
oncandidatepairchange: null

onicestatechange: function () { self._updateConnectionState(); }
role: "unknownRole"
state: "new"
```

I'll get a fiddle up asap

**Comment by justinIs** [comment]
https://jsfiddle.net/tx65wv5q/1/

Just click run, you should see the exception in your console

**Comment by justinIs** [comment]
Any luck in getting it to reproduce?

While doing more testing, we signed in with a different user on the same computer and there were no errors.

**Comment by fippo** [comment]
works as expected when I tested on browserstack. The only thing I can thing of is having ice candidate restrictions on which is hidden *somewhere* in the Edge settings.

**Comment by KaptenJansson** [comment]
@justinIs can we close this?
