### ISSUE TITLE
ERROR_CONTENT in SDP Android to iOS

### ISSUE THREAD

**Issue by yogaboy** [webrtcHacks/adapter#727]
**Browsers and versions affected**
Samsung S8 with Android 7.0 with Chrome 62.0.3202.84
iOS 11.2 beta 4 under Safari (iPad mini)

**Description**
Unable to set remote description between these two. I suspect a codec problem, but don't know if the SDP is being modiified by adapter.js

I've put in a bug report already with Chromium as I think it's still likely their issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=749013

**Steps to reproduce**
Connect a session with these two devices (local loop is okay)

**Expected results**
Connection established and flowing

**Actual results**
"OperationError: Failed to set remote offer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set remote video description send parameters.."

SDP:

v=0
o=- 2792111575520691438 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS LopLZ9fYBttbr1htxE7TSNe91fIcBdGnZqEM
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 9 0 8 105 13 110 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:Y5EM
a=ice-pwd:2Gjy25MP1l5ZK3UhT7paYq8Z
a=ice-options:trickle
a=fingerprint:sha-256 6B:E0:F5:5D:7D:8F:67:D8:D2:45:15:9C:85:0C:D7:97:10:39:4C:4F:C7:96:0A:7B:3B:60:41:23:72:E3:78:04
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:432575685 cname:75ZBlhQrw+If2vHJ
a=ssrc:432575685 msid:LopLZ9fYBttbr1htxE7TSNe91fIcBdGnZqEM c9dd542f-5118-46d5-819a-41a305a26602
a=ssrc:432575685 mslabel:LopLZ9fYBttbr1htxE7TSNe91fIcBdGnZqEM
a=ssrc:432575685 label:c9dd542f-5118-46d5-819a-41a305a26602
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 127 104
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:Y5EM
a=ice-pwd:2Gjy25MP1l5ZK3UhT7paYq8Z
a=ice-options:trickle
a=fingerprint:sha-256 6B:E0:F5:5D:7D:8F:67:D8:D2:45:15:9C:85:0C:D7:97:10:39:4C:4F:C7:96:0A:7B:3B:60:41:23:72:E3:78:04
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 red/90000
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:102 ulpfec/90000
a=rtpmap:127 H264/90000
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:104 rtx/90000
a=fmtp:104 apt=127
a=ssrc-group:FID 3175622802 2713831672
a=ssrc:3175622802 cname:75ZBlhQrw+If2vHJ
a=ssrc:3175622802 msid:LopLZ9fYBttbr1htxE7TSNe91fIcBdGnZqEM 9dde4b53-387b-425e-b9b0-28bb7edebe31
a=ssrc:3175622802 mslabel:LopLZ9fYBttbr1htxE7TSNe91fIcBdGnZqEM
a=ssrc:3175622802 label:9dde4b53-387b-425e-b9b0-28bb7edebe31
a=ssrc:2713831672 cname:75ZBlhQrw+If2vHJ
a=ssrc:2713831672 msid:LopLZ9fYBttbr1htxE7TSNe91fIcBdGnZqEM 9dde4b53-387b-425e-b9b0-28bb7edebe31
a=ssrc:2713831672 mslabel:LopLZ9fYBttbr1htxE7TSNe91fIcBdGnZqEM
a=ssrc:2713831672 label:9dde4b53-387b-425e-b9b0-28bb7edebe31

**Comment by Jagdeep-Sing** [comment]
you found any solution?

**Comment by fippo** [comment]
see https://bugs.chromium.org/p/webrtc/issues/detail?id=8584 -- adapter doesn't munge the SDP so there is nothing to be done here.
