### ISSUE TITLE
No op add/removeEventListener methods

### ISSUE THREAD

**Issue by KaptenJansson** [webrtcHacks/adapter#73]
Currently Chrome unstable (45) has the `navigator.medaDevices` object but without `addEventListener` and `removeEventListener` methods.

This causes two [tests](https://travis-ci.org/webrtc/adapter/jobs/70575016) to fail because we conditionally add `addEventListener` and `removeEventListener`functions to `navigator.medaDevices` only if `!navigator.mediaDevices`.

@jan-ivar, @alvestrand, @fippo this was added in #45 to prevent some crash. Should we add something like this:

```
if (typeof navigator.mediaDevices.removeEventListener === 'undefined' ||
      typeof navigator.mediaDevices.addEventListener === 'undefined') {
    // in case someone wants to listen for the devicechange event.
    navigator.mediaDevices.addEventListener = function() { };
    navigator.mediaDevices.removeEventListener = function() { };
```

  }

to make the tests pass on Chrome unstable?

**Comment by fippo** [comment]
LGTM, but can't we just get that fixed before the 45 release? :-)

**Comment by alvestrand** [comment]
As a matter of style: I think we should add each dummy function in its own condition.
As a matter of substance: we haven't implemented the devicechange event. The only purpose of the dummy function is to make the tests pass. Should the dummy functions log "OK, but this will achieve nothing" or something silly like that?

**Comment by fippo** [comment]
https://github.com/MicrosoftEdge/Demos/blob/master/photocapture/scripts/demo.js#L181 is actually using this -- but I forgot to make a PR to that demo to make it use adapter :-/

**Comment by alvestrand** [comment]
45 has already been cut, I think - either that or we cut on Friday. ondevicechange won't make it.

**Comment by jan-ivar** [comment]
wfm
