### ISSUE TITLE
No graceful degradation if webRTC is disabled on browser level

### ISSUE THREAD

**Issue by gregor** [webrtcHacks/adapter#730]
**Browsers and versions affected**
Firefox 57 with `media.peerconnection.enabled` set to `false`
(Mozilla/5.0 (Windows NT 6.1; rv:57.0) Gecko/20100101 Firefox/57.0)

**Description**
We use adapter.js shim in [Wire for web](https://github.com/wireapp/wire-webapp). This issue had previously been addressed in #260 but is now reoccuring.

A user disabled webRTC manually in his Firefox browser config by setting  `media.peerconnection.enabled` to `false`. As you currently expect webRTC capabilities solely based on browser and version detection, adapter.js thows an error. The script execution of stops and our page no longer properly loads.

https://github.com/wireapp/wire-webapp/issues/1915

**Steps to reproduce**
1.  manually disable webRTC in Firefox browser settings
2. go to https://app.wire.com and try to log in

**Expected results**
adapter.js should smoothly degrade and recognize the missing APIs

**Actual results**
RTCPeerConnection is undefined

Loading of adapter.js fails and thus subsequent vendor files in our minified version are not instantiated.

**Comment by fippo** [comment]
this broke recently -- #731 fixes it.

**Comment by gregor** [comment]
Thanks for the quick reply and taking care of it.
