### ISSUE TITLE
addTrack and dtmf

### ISSUE THREAD

**Issue by henbos** [webrtcHacks/adapter#733]
Chrome currently has support for:
- Legacy: addStream
- Legacy: createDTMFSender
Which work together.

Chrome is also shipping (M64):
- Spec: addTrack
Which does not work together with createDTMFSender.

But does not have support for:
- Spec: RTCRtpSender.dtmf

When using addTrack, adapter.js's shim of RTCRtpSender.dtmf does not work because native addTrack does not work together with native createDTMFSender.

Two paths forward to resolve this issue:
- Anyone who wants to use DTMF has to rely on addStream for it to work.
- adapter.js keeps shimming addTrack for another version, meaning addTrack is built on top of addStream and RTCRtpSender.dtmf will work like before.

**Comment by henbos** [comment]
What do you think is the preferred way forward, @KaptenJansson and @fippo ? Do we keep shimming addTrack so that dtmf doesn't break or do we update failing examples - like https://webrtc.github.io/samples/src/content/peerconnection/dtmf/ fails on Canary - to use addStream instead of addTrack?

**Comment by fippo** [comment]
I would rather not delay testing of the native addTrack by adapter (who spot + report issues) users for the sake of DTMF

**Comment by henbos** [comment]
The https://webrtc.github.io/samples/src/content/peerconnection/dtmf/ is fixed by https://github.com/webrtc/samples/pull/972.

Let's keep this issue open until addTrack and dtmf works, which likely means removing shimming when properly supported by Chrome.
Also check Firefox status...

**Comment by KaptenJansson** [comment]
What's the latest here @henbos ?

**Comment by henbos** [comment]
I'm working on https://crbug.com/803021 which will also fix the createDTMFSender bug https://crbug.com/806875. Expect this to be resolved in Chrome M66.

**Comment by fippo** [comment]
this just made it to beta in the expectations. But you know what is great: IT MEANS THE FLAKY TEST JUST FAILS ALL THE TIME 😂

**Comment by henbos** [comment]
Chrome has fixed addTrack+dtmf in M66, closing issue.
