### ISSUE TITLE
Cannot assign to read only property  'RTCPeerConnection'

### ISSUE THREAD

**Issue by ostap0207** [webrtcHacks/adapter#738]
**Browsers and versions affected**
Mozilla/5.0 (iPad; CPU OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H143 Safari/600.1.4

**Description**
Shim fails with the following error:
```
Cannot assign to read only property 'RTCPeerConnection' of [object global]:
TypeError: Cannot assign to read only property 'RTCPeerConnection' of [object global]:
Object.o.shimPeerConnection
```

Looks like the browser type was incorrectly detected and the wrong shim was applied

**Comment by fippo** [comment]
what browser is that? iOS before iOS 11 doesn't support WebRTC so i wonder into what path it goes.

**Comment by ostap0207** [comment]
UA (also in the description): Mozilla/5.0 (iPad; CPU OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H143 Safari/600.1.4
That's all I can say based on our logs.

**Comment by ostap0207** [comment]
Based on our stacktrace it uses shim for chrome.

**Comment by fippo** [comment]
according to [platform](https://www.npmjs.com/package/platform) that is safari. And
```
> platform.parse("Mozilla/5.0 (iPad; CPU OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H143 Safari/600.1.4")
{ description: 'Safari 8.0 on Apple iPad (iOS 8.4)',
  layout: 'WebKit',
  manufacturer: 'Apple',
  name: 'Safari',
  prerelease: null,
  product: 'iPad',
  ua: 'Mozilla/5.0 (iPad; CPU OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H143 Safari/600.1.4',
  version: '8.0',
  os: 
   { architecture: 32,
     family: 'iOS',
     version: '8.4',
     toString: [Function: toString] },
  parse: [Function: parse],
  toString: [Function: toStringPlatform] }
```
the chrome shim should be guarded by checks for navigator.webkitGetUserMedia which should not exist in that version...

**Comment by ostap0207** [comment]
Yes, that's how it supposed to work, but we still somehow got this error. Makes me think if it possible that `navigator.webkitGetUserMedia` is defined in safari in some cases or overridden.
https://github.com/webrtc/adapter/pull/722 seem fix this error though.
