### ISSUE TITLE
setLocalDescription cost too much time

### ISSUE THREAD

**Issue by 493326889** [webrtcHacks/adapter#744]
**Browsers and versions affected**

 
![image](https://user-images.githubusercontent.com/3177587/34669369-46363b18-f4ac-11e7-82e0-8962633839ae.png)

**Description**
we found that in some user`s browser , create offer and setDescription will cost more than 3s. so i add some log in code and found that the time cost in setlocaldescription this function.

**Steps to reproduce**

**Expected results**

**Actual results**

**Comment by KaptenJansson** [comment]
This is most likely an issue in the browser or even the users machine (overloaded/low performance). I would file a bug in the appropriate browser bug tracker with relevant info like hardware specs, browsers and OS version along with the reproductions steps. If you have code example/demo app (e.g. jsfiddle), please include it as well.

**Comment by 493326889** [comment]
![image](https://user-images.githubusercontent.com/3177587/34670011-6ff93a38-f4af-11e7-9400-cbfad1dd33d0.png)
@KaptenJansson  code below
the ua  
Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by 493326889** [comment]
and if it was user`s machine (overloaded/low performance) , why createOffer time was less then setLocalDescription.

**Comment by KaptenJansson** [comment]
First of all, you are using Chrome 55, that's ancient, unsupported and should not be used anymore.

Second, please put the code in a jsfiddle or something like that, screenshots of random code is hard to do anything with especially with some many pieces of code defined in other places, for all we know, it could be those pieces that take time. You can always use chrome://tracing to figure out what specifically is taking so long.
