### ISSUE TITLE
Prebuild releases in NPM are not full or have wrong dependencies' location path

### ISSUE THREAD

**Issue by kalitine** [webrtcHacks/adapter#750]
**Browsers and versions affected**
All browsers.
Webrtc-adapter: v6.1.0

**Description**
There are 4 prebuild releases in NPM repository. In each of them there are several calls of `require` function. For instance:
```javascript
// In out/adpater_no_edge_no_global.js
// ...
var adapterFactory = require('./adapter_factory.js');
// ...
var utils = require('./utils');
// ...
```
The location of those dependencies is wrong, as all prebuilds are located inside `out` folder.

**Steps to reproduce**

**Expected results**
Better to have no calls of `require` function in prebuilds, as by definition they are already built. Or less desirable solution would be to fix the relative path of dependencies at least.

**Actual results**
There are several calls of `require` function in each prebuild .js file inside `out` folder and the relative path of required dependencies is wrong.

**Comment by fippo** [comment]
this is stock browserify behaviour. Are you using the generated file with something like requirejs? That isn't going to work.

**Comment by kalitine** [comment]
The problem comes when I run tests with Karma. The code is in TypeScript and I use `karma-typescript` plugin to parse files before serving to browser. This plugin parses also the `adapter_no_edge_no_global.js` file for dependencies. However I have found a solution:

```javascript
// in karma.conf.js
// ...
bundlerOptions: {
  noParse: ['webrtc-adapter/out/adapter_no_edge_no_global.js']
},
// ...
```
I use RollupJS for build, but, I guess thanks to the tree-shaking, the calls to `require` function are removed. I think It is still maybe useful to remove these calls from build to prevent such problems, but it is ok like this too.

**Comment by KaptenJansson** [comment]
Please provide a PR with your proposed solution and we can take a look.
