### ISSUE TITLE
Ability to generate SDP without encryption enabled

### ISSUE THREAD

**Issue by pjosep** [webrtcHacks/adapter#752]
**Browsers and versions affected**
Microsoft Edge 41.16299.15.0
Microsoft EdgeHTML 16.16299

**Description**
Need the ability to generate an SDP without encryption (i.e.,  RTP/AVPF instead of UDP/TLS/RTP/SAVPF).

**Steps to reproduce**
1. Create a PC
2. Add stream
3. Create Offer

**Expected results**
An offer that contains RTP/AVPF in the m= line

**Actual results**
An offer that contains UDP/TLS/RTP/SAVPF in the m= line

**Comment by fippo** [comment]
Encryption is mandatory in WebRTC and Edge's ORTC implementation doesn't allow unencrypted RTP either. If you have such a requirement a gateway like [janus](https://github.com/meetecho/janus-gateway/) might be required.
