### ISSUE TITLE
webrtc-adapter issue

### ISSUE THREAD

**Issue by kknaidumca** [webrtcHacks/adapter#753]
After using adapter.js RTCPeerconnection,getusermedia and RTCicecandidate in firefox 52.0.2  the video stream is getting freezed. Please help to resolve this.
The video streaming has to work without freezing
The video streaming gets freezed in firefox browser

**Comment by fippo** [comment]
https://webrtc.github.io/samples/src/content/getusermedia/gum/ works fine in Firefox 52. As mentioned on [discuss-webrtc](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/discuss-webrtc/r6ynuaN_7wY/9xO5v3J0BgAJ), providing a (not) working sample helps a lot.

**Comment by kknaidumca** [comment]
Localstream working but remote stream gets freezed

**Comment by fippo** [comment]
does this happen on https://webrtc.github.io/samples/src/content/peerconnection/pc1/ as well?

**Comment by kknaidumca** [comment]
If i use navigator.mediaDevices.getUserMedia in firefox I get this 
 ::  getUserMedia   
Returned stream  Promise { <state>: "pending" } 
App :: Media devices Array [ MediaDeviceInfo, MediaDeviceInfo, MediaDeviceInfo, MediaDeviceInfo ]
And the stream does not return

In Chrome  I get this error
Uncaught TypeError: Cannot redefine property: ontrack
    at Function.defineProperty (<anonymous>)
    at Object.wrapPeerConnectionEvent (adapter-latest.js:4649)
    at Object.shimOnTrack (adapter-latest.js:2556)
    at module.exports (adapter-latest.js:2397)
    at Object.<anonymous> (adapter-latest.js:2321)
    at Object.3../adapter_factory.js (adapter-latest.js:2323)
    at s (adapter-latest.js:1)
    at e (adapter-latest.js:1)
    at adapter-latest.js:1
    at adapter-latest.js:1


So I am using navigator.getUserMedia

**Comment by kknaidumca** [comment]
With navigator.getUserMedia the remotestreaming gets freezed in firefox

**Comment by KaptenJansson** [comment]
Could you show your code in a jsfilddle?

**Comment by kknaidumca** [comment]
Now navigator.mediaDevices.getUsermedia is working for both chrome and firefox, but still the video freezes. I am using pc.addstream(localstream); and pc.ontrack for remotestream display (addtrack is not working) 

Local SDP
v=0
o=mozilla...THIS_IS_SDPARTA-52.0.2 4112845583769853904 2 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 27:21:04:49:DB:0E:DD:D0:66:CA:84:0A:96:30:50:C9:E8:B7:4E:CF:D4:5B:DB:3D:14:53:11:37:06:BC:C7:54
a=group:BUNDLE audio-3186563720 video-2544741406 data audio-3603558324 video-957478833
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 29522 RTP/SAVPF 111 126
c=IN IP4 122.171.70.234
a=candidate:0 1 UDP 2122252543 10.0.0.20 52510 typ host
a=candidate:2 1 UDP 1686052607 122.171.70.234 29522 typ srflx raddr 10.0.0.20 rport 52510
a=sendrecv
a=end-of-candidates
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=fmtp:111 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=fmtp:126 0-15
a=ice-pwd:d5864271dbd35960fc800a1c7d44a3af
a=ice-ufrag:d65e4eb0
a=mid:audio-3186563720
a=msid:{047226c9-7242-4942-a36d-a2cac40bc44c} {a926fa61-7151-47e8-abd3-303f7582e8f1}
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtpmap:126 telephone-event/8000
a=setup:active
a=ssrc:1039352033 cname:{5c9d7c63-39e5-4d5a-afa5-8540c987041e}
m=video 29522 RTP/SAVPF 100
c=IN IP4 122.171.70.234
a=sendrecv
a=fmtp:100 max-fs=12288;max-fr=60
a=ice-pwd:d5864271dbd35960fc800a1c7d44a3af
a=ice-ufrag:d65e4eb0
a=mid:video-2544741406
a=msid:{047226c9-7242-4942-a36d-a2cac40bc44c} {02a67789-1120-4067-94b2-4bd0ba906dc6}
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 goog-remb
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=setup:active
a=ssrc:1304109494 cname:{5c9d7c63-39e5-4d5a-afa5-8540c987041e}
m=application 29522 DTLS/SCTP 5000
c=IN IP4 122.171.70.234
a=sendrecv
a=ice-pwd:d5864271dbd35960fc800a1c7d44a3af
a=ice-ufrag:d65e4eb0
a=mid:data
a=rtcp-mux
a=sctpmap:5000 webrtc-datachannel 256
a=setup:active
a=ssrc:3593254187 cname:{5c9d7c63-39e5-4d5a-afa5-8540c987041e}
m=audio 29522 RTP/SAVPF 111 126
c=IN IP4 122.171.70.234
a=recvonly
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=fmtp:111 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=fmtp:126 0-15
a=ice-pwd:d5864271dbd35960fc800a1c7d44a3af
a=ice-ufrag:d65e4eb0
a=mid:audio-3603558324
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtpmap:126 telephone-event/8000
a=setup:active
a=ssrc:3788970438 cname:{5c9d7c63-39e5-4d5a-afa5-8540c987041e}
m=video 29522 RTP/SAVPF 100
c=IN IP4 122.171.70.234
a=recvonly
a=fmtp:100 max-fs=12288;max-fr=60
a=ice-pwd:d5864271dbd35960fc800a1c7d44a3af
a=ice-ufrag:d65e4eb0
a=mid:video-957478833
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 goog-remb
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=setup:active
a=ssrc:3982046599 cname:{5c9d7c63-39e5-4d5a-afa5-8540c987041e}
Remote SDP
v=0
o=- 1923518516 2 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=group:BUNDLE audio-3186563720 video-2544741406 data audio-3603558324 video-957478833
a=msid-semantic:WMS *
m=audio 1 RTP/SAVPF 111 103 104 126
c=IN IP4 0.0.0.0
a=candidate:1 1 tcp 2130706431 2001:558:fc18:2:f816:3eff:feb6:53f8 4443 typ host tcptype passive generation 0
a=candidate:2 1 tcp 2130706431 96.118.248.46 4443 typ host tcptype passive generation 0
a=candidate:3 1 udp 2113939711 2001:558:fc18:2:f816:3eff:feb6:53f8 10000 typ host generation 0
a=candidate:4 1 udp 2113932031 96.118.248.46 10000 typ host generation 0
a=sendrecv
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=fingerprint:sha-1 62:FE:A8:3B:67:CC:EA:CC:B2:0A:7E:6B:FE:8A:0D:6C:49:7D:E6:11
a=ice-pwd:5esigo2sfsqi808g6ca545d84n
a=ice-ufrag:b6ke11c55h6v12
a=mid:audio-3186563720
a=msid:mixedmslabel mixedlabelaudio0
a=rtcp:1 IN IP4 0.0.0.0
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtpmap:103 ISAC/16000/1
a=rtpmap:104 ISAC/32000/1
a=rtpmap:126 telephone-event/8000
a=setup:actpass
a=ssrc:3186563720 cname:mixed
a=ssrc:3186563720 label:mixedlabelaudio0
a=ssrc:3186563720 mslabel:mixedmslabel
m=video 1 RTP/SAVPF 100 107 101
c=IN IP4 0.0.0.0
a=candidate:1 1 tcp 2130706431 2001:558:fc18:2:f816:3eff:feb6:53f8 4443 typ host tcptype passive generation 0
a=candidate:2 1 tcp 2130706431 96.118.248.46 4443 typ host tcptype passive generation 0
a=candidate:3 1 udp 2113939711 2001:558:fc18:2:f816:3eff:feb6:53f8 10000 typ host generation 0
a=candidate:4 1 udp 2113932031 96.118.248.46 10000 typ host generation 0
a=sendrecv
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=fingerprint:sha-1 62:FE:A8:3B:67:CC:EA:CC:B2:0A:7E:6B:FE:8A:0D:6C:49:7D:E6:11
a=ice-pwd:5esigo2sfsqi808g6ca545d84n
a=ice-ufrag:b6ke11c55h6v12
a=mid:video-2544741406
a=msid:mixedmslabel mixedlabelvideo0
a=rtcp:1 IN IP4 0.0.0.0
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtcp-fb:107 ccm fir
a=rtcp-fb:107 nack
a=rtcp-fb:107 nack pli
a=rtcp-fb:107 goog-remb
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 goog-remb
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=rtpmap:107 H264/90000
a=rtpmap:101 VP9/90000
a=setup:actpass
a=ssrc:2544741406 cname:mixed
a=ssrc:2544741406 label:mixedlabelvideo0
a=ssrc:2544741406 mslabel:mixedmslabel
a=ssrc:3771885077 cname:75289d8d-e5fd-4429-a9b7-705c5f12168f
m=application 1 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=candidate:1 1 tcp 2130706431 2001:558:fc18:2:f816:3eff:feb6:53f8 4443 typ host tcptype passive generation 0
a=candidate:2 1 tcp 2130706431 96.118.248.46 4443 typ host tcptype passive generation 0
a=candidate:3 1 udp 2113939711 2001:558:fc18:2:f816:3eff:feb6:53f8 10000 typ host generation 0
a=candidate:4 1 udp 2113932031 96.118.248.46 10000 typ host generation 0
a=sendrecv
a=fingerprint:sha-1 62:FE:A8:3B:67:CC:EA:CC:B2:0A:7E:6B:FE:8A:0D:6C:49:7D:E6:11
a=ice-pwd:5esigo2sfsqi808g6ca545d84n
a=ice-ufrag:b6ke11c55h6v12
a=mid:data
a=rtcp-mux
a=sctpmap:5000 webrtc-datachannel 1024
a=setup:actpass
m=audio 1 RTP/SAVPF 111 103 104 126
c=IN IP4 0.0.0.0
a=candidate:1 1 tcp 2130706431 2001:558:fc18:2:f816:3eff:feb6:53f8 4443 typ host tcptype passive generation 0
a=candidate:2 1 tcp 2130706431 96.118.248.46 4443 typ host tcptype passive generation 0
a=candidate:3 1 udp 2113939711 2001:558:fc18:2:f816:3eff:feb6:53f8 10000 typ host generation 0
a=candidate:4 1 udp 2113932031 96.118.248.46 10000 typ host generation 0
a=sendrecv
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=fingerprint:sha-1 62:FE:A8:3B:67:CC:EA:CC:B2:0A:7E:6B:FE:8A:0D:6C:49:7D:E6:11
a=ice-pwd:5esigo2sfsqi808g6ca545d84n
a=ice-ufrag:b6ke11c55h6v12
a=mid:audio-3603558324
a=msid:8ca302f8-1d56-4964-9896-272b4fdc0325 7ec6a491-bbde-4ae6-896e-797b44104fc2
a=rtcp:1 IN IP4 0.0.0.0
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtpmap:103 ISAC/16000/1
a=rtpmap:104 ISAC/32000/1
a=rtpmap:126 telephone-event/8000
a=setup:actpass
a=ssrc:3603558324 cname:75289d8d-e5fd-4429-a9b7-705c5f12168f
m=video 1 RTP/SAVPF 100 107 101
c=IN IP4 0.0.0.0
a=candidate:1 1 tcp 2130706431 2001:558:fc18:2:f816:3eff:feb6:53f8 4443 typ host tcptype passive generation 0
a=candidate:2 1 tcp 2130706431 96.118.248.46 4443 typ host tcptype passive generation 0
a=candidate:3 1 udp 2113939711 2001:558:fc18:2:f816:3eff:feb6:53f8 10000 typ host generation 0
a=candidate:4 1 udp 2113932031 96.118.248.46 10000 typ host generation 0
a=sendrecv
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=fingerprint:sha-1 62:FE:A8:3B:67:CC:EA:CC:B2:0A:7E:6B:FE:8A:0D:6C:49:7D:E6:11
a=ice-pwd:5esigo2sfsqi808g6ca545d84n
a=ice-ufrag:b6ke11c55h6v12
a=mid:video-957478833
a=msid:8ca302f8-1d56-4964-9896-272b4fdc0325 7362e26c-c28d-432a-b3ea-1430663f607a
a=rtcp:1 IN IP4 0.0.0.0
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtcp-fb:107 ccm fir
a=rtcp-fb:107 nack
a=rtcp-fb:107 nack pli
a=rtcp-fb:107 goog-remb
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 goog-remb
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=rtpmap:107 H264/90000
a=rtpmap:101 VP9/90000
a=setup:actpass
a=ssrc:957478833 cname:75289d8d-e5fd-4429-a9b7-705c5f12168f
RTP Stats
outbound_rtcp_video_1
Local: 12:56:50 GMT+0530 (IST) inboundrtp SSRC: 1304109494 Received: 23159 packets (21779.41 Kb) Lost: 3353 Jitter: 30.048 RTT: 1 ms

outbound_rtcp_audio_0
Local: 12:56:42 GMT+0530 (IST) inboundrtp SSRC: 1039352033 Received: 21908 packets (1647.38 Kb) Lost: 6742 Jitter: 1.039 RTT: 1 ms

inbound_rtp_audio_0
Local: 12:56:50 GMT+0530 (IST) inboundrtp SSRC: 0

inbound_rtp_video_1
Local: 12:56:50 GMT+0530 (IST) inboundrtp SSRC: 0

inbound_rtp_video_4
Decoder: Avg. bitrate: 0.15 Mbps (0.15 SD) Avg. framerate: 5.81 fps (7.10 SD)

Local: 12:56:50 GMT+0530 (IST) inboundrtp SSRC: 957478833 Received: 11606 packets (10850.75 Kb) Lost: 3560 Jitter: 2.868

Remote: 12:56:49 GMT+0530 (IST) outboundrtp SSRC: 957478833 Sent: 19433 packets (18316.72 Kb)

inbound_rtp_audio_3
A/V sync: -1405 ms Jitter-buffer delay: 35 ms

Local: 12:56:50 GMT+0530 (IST) inboundrtp SSRC: 3603558324 Received: 17406 packets (1975.25 Kb) Lost: 0 Jitter: 0.012

Remote: 12:56:27 GMT+0530 (IST) outboundrtp SSRC: 3603558324 Sent: 27996 packets (2125.37 Kb)

outbound_rtp_video_1
Encoder: Avg. bitrate: 0.29 Mbps (0.12 SD) Avg. framerate: 12.95 fps (3.44 SD) Dropped frames: 2800119

Local: 12:56:50 GMT+0530 (IST) outboundrtp SSRC: 1304109494 Sent: 26652 packets (25622.79 Kb)

Remote: 12:56:50 GMT+0530 (IST) inboundrtp SSRC: 1304109494 Received: 23159 packets (21779.41 Kb) Lost: 3353 Jitter: 30.048 RTT: 1 ms

outbound_rtp_audio_0
Local: 12:56:50 GMT+0530 (IST) outboundrtp SSRC: 1039352033 Sent: 29243 packets (3072.56 Kb)

Remote: 12:56:42 GMT+0530 (IST) inboundrtp SSRC: 1039352033 Received: 21908 packets (1647.38 Kb) Lost: 6742 Jitter: 1.039 RTT: 1 ms

inbound_rtcp_video_4
Local: 12:56:49 GMT+0530 (IST) outboundrtp SSRC: 957478833 Sent: 19433 packets (18316.72 Kb)

inbound_rtcp_audio_3
Local: 12:56:27 GMT+0530 (IST) outboundrtp SSRC: 3603558324 Sent: 27996 packets (2125.37 Kb)

**Comment by KaptenJansson** [comment]
I repeat my last comment, could you show your code in a jsfiddle? Does appr.tc work for you ?

**Comment by kknaidumca** [comment]
yeah appr.tc works in the browsers. We are using xmpp and DTMF is that causing the video freeze.

**Comment by nils-ohlmeier** [comment]
It is possible that you are using Jitis?
If you are using a recent version of Jitsi you might encounter this problem https://bugzilla.mozilla.org/show_bug.cgi?id=1430476

**Comment by fippo** [comment]
you might want to file an issue in the jitsi-videobridge repository instead.

**Comment by KaptenJansson** [comment]
Closing as per the last comments.
