### ISSUE TITLE
Problem with Chrome 64.0.3282.123

### ISSUE THREAD

**Issue by CarmineScala92** [webrtcHacks/adapter#755]
**Browsers and versions affected**
Good Afternoon i have a problem with Google Chrome (64.0.3282.123)

**Description**

the video stream does not work. Since I have updated chrome I have this problem.  
In the example on-line => https://serratus.github.io/quaggaJS/examples/live_w_locator.html appear black screen.

**Steps to reproduce**

**Expected results**

**Actual results**

**Comment by fippo** [comment]
```
{width: {min: 640}, height: {min: 480}, aspectRatio: {min: 1, max: 100}, facingMode: {ideal: ["environment"]}}
```
these constraints might fail. Can you try if the same happens without adapter.js?

**Comment by CarmineScala92** [comment]
I tried not to import the adapter.js library, but on Chrome (64.0.3282.123) I always have the same problem. While on Firefox it works. How can I solve the problem?

Thank you for support

**Comment by CarmineScala92** [comment]
If you try to open this link (https://webrtc.github.io/samples/src/content/getusermedia/gum/), Live video does not appear on Chrome 64.0.3282.123

**Comment by fippo** [comment]
if navigator.mediaDevices.enumerateDevices().then(devices => console.log(devices)) does not show any video devices then calling getUserMedia({video: true}) will fail. Use enumerateDevices before calling getUserMedia to find out if there is a camera.

**Comment by CarmineScala92** [comment]
Quagga.js first calls the navigator.mediaDevices function and then getUserMedia. The problem is quagga.js that does not locate the camera?

**Comment by gruhn** [comment]
Your demo works fine on my Chrome 64 instance

**Comment by CarmineScala92** [comment]
Android device?

**Comment by gruhn** [comment]
No, Linux Desktop. It works on my Android 5 but I could only check Chrome 63. There is no update for my system yet.

**Comment by KaptenJansson** [comment]
I think this is an issue on your device, does it work in other apps like appr.tc?

**Comment by fippo** [comment]
> If you try to open this link (https://webrtc.github.io/samples/src/content/getusermedia/gum/), Live video does not appear on Chrome 64.0.3282.123

And does it show any error?

**Comment by veikkoeeva** [comment]
Hi! Windows 10 here, it appears all the samples that try to capture video from my webacom do not function except in Firefox. The error is basically `NotReadableError`, here's a screenshot from the chat:

![kuva](https://user-images.githubusercontent.com/5158694/36381955-fdadbd12-158f-11e8-9da2-8e1ab9ca4ed6.png)

I tried to troubleshoot using https://webrtc.github.io/samples/src/content/getusermedia/gum/ and use the debugger to find the root cause, but didn't find anything (for the time being). Save for the `NotReadableError` that surfaces.

**Comment by tajulsdream** [comment]
i am also facing a similar problem. In latest version of chrome in Android back camera is not opening. always front camera coming out. FireFox and safari is ok. Is there any luck with anyone?

**Comment by KaptenJansson** [comment]
@tajulsdream have you tried using an web page that has enumerateDevices capabilites to select the camera? Like https://webrtc.github.io/samples/src/content/devices/input-output/ ?

Also please always state the version of the browser, latest does not mean much at a later time and everyone has to look up which version.

**Comment by veikkoeeva** [comment]
I can report that at least in different machine Edge, Firefox and Chrome appear to be functioning correctly This other machine is also "latest Windows 10" with up-to-date evergreen browsers, I omit the version numbers as of now.

I also note that if there is a steam on already in some browser, the others fail to open the device. I do not know if this was the situation when I tried (at least it was acceidental if it was so) and if this situation should be coverered somehow.

**Comment by karls** [comment]
@veikkoeeva FWIW, on Windows only a single consumer (program, app, tab, etc) can read the stream from a video device. This is intended behaviour as far as I know.
