### ISSUE TITLE
getUserMedia throws TypeError in Chrome for Android

### ISSUE THREAD

**Issue by gruhn** [webrtcHacks/adapter#756]
**Browsers and versions affected**

At least Chrome 37 and Chrome 42 on Android 5.1.1 but I assume *Chrome 44 and below* in general.

**Description**

Calling `navigator.mediaDevices.getUserMedia` throws `TypeError: undefined is not a function`.

I believe [this line](https://github.com/webrtc/adapter/blob/master/release/adapter.js#L3333) is where the error comes from. `find` seems to be the function that is undefined here, which makes sense to me since `Array.prototype.find` was first introduced in Chrome 45.

I forwarded this from another repository. For more details you can go to the [original issue](https://github.com/gruhn/vue-qrcode-reader/issues/16).

**Steps to reproduce**

The exact call that produces the error:
```js
navigator.mediaDevices.getUserMedia({
  audio: false,
  video: {
    facingMode: { ideal: 'environment' },
    width: { min: 360, ideal: 1280, max: 1920 },
    height: { min: 240, ideal: 720, max: 1080 }
  }
})
```
You can also visit [this web page where the error occurs](https://gruhn.github.io/vue-qrcode-reader/).

**Comment by CarmineScala92** [comment]
i have same problem with chrome (64.0.3282.123), i don't see the strem video when i open this link with chrome https://gruhn.github.io/vue-qrcode-reader/

**Comment by gruhn** [comment]
Really? Do you see [this error message](https://github.com/gruhn/vue-qrcode-reader/issues/16) too?

**Comment by CarmineScala92** [comment]
when i open this link  https://gruhn.github.io/vue-qrcode-reader/   i see this error :
![image](https://user-images.githubusercontent.com/21006592/35555395-558fd8d6-059f-11e8-9259-15e3a03c9a6d.png).

I have this problem with Chrome while Firefox it work.

**Comment by gruhn** [comment]
Interesting but it doesn't seem to be `webrtc-adapter` related. Thanks though, I'll try to reproduce this later.

**Comment by KaptenJansson** [comment]
We do not support ancient browsers. Are you using old browsers purely to repro this bug or are you actually using old browsers in your project?

Using API's introduced 3 years ago I think is fair game ;)

Not sure why you forwarded this bug here?

**Comment by gruhn** [comment]
I didn't encounter this error at all but a user of a public Vue.js component of mine. He reported that issue and I  concluded it's a `webrtc-adapter` issue. That's why I forwarded it.

But your right it's reasonable to not support browsers that old. I would still expect that this shim leaves `getUserMedia` undefined in browsers that aren't supported so I can at least properly feature detect.

**Comment by KaptenJansson** [comment]
Well we are using standard API's in the browser to do certain things and its not reasonable to have to shield every API call due to some users using 3 year old browsers which lack common API's like `Array.prototype.find` .
