### ISSUE TITLE
getStats: shim different report names

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#76]
#46 polyfilled the getStats but did not do any field name rewriting as I noticed in https://github.com/webrtc/samples/pull/551

In that case it was type=ssrc vs type=outboundrtp. 

Identifying what needs to be done here is probably the difficult part, maybe something that could be done more easily during the september F2F meeting @alvestrand @jan-ivar @vr000m?

**Comment by fippo** [comment]
other differences:
- firefox has a mediaType audio/video on the inbound/outbound rtp reports. I used the googFrameHeight to get an equivalent condition
- firefox calculates mean bitrates on it's own which is somewhat useful

**Comment by fippo** [comment]
- googCandidatePair has googActiveConnection which is roughly equivalent to candidatePair's selected. Note that the former is the string "true"/"false" and the latter is a boolean.

**Comment by jan-ivar** [comment]
> firefox has a mediaType audio/video on the inbound/outbound rtp reports. 

`mediaType` was based on @alvestrand 's [idea on the list a year ago](https://lists.w3.org/Archives/Public/public-webrtc/2014May/0241.html), but it doesn't seem to have made it to http://w3c.github.io/webrtc-stats/#idl-def-RTCRTPStreamStats , unless I'm looking in the wrong place?

**Comment by alvestrand** [comment]
@jan-ivar can you file a bug against webrtc-stats?
As one of the author team: We forgot this one.

**Comment by jan-ivar** [comment]
Filed as https://github.com/w3c/webrtc-stats/issues/9.

**Comment by fippo** [comment]
- on the [candidate report](http://w3c.github.io/webrtc-stats/#icecandidate-dict*), portNumber and priority are strings instead of numbers in chrome. _grmbl_

**Comment by KaptenJansson** [comment]
> on the candidate report, portNumber and priority are strings instead of numbers in chrome. grmbl

@fippo thanks for pointing this out, I filed https://code.google.com/p/chromium/issues/detail?id=520923. Please star it to follow its progress.

**Comment by KaptenJansson** [comment]
I guess this is suffering the same fate as #5

**Comment by fippo** [comment]
yeah. I need to find time and talk with @alvestrand about #124 and then move that over to the new structure.
