### ISSUE TITLE
In firefox iceconnection disconnects automatically while streaming video

### ISSUE THREAD

**Issue by UmaMuthu** [webrtcHacks/adapter#769]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [ ] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [ ] This issue only happens when adapter.js is used

**Note: If the checkboxes above are not checked, the issue will be closed.**

## Versions affected

**Firefox 52.0.2**

**https://webrtc.github.io/adapter/adapter-latest.js **

## Description
I am using RTCPeerConnection, navigator.mediaDevices.getUserMedia, RTCIceCandidate, xmpp, DTMF, iceservers 

## Steps to reproduce
While streaming video in the Firefox Browser, iceconnection gets disconnected automatically and the video freezes and it gets connected again and soon disconnects and freezes, but this does not happen in Chrome Browser.

## Expected results
Video Streaming should happen continuously without freezing in firefox

## Actual results
Video gets freezed in Firefox

**Comment by KaptenJansson** [comment]
So the issue does not happen when NOT using adapter.js? Not sure what adapter has to do with this, sounds more like a network issue.

Also, make sure to fulfill all the conditions in the checkboxes, they are there for a reason, an issue without enough information is not actionable and a waste of time.
