### ISSUE TITLE
Extract only getUserMedia required shims

### ISSUE THREAD

**Issue by xban1x** [webrtcHacks/adapter#772]
I have a use case where i only require your library for the getUserMedia shims. Is it possible you could ship a sepearete JS file for inclusion in ES6?

**Comment by elmarti** [comment]
Hi, I don't mean to detract from this project, but I am currently using FlyAdapter (written by me) to make it easier to work with CommonJS and Adapter. (It's basically a wrapper)
https://github.com/RTCFly/FlyAdapter

I'm more than happy to derive some sort of PR from this to make Adapter provide this functionality by default, but until then, this works for me pretty well. 

Not sure if that's what you mean, but I hope this is useful.

**Comment by xban1x** [comment]
Well what i want is that from this picture in my bundle-analyzer 

http://prntscr.com/icadjz

I could remove sdp and rtcpeerconnection-shim since for my use case they are just bloatware. I only really require the getUserMedia and enumerateDevices from this library.

**Comment by fippo** [comment]
in current browser versions you probably don't need the getUserMedia shims at all anymore.

You can always include them directly and write your own stripped-down version of the factory in https://github.com/webrtc/adapter/blob/master/src/js/adapter_factory.js#L14

**Comment by KaptenJansson** [comment]
Does this answer your question? I'm happy to review PRs with your proposed solution.

**Comment by xban1x** [comment]
What I would like if this projects exposed all of its inners on the root level so I could import shims directly without having to use your adapter_factory. 

If someone were to add d.ts. files that would be even better. I am using this project only for its use of getUserMedia, srcObject, and enumerateDevices.

I am only asking to allow an option for the developer to choose which parts of your project to include. If you have any idea how I can do that myself please tell me...

**Comment by fippo** [comment]
someone has to do it. Not me unfortunately.
