### ISSUE TITLE
In Firefox, removing audio track from a stable connection with Chrome, causes the Offer to be rejected and disconnects connection

### ISSUE THREAD

**Issue by itsthetaste** [webrtcHacks/adapter#773]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Versions affected

I'm testing between Chrome 63.0.3239.132 and Firefox 57.0 and have tried adapter.js versions 6.0.0, 6.0.1, 6.0.3, 6.1.0 and 6.1.1.

## Description

Testing between Chrome and Chrome seems fine.
Testing between Firefox and Firefox also seems fine.
But between Firefox and Chrome the issue occurs. (I've not got onto testing Edge or Safari yet).

I create a RTCPeerConnection between Chrome and Firefox, add a video and an audio track to the Firefox end, then negotiate and get a stable connection with video and audio streaming correctly.  I then stop the track and remove the track from the Firefox end and renegotiate the connection.  My offers is generated, I send it across to Chrome, set it into the it's setRemoteDescription, Chrome detects the track has ended, but then fails the call to setLocalDescription with the answer that it made.  Causing the error: OperationError Failed to set local answer sdp: Failed to push down transport description: Applying an answer transport description without applying any offer.

Here are the offers generated by Firefox and the answers generated by Chrome

Audio and Video
Offer
v=0
o=mozilla...THIS_IS_SDPARTA-57.0 846080820702645861 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 F4:D1:61:A5:C6:6C:99:EA:75:34:9C:CC:DA:1A:76:A7:72:57:CD:4F:CE:9A:35:30:F8:78:7C:76:97:2B:A1:D2
a=group:BUNDLE sdparta_0 sdparta_1
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8 101
c=IN IP4 0.0.0.0
a=sendrecv
a=extmap:1/sendonly urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=fmtp:101 0-15
a=ice-pwd:861fb94048824cb17b69c8cad6098f45
a=ice-ufrag:e9186892
a=mid:sdparta_0
a=msid:{13545980-46b1-42f3-8c75-f73a17c9193d} {b0f24c72-27c7-4af3-b56f-ebf9fbddde0e}
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=setup:actpass
a=ssrc:3899616141 cname:{f859552d-1770-45aa-9b24-03757fe16ece}
m=video 9 UDP/TLS/RTP/SAVPF 120 121 126 97
c=IN IP4 0.0.0.0
a=sendrecv
a=extmap:1 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
a=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1
a=fmtp:120 max-fs=12288;max-fr=60
a=fmtp:121 max-fs=12288;max-fr=60
a=ice-pwd:861fb94048824cb17b69c8cad6098f45
a=ice-ufrag:e9186892
a=mid:sdparta_1
a=msid:{13545980-46b1-42f3-8c75-f73a17c9193d} {87a9bc9f-8ea5-4528-b9ed-e01b9704a714}
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 ccm fir
a=rtcp-fb:120 goog-remb
a=rtcp-fb:121 nack
a=rtcp-fb:121 nack pli
a=rtcp-fb:121 ccm fir
a=rtcp-fb:121 goog-remb
a=rtcp-fb:126 nack
a=rtcp-fb:126 nack pli
a=rtcp-fb:126 ccm fir
a=rtcp-fb:126 goog-remb
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 goog-remb
a=rtcp-mux
a=rtpmap:120 VP8/90000
a=rtpmap:121 VP9/90000
a=rtpmap:126 H264/90000
a=rtpmap:97 H264/90000
a=setup:actpass
a=ssrc:905434405 cname:{f859552d-1770-45aa-9b24-03757fe16ece}

Answer
v=0
o=- 5272920877071744502 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE sdparta_0 sdparta_1
a=msid-semantic: WMS
m=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8 101
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:64qV
a=ice-pwd:pWhRnh3gJp6v3Nq/cfSJTB5r
a=ice-options:trickle
a=fingerprint:sha-256 8B:A9:BE:CF:7A:71:D1:17:F4:82:73:3C:CF:BC:5A:A0:7D:13:8C:78:40:40:B9:1B:A6:F5:9B:7E:C8:DD:B6:2E
a=setup:active
a=mid:sdparta_0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=recvonly
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
m=video 9 UDP/TLS/RTP/SAVPF 120 121 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:64qV
a=ice-pwd:pWhRnh3gJp6v3Nq/cfSJTB5r
a=ice-options:trickle
a=fingerprint:sha-256 8B:A9:BE:CF:7A:71:D1:17:F4:82:73:3C:CF:BC:5A:A0:7D:13:8C:78:40:40:B9:1B:A6:F5:9B:7E:C8:DD:B6:2E
a=setup:active
a=mid:sdparta_1
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:1 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=recvonly
a=rtcp-mux
a=rtpmap:120 VP8/90000
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 ccm fir
a=rtcp-fb:120 goog-remb
a=fmtp:120 max-fr=60;max-fs=12288
a=rtpmap:121 VP9/90000
a=rtcp-fb:121 nack
a=rtcp-fb:121 nack pli
a=rtcp-fb:121 ccm fir
a=rtcp-fb:121 goog-remb
a=fmtp:121 max-fr=60;max-fs=12288
a=rtpmap:126 H264/90000
a=rtcp-fb:126 nack
a=rtcp-fb:126 nack pli
a=rtcp-fb:126 ccm fir
a=rtcp-fb:126 goog-remb
a=fmtp:126 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f

Turn off Audio
Offer
v=0
o=mozilla...THIS_IS_SDPARTA-57.0 846080820702645861 1 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 F4:D1:61:A5:C6:6C:99:EA:75:34:9C:CC:DA:1A:76:A7:72:57:CD:4F:CE:9A:35:30:F8:78:7C:76:97:2B:A1:D2
a=group:BUNDLE sdparta_1
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 0 UDP/TLS/RTP/SAVPF 0
c=IN IP4 0.0.0.0
a=inactive
a=mid:sdparta_0
a=rtpmap:0 PCMU/8000
m=video 9 UDP/TLS/RTP/SAVPF 120 121 126 97
c=IN IP4 0.0.0.0
a=sendrecv
a=extmap:1 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
a=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1
a=fmtp:120 max-fs=12288;max-fr=60
a=fmtp:121 max-fs=12288;max-fr=60
a=ice-pwd:861fb94048824cb17b69c8cad6098f45
a=ice-ufrag:e9186892
a=mid:sdparta_1
a=msid:{13545980-46b1-42f3-8c75-f73a17c9193d} {87a9bc9f-8ea5-4528-b9ed-e01b9704a714}
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 ccm fir
a=rtcp-fb:120 goog-remb
a=rtcp-fb:121 nack
a=rtcp-fb:121 nack pli
a=rtcp-fb:121 ccm fir
a=rtcp-fb:121 goog-remb
a=rtcp-fb:126 nack
a=rtcp-fb:126 nack pli
a=rtcp-fb:126 ccm fir
a=rtcp-fb:126 goog-remb
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 goog-remb
a=rtcp-mux
a=rtpmap:120 VP8/90000
a=rtpmap:121 VP9/90000
a=rtpmap:126 H264/90000
a=rtpmap:97 H264/90000
a=setup:actpass
a=ssrc:905434405 cname:{f859552d-1770-45aa-9b24-03757fe16ece}

Answer
v=0
o=- 5272920877071744502 3 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE sdparta_1
a=msid-semantic: WMS
m=audio 0 UDP/TLS/RTP/SAVPF 0
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=mid:sdparta_0
a=inactive
a=rtpmap:0 PCMU/8000
m=video 9 UDP/TLS/RTP/SAVPF 120 121 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:64qV
a=ice-pwd:pWhRnh3gJp6v3Nq/cfSJTB5r
a=ice-options:trickle
a=fingerprint:sha-256 8B:A9:BE:CF:7A:71:D1:17:F4:82:73:3C:CF:BC:5A:A0:7D:13:8C:78:40:40:B9:1B:A6:F5:9B:7E:C8:DD:B6:2E
a=setup:active
a=mid:sdparta_1
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:1 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=recvonly
a=rtcp-mux
a=rtpmap:120 VP8/90000
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 ccm fir
a=rtcp-fb:120 goog-remb
a=fmtp:120 max-fr=60;max-fs=12288
a=rtpmap:121 VP9/90000
a=rtcp-fb:121 nack
a=rtcp-fb:121 nack pli
a=rtcp-fb:121 ccm fir
a=rtcp-fb:121 goog-remb
a=fmtp:121 max-fr=60;max-fs=12288
a=rtpmap:126 H264/90000
a=rtcp-fb:126 nack
a=rtcp-fb:126 nack pli
a=rtcp-fb:126 ccm fir
a=rtcp-fb:126 goog-remb
a=fmtp:126 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f

## Steps to reproduce

I'm not sure how to upload code to show the issue in a contained environment because there 2 browsers involved and a signalling server.  Hopefully the description is enough?

## Expected results

I expect chrome to set new offer into it's remoteDescription, disconnect the track, create an answer, set it into it's localDescription, send it back to firefox to set into it's remoteDescription and the connection to remain stable.

## Actual results

Chrome sets the new offer into it;s remoteDescription, disconnects the track, creates an answer but fails to set it into it's localDescription causing the connection to disconnect.

**Comment by fippo** [comment]
do you have a chrome://webrtc-internals dump of the chrome side of things?

`OperationError Failed to set local answer sdp: Failed to push down transport description: Applying an answer transport description without applying any offer.` suggests some weirdness in your api calls

**Comment by itsthetaste** [comment]
Hi, yes here's one.
[webrtc_internals_dump (1).txt](https://github.com/webrtc/adapter/files/1707660/webrtc_internals_dump.1.txt)

**Comment by fippo** [comment]
api calls look good. @nils-ohlmeier @taylor-b this looks like something for you folks. I would bet on the mediasection chosen for bundle becoming rejected.

**Comment by itsthetaste** [comment]
thanks for taking a look

**Comment by KaptenJansson** [comment]
Just to make it clear, this only happens with adapter.js? You have tried without adapter.js?

**Comment by itsthetaste** [comment]
Hi, I wouldn't be able to add and remove tracks in chrome without adapter.js, so unfortunately I can't really try it.  The library i've been writing follows the spec (I believe), using addTrack, removeTrack and ontrack.  I know at some point I'll need to switch it out to using transcievers, but it didn't look like anybody was supporting those when I started making this Library a few months ago.  I appreciate this might not be an issue with what adapter.js is doing, maybe its something that needs doing or is caused by the recent firefox update.  I'm just about to rollback to 55 and 56 and try in there.

**Comment by itsthetaste** [comment]
Rolling back to older versions of firefox didn't help

**Comment by taylor-b** [comment]
This is a longstanding known bug: https://bugs.chromium.org/p/webrtc/issues/detail?id=6704

In short, Chrome doesn't like when you reject the m= section that things are being "bundled" on (the one whose identifier appears first in "a=group:BUNDLE").

**Comment by nils-ohlmeier** [comment]
Good point @taylor-b 
I'm pretty sure Firefox also still has issues when the offerer removes/disables the bundled m-section (so if you would remove the track on the Chrome side and then send the offer to Firefox).

**Comment by KaptenJansson** [comment]
Closing as per last comments.

**Comment by itsthetaste** [comment]
thanks for help guys, following the link @taylor-b posted and the link off that it gave me the idea to try and munge the sdp.  That didn't work, but another idea in the thread was to put the data channel first.  So, I added a data channel first and hey presto, I can now add and remove tracks in whatever order I like :)
