### ISSUE TITLE
Any demon with adapter.js ?

### ISSUE THREAD

**Issue by extremety1989** [webrtcHacks/adapter#781]
- [ ] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [ ] I have provided browser name, version and adapter.js version
- [*] This issue only happens when adapter.js is used

How to use adapter.js ?
Can somebody provide me a demo please ?

**Comment by simkesd** [comment]
In the adapter README you'll find a link to the Samples page - [This one](https://github.com/webrtc/samples). All the examples in there are using adapter.js.

From what I know, there's no much difference to using normal WebRTC API, as this is just a shim that helps you achieve the same thing across multiple browsers.

**Comment by extremety1989** [comment]
@simkesd  so there is no way to modify function in webrtc?
  i want make it possible to generate always same Session, like that

SDPUtils.generateIdentifier = function() {
  // return Math.random().toString(36).substr(2, 10);
  return 6550572165951737818;
};

**Comment by fippo** [comment]
@extremety1989 your question doesn't seem to be about adapter.js but about the WebRTC API in general. Please use the discuss-webrtc mailing list which is linked from the text you deleted.

**Comment by extremety1989** [comment]
@fippo okey thanks
