### ISSUE TITLE
Edge user media resolution changes based on cosmetic video dimensions

### ISSUE THREAD

**Issue by dcreey** [webrtcHacks/adapter#787]
## Versions affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**
Microsoft Edge 41.16299.15.0
Microsoft EdgeHTML 16.16299
Possibly other Edge versions

**adapter.js (e.g. 6.1.0)**
Latest. From https://webrtc.github.io/adapter/adapter-latest.js
Also see this on a much older version 4.x.x

## Description
Requesting GUM at certain resolutions is initially successful, but establishing a peer connection with that userMedia changes the actual encoded/sent frame resolution. Seems to have something to do with the video element dimensions - height/width styles.

Tested:
- 1080p GUM with 180p video dimensions. Video quality drops to 360p or 180p.
- 180p GUM with 1080p video dimensions. Video quality jumps to 720p or 1080p.

## Steps to reproduce
Tests:
- 180p jumping to 720 or 1080 - https://jsfiddle.net/phenixRTS/825qguh2/   (big videos. Scroll down for buttons)
- 1080p dropping to 360 or 180 - https://jsfiddle.net/phenixRTS/fub87m4p/

These fiddles are based on the pc1 sample. Steps:
1) Press start. You will note GUM resolution looks as expected.
2) Press call. You will see the video dimension stays fixed but the actual quality of the video changes in both the local and subsequently the remote videos. Note the actual values for the sent/received frameHeight also reflect the apparent changes.

## Expected results
The user media resolution should stay fixed at the requested GUM options. 

## Actual results
The user media resolution changes based on cosmetic video dimensions.

**Comment by fippo** [comment]
this doesn't sound like an adapter issue (and note that we have the questions in the issue template for a reason).

> The user media resolution should stay fixed at the requested GUM options.

In general that is not guaranteed due to bandwidth constraints

@aboba: does Edge adapt to displayed resolution via some header extension?

**Comment by KaptenJansson** [comment]
How is this an adapter issue? We do not modify mediastreams, video tags or control network transport behavior on peerconnections. It could be doing scaling due to network limitations, CPU etc.
