### ISSUE TITLE
adapter.js should not pollute the global namespace

### ISSUE THREAD

**Issue by juberti** [webrtcHacks/adapter#8]
From https://github.com/webrtc/samples/issues/297

ibc commented on Dec 13, 2014
No one in the world should define a global function called trace() (and so many other window globals defined in adapter.js).

adapter.js seems to ignore any new design pattern and JS module system (AMD, CommonJS, etc).

Would you accept a PR removing all the global stuff and providing a library suitable to be loaded by any existing JS module loader without polluting the window global namespace?
Sam Dutton
 Owner
samdutton commented on Dec 13, 2014
You have a point :).

adapter.js worked OK in the context of the demos it was initially built for but, of course, will cause namespace pollution in larger projects.

At the very least it would be great to refactor it from an object-oriented approach with no globals.

@juberti @KaptenJansson @phoglund WDYT?
Iñaki Baz Castillo

ibc commented on Dec 13, 2014
I mean something that can be loaded with npm install webrtc-adapter (and borwserified with browserify), and Bower, and so on.
Iñaki Baz Castillo

ibc commented on Dec 13, 2014
Let me know if you are interested and I will provide a PR.
Justin Uberti
 Owner
juberti commented on Dec 14, 2014
yeah, I think it's time for adapter.js to grow up. Would you mind changing the title of this issue to be more descriptive?

And please provide an initial PR for the adapter - we'll then have to do a subsequent PR for changing all of our sample code.
Iñaki Baz Castilloibc changed the title from Please build modern JS to Make adapter.js a modern JS library (module systems aware) on Dec 14, 2014
Iñaki Baz Castillo

ibc commented on Dec 14, 2014
I will start in my own repo by creating a JS "project" (not a single adapter.js file), which will include Grunt/gulp tasks for linting, browserifying, etc.

Let me some time please, I will notify it here when done.
Sam Dutton
 Owner
 samdutton commented on Dec 14, 2014
Thanks for doing this!

adapter.js will be happy to get some attention :).
…
Justin Uberti
 Owner
juberti commented on Dec 14, 2014
Before spending too much time, it would be good to get a high-level overview of what you expect it to look like in the end. I am all for avoiding global namespace pollution but I want to make sure we're not biting off too much here.
Christoffer Jansson
 Owner
KaptenJansson commented on Dec 14, 2014
SGTM
Will

willscott commented on Dec 15, 2014
FYI - I've begun maintaining a CommonJS library to do something similar: https://www.npmjs.org/package/webrtc-adapter
Iñaki Baz Castillo

ibc commented on Dec 15, 2014
@willscott found that yesterday, I will do something similar, but including a new JS namespace to place in there all the util functions exposed by the current adapter.js.
Will

willscott commented on Dec 15, 2014
@ibc If I understand, you want to see createIceServer & similar explicitly exported, right?

My motivation was to be able to pull in adapter via browserify, and have it find what's in scope via typeof rather than probing navigator, which isn't available for firefox addons.

If the intermediate utility functions are useful, I'd be happy to see those exported.
Iñaki Baz Castillo

ibc commented 26 days ago
Hi, finally I've taken a different approach. It covers more than what adapter.js provides as it is a full wrapper over the RTCPeerConnection interface (along with all the other WebRTC interfaces and functions). It is loadable via Node+browserify, AMD, RequireJS, etc, and it does not pollute the global (window) namespace, even stuff like RTCPeerConnection, etc. Instead it provides a single entry module called "rtcninja":

https://github.com/ibc/rtcninja.js

The documentation is still missing however.
Justin Uberti
 Owner
juberti commented 26 days ago
Thanks. 2KLOC seems kind of heavy though for this shim lib. I think we probably want to have something more like willscott's webrtc-adapter.

Perhaps the documentation will make the value more clear, but I was also somewhat wary of the various timers I saw in your implementation.

**Comment by juberti** [comment]
Next step on this should be to make webrtc a global object that exposes .detectedVersion, .detectedBrowser, .trace, .attachMediaStream, .reattachMediaStream.

After that, we should clean out legacy cruft like createIceServers.

**Comment by fippo** [comment]
createIceServers should be obsolete in FF37. @jesup?

**Comment by 486** [comment]
Does this include not overwriting window.RTCPeerConnection, window.RTCSessionDescription etc.? 
IMHO that should be optional. If there is another library using WebRTC on a page it should be able to do its own fixing / detection.

**Comment by fippo** [comment]
the point of adapter.js is hiding those differences -- you can still get the original browser from webrtcDetectedBrowser et al. Works like charm for simplewebrtc (or rather it's lowlevel modules)

**Comment by ibc** [comment]
There are better and independent modules to get the exact browser version and platform such as [bowser](https://www.npmjs.com/package/bowser).

[rtcninja](https://github.com/eface2face/rtcninja.js) uses it and exports it, and it does not create any global (but `window.rtcninja` if no JS modern loader is detected).

**Comment by KaptenJansson** [comment]
This will be covered in #164.

**Comment by KaptenJansson** [comment]
Fixed in #164.
