### ISSUE TITLE
Chrome 65 throws exception when trying to access RTCRtpSender.dtmf

### ISSUE THREAD

**Issue by sherlock1982** [webrtcHacks/adapter#802]
## Versions affected

**Chrome  65.0.3325.181**
**adapter.js 6.1.4**

## Description
Chrome 65 throws exception when trying to access RTCRtpSender.dtmf because RTCRtpSender doesn't have _pc for RTCPeerConnection anymore.
Was working in Chrome 64. 

## Steps to reproduce

       const audio = peerConnection.addTrack(track, localStream);
       audio.dtmf

## Expected results
Return RTCDtmfSender or undefined

## Actual results
Throws an exception here:

      Object.defineProperty(window.RTCRtpSender.prototype, 'dtmf', {
        get: function() {
          if (this._dtmf === undefined) {
            if (this.track.kind === 'audio') {
              this._dtmf = this._pc.createDTMFSender(this.track);
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ // this._pc undefined
            } else {
              this._dtmf = null;
            }
          }
          return this._dtmf;
        }
      });

UPDATE:

Moreover when I fix nullptr exception it gives another: `Failed to execute 'createDTMFSender' on 'RTCPeerConnection': No local stream is available for the track provided.`

WORKAROUND 1:
In adapter.js:
Looks like the proper way to fix it is to drop usage of `shimAddTrackRemoveTrackWithNative` (comment out line with browser version >=65 check)

WORKAROUND 2:
Use addStream. Though it declared deprecated looks like it's a must have for createDTMFSender in Chrome

**Comment by fippo** [comment]
you're running into two issues here:
1) trying to use the audio sender from addTrack instead of getSenders
2) #733 which means the native addTrack doesn't work with dtmf in M65

**Comment by henbos** [comment]
You can fix so that addTrack() also adds "this._pc" before returning the sender or you can use getSenders() which adds _pc.

RTCRtpSender.dtmf is shipping in M66: https://groups.google.com/forum/#!msg/discuss-webrtc/zcvEBJUdFgs/yZroCB4-AwAJ

**Comment by sherlock1982** [comment]
Thank you, I see now. Than I think we can close it as duplicate.

**Comment by henbos** [comment]
Nevermind, see fippo's comment, addTrack() and dtmf are not compatible in 65 and you have to use addStream(), but in M66 both addTrack() and .dtmf work

**Comment by sherlock1982** [comment]
Just a small addition than: It might make sense to remove the check for version 65. Might be replace it with version 66.
Though it brings some native functions it also breaks DTMF.
