### ISSUE TITLE
Cannot set property 'foundation' of undefined

### ISSUE THREAD

**Issue by etienne-martin** [webrtcHacks/adapter#803]
## Versions affected

**Chromium Version 67.0.3372.0 (Developer Build) (64-bit)**

**adapter.js (e.g. 5.0.0)**

## Description

I'm getting the following error when migrating from `4.2.2` to `5.0.0`.

```
TypeError: Cannot set property 'foundation' of undefined
      
at Object.v.parseCandidate (<anonymous>:1:53284)
at new n.RTCIceCandidate (<anonymous>:1:107982)
```

## Steps to reproduce

I'm importing the lib with (typescript):

```
import * as adapter from "webrtc-adapter";
```

Create an offer with `offerToReceiveAudio` set to `1` and set it as the local description.

## Expected results

Should trigger the `onicecandidate` event.

## Actual results

Get the error above.

**Comment by fippo** [comment]
can you provide a jsfiddle to reproduce? https://jsfiddle.net/xr5bm8Lu/ works fine

**Comment by etienne-martin** [comment]
My bad, the issue was caused by uglify.

Sorry for bothering you with that.
