### ISSUE TITLE
InvalidAccessError for new window.RTCICEGatherer() in Edge 

### ISSUE THREAD

**Issue by imad-ant** [webrtcHacks/adapter#816]
## Versions affected

**Edge 41.16299**

**adapter.js (6.1.5)**

## Description

Issue occurs on line 564 of adapter.js:
 ```
var iceGatherer = new window.RTCIceGatherer({
      iceServers: this._config.iceServers,
      gatherPolicy: this._config.iceTransportPolicy
    });
    Object.defineProperty(iceGatherer, 'state',
        {value: 'new', writable: true}
    );
```

wherein the configuration is:
```
{ 
	    iceServers : [
	        {urls: "stun:stun.l.google.com:19302"}, // Previously "url", deprecated.
	        {urls: "stun:stun1.l.google.com:19302"},
	        {urls: "stun:stun2.l.google.com:19302"},
	        {urls: "stun:stun3.l.google.com:19302"},
	        {urls: "stun:stun4.l.google.com:19302"},
	        {urls: "stun:23.21.150.121"},
	        {urls: "stun:stun01.sipphone.com"},
	        {urls: "stun:stun.ekiga.net"},
	        {urls: "stun:stun.fwdnet.net"},
	        {urls: "stun:stun.ideasip.com"},
	        {urls: "stun:stun.iptel.org"},
	        {urls: "stun:stun.rixtelecom.se"},
	        {urls: "stun:stun.schlund.de"},
	        {urls: "stun:stunserver.org"},
	        {urls: "stun:stun.softjoys.com"},
	        {urls: "stun:stun.voiparound.com"},
	        {urls: "stun:stun.voipbuster.com"},
	        {urls: "stun:stun.voipstunt.com"},
	        {urls: "stun:stun.voxgratia.org"},
	        {urls: "stun:stun.xten.com"}] 
	    };
```

This configuration's stun servers work on other browser's (I am aware it is bad practice to have more than two STUN/TURN servers). It seems to have similarities with #645 , however, the solution for that issue is not applicable in this situation wherein there are no `?transport' substrings within the STUN/TURN server URL's. 

## Steps to reproduce
Create a new Offer on Microsoft Edge/

## Expected results
Success / Failure with debug info.

## Actual results
Console Error on Edge stating "InvalidAccessError"

**Comment by fippo** [comment]
add `?transport=udp` and a port?

**Comment by imad-ant** [comment]
Resolved, the issue was indeed because I was missing the `?transport=udp`
