### ISSUE TITLE
{facingMode: "environment"} camera switching doesn't work in Mobile Chrome 

### ISSUE THREAD

**Issue by x3mlestat** [webrtcHacks/adapter#820]
hi guys,
I still have issue that was described in https://github.com/webrtc/adapter/issues/594
Camera don't switched in Android Chrome  (in FF and Safari everything is OK).
Seem to this issue  was not be fixed ? 

Browsers and versions affected

Chrome for Android 66.

Steps to reproduce

```
var constraints = {video: {facingMode: "environment"}}
navigator.mediaDevices.getUserMedia(constraints)
```
or

```
var constraints = {video: {facingMode: {exact: "environment"}}}
navigator.mediaDevices.getUserMedia(constraints)
```

Expected results

Get the back-facing camera stream.

Actual results

Get the front-facing camera stream (the first code sample) or nothing — the browser does not request the permission (the second code sample).

**Comment by fippo** [comment]
Does this happen without adapter as well? If yes please file an issue over on crbug.com, include details about what device you tried this on and link the bug number here.

**Comment by x3mlestat** [comment]
hi fippo,

Without adapter camera switching working perfect.
Tested on mobile Chrome on Xiaomi a1.

switching code : 

```
video: { facingMode: "environment"}
video: { facingMode: "user"}
```

**Comment by fippo** [comment]
the current version of adapter doesn't modify the constraints for Chrome 61+, see [here](https://github.com/webrtc/adapter/blob/master/src/js/chrome/getusermedia.js#L70)

**Comment by getify** [comment]
Just wanted to report that I am able to switch to `facingMode: { exact: "environment", }` in mobile Chrome (Android 7, Chrome 67.0.3396.68). I am using the latest adapter.

**Comment by rlueders** [comment]
I am having the same problem. Is there an alternative to facingMode that allows for easy camera switching?

**Comment by fippo** [comment]
seems like a chrome bug, not something adapter does. Please file issues on crbug.com

**Comment by ghost** [comment]
Do you know how to choose the camera using navigator.webkitGetUserMedia ?

**Comment by mamoyko** [comment]
how can i import the adapter on angular 8?

i tried adding this code on the main.js

`import 'webrtc-adapter'`

and 

`import adapter from 'webrtc-adapter';`

this is how i add the videoOptions 

```
public videoOptions: MediaTrackConstraints = {
        facingMode: "environment"
};
```

still no luck, setting the rear camera into default still not working
