### ISSUE TITLE
 pc.getSenders is not a function

### ISSUE THREAD

**Issue by TheRadioGuy** [webrtcHacks/adapter#821]
- [X] This issue only happens when adapter.js is used
- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [X] I have provided browser name, version and adapter.js version

# Versions affected

**Browser name including version (Chrome 61)**

**adapter.js (6.1.0)**

## Description
`pc.getSenders is not a function`

## Steps to reproduce

1. get MediaStream
2. ` peer1.addTrack(stream.getTracks()[0], stream);`
## Expected results
Track has been added to RTCPeerConnection
## Actual results
Error

**Comment by fippo** [comment]
you have just checked the boxes without answering any of the questions...

**Comment by TheRadioGuy** [comment]
Update.

**Comment by fippo** [comment]
I tried with with that version combination and it works fine. On what line does the error occur?

**Comment by TheRadioGuy** [comment]
chrome_shim.js:393.

So, I have used Electron 2.0.0

**Comment by fippo** [comment]
that works here too (and we have CI covering electron as well). Do you have a jsfiddle to avoid confusion?
What does `'getSenders' in RTCPeerConnection.prototype` return?

**Comment by alvestrand** [comment]
perhaps peer1.getSenders() is better than pc.getSenders()?
Without a fiddle, it's not clear what the relationship between "pc" and "peer1" is.

**Comment by TheRadioGuy** [comment]
@fippo, `undefined`

**Comment by TheRadioGuy** [comment]
So, i use this library with wrtc + simple-peer

**Comment by TheRadioGuy** [comment]
I replace wrtc to window!

Thanks!
