### ISSUE TITLE
safari: polyfill sender.getStats()/receiver.getStats()

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#826]
- [X] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [ ] This issue only happens when adapter.js is used

## Versions affected
latest
**Browser name including version (e.g. Chrome 64.0.3282.119)**
Safari (stable, possibly STP as well)

**adapter.js (e.g. 6.1.0)**
latest

## Description
https://webrtc.github.io/samples/src/content/peerconnection/audio/ is broken in Safari since we moved to sender.getStats()

We should polyfill this like we do for older Chrome versions. Ideally this will just need to reuse code from #809

@youennf do you have a tracking bug for this?

**Comment by fippo** [comment]
ah... the current code runs into issues because it is looking for stats with type=track which are missing.

**Comment by youennf** [comment]
I filed https://bugs.webkit.org/show_bug.cgi?id=186248

**Comment by fippo** [comment]
@youennf wdyt of polyfill this returning the full stats of no stats with type=track are found?

Users will have to iterate over the results anyway and this would allow applications to migrate to sender.getStats today. See https://github.com/webrtc/samples/issues/1057 for a example of such an issue

**Comment by fippo** [comment]
shipped natively in https://trac.webkit.org/changeset/236207/webkit/

**Comment by fippo** [comment]
probably not required anymore.
