### ISSUE TITLE
Shim maxPacketLifeTime -> maxRetransmitTime in Chrome

### ISSUE THREAD

**Issue by lgrahl** [webrtcHacks/adapter#827]
We should shim `maxPacketLifeTime` to `maxRetransmitTime` when calling `createDataChannel` in Chrome.

**Comment by fippo** [comment]
:+1: have you filed an upstream bug? Ideally we can convince @henbos  this is trivial to fix :-)

**Comment by lgrahl** [comment]
You mean this one? https://bugs.chromium.org/p/chromium/issues/detail?id=696681

**Comment by fippo** [comment]
ah, nagging @guidou then :-)

**Comment by lgrahl** [comment]
Ping (maybe someone wants to do this :grin: ).

**Comment by fippo** [comment]
tenatively closing as Chrome does this natively
