### ISSUE TITLE
is it possible to polyfill getDisplayMedia?

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#830]
the short answer is no but I'd rather have it written up here instead of discusing it over and over again.

So @alvestrand asked whether it would be possible to polyfill getDisplayMedia.

For Mozilla (and @jan-ivar please correct me if I am wrong) the answer is a "no" since getDisplayMedia does not restrict the capture surfaces while the current mediaSource API requires the application to choose etiher 'screen' or 'window'. And we do not want to polyfill with an opinion.

For Chrome its a bit more complicated. Chrome currently requires an extension to be installed.
For getDisplayMedia to work there are two things that are needed to do:
1) check if the extension is installed and if not either install it on-demand (note that this requires certain keys in the html head) or throw an error
2) manage the communication with the background extension to obtain an id to feed into getUserMedia

Both are things that are currently done by applications. [this extension sample](https://github.com/otalk/getScreenMedia/tree/master/chrome-extension-sample) shows a way to do this (support is determined by checking a sessionStorage flag).
Including this in adapter increases the codebase considerably and will not be something that is useful for anyone that uses a different pattern to communicate with the extension.

**Comment by alvestrand** [comment]
"no" seems like a good answer.
grasping at straws: would it be feasible to polyfill the function in Chrome by having a call-out in the adapter that returned the chosen ID? This would then have to be initialized by the page owner to something that calls his private extension-comms API - which means that the page-owner would have to write code that is only useful with adapter.js, something we generally want to avoid.
The only (small) advantage to the page-owner would be that when getDisplayMedia becomes available, his page would take advantage of it at once, with the only difference being that his call-out function is no longer called.
But "no" is a perfectly reasonable answer too.

**Comment by fippo** [comment]
yeah, that is what I considered... bring your own function that returns a promise. But that still comes with a cost of plugging in adapter whereas its just drop-in.

And given the time window we have I doubt we get significant adoption of that feature until... September.

**Comment by fippo** [comment]
@huibk FYI since you made rather uneducated statements on stage again...

**Comment by jan-ivar** [comment]
In Firefox we could shim getDisplayMedia to offer window sharing only, or full-screen sharing only, but not both.

**Comment by jan-ivar** [comment]
I think we should reconsider shimming getDisplayMedia in adapter.js. In Firefox, adapter could open a web dialog to ask the user to pick between full-screen or window. That's the same amount of clicks as Chrome's current dialog, as I understand it.

**Comment by fippo** [comment]
i'd rather not do anything opinionated or involving UX here. This is a polyfill...

**Comment by fippo** [comment]
done in #841
