### ISSUE TITLE
Undefined `constraint` field into `OverconstrainedError`

### ISSUE THREAD

**Issue by yak80** [webrtcHacks/adapter#835]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Versions affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**
 Chrome 67.0.3396.87 MacOs

**adapter.js (e.g. 6.1.0)**
webrtc-adapter: 6.2.1

## Description
When I connect to not correct media device it return wrong error.

## Steps to reproduce
Exec `navigator.getUserMedia` with wrong device constraints(device  '4803cc..' not connected to PC):
```
constraints= {"audio":{"deviceId":{"exact":"default"}},"video":{"height":{"ideal":480},"width":{"ideal":640},"deviceId":{"exact":"4803cce5e1f6b324950c15cd9f55ae0ba87e08df68b2c8c746fdd210c994f14f"}}}
```
`origGetUserMedia` throw correct error: 
```
{name: "OverconstrainedError", message: null, constraint: "deviceId"}
```

but adapter throw error with undefined `constraint`:
```
{name: "OverconstrainedError", message: null, constraint: undefined}
```

Looks like prob is this [line](https://github.com/webrtc/adapter/blob/04385e855315077cf1d61febc26f5400632f6e3a/src/js/chrome/getusermedia.js#L151), it wait `constraintName` field, but receive `constraint`. Locally hot-fixed with next code:
```
      constraint: (typeof e.constraintName !==  'undefined')
          ? e.constraintName
          : e.constraint,
```

## Expected results
Must thrown error with correct `constraint` field:
```
{name: "OverconstrainedError", message: null, constraint: "deviceId"}
```

## Actual results
```
{name: "OverconstrainedError", message: null, constraint: undefined}
```

**Comment by fippo** [comment]
@jan-ivar can you take a look? You know mediacapture-streams better than I do

**Comment by jan-ivar** [comment]
> `origGetUserMedia` throw correct error:

Do you have a fiddle to show this? When I [test that](https://jsfiddle.net/jib1/m4tckheo/) in Chrome on OSX without adapter, I get:
```
OverconstrainedError
undefined
undefined
```

**Comment by yak80** [comment]
@jan-ivar 

When i debug adapter code i have `constraint: deviceId`:
```js
//webrtc-adapter/src/js/chrome/getusermedia.js:231

    var origGetUserMedia = navigator.mediaDevices.getUserMedia.
        bind(navigator.mediaDevices);
    navigator.mediaDevices.getUserMedia = function(cs) {
      return shimConstraints_(cs, function(tmp) {

        /*!!!*/ const c = {"audio": false,"video":{"deviceId":{"exact":"4803cce5e1f6b324950c15cd9f55ae0ba87e08df68b2c8c746fdd210c994f14f"}}};

        return origGetUserMedia(c).then(function(stream) {
          if (c.audio && !stream.getAudioTracks().length ||
              c.video && !stream.getVideoTracks().length) {
            stream.getTracks().forEach(function(track) {
              track.stop();
            });
            throw new DOMException('', 'NotFoundError');
          }
          return stream;
        }, function(e) {

            /*!!!*/ console.log('origGetUserMedia exception=', e);
            /*!!!*/ console.log('return reject exception', shimError_(e));

          return Promise.reject(shimError_(e));
        });
      });

```

Console:
```
getusermedia.js:247 
origGetUserMedia exception= OverconstrainedError {name: "OverconstrainedError", message: null, constraint: "deviceId"}

getusermedia.js:248 
return reject exception {name: "OverconstrainedError", message: null, constraint: undefined, toString: ƒ}
```

In any case Chrome returns field `constraint`, not `constraintName`. Looks like FF [too](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia): 
```
The error is an object of type OverconstrainedError, and has a `constraint` property whose... 
``` 

P.S.: into your fiddle i have undefined constraint too(possible prob that you use navigator.getUserMedia instead navigator.mediaDevices.getUserMedia).

**Comment by yak80** [comment]
@jan-ivar 

> Do you have a fiddle to show this? 

Yes, in [this fiddle](https://jsfiddle.net/geys4z13/) returned `constraint: 'deviceId'`

**Comment by jan-ivar** [comment]
Ah, sorry I got fooled by jsfiddle's *Resources* section (didn't see I was running with adapter). :-/

Your fix sounds reasonable, though at some point we should probably consider removing the chrome shimming here. @henbos do you see a reason to keep it? Anything specific we could feature-detect on here?

**Comment by fippo** [comment]
lets do a version switch? @guidou when did you fix the errors...
Also we should just mangle the error name instead of returning a new object which would have avoided the issue

**Comment by guidou** [comment]
IIRC, OverconstrainedError was introduced in Chrome M64.
