### ISSUE TITLE
URL.createObjectURL(stream) has been deprecated

### ISSUE THREAD

**Issue by gzelibean** [webrtcHacks/adapter#848]
The adapter.js uses this function, which will also be removed from Chrome soon and is deprecated in other browsers as well.

**Comment by Talbot3** [comment]
yes , today I have same problem on my production app.
that exception is 
```
Failed to execute createObject URL on URL
```

**Comment by fippo** [comment]
@gzelibean adapter only uses this in *very* old versions of Chrome. What line of code are you referring to?

**Comment by gzelibean** [comment]
@fippo thank you for the reply :) 

usage of createObjectURL() to attach streams to media elements. 
re:
L3074  this.src = URL.createObjectURL(stream); 
L3081 self.src = URL.createObjectURL(stream); 
L3087 self.src = URL.createObjectURL(stream); 
L3969 URL.createObjectURL = function(stream) 
I am using chrome version 59

**Comment by Talbot3** [comment]
current version is version 27 on windows xp system

**Comment by fippo** [comment]
@gzelibean the first four of these are inside a if (!('srcObject' in window.HTMLMediaElement.prototype)) block so they will not get executed in Chrome 59. Line 3969 is defining its own version of URL.createObjectURL and will not be affected by the deprecation.

@orangebook chrome 27 is more than four years old. This is not supported.

**Comment by gzelibean** [comment]
@fippo However, this specific line number inside the definition of URL.createObjectURL's new version causes the browser to throw a deprecation warning.

L4001 utils.deprecated('URL.createObjectURL(stream)',)

Does it mean it's OK to ignore the warning since it should not be affected by the deprecation?

**Comment by fippo** [comment]
This is an adapter.js warning, not a browser warning. Update your own code not to use URL.createObjectURL which is what both Chrome and adapter are trying to encourage by these annyoing warnings
