### ISSUE TITLE
Failed to execute 'createObjectURL' on 'URL'

### ISSUE THREAD

**Issue by Talbot3** [webrtcHacks/adapter#849]
- [ ] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name: Chrome 59.0.3071 and adapter.js version: 6.2.0
- [x] This issue only happens when adapter.js is used: yes 

## Versions affected

**Chrome Vertions >= 27.0.3071 **
Because WebKitVersion is WebKit 537.36
@see https://en.wikipedia.org/wiki/Google_Chrome_version_history
**adapter.js (6.2.0)**

## Description
Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.

## Steps to reproduce
UnKnown

## Expected results
no exception

## Actual results
```
Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
```

**Comment by fippo** [comment]
Without steps to reproduce this is not actionable. I tried the following in Chrome 59 (which is pretty old):
* go to https://webrtc.github.io/samples/src/content/getusermedia/gum/
* allow camera access
* paste URL.createObjectURL(stream) into the console

This works and does not throw an exception. What argument are you passing to URL.createObjectURL?

**Comment by Talbot3** [comment]
@fippo  argument is MediaStream
but chrome version very lower, may be just 27.but not found chrome offline installer 27

**Comment by fippo** [comment]
This sounds like a native error. In a chrome version that old you might want to try webkitURL.createObjectURL.

Either way, I don't think this is something where adapter is causing the issue and if then the recommendation is not to use a 5+ year old version of chrome.

**Comment by jeortegar** [comment]
@orangebook 
it just replaces this video.srcObject = (stream)
