### ISSUE TITLE
Safari 12 getUserMedia({deviceId: {exact: deviceId}}) produces Invalid Constraint.

### ISSUE THREAD

**Issue by thedracle** [webrtcHacks/adapter#850]
- [ X ] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
https://jsfiddle.net/cg1b93fm

- [ X ] I have provided browser name, version and adapter.js version
Safari 12, https://webrtc.github.io/adapter/adapter-latest.js

- [ N/A ] This issue only happens when adapter.js is used

Adapter should abstract this I assume so it works with the 'exact' syntax in Safari 12.

## Versions affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**
Safari 12, Mojave Beta.

**adapter.js (e.g. 6.1.0)**
Latest

## Description
Newest Safari 12 starts producing Invalid Constraint error when deviceId: {exact: deviceId} is provided.

## Steps to reproduce
Attempt to set a deviceId using the 'exact' syntax.

## Expected results
gUM should succeed.

## Actual results
gUM does not succeed.

**Comment by fippo** [comment]
is this a regression in safari on mojave beta? If so you might want to file a bug on https://bugs.webkit.org

cc @youennf

**Comment by thedracle** [comment]
@fippo,
This isn't due to anyones knowledge to a spec change potentially?

If not, I'll try to pursue it with WebKit.

Is it possible if Safari 12 releases with this that Adapter would still provide a work-around for uniform compatibility between browsers?

**Comment by thehunmonkgroup** [comment]
Using reference code at https://staging-connect.circleanywhere.com/public/misc/safari-device-exact.html, using getUserMedia({deviceId: {exact: deviceId}}) with adapter-latest.js works for me on iOS 11.4.1, iOS 12 Beta 4, and Safari Technology Preview 61 on OS X High Sierra.

**Comment by thedracle** [comment]
The results for https://staging-connect.circleanywhere.com/public/misc/safari-device-exact.html produce "Invalid Constraint Error" for Safari 12 (14606.1.24.40.1) on Mojave Beta:
<img width="878" alt="screen shot 2018-07-23 at 4 58 19 pm" src="https://user-images.githubusercontent.com/1301817/43107306-a3df42f0-8e99-11e8-85a3-3b52ccacdcc6.png">

**Comment by thedracle** [comment]
https://bugs.webkit.org/show_bug.cgi?id=187933

**Comment by tgabi333** [comment]
seems to be resolved?

**Comment by fippo** [comment]
yeah, closing here.
