### ISSUE TITLE
Need guideline to add end-of-candidate for React Native Package to communicate with Edge

### ISSUE THREAD

**Issue by Shhzdmrz** [webrtcHacks/adapter#852]
Hi,

Sorry to ask this question here but need guideline to add end-of-candidate to communicate with Edge otherwise it generate warning `Timeout for addRemoteCandidate. Consider sending an end-of-candidates notification`. 

I am using [react native package webrtc](https://github.com/oney/react-native-webrtc) which is not handling end-of-candidate as WebRTC Adapter handling for Edge. Could any one please guide my how should I add end-of-candidate?

I am using WebRTC Adapter for Edge and I am receiving end-of-candidate but from the app I am unable to send end-of-candidate.

Thank you in advance.

**Comment by mariuszbeltowski** [comment]
@Shhzdmrz As far as I know `end-of-candidates` required by the edge is just an empty candidate object `{}`

**Comment by fippo** [comment]
when you see [this](https://github.com/oney/react-native-webrtc/blob/master/RTCPeerConnection.js#L316-L318) in react-native you need to signal it *somehow* to the Edge peer which should call pc.addIceCandidate(null) at that point.

How you do that is beyond the scope of adapter or WebRTC.

**Comment by Shhzdmrz** [comment]
Edge is setting local description with end-of-candidate and also set it on the app as remote description for edge but I think app also need to add end-of-candidate before setting remote description on Edge. Please correct me If i am wrong.
How should I set the app local description with end of candidate and same on the remote description?
@bmariusz on Edge I am setting it I need to set it on the android side.
@fippo I need to set it inside the app candidate Edge is setting correctly.

**Comment by mariuszbeltowski** [comment]
Edge must receive this `end-of-candidate` from its peer which is simply represented by `null` candidate. So, on the peer side, when candidates gathering is complete `RTCPeerConnection.prototype.onicecandidate` will give you a `null` candidate, and you should notify Edge peer about this and run `pc.addIceCandidate(null)` there as @fippo mentioned.

**Comment by fippo** [comment]
are you using trickle-ice (i.e. do you call addIceCandidate at all) or not?

**Comment by Shhzdmrz** [comment]
@bmariusz I tried adding null candidate as addIceCandidate(null) after complete gathering but it returning the error unable to add candidate. This only happened on app side where I am using above react-native-webrtc package.

**Comment by Shhzdmrz** [comment]
@fippo yes I am calling it but when I am adding null candidate its giving me error for unable to add.

**Comment by fippo** [comment]
don't do addIceCandiate(null) in react-native-webrtc, this is only required in Edge. adapter will ignore it for all other browsers but adapter doesn't support react-native-webrtc

**Comment by Shhzdmrz** [comment]
@fippo thats what I am avoiding and Chrome is working fine without it but Edge I think required. So what should I do to notify Edge in remote description about end-of-candidate ?

**Comment by fippo** [comment]
try adding a=end-of-candidates in each section of the SDP.

**Comment by fippo** [comment]
closing, please reopen or holler if there is more.
