### ISSUE TITLE
ontrack transceiver shim broken in M69+

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#857]
- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used

## Versions affected
**Browser name including version (e.g. Chrome 69.0.3497.12)**
**adapter.js (e.g. 6.3.0)**

## Description

tests fail currently with this error:
```
  track event
    the event has
      ✖ a transceiver that has a receiver
        HeadlessChrome 69.0.3497 (Linux 0.0.0)
      Error: Uncaught TypeError: Cannot read property 'receiver' of null 
    (node_modules/chai/chai.js:1179)
```
This is because we do not attempt to shim trackEvent.transceiver if `RTCRtpTransceiver in window`.
But while that is true, the transceiver is only set with sdpSemantics set to unified-plan
I'd prefer to avoid an unconditional shim or one that has a specific version...

**Comment by alvestrand** [comment]
You can detect this case by checking if the transceiver has a receiver, I think.
In Unified Plan it will always have one; in plan B .... it seems not.

**Comment by fippo** [comment]
yes, the shim doesn't attempt to overwrite for that reason. But it won't get activated when transceivers are implemented. #861 fixes that but it means there is no way for the shim to automatically kick in when it is no longer required which is very sad.
