### ISSUE TITLE
CreateOffer only works with promises in Safari 11.1.2

### ISSUE THREAD

**Issue by kekkokk** [webrtcHacks/adapter#859]
- [ X ] I have provided steps to reproduce
[Jsfiddle](https://jsfiddle.net/cg1b93fm/18/)
- [ X ] I have provided browser name, version and adapter.js version
Safari 11.1.2 on MacOs Sierra 10.12.6 / adapterjs 6.1.3
- [ X ] This issue only happens when adapter.js is used
Not really, with adapter, promise based createOffer works, without both of them fails.

## Description
When creating an offer with constraints { offerToReceiveAudio: true, offerToReceiveVideo: true } with a callback style createoffer, the sdps generated are only:

```
{sdp: "v=0
↵o=- 6889517193703606396 2 IN IP4 127.0.0.1
↵s=-
↵t=0 0
↵a=msid-semantic: WMS
↵", type: "offer"}
```

when using promise based createOffer, everything works fine.
Shouldn't adapter shim the legacy callback style in Safari and produce the same result?

**Comment by fippo** [comment]
this looks like a conflict in the order of shims... shimCreateOfferLegacy is called after shimCallbackAPI and only does promises.

**Comment by fippo** [comment]
Thanks for reporting and :clap: @dagingaa for fixing it.
I'll publish a new patch release shortly.

Also cc @youennf in case you have people running into this.

**Comment by kekkokk** [comment]
do you plan to release 6.3.2 soon on npm?

**Comment by fippo** [comment]
done now
