### ISSUE TITLE
ignore addIceCandidate with empty candidate string

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#863]
we should ignore addIceCandidate where candidate is the empty string which is the new way to signal end-of-candidates.

No browsers emit this yet. Main problem is determining when to stop ignoring this...

**Comment by jan-ivar** [comment]
The best we can do here I think is to make guesses as to when browsers might fix this, and ignore for versions older than that guess, and then keep updating adapter until browsers fix this. :-(

**Comment by fippo** [comment]
yeah. we might consider doing this only when we know a fix version... that way we at least remove the backward compat worry

**Comment by fippo** [comment]
Chrome 74 (?) just started not throwing on candidate: "" so we might ignore it in Chrome < 74 for backward compat.

**Comment by fippo** [comment]
Hrm... so Firefox Nightly just started generating those candidates (h/t @docfaraday).
Afaics Chrome still/again (?!) throws on
```
pc.addIceCandidate({sdpMLineIndex: 0, candidate: ""})
```

**Comment by fippo** [comment]
#983 fixed this for Chrome and Firefox. Interestingly, Chrome M77 still throws natively.
Remains an issue for Safari where @dagingaa filed [an issue](https://bugs.webkit.org/show_bug.cgi?id=199316)

**Comment by fippo** [comment]
@youennf can you take a look at the webkit issue filed please and let me know what the plans for this are? I can't polyfill it without an "this is no longer required" indication

**Comment by mpizenberg** [comment]
Just got bitten by this for Safari. The symptom was that the non-safari peer would see the safari one but not vice-versa.

**Comment by hthetiot** [comment]
> Chrome 74 (?) just started not throwing on candidate: "" so we might ignore it in Chrome < 74 for backward compat.

I respectfully disagree with that statement, we logs all Javascript Errors and I saw following errors on Chrome 81+ when using webrtc-adapter, we ended up filtering empty candidate string, we also suspect that the empty candidate is due webrtc-adapter itself but we have not proven that.

> bad ice candidate (OperationError): {"type":"candidate","label":2,"id":"2","candidate":"candidate:3641010140 1 udp 2122260223 169.254.60.68 53319 typ host generation 0 ufrag u0l3 network-id 3"}

**Comment by snettah** [comment]
if you get this error on Safari (14 for me)

`Unhandled Rejection (OperationError): Expect line: candidate:<candidate-str>`

check your candidate.candidate if the string il empty, I've got this error only with Safari.

```
    socket.on("candidate", async (id, candidate) => {
      if (candidate && candidate.candidate !== "") {
        try {
```

**Comment by fippo** [comment]
@youennf ping. Polyfilling this without a fix version when this is no longer required will cause long-term harm

**Comment by jan-ivar** [comment]
Can't we polyfill it like this?
```js
    const nativeAddIceCandidate = window.RTCPeerConnection.prototype.addIceCandidate;
    window.RTCPeerConnection.prototype.addIceCandidate = async function addIceCandidate() {
      try {
        await nativeAddIceCandidate.apply(this, arguments);
      } catch (e) {
        if (e.name != "OperationError" || typeof arguments[0] != "object" || arguments[0].candidate !== "") {
          throw e;
        }
      }
    }
  }
```
...or whatever the non-async/await version would be.

**Comment by fippo** [comment]
practically yes but that code would stay there forever and may lead to deprioritizing any fixes.

**Comment by jan-ivar** [comment]
That's the nature of the game with polyfills, is it not?

Of course if we could polyfill the `"completed"` connectionState at the same time that would be ideal!

**Comment by youennf** [comment]
Quickly looking, this seems solved in WebKit ToT and Safari Tech Preview, probably since September 2020.

**Comment by youennf** [comment]
Looking at https://wpt.fyi/results/webrtc/RTCPeerConnection-addIceCandidate.html?label=experimental&label=master&aligned, I can see some tests where Safari is the only one failing.
Let me know if you are aware of some related failures that may be particularly annoying.
