### ISSUE TITLE
createOffer() offerToReceiveAudio/offerToReceiveVideo shim doesn't work between Chrome/iOS

### ISSUE THREAD

**Issue by thehunmonkgroup** [webrtcHacks/adapter#869]
- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used

## Versions affected

Chrome 68.0.3440.106 (Official Build) (64-bit) / iOS 11.4.1 / adapter-latest.js

## Description

Using the test code at https://staging-connect.circleanywhere.com/public/ios/adapter-createoffer-options/#afb6e along with latest adapter.js, which is supposed to correctly shim offerToReceiveAudio/offerToReceiveVideo options on RTCPeerConnection.createOffer().

However, setting both of those options to false still results in audio/video being received from the peer when the two endpoints are Chrome and iOS.

I will add that I was getting inconsistent results, sometimes audio/video wasn't received and sometimes it was, however, they should never be received in this situation.

## Steps to reproduce

1. Set createOffer() offerToReceiveAudio/offerToReceiveVideo options on a peer connection to false
2. Play received remote stream

## Expected results

No audio/video should be received

## Actual results

Audio/video are received

**Comment by fippo** [comment]
ah yes... safari has "plan b transceivers" which means this doesn't work. See #676.
Wondering if we should at least warn about this...

**Comment by fippo** [comment]
can you check in tech preview which should support unified plan and therefore have the proper transceivers?

**Comment by thehunmonkgroup** [comment]
Ran some quick tests, and this still seems to be an issue. Audio/video are still received by the peer in Safari Tech Preview even when offerToReceiveAudio/offerToReceiveVideo options on a peer connection are set to false

**Comment by fippo** [comment]
Might be fixed in [release 71](https://webkit.org/blog/8517/release-notes-for-safari-technology-preview-71/) of STP:
```
Enabled setting RTCRtpTransceiver.direction (r237974)
Fixed RTCPeerConnection.getTransceivers to always expose all transceivers (r238150)
```

**Comment by thehunmonkgroup** [comment]
Seems to be working now.
