### ISSUE TITLE
Investigate if we can use chromium stable-2 versions

### ISSUE THREAD

**Issue by KaptenJansson** [webrtcHacks/adapter#87]
[Chromium builds](https://www.chromium.org/getting-involved/download-chromium)

Issue created based on https://github.com/webrtc/adapter/pull/86#issuecomment-122756406

**Comment by fippo** [comment]
http://stackoverflow.com/a/22050581/4352772 was very, very, helpful. The gist is:
go to https://omahaproxy.appspot.com/, enter your favorite version in the position lookup thing.
Alternatively (undocumented) get https://omahaproxy.appspot.com/revision.json?version=46.0.2478.0

Extract chromium_base_position, go to http://commondatastorage.googleapis.com/chromium-browser-continuous/index.html
Grab zip from http://commondatastorage.googleapis.com/chromium-browser-continuous/index.html?prefix=_architecture_/_chromium_base_
Unzip, profit.

Maybe we should consider moving to those zips in favor of debs as well WRT to #118 (even though I think this needs a little more shell magic)

**Comment by KaptenJansson** [comment]
Sounds good, however I think if we invest in this, lets skip shell and use python instead to ensure higher portability, apps in shell behave differently on Mac Os and Linux (things like regex in grep etc). Also this could be easily adapted to even work on Windows (pretty sure python can eliminate path issues etc).

@phoglund wrote the python framework for apprtc where among other things GAE is downloaded etc, we could reuse that. E.g.: https://github.com/webrtc/apprtc/blob/master/build/get_python_test_deps.py.

**Comment by fippo** [comment]
python sounds like a plan. Or we just use nodejs since it's a dep for travis anyway. I have no opinion.

minor issue I ran into with chrome 41: 

```
Chrome version must be >= 42.0.2311.0
```

so that is the oldest version we can test. The tests fail on the srcObject things but that was expected.

**Comment by KaptenJansson** [comment]
If nodejes can do it without shell (or can be executed in whatever "shell" it's installed in), then yes lets do it.

**Comment by fippo** [comment]
small steps however, let's download zips first: 
https://github.com/fippo/travis-multirunner/tree/zipdownload

Ran into an issue with the dev version. omahaproxy says the current version is 46.0.2478.0 which translates into rev 342568 but the [download directory](https://commondatastorage.googleapis.com/chromium-browser-continuous/index.html?prefix=Linux_x64/342568/) is empty. Didn't have much luck with several versions from https://omahaproxy.appspot.com/history either. Hrm...

**Comment by KaptenJansson** [comment]
Do we still want to do this? I think it will be hard to get right and stable due to the issues you mentioned. I think it's more important to get a solution that works cross platform, albeit only downloading the latest version from the different release channels.

**Comment by fippo** [comment]
well, I never got an answer from anyone on the chromium list wrt to downloading zips so I don't see how we can do that unless we manually track a "last known good old version".

I'd still like to do it but not sure when i'll have time. Assign it to me please so we know it is handled.

**Comment by KaptenJansson** [comment]
Lets close this in favor of unit tests.
