### ISSUE TITLE
Provide RTCSctpTransport.maxChannels

### ISSUE THREAD

**Issue by lgrahl** [webrtcHacks/adapter#872]
Perhaps we should add an implementation of the recently added `RTCSctpTransport.maxChannels` attribute. Considering how extremely slow progress is going for pretty much all data channel implementations in browsers, it's unlikely we will see this soon.

This might not be easy though. Detecting this value is impossible since we don't have access to SCTP. The only thing we can do is match local and remote browser (and version, if possible) to a matrix.

**Comment by lgrahl** [comment]
So, I guess this is more of a question for now whether we want to do that.

**Comment by fippo** [comment]
is there a safe minimum value we could provide in order to allow the right programming model?

**Comment by lgrahl** [comment]
When we know we're talking to a browser, [kind of yes](https://stackoverflow.com/a/51704584/2848269). In any other case, we don't have a clue and I'm not sure what to do in that case. The minimum could be as low as 1.

**Comment by fippo** [comment]
closing given that this is only for plan-b and plan-b is going away this doesn't seem to be important anymore
