### ISSUE TITLE
Pull shimCreateObjectURL once Chrome 71 rolls around

### ISSUE THREAD

**Issue by jan-ivar** [webrtcHacks/adapter#874]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Versions affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**
All

**adapter.js (e.g. 6.1.0)**
All

## Description
Neither Safari nor Firefox 62 nor Chrome 71 support createObectURL anymore (unsure about Edge), so once Chrome 71 is released, I propose adapter pull its createObjectURL shim, and get back to shimming the spec only.

## Steps to reproduce
[jsfiddle](https://jsfiddle.net/jib1/nehux7yg/)

## Expected results
TypeError

## Actual results
Works.

**Comment by mmckenziedev** [comment]
To be clear, browsers no longer support that API for use on MediaStream objects. `createObectURL` still exists and is still the only way to assign `Blob` or `MediaSource` objects to a media element.

**Comment by fippo** [comment]
Yes. We are just removing the shim which only applied to mediastreams anyway
