### ISSUE TITLE
InvalidAccessError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Failed to set remote video description send parameters.

### ISSUE THREAD

**Issue by wj985712588** [webrtcHacks/adapter#884]
## Versions affected

Both CefSharp 49.0/CefSharp 67.0

adapter.js from url:https://webrtchacks.github.io/adapter/adapter-latest.js  (5399 lines)

## Description

InvalidAccessError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Failed to set remote video description send parameters.

## Steps to reproduce

Create Offer from ios device(not sarfri),and add it to CefSharp 49.0/67.0 on windows

## Expected results

add successfully

## Actual results

failed(maybe  h.264?)

**Comment by fippo** [comment]
codec interop issue, see https://bugs.chromium.org/p/webrtc/issues/detail?id=4957
