### ISSUE TITLE
need to add dist/ to release

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#886]
master is currently missing a step to build the ES5 version when making a release. Thanks @ibc for noticing

**Comment by fippo** [comment]
probably just a "git add"

**Comment by ibc** [comment]
Adding `dist/xxxxxx.js` to the repo and NPM package is not the proper way to go nowadays. Such a `xxxxxxx.js` file is usually transpiled to ES5, which is not needed in current browsers. Even if it was needed, the new "approach" is having dependencies in ES6 and let the user app transpile them if needed.

So, couldn't `main` in package.json just point to `src` dir? And, taking into account that this lib exports different versions, wouldn't it make sense to properly export all of them so the app takes the preferred one?:

```js
const { adapterNoEdge as adapter } from 'webrtc-adapter`;
```

Also, remove all those ugly `xxxxx_no_global.js` files and replace them with a simple "helper":

```js
const { adapterNoEdge as adapter } from 'webrtc-adapter`;

adapter.exposeGlobals(); // creates window.RTCPeerConnection, etc.
```

Let's move to 2018!

**Comment by fippo** [comment]
hrm... since this version is going to be a breaking change not transpiling to ES5 might be the way to go indeed... :-)

**Comment by fippo** [comment]
I thought you needed module in package.json, not main?
https://medium.com/@kelin2025/so-you-wanna-use-es6-modules-714f48b3a953

**Comment by ibc** [comment]
AFAIS such a `module` entry is intended for Node.js apps. No idea, honestly.

**Comment by fippo** [comment]
using
```
  "module": "./src/js/adapter_core.js",
```
and changing the export there to
```
export default adapter;
```
worked for me. After I changed all my `const adapter = require('webrtc-adapter');` to `import adapter from 'webrtc-adapter';`
:sob:

**Comment by fippo** [comment]
the above worked for me so will publish under the next tag soon.

**Comment by sergek** [comment]
> the new "approach" is having dependencies in ES6 and let the user app transpile them if needed.

Apparently the team behind the most popular transpiler - babel are no fans of this "new" approach.

Babel 7 has stopped to transpile anything inside node_modules directory, and I just spent a half a day of my life trying to find a way around this.

Guys, can you explain how this even supposed to work? I have an app which import a dependency - react-qr-reader. In the index file of this package there is a code:

// Require adapter to support older browser implementations
require('webrtc-adapter')

In the required file the first thing that's happening is 
import {adapterFactory} from './adapter_factory.js';

What happens next in Chrome - SyntaxError: Unexpected token {

How can this work?

**Comment by ajbeaven** [comment]
Completely agree. Shipping a compiled version is way more desirable and I don't understand why you would not.

[Here's](https://babeljs.io/blog/2018/06/26/on-consuming-and-publishing-es2015+-packages#publishing-non-standard-syntax) what the guys from babel have to say about this (in 2020):

> **Publishing Non-standard Syntax**
>
> As a library author, publishing non-standard syntax is setting our users up for possible inconsistencies, refactoring, and breakage of their projects. Because a TC39 proposal (even at Stage 3) has a possibility of changing, it means we will inevitability have to change the library code. A "new" proposal doesn't mean the idea is fixed or certain but rather that we collectively want to explore the solution space.
> 
> At least if we ship the compiled version, it will still work, and the library maintainer can change the output so that it compiles into code that works the same as before. Shipping the uncompiled version means that anyone consuming a package needs to have a build step to use it and needs to have the same configuration of Babel as us. This is in the same bucket as using TS/JSX/Flow: we wouldn't expect consumers to configure the same compiler environment just because we used them.
