### ISSUE TITLE
Chrome getDisplayMedia width and height constraints

### ISSUE THREAD

**Issue by fh-nano** [webrtcHacks/adapter#887]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Versions affected

**Chrome 69.0.3497.100**

**adapter.js (v6.4.0)**

## Description
Screen resolution can not be set with getDisplayMedia on current adapter.js release. 

When passing in constraints to getDisplayMedia containing width/height properties, those properties get ignored

in https://github.com/webrtcHacks/adapter/blob/8e5e27ccfa34f18e14f34d9ec1fc4e04734319cb/src/js/chrome/chrome_shim.js#L850

I can see that resolution is ignored:

` constraints.video = {
            mandatory: {
              chromeMediaSource: 'desktop',
              chromeMediaSourceId: sourceId,
              maxFrameRate: constraints.video.frameRate || 3
            }
          };`

## Expected results
Screen share preview should have the expected resolution of 1280x720 when passing in:

`  {...,  width: 1280, height: 720, framerate: 5}`

or similar (maxWidth/maxHeight).

## Actual results
The resolution is not applied in Chrome. 
In Firefox on the other hand setting resolution works pretty well.

Is there a reason why those values get ignored? I would like to limit the resolution on huge displays (eg. 4k) to 1080p max.

I could get it to work by changing shimGetDisplayMedia and adding

`              maxWidth: 1920,
              maxHeight: 1080,`

to the mandatory object.

Thanks for all your work and
best regards

Finn

**Comment by fippo** [comment]
The shim was written assuming there would be no constraints, it probably makes sense to update that given that constraints are in the specification now. @jan-ivar wdyt?

Until we figure out the right course of action you might try using track.applyConstraints to change the width afterwards

**Comment by fh-nano** [comment]
Thank you very much for the quick response.
I will check track.applyConstraints in the meanwhile

**Comment by fippo** [comment]
oops, forgot to tag this in the commit. PR in #890

**Comment by fippo** [comment]
this should be in 6.4.1, let me know if it works.

**Comment by fippo** [comment]
6.4.1 was bad, so was 6.4.2.

6.4.3 should be better.
