### ISSUE TITLE
Script should silently fail if `RTCPeerConnection` is undefined

### ISSUE THREAD

**Issue by igor10k** [webrtcHacks/adapter#895]
- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used

## Versions affected

Browser: **Google Crawler**
**webrtc-adapter 6.4.3**

## Description

Google crawler uses some special version of Chrome to crawl pages and it has no `RTCPeerConnection` support. That leads to google crawler seeing blank pages for SPA because of a JS error.

## Steps to reproduce

1. Import `webrtc-adapter` somewhere in any SPA (e.g create-react-app) so it's all bundled in a single file
2. Use https://search.google.com/test/mobile-friendly to see that it fails with `Uncaught TypeError: Cannot read property 'prototype' of undefined` that happens on `RTCPeerConnection.prototype`

## Expected results

Google crawler can render the page

## Actual results

Google crawler can not render the page

**Comment by fippo** [comment]
I just tested and could not reproduce testing https://webrtc.github.io/samples/src/content/peerconnection/pc1/ -- does it still happen?

**Comment by igor10k** [comment]
@fippo yes.

Click on "View Details":

<img width="300" alt="screen shot 2018-11-12 at 21 32 15_" src="https://user-images.githubusercontent.com/1244342/48370614-8be6c200-e6c2-11e8-87bd-3e46b84835ae.png">

Observe the error at the bottom:

<img width="300" alt="screen shot 2018-11-12 at 21 33 28" src="https://user-images.githubusercontent.com/1244342/48370659-9e60fb80-e6c2-11e8-8ec9-83075d90624e.png">

**Comment by mariuszbeltowski** [comment]
Fixed in https://github.com/webrtcHacks/adapter/pull/899 Could you review @fippo, please?
