### ISSUE TITLE
Move getDisplayMedia to navigator.mediaDevices

### ISSUE THREAD

**Issue by jan-ivar** [webrtcHacks/adapter#896]
A heads-up that `getDisplayMedia` just moved to `navigator.mediaDevices.getDisplayMedia` in https://github.com/w3c/mediacapture-screen-share/pull/86.

We should update adapter.js to match ASAP.

**Comment by fippo** [comment]
yes, probably worth a patch release of the old version. I suspect we'll need to keep the old version around for a while. But MAYBE add a deprecation warning :-)

@jan-ivar can you add a note to the blog post?

**Comment by jan-ivar** [comment]
[Done](https://blog.mozilla.org/webrtc/getdisplaymedia-now-available-in-adapter-js/). Thanks @fippo for the reminder!

**Comment by fippo** [comment]
How do we handle backward compat? Do we shim navigator.getDisplayMedia if navigator.mediaDevices.getDisplayMedia is available natively?
