### ISSUE TITLE
Unicode Character 'CYRILLIC CAPITAL LETTER EM' in source code

### ISSUE THREAD

**Issue by kekkokk** [webrtcHacks/adapter#900]
## Versions affected

AdapterJS release 6.4.5

## Description

Webpack complains about the presence of a 

`Unicode Character 'CYRILLIC CAPITAL LETTER EM' (U+041C)
` (what??) in the dist code.

To be more specific:

![screen shot 2018-11-14 at 17 29 16](https://user-images.githubusercontent.com/15072723/48496681-d8e9a600-e832-11e8-823a-ed3bad2d8c60.png)

in line 3667 and 4720 of adapter.js (full)

**Comment by fippo** [comment]
*sigh* why did the linter not catch this? Fix upcoming...

**Comment by fippo** [comment]
fix should be published as 6.4.6

**Comment by kekkokk** [comment]
Since we are there, can I ask you how to use getDisplayMedia on chrome 70+ with Experimental Web Platform features flags enabled?
should I ask for navigator.mediadevices.getDisplayMedia?
cause I put few logs in adapter and seems to never reach the code (just did a 10 min try yesterday so I'm not really sure). 
because navigator.getDisplayMedia seems to does not exist. 

[W3C](https://w3c.github.io/mediacapture-screen-share/#bib-getusermedia) here they use navigator.mediadevices.getusermedia

[MOZILLA](https://blog.mozilla.org/webrtc/getdisplaymedia-now-available-in-adapter-js/) here they instead use navigator.getDisplayMedia()

**Comment by fippo** [comment]
the mozilla post has been updated. If you used navigator.getDisplayMedia in adapter 6.x please use navigator.mediaDevices.getDisplayMedia in 7.x -- this is also what should be available natively in Chrome
