### ISSUE TITLE
stun filtering in edge seems to be broken

### ISSUE THREAD

**Issue by justinIs** [webrtcHacks/adapter#903]
- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Versions affected

**EDGE (all)**

**adapter.js (e.g. 6.4.6)**

## Description
In `shimPeerConnection` here: 
https://github.com/webrtcHacks/adapter/blob/f6aa47d8b9dcd684ab8e08da58ab0cc8ea9c5a80/src/js/edge/edge_shim.js#L74
This code block is not passing the `edgeVersion` to the `filterIceServers` method, causing it to always fail.
In master I see that code is actually fixed: https://github.com/webrtcHacks/adapter/blob/master/src/js/edge/edge_shim.js#L75

But that change was made 12 days ago, in the `6.4.6` release the code is still broken. This is causing issues for EDGE not being able to perform STUN while gathering ICE candidates, which prevents call setup from happening.

## Steps to reproduce
Create a peer connection on EDGE

## Expected results
Does not filter out valid ICEServers

## Actual results
Filters out valid ICEServers

**Comment by fippo** [comment]
Edge can (still) not use stun servers sadly. Check this e.g. by using RTCIceGatherer manually. And oddly I get errors in the insider release which suggest it might not be safe to pass them...

Will check if that is safe to cherry-pick and then get it into the next patch release.

**Comment by justinIs** [comment]
Do you know if there exists some ticket with Microsoft for this issue? Surely someone must be looking into it.

All I can find is this one here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14489825/

has no response and is a year old.

**Comment by fippo** [comment]
lets page @aboba -- seems like we're lucky that adapter had this bug about filtering?

**Comment by aboba** [comment]
Although there is no open ticket, the issue (inability to support STUN servers) still exists in Edge (though not in the UWP SDKs).

**Comment by fippo** [comment]
@aboba yeah but I have seen RTCIceGatherer throw as well which is a bit surprising:
```
var g = new RTCIceGatherer({gatherPolicy: "all", iceServers: [{urls: "stun:stun.l.google.com:19302?transport=udp"}]})
```
which suggests the "filter stun" in native is broken and the adapter bug of still filtering protected from that. So I am a bit hesitant to fix it.

Adding bogus username and credentials makes things work.

**Comment by justinIs** [comment]
@fippo what do you mean by

> Adding bogus username and credentials makes things work.

Does that cause STUN to work?

**Comment by fippo** [comment]
@justinIs no, it just does not throw anymore like it is supposed to do. If you want to get serverreflexive candidates without running a turn server, you might try passing a turn url with invalid credentials.

**Comment by justinIs** [comment]
oh awesome, thanks for the info.

**Comment by fippo** [comment]
It seems we need to continue filtering ourselves since 17.17134 throws an exception on stun urls too :-(

**Comment by ceztko** [comment]
> It seems we need to continue filtering ourselves since 17.17134 throws an exception on stun urls too :-(

@fippo , I did some more testing: similarly to what I've done in #911, I tried to disable `filterIceServers` in `adapter.js` with Edge 42.17134.1.0 and just use STUN servers: the connection didn't establish (so STUN servers are still not supported) but I didn't receive any exception from Edge. Microsoft EdgeHTML version is 17.17134 . When/where exactly are you observing the exception?

**Comment by fippo** [comment]
@ceztko did
```
var g = new RTCIceGatherer({gatherPolicy: "all", iceServers: [{urls: "stun:stun.l.google.com:19302?transport=udp"}]})
```
not throw? It does for me both in Edge 17.17134 and the Windows insider builds

**Comment by ceztko** [comment]
> @ceztko did
> 
> ```
> var g = new RTCIceGatherer({gatherPolicy: "all", iceServers: [{urls: "stun:stun.l.google.com:19302?transport=udp"}]})
> ```
> not throw? It does for me both in Edge 17.17134 and the Windows insider builds

Yes, it definetely crash with error "SCRIPT5022: InvalidAccessError". This happen with or without `filterIceServers` enabled, so I guess there's no wrapping for this `RTCIceGatherer` in `adapter.js`. It does **not** crash if I do:

```
var g = new RTCIceGatherer({gatherPolicy: "all", iceServers: [{urls: "stun:stun.l.google.com:19302"}]})
```

So, removing `?transport=udp` fixes the crash in this case (STUN doesn't work anyway, though).

**Comment by ceztko** [comment]
> So, removing `?transport=udp` fixes the crash in this case (STUN doesn't work anyway, though).

Ah, ok. So the filter wants `?transport=udp` for TURN servers but does **not** want it for STUN? I understood it required `?transport=udp` for both, sorry.

**Comment by fippo** [comment]
the underlying behaviour of Edge is a bit... weird.
