### ISSUE TITLE
shim connectionState + connectionstatechange event

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#909]
Chrome just landed connectionState in M72, see https://bugs.chromium.org/p/chromium/issues/detail?id=823144
Firefox lacks support, see https://bugzilla.mozilla.org/show_bug.cgi?id=1265827
Safari has it in tech preview and 11.1.2. Bug here: https://bugs.webkit.org/show_bug.cgi?id=169978
Edge/RTCPeerConnection-shim supports it

Given that Chromes iceConnectionState was essentially connectionState it should be possible to polyfill there. But this is only useful if we do the same in Firefox. Where iceConnectionState is actually the iceConnectionState...

**Comment by fippo** [comment]
[WIP branch](https://github.com/webrtcHacks/adapter/tree/connectionstatechange)

**Comment by nils-ohlmeier** [comment]
Polyfilling for Firefox makes probably sense, since right now it would be purely based on the ICE connection state any how.

The only corner case is how to aggregate if the PC has multiple ICE transports (instead of bundling them).
