### ISSUE TITLE
figure out if there is a way to test Edge through selenium

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#92]
http://blogs.windows.com/msedgedev/2015/07/23/bringing-automated-testing-to-microsoft-edge-through-webdriver/
-- Edge just got support for this. Possibly might make more sense to do this in the samples which are already using Selenium.

@alvestrand :-)

**Comment by KaptenJansson** [comment]
Travis-ci does not support Windows yet (it's being worked on but slowly), Linux and Mac only.

As an alternative maybe we could use http://www.appveyor.com/ for Windows?

**Comment by KaptenJansson** [comment]
And yes I do agree we should do this in samples for Edge due to the use of Selenium.

**Comment by KaptenJansson** [comment]
Filed https://github.com/webrtc/samples/issues/592 in the samples repo for this.

**Comment by xdumaine** [comment]
@KaptenJansson Do you know how to get tests to run on mac? I'd like to avoid setting up a vm just for running tests if possible.

**Comment by KaptenJansson** [comment]
Travis multi-runner currently uses .deb packages. I've not looked into if there are more things that are needed to be changed in order for this run on Mac. Please file an issue and I will see if we can get it to work.
