### ISSUE TITLE
Calling getDisplayMedia ends up with "TypeError: invalid calling object" in Edge

### ISSUE THREAD

**Issue by windicted** [webrtcHacks/adapter#926]
- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used

## Versions affected

**Microsoft Edge 44.17763.1.0**

**adapter.js 7.x.x and latest**

## Description

Calling `navigator.mediaDevices.getDisplayMedia({ video: true })` ends up with "TypeError: invalid calling object" error in Edge. It seems the error is thrown due to a typo in the following line: https://github.com/webrtcHacks/adapter/blob/a31beed5c9d317e4cac2cefef19053e3671f63c6/src/js/edge/getdisplaymedia.js#L23

It seems that instead of `window.navigator.mediaDevices` we should pass `window.navigator` to the `bind` function. 

## Steps to reproduce

1) Open in Microsoft Edge any page which loads adapter.js (e.g https://webrtc.github.io/samples/src/content/getusermedia/gum/)
2) Open Developer Tools
3) Execute the following code in the Console:
```
navigator.mediaDevices.getDisplayMedia({ video: true }).catch((error) => { alert(error); })
```

## Expected results

Appearing of a dialog which asks for permission to share your screen.

## Actual results

Appearing of an alert with a following message: "TypeError: invalid calling object".

**Comment by fippo** [comment]
Thank you! Missing automated tests for this. PR with the fix is up, will publish a new version shortly

**Comment by fippo** [comment]
Published the new version as 7.2.1 -- not sure when I can update the webrtc.github.io version, hopefully you're using it from npm.

**Comment by windicted** [comment]
Thank you! NPM version suits me well.

**Comment by fippo** [comment]
webrtc.github.io is also updated now, thanks @alvestrand
