### ISSUE TITLE
How to obtain object from navigator.getUserMedia() in mobile web?

### ISSUE THREAD

**Issue by hktalent** [webrtcHacks/adapter#928]
How to obtain object from navigator.getUserMedia() in ios mobile web?
chrome ios undefined is not an object (evaluating 'navigator.mediaDevices.getUserMedia ios

https://stackoverflow.com/questions/44576832/how-to-obtain-object-from-navigator-getusermedia-in-mobile-web

iOS safari is ok: navigator.mediaDevices.getUserMedia

**Comment by fippo** [comment]
iOS webview does not support getUserMedia. See https://bugs.chromium.org/p/chromium/issues/detail?id=752458
Not an issue adapter can solve.
