### ISSUE TITLE
getUserMedia issues with Chrome 73.0.3683.68

### ISSUE THREAD

**Issue by barisbalic** [webrtcHacks/adapter#943]
- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used

## Versions affected
Chrome 73.0.3683.68 on iOS

**adapter.js (latest)**

## Description

After an update to some iPads I found that users were no longer able to take photos, I was not using the adapter at this time, just the in-built calls.  I tried to fix the issue, and managed to do so for Safari only which is not our browser of choice, so my next step was to find this adapter and make use of it.
While everything works fine on desktop, I discovered that several (maybe all) of the WebRTC sample pages do not work for Chrome on iOS under the version I've listed, and there's no documentation suggesting they shouldn't, in this project or elsewhere.

## Steps to reproduce

Visit the following URLs:
- https://webrtc.github.io/samples/src/content/getusermedia/canvas/
- https://webrtc.github.io/samples/src/content/getusermedia/gum/

## Expected results

The sample pages allow you to see a video stream from the camera, and in the canvas case, allow you snap a still image.

## Actual results

No stream is loaded.   In the `gum` sample, the error `getUserMedia error: TypeError` is presented on the page.

**Comment by fippo** [comment]
Chrome on ios does not support getUserMedia, see https://bugs.chromium.org/p/chromium/issues/detail?id=752458

**Comment by barisbalic** [comment]
@fippo ahh, now I'm fairly sure that it was working fine ~3 months ago when I last checked, but memory is never perfect, and this looks like it's been an issue for way longer.  Sorry for any confusion.
