### ISSUE TITLE
Cannot assign to read only property exports of object

### ISSUE THREAD

**Issue by bumi001** [webrtcHacks/adapter#944]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [ ] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [ X] I have provided browser name, version and adapter.js version
- [X ] This issue only happens when adapter.js is used

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Versions affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**
Version 73.0.3683.103 (Official Build) (64-bit)

**adapter.js (e.g. 6.1.0)**
7.2.2

## Description
I include it like
import adapter from 'webrtc-adapter'

## Steps to reproduce
Insert the above line in any reactjs component

## Expected results
Component should load

## Actual results
The app doesn't load. It displays:
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

**Comment by RyRy79261** [comment]
Getting the exact same issue

**Comment by fippo** [comment]
https://github.com/webrtcHacks/adapter/pull/948 should fix that but we're currently waiting on the tests to become more green before publishing a new version.

**Comment by RyRy79261** [comment]
@fippo The issue I'm getting is that another package I'm using is calling this in a require statement, I'm guessing taking that approach would cause this issue?

**Comment by fippo** [comment]
ah... is this not #948. Sounds like an issue with the bundler, which one is used?

**Comment by RyRy79261** [comment]
@fippo So I was using a react qr scanner, and what happened was when you target this with require it automatically targeted adapter5 or something rather than core which used export. 

Resulting in this issue at compile in webpack.

**Comment by fippo** [comment]
hoping this isn't an issue anymore, please holler if that is wrong

**Comment by bumi001** [comment]
I agree that this issue is resolved. In my package.json, I have:
"webrtc-adapter": "7.7.0"
