### ISSUE TITLE
msid test failure in FF nightly

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#958]
https://travis-ci.org/webrtcHacks/adapter/jobs/528222710#L1532
shows that [this test](https://github.com/webrtcHacks/adapter/blob/master/test/e2e/msid.js#L56) fails in Firefox Nightly (68.0a1)

@jan-ivar why did that change? I know we can't and should not rely on track ids anymore but so far this worked locally so I'd like to understand the rationale before "fixing" that test.

**Comment by jan-ivar** [comment]
Odd, this doesn't reproduce for me https://jsfiddle.net/jib1/sd364btp/ Anyone else seeing it? cc @docfaraday

**Comment by docfaraday** [comment]
We don't put the send track id in the sdp anymore.

**Comment by fippo** [comment]
Will change that test then, I *think* its for testing some Chrome munging anyway. Thank you!
