### ISSUE TITLE
Investigate why translateIce test fails on travis

### ISSUE THREAD

**Issue by KaptenJansson** [webrtcHacks/adapter#96]
https://github.com/fippo/adapter/commit/7d69f861abffcde8f8b0bce0710fc38cf417c32b

**Comment by fippo** [comment]
the core issue is that on the travis VMs, setting iceTransports to relay with empty TURN servers does not result in an empty candidate.

This works locally, might be related to the networking setup which is explained at http://docs.travis-ci.com/user/ci-environment/#Networking

**Comment by fippo** [comment]
pebcak once again. https://travis-ci.org/webrtc/adapter/jobs/72748188#L523 shows that the test succeeds, it's just an t.end missing.
