### ISSUE TITLE
chrome beta/unstable test failures

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#964]
we seem to have new failures in unstable in beta now that the ICE issues are gone:
```
+ERR addIceCandidate "before each" hook for "resolves when called with null" timeout
+ERR maxMessageSize send largest possible single message AssertionError
+ERR maxMessageSize throws an exception if the message is too large AssertionError
+ERR maxMessageSize throws an exception if the message is too large (using a secondary data channel) AssertionError
```
@lgrahl can you take a look at the datachannel ones please? I'll take a look at why addIceCandidate(null) fails while addIceCandidate(undefined) still passes

**Comment by fippo** [comment]
wrt addIceCandidate I've pulled the test into a fiddle:
https://jsfiddle.net/ujoLxd56/
-- this fails with both null and undefined while the karma test only fails with null.
With a local adapter build it looks like the main addIceCandidate shim is not called.
Bad revision: 650671
Good revision:  638880
Bisect:
```
python bisect-builds.py --use-local-cache -a linux64 -b 650671 -g 638880 --user-data-dir=/tmp https://jsfiddle.net/ujoLxd56/
```
(test: does console log an error?) points to
https://chromium.googlesource.com/chromium/src/+log/59490dd45840550cc25232167d13d30795fd9f85..ee949cd4fef997e3878cfba822535c2614174951

https://github.com/webrtcHacks/adapter/blob/master/test/e2e/addIceCandidate.js#L37-L38
adds a candidate without sdpMLineIndex. 

@guidou: I don't understand why this would throw in one case but not the other?!
Either way, I think addIceCandidate with just sdpMid is ok. cc-ing @alvestrand for a second opinion.

**Comment by nils-ohlmeier** [comment]
AFAIK the spec says you have to have either sdpMLineIndex or sdpMid set. So adding an ICE candidate without MLineIndex should work. Isn't there a WPT test which should cover this?

**Comment by fippo** [comment]
there is a test named `Add candidate with only valid sdpMid should succeed` which passes.
From webrtc-internals the difference is that in the fiddle sdpMLineIndex is null while in the wpt test it is 0.
The difference here is adapter explicitly calling new RTCIceCandidate. Changing the test to
```
    return pc.setRemoteDescription(sessionDesc)
      .then(() => pc.addIceCandidate(new RTCIceCandidate({
        candidate: candidateStr1,
        sdpMid: sdpMid1 })));
  }, 'Add candidate with only valid sdpMid should succeed');
```
fails too.

**Comment by fippo** [comment]
(it would probably be good for adapter to stop doing this implicit conversion in recent versions... need to find out the versions where this shipped and then do a conditional)

**Comment by lgrahl** [comment]
It looks like the *infinity* value of `maxMessageSize` made it into beta, contrary to my recommendation in [the *intent to implement*](https://groups.google.com/a/chromium.org/d/msg/blink-dev/hs0xuxTrvrc/7hv3P0ZBAQAJ). I'm not that familiar with Google's shipping model but it would be terrible if this makes it into release unfixed.

**Comment by alvestrand** [comment]
In which version are you seeing infinity without setting the "experimental features" flag?
We held back on releasing sctpTransport in 75 because we didn't have maxMessageSize done; I submitted the fix that made all tests pass into 76 this Friday.

**Comment by fippo** [comment]
https://travis-ci.org/webrtcHacks/adapter/builds/533924802 -- afaics this only happens with experimental features on -- which I thought wasn't used anymore but surprise, it was :-)

**Comment by lgrahl** [comment]
@alvestrand @fippo I missed that we test with and without the *experimental feature* flag. As this only happens with the flag, we don't need to worry, so apologies for the alarm and enjoy your sunday evening. :slightly_smiling_face:

**Comment by fippo** [comment]
filed https://bugs.chromium.org/p/chromium/issues/detail?id=965483 for addIceCandidate, will update the tests (or ignore them for a while)

**Comment by fippo** [comment]
All green again. I'll have to pull the expectations along for a while but that is ok.

Thanks all.
