### ISSUE TITLE
Support for promise based OfflineAudioContext.startRendering().then on Safari

### ISSUE THREAD

**Issue by sachingargtech** [webrtcHacks/adapter#971]
Safari on iOS does not implement the new recommended promise based API for OfflineAudioContext, only implements the old onComplete API. This looks like something that can be polyfilled in this adaper.

Details:
https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioContext/startRendering

Event-based version:
```
offlineAudioCtx.startRendering();
offlineAudioCtx.oncomplete = function(e) {
  // e.renderedBuffer contains the output buffer
}
```

Promise-based version:
```
offlineAudioCtx.startRendering().then(function(buffer) {
  // buffer contains the output buffer
});
```

**Comment by fippo** [comment]
This should be done in a more complete webaudio polyfill, not in a webrtc one.
