### ISSUE TITLE
data channel test failures in chrome beta

### ISSUE THREAD

**Issue by fippo** [webrtcHacks/adapter#976]
chrome beta now fails the datachannel tests in plan-b mode without experimental web platform features flag :-(

https://travis-ci.org/webrtcHacks/adapter/jobs/546182709
@alvestrand @lgrahl can one of you please take a look and tell me whether that failure is good or bad?

**Comment by lgrahl** [comment]
Haven't looked at it in detail, yet. Could it be that the `RTCSctpTransport` exists in that mode but doesn't hold a useful value for `maxMessageSize`?

**Comment by fippo** [comment]
bingo. `'sctp' in window.RTCPeerConnection.prototype` is true so your maxMessageSize shim doesn't kick in but pc.sctp is null in plan-b mode.

There is zero difference wrt sctp between unified plan and plan-b so what is the plan here @alvestrand?

**Comment by alvestrand** [comment]
RTCSctpTransport depends on RTCDtlsTransport, which is an Unified Plan-only feature.
We didn't think there was any reason to add a partial RTCSctpTransport implementation in plan-b.

**Comment by fippo** [comment]
Only exposing icetransport + dtlstransport on unified-plan is not a decision I would consider wise either (and both have very little dependency on the SDP). You had no problem exposing RTCRtpSender and RTCRtpReceiver in plan-b mode so why is this different?

Either way, can you consider fixing Lennarts shim with something a bit more dynamic? Neither of us thinks that paying the price for your decision is a good thing.

**Comment by fippo** [comment]
Fix in #979. I am not in favor of the "chrome webrtc team" doing what is the least effort for them and then breaking stuff. :-1:
