### ISSUE TITLE
pc.getStats.length returns incorrect value

### ISSUE THREAD

**Issue by t-mullen** [webrtcHacks/adapter#981]
- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used

## Versions affected

Firefox 67.0.3 (64-bit / Ubuntu)
adapter.js 6.4.8

## Description
`pc.getStats.length` should return zero since the spec-compliant function specifies default values for all arguments:
https://www.w3.org/TR/webrtc/#dom-rtcrtpsender-getstats
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length

## Steps to reproduce
1. Create a RTCPeerConnection shimmed with adapter.js
2. Log `pc.getStats.length`.
3. Observe it is not spec-compliant and does not match any browser behaviour.

## Expected results
`0`

## Actual results
`3`

**Comment by t-mullen** [comment]
Providing default arguments or overloading `getStats.length` should fix this issue.

**Comment by fippo** [comment]
i've followed [the discussion](https://github.com/feross/simple-peer/issues/470) and #980 should fix that. Ironic that simple-peer copied the detection logic from adapter and that broke...

**Comment by fippo** [comment]
fixed in 7.2.5 -- let me know if not!
