### ISSUE TITLE
Safari  12.1.1 RTCPeerConnection.addTrack() runs into type error

### ISSUE THREAD

**Issue by MasterXS** [webrtcHacks/adapter#989]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [* ] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [ *] I have provided browser name, version and adapter.js version
- [* ] This issue only happens when adapter.js is used

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Versions affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**

Safari 12.1.1
**adapter.js (e.g. 6.1.0)**
7.2.6

## Description
RTCPeerConnection.addTrack() run into type error
"Unhandled Promise Rejection: TypeError: Type error"

if removing the adapter.js, RTCPeerConnection.addTrack() works as expected.

## Steps to reproduce
using getUserMedia with audio and video and then call RTCPeerConnection to addTrack of the stream got from getUserMedia().

## Expected results

RTCPeerConnection.addTrack() works as expected

## Actual results
RTCPeerConnection.addTrack() - 
Unhandled Promise Rejection: TypeError: Type error

**Comment by fippo** [comment]
are you calling `addTrack(sometrack)` or `addTrack(sometrack, somestream)`?

**Comment by MasterXS** [comment]
addTrack(track) @fippo thanks

**Comment by fippo** [comment]
Safari doesn't like being called with _addTrack(this, track, undefined) [here](https://github.com/webrtcHacks/adapter/blob/master/src/js/safari/safari_shim.js#L50) it seems. @youennf FYI.

Easy to fix, new version coming soon.

**Comment by fippo** [comment]
Fixed in 7.2.7, thanks for the report!

**Comment by MasterXS** [comment]
@fippo thanks for your quick support

**Comment by MasterXS** [comment]
@fippo just verified with v7.2.7, the type error issue disappear but addTrack(track) run into this error:
"Unhandled Promise Rejection: TypeError: Argument 1 ('track') to RTCPeerConnection.addTrack must be an instance of MediaStreamTrack". any thought?

**Comment by fippo** [comment]
7.2.8 is on npm now

**Comment by kpwa** [comment]
> @fippo just verified with v7.2.7, the type error issue disappear but addTrack(track) run into this error:
> "Unhandled Promise Rejection: TypeError: Argument 1 ('track') to RTCPeerConnection.addTrack must be an instance of MediaStreamTrack". any thought?

am also expirincing this. What is the solution please?

**Comment by fippo** [comment]
adding a stream as second argument should work.
