### ISSUE TITLE
addTransceiver Firefox ignores init options

### ISSUE THREAD

**Issue by kekkokk** [webrtcHacks/adapter#998]
##  Description
It seems to me that the addTransceiver function in Firefox is ignoring the sendEncodings parameter during initialization.

As per doc: [MDN](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addTransceiver) the constructor takes in input an init object which can contains the sendEncodings options.

When passing this object to Chrome, everything's fine
When passing this object to Firefox, it gets ignored. The only way to apply these parameters, is getting the sender configuration, re-add the sendEncodings parameters and set again the options into the sender.

This last step, however, is not very appreciated by Chrome which complaints about the fact that we are re-setting the rids which are now read only.

This was stated clearly  in this PSA [Spec-compliant Simulcast using addTransceiver API](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/discuss-webrtc/32Y1AUzQ9XU/rfzss0SQAgAJ)

> The simulcast envelope (i.e. the number of layers and their RIDs) cannot be changed and is determined in the call to addTransceiver().
> After the number of layers is determined, the RtpSenderInterface can be queried for the parameters using getParameters()
> and the configuration for layers (not their number or RIDs) can change using setParameters().

I suspect this is a Firefox bug, and if so, adapter can shim the addTransceiver function (only in Firefox) and re-apply the init parameters so we don't have to manage the different cases in our client logic.

Also, if you think this is a bug and not mine misunderstanding, I'll proceed to file a bug issue.

## Steps to reproduce
discalimer: Not an html/css developer here so please be gentle with my example page. Also note that I reused a "playground" page with lots of other things but you can find the culprit on JS line 179.

Chrome 75.0.3770.100, FF 68.0.1

[LINK TO EXAMPLE CODEPEN](https://codepen.io/anon/pen/jgBdzx)

Click get media
Click Create PeerConnection
Click Create Offer
Observe Generated offer

## Expected results
> Chrome, Firefox: contains simulcast and rids infos

## Actual results
> Chrome: OK
> Firefox: No simulcast and rids in there, also the sender.getParameters() called after the constructor returns an empty object.

If you change the line 179 in if (true), then Firefox works but chrome complaints

What do you think @fippo? Am I missing something?
thanks

**Comment by fippo** [comment]
I don't see what adapter could do here? And people who use simulcast have different codepaths already so there is little incentive to add something.

cc @jan-ivar

**Comment by kekkokk** [comment]
Adapter could shim the addTransceiver function if Firefox is detected, call the base addtransceiver function and then reapply the parameters passed.
I think this is not only a simulcast situation since you can also define other important properties such as the maxbitrate

**Comment by fippo** [comment]
had a quick chat with this. This can be shimmed in quite elegant ways actually...
1) the shim calls addTransceiver with the supplied arguments
2) the shim calls sender.getParameters and checks if the supplied arguments (encodings) are present.
3) if present return the transceiver
4) if not present, populate from provided arguments and call setParameters

Now the question is if you want to volunteer @kekkokk :-)

**Comment by kekkokk** [comment]
Sure!

**Comment by kekkokk** [comment]
Ok so, some news here:

AddTransceiver as per [MDN](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addTransceiver) return a transceiver object.

But sender.setParameters() [MDN](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender/setParameters) returns a promise.

Also not that addTransceiver expect an object with name: sendEncodings
But setParameters expect an object named: encodings

So I think this is a big inconsistency and I really don't know how to handle the fact that I would have to wrap a "promise" inside an async code.

simply calling setParameters in the shim, after calling the origAddTransceiver have no effect, since if the createoffer is called after the addtransceiver, these parameters are still not set in the sender... :(

This seems to be a known issue:
[Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1396918)

I don't know how to approach this atm

**Comment by jan-ivar** [comment]
> So I think this is a big inconsistency

@kekkokk I think it's intentional, since `encodings` in the scope of `addTransceiver` could mean send and/or receive. We'd need to work around it, e.g. like this:
```js
setParameters(Object.assign({}, init, {encodings: init.sendEncodings}))
```
> don't know how to handle the fact that I would have to wrap a "promise" inside an async code

We can't. We'd need to write `addTransceiver`'s [input validation steps](http://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-addtransceiver) so we can throw instead of reject on errors, then call
```js
setParameters(aboveArgs).catch(() => {});
```
...to suppress any asynchronous errors, and then return without waiting on the promise.

> if the createoffer is called after the addtransceiver, these parameters are still not set in the sender... :(

We can take advantage of the spec here, which mandates that createOffer MUST [rerun itself](http://w3c.github.io/webrtc-pc/#dfn-final-steps-to-create-an-offer) *"If connection was modified."* Unfortunately, Firefox doesn't do that yet. It's [bug 1544107](https://bugzilla.mozilla.org/show_bug.cgi?id=1544107).

But I think this gives adapter license to intercept `createOffer` here and re-run it if it comes back without this change. A bit more work, but let me know if you're up for it!
